### ISSUE TITLE
`null` value for 'allowed' funding methods param breaks render

### ISSUE THREAD

**Issue by dechov** [paypal/paypal-checkout#1006]
Our Smart Payment Buttons integration broke late on Friday due to a change [[PR](https://github.com/paypal/paypal-checkout/pull/1001)] released in 4.0.254, because we were passing `null` as the `funding.allowed` parameter to `paypal.Button.render` and this change doesn't include a check for falsy values.

<img width="434" alt="screen shot 2019-02-03 at 11 34 09 am" src="https://user-images.githubusercontent.com/1867547/52220391-ba60dd00-286c-11e9-8439-2ebf2b44c43b.png">

Although we've patched this in our latest version, older versions are still broken.

**Comment by dechov** [comment]
Yes, it's fixed in our integration with the 4.0.255 release. Thank you!

**Comment by laphilia** [comment]
Thanks a lot. The button  now works !
