### ISSUE TITLE
payment() should support billing tokens

### ISSUE THREAD

**Issue by bluepnume** [paypal/paypal-checkout#101]

**Comment by bluepnume** [comment]
Done.

**Comment by eliotsykes** [comment]
@bluepnume sorry for commenting on a closed issue, do you happen to know of an example using the checkout.js billing token feature?

**Comment by bluepnume** [comment]
So -- the idea is exactly the same, if you have an `EC-XXXXXXXX` token from a billing call, you can pass it back in `payment()`.

```javascript
        payment: function() {
            return paypal.request.post(CREATE_BILLING_URL).then(function(data) {
                return data.token;
            });
        },
```

https://developer.paypal.com/docs/api/payments.billing-agreements

Let me know if I can clarify further on this.
