### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by vismagine** [paypal/paypal-checkout#105]
Hi everyone,
I am using checkout V4 to do a payment against the 'sandbox' and trying to implement the Basic PayPal Checkout Button. All the code works fine until it gets to the point of 'Confirm' or 'Pay now' within the PayPal-Pop-Up ... at this point the Pop-Up closes and no further call are made to the Button (as example: onAuthorize is not initiated). 

At this point the console shows several a warning and errors after 3 x _apy_retry_. Is this a known issue or does someone have a suggestion on this?

Any help is welcome and thank you very much in advance,
Christian

UPDATE: in Google Chrome (Version 54) it is possible to complete the payment, i am having the errors just within Firefox V49.0.2

**Warning**
`missing_csrf_jwt Object { timestamp=1479294755397,  windowID="5fbc81d2c8",  pageID="3768daa62d"}`

**Error**
`"NetworkError: 500 Internal Server Error - https://www.sandbox.paypal.com/webapps/hermes/api/payment/PAY-1UH37573M6748251ALAWD6BI?"`

`http_response_500 Object { timestamp=1479294756872,  windowID="5fbc81d2c8",  pageID="3768daa62d"}`

**Response of the GET Payment request from button.js**
`{"ack":"error","message":"Unhandled api error","meta":{"calc":"5c86b8d3140ef","rlog":"rKGmcXTB%2B2NqZAMhrf0E
%2BSi2kRuzAYN1zBd6UkYGjcFtNQ0WfaI3FHIbPIRTaJRcwP4CM4%2FkeW05efr7awS8xw_1586cc53450"},"server":"Wb_7k
zG8hs8iXSTxTssRX7gAbhKsGUveN-Qi5qR4xO-eChao8SHpy7dW9-lcr1X7z1Ex578DclpDjpNeK6E56fHpDAqRWL8SI0Od4rpHe
HT57pjggRD85TXSwGA9IYgdTw8WLisakLokxa9yxvmsjiYYO9Sf8Hnb4sanRFuPznDh8b4zEXUgz2kxautGGtS3lTXJjgK9TVqouGCqrStk_j4GQC1ssToOZ0n6am"
}`

**Comment by bluepnume** [comment]
Thanks for the detailed report! I'll take a look at firefox and try to see if I can repro this.

Thanks,
Daniel

**Comment by bluepnume** [comment]
@vismagine Can you please try now? Should hopefully be resolved.

**Comment by vismagine** [comment]
Thank you very much for your help on this issue Daniel. My first retry showed good results already. I was able to finalize the payment without the mentioned errors in Firefox.

Again, many thanks for your fast help on that issue. It is good to know that help is offered when its needed the most :)

Thanks,
Christian

**Comment by milosb793** [comment]
Hey @bluepnume, would you mind to tell what was the issue? I'm facing the same error on the localhost, not sure is it up to me or something else.
