### ISSUE TITLE
Doc issues

### ISSUE THREAD

**Issue by bluepnume** [paypal/paypal-checkout#115]
- [x] Semicolon crept into `paypal.request.post(...);` - https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/advanced-integration/
- [x] `data.payment` should be `actions.payment.get()` - https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/basic-integration/
- [x] Need to remove `data-version-4` now v4 is ramped to 100%
- [x] Remove all references to window.paypalCheckoutReady

**Comment by abarco** [comment]
pending merge

**Comment by abarco** [comment]
Merged
