### ISSUE TITLE
Popup window not redirecting when clicking fast enough on button

### ISSUE THREAD

**Issue by davibennun** [paypal/paypal-checkout#119]
When a user clicks on the paypal button fast enough, paypal popup won't redirect and the loading bar would go on forever.

You can reproduce going to one of example links from the docs:
http://plnkr.co/edit/3vfNSVRyq86pDR5mH4HH?p=preview

**Comment by bluepnume** [comment]
Thanks for the report. I'm having a little trouble reproducing this though -- which browser are you using? And do you see any console errors in the parent window?

**Comment by bluepnume** [comment]
@davibennun Any chance of a little help repro'ing this? Still haven't had any luck :(

**Comment by bluepnume** [comment]
Closing this unless you can still repro.
