### ISSUE TITLE
Amount not displayed and wrong text for the "commit: true" flow

### ISSUE THREAD

**Issue by andreabondi** [paypal/paypal-checkout#120]
The total amount is missing on the upper right corner of the popup and wrong text "You'll be able to review..." under the "Pay Now" button. This is correct if Line Item Details are passed.

<img width="459" alt="screen shot 2016-11-28 at 17 37 07" src="https://cloud.githubusercontent.com/assets/1085145/20679581/713c2c18-b593-11e6-9118-7953f6280c1c.png">

**Comment by marcocristalli** [comment]
Same here!
The amount is not showing up even if `commit:false`

**Comment by andreabondi** [comment]
@marcocristalli thanks for your comment. With `commit:false` not showing the amount is the expected behaviour, since the buyer will review the order on the seller's final confirmation page before completing the transaction.

**Comment by abarco** [comment]
Hi guys @andreabondi, @marcocristalli  
Thnx for bringing it to our attention. We've found the issue and this will be resolved by our next push, probably early Jan.

**Comment by bluepnume** [comment]
Assuming this is fixed now, closing.
