### ISSUE TITLE
checkout.js with Google Apps Script - it's confused about the window to use

### ISSUE THREAD

**Issue by brucemcpherson** [paypal/paypal-checkout#125]
I'm trying to use checkout.js v4 in an Apps Script add-on sidebar. 
Using the demo code from the express checkout docs unaltered, the button renders fine in the provided element, but the popup...
a) is centered over the underlying google document (as opposed to in the sidebar)
b) fails with this error, without rendering anything

```
VM592 checkout.js:9315 ppxo_xc_ppcheckout_error Object {error: "Error: Unable to delegate rendering. Possibly the …s://www.paypalobjects.com/api/checkout.js:1368:21", timestamp: 1481019226913, windowID: "5dd9fe9dc2", pageID: "47b85a6c9c", host: "www.sandbox.paypal.com"…} 

 Error: Unable to delegate rendering. Possibly the component is not loaded in the target window.
```

Any way to get around this?
When using Stripe for payments, it's dialog fits itself  nicely inside its parent Iframe - which is the apps script sidebar (as opposed to centering itself over the hosting document) - this is the same behavior I was expecting (and need ) to see from checkout.js

**Comment by bluepnume** [comment]
@brucemcpherson Thanks for raising the issue. Normally checkout.js expects to be able to be render to the top window.

I'm guessing there's no way for this integration that checkout.js could be included in the top window too? If it could be, that should fix this problem, otherwise maybe there's something else we can do.

**Comment by brucemcpherson** [comment]
No - the top window belongs to the Google Sheets/Docs/Forms UI. The sidebar
is an IFrame in which the add-on app renders under the control of the UI as
in the example attached. The add-on app is on the right.

[image: Inline images 1]

Here's how the Stripe API renders inside the add-on IFrame.
[image: Inline images 2]

**Comment by bluepnume** [comment]
Would you mind re-adding the screenshots you sent? They're not visible on github.

We're mooting the best way to handle cases like this where you're embedded on a page that you don't own. A lot of the design of the checkout app is based around running in the top level window, so trying to find a path forward here.

**Comment by brucemcpherson** [comment]
I replied by email and it lost the inline images. Here they are again, with the sidebar on the right.
![image 1](https://cloud.githubusercontent.com/assets/1894020/21029382/567d8e16-bd91-11e6-944c-5d67b978e93e.png)
And you'll see from the this image how Stripe manage to get their iframe within the sidebar.
![image 2](https://cloud.githubusercontent.com/assets/1894020/21029391/60000c02-bd91-11e6-9c2e-43e51addb807.png)

You'll see more about how add-ons look here - 
http://ramblings.mcpher.com/Home/excelquirks/addons/dicersv2

**Comment by bluepnume** [comment]
Thanks for the screenshots. We'll look into it but can't promise a lot of traction on this until Jan, since we're in the middle of holiday season.

**Comment by roy-prasenjit** [comment]
Looking for updates on this issue. Any news?

**Comment by louking** [comment]
I'm also seeing this problem - is there any workaround?

**Comment by tanyagupta** [comment]
I am also I'm also seeing this problem with v4.
Has there been any update? (also on GAS, working on a Docs Add-On)

**Comment by fomojola** [comment]
As a follow up, I tried this using a modal dialog (instead of a sidebar) and the same problem persists: the console has the same window rendering error and the checkout window doesn't appear.

@bluepnume is there a specific IPC library being used that prevents rendering in an iframe? Or is there an additional stub or library we can add to the HTML that is loading in the iframe that will get past this item.

**Comment by jonton11** [comment]
+1 would love to learn of an update or workaround for this

**Comment by bluepnume** [comment]
@fomojola There's no technical reason this isn't possible -- we just need to get some priority on our side to do the work. I'll keep this thread updated when I manage to get to this.

**Comment by bluepnume** [comment]
Sorry for the long delay on this issue. It's now resolved -- the button should be usable in an iframe even when checkout.js is not loaded in the parent.
