### ISSUE TITLE
Is there a way to let user approve billing agreement from light box by checkout.js?

### ISSUE THREAD

**Issue by billsliu** [paypal/paypal-checkout#131]
I have created a billing agreement in server side, and I have the billing agreement approval link https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-3Y110350RV7380205. I need to let user to approve this billing agreement, I can redirect user to this PayPal link for approving from my site, but this will move user away to PayPal from my site completely. I want to show the approval step in light box by checkout.js. How can I do it?

**Comment by bluepnume** [comment]
You can just pass back that EC- token in the `payment` function on the client side.

It's the "advanced" integration, which supports generating tokens on the server side: https://github.com/paypal/paypal-checkout/blob/master/docs/button.md#advanced-integration

**Comment by billsliu** [comment]
Is this code correct?

	payment: function (resolve, reject) {
		var token = 'EC-3Y110350RV7380205'; // token will generate in server side
       		resolve(token);
    	}

**Comment by bluepnume** [comment]
Yep, that looks correct to me. Don't forget to `reject` in the case of any errors, so the paypal flow can teardown correctly.

**Comment by billsliu** [comment]
Thanks a lot for your reply

**Comment by bluepnume** [comment]
No problem!

**Comment by albertbanez** [comment]
Hi i would like to ask some questions too. -)
1. This var token = 'EC-3Y11030RV7380205' is not the paymentId yet right? Can we pass this token directly to the OnAuthorize function already? We need the PaymentId first right?
