### ISSUE TITLE
BillingAgreements functionality

### ISSUE THREAD

**Issue by neshke89** [paypal/paypal-checkout#133]
Hello again,
I can see that there's written function at paypal.rest.billingAgreement.create().
Is this functionality working? I'm getting wierd results. I'm able to use it and get payment and Billing Agreement token back, but I'm unable to execute payment with same payment (EC) token.
Also, I wasn't able to find api endpoint  v1/billing-agreements/agreement-tokens at restApi docs so that I can read more on subject.
Problem is that I'm getting this error for token when executing payment with REST API:
`{
  "name": "BUSINESS_VALIDATION_ERROR",
  "details": [
    {
      "field": "validation_failure",
      "issue": "Invalid Payment Token."
    }
  ],
  "message": "Validation Error.",
  "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#BUSINESS_VALIDATION_ERROR",
  "debug_id": "8f7432b4a2c18"
}`
IF I create biling plan using documented API functions (manually from postman), and authorize it using link which is receieved from api, executing works.

Creation code:
` return paypal.rest.billingAgreement.create(this.props.env, this.props.client, {
                name: "Sample Plan agreement",
                description: "Agreement for subscription",
                start_date: "2016-12-13T15:49:04Z", //always in future
                plan: {
                    id: "P-9G01659268119733H4PSWRZY",
                  "description": "Plan with regular and trial",
                    type: "MERCHANT_INITIATED_BILLING",
                },

                payer: {
                    "payment_method": "paypal"
                },
            });`

**Comment by bluepnume** [comment]
My recommendation is to not use `paypal.rest.billingAgreement.create` on the client side, for now. This is an undocumented feature, and we haven't finalized how it's going to work. You can still get this working using server-side REST calls to the billing apis though, so long as you pass the token back to the `payment()` method using the [advanced integration](https://github.com/paypal/paypal-checkout/blob/master/docs/button.md#advanced-integration)

**Comment by WayneUong** [comment]
@bluepnume When I create a billingAgreement on server side, how should I proceed with checkout V4? If I get the token from `approval_url` and use `resolve(token)`, the lightbox just closes and onCancel is called.

If I redirect to `approval_url`, then the legacy checkout screen is shown, not the express checkout screen,

**Comment by Miguelcldn** [comment]
Hey @WayneUong, maybe I'm a little late to help but here is my working code if that helps you

```javascript
paypal.Button.render({
        env: 'sandbox',
        locale: 'es_ES',

        payment: (resolve, reject) => {
          let backUrl = config.paypal.backUrl;

          //Ask my server to create a subscription and bring me an agreement token
          //with the ruby-sdk, its Agreement object has the token -> agreement.token
          Checkout.subscribePaypal(backUrl).then((response) => {
            resolve(response.token);
          });
        },

        onAuthorize: (data) => {
          //Ask my server to execute the agreement
          Checkout.agreePaypal(data.paymentToken);
        },

        onCancel: () => { }

      }, "#paypal-subscribe-button");
```

**Comment by bluepnume** [comment]
@WayneUong sorry missed your comment the first time. There was a bug which was causing `onCancel` to be called. This should now be fixed. Can you let me know if you still see the issue?

**Comment by WayneUong** [comment]
@bluepnume it works fine now. Thank you.
