### ISSUE TITLE
`main` key incorrect in package.json

### ISSUE THREAD

**Issue by M-Porter** [paypal/paypal-checkout#135]
The [`main`](https://github.com/paypal/paypal-checkout/blob/master/package.json#L5) key points to `index.js` which does not exist which causes statements such as `const paypal = require('paypal-checkout')` or `import paypal from 'paypal-checkout'` to fail.

Solution:
* Change `main` to point to `dist/checkout.js` so the library can actually be used as a module in build systems without alias shims.

**Comment by bluepnume** [comment]
Good catch, thanks. Checking into it.

**Comment by bluepnume** [comment]
Added index.js
