### ISSUE TITLE
Succeeded authorization triggers onCancel event

### ISSUE THREAD

**Issue by neshke89** [paypal/paypal-checkout#137]
Here's workflow:
I'm using servers side to generate agreement billing token.
After authorization cancel event is trigered but token is authorized succesfully.

-I've tested token using postman and PayPal api call for execution transaction with token returned in onCancel which was done sucessfully.

**Comment by bluepnume** [comment]
Can you share your code? You're saying you're seeing both `onAuthorize` **and** `onCancel` called for the same transaction?

**Comment by bluepnume** [comment]
OK we've managed to repro this. @abarco is working on a fix.

Thanks,
Daniel

**Comment by neshke89** [comment]
It was a bussy day, sorry for not answering immediatelly.
As you've managed to repro, I'll just confirm behaviour.
It's triggering onCancel, not onAuthorize  even when paymen token was authorized.

**Comment by abarco** [comment]
Hi @neshke89, we have a fix. You can expect it to be pushed by early Jan

**Comment by WayneUong** [comment]
Hi @abarco, this issue is still not fixed in 4.0.37? This is breaking our subscriptions and we need it asap. Is there a temporary fix for now?

**Comment by abarco** [comment]
Hi @WayneUong, I'm afraid there is no temporary fix for this. The issue is not part of the checkout script, but the paypal app. We won't be able to push until early Jan.

**Comment by bluepnume** [comment]
@abarco can you confirm this works after yesterday's checkout push?

**Comment by abarco** [comment]
Yup, closing the issue. The correct handler is being called.
