### ISSUE TITLE
Is there a way to trigger flow with my own selector (button)?

### ISSUE THREAD

**Issue by yabdab** [paypal/paypal-checkout#138]
I want to trigger the flow with my app's own function. Is this possible?

If so, how can I do this and still reap the benefits of the flow callBacks ( onCancel, onAuthorize, etc.. ) on my app?

**Comment by yabdab** [comment]
To elaborate, I want to be able to launch the flow in mini-browser window ( not lightbox  ) when a user clicks a button i create. Then still be able to receive callbacks to my app so it can act accordingly.

Really hoping this is a possibility?

**Comment by bluepnume** [comment]
Hi yabdab,

One requirement of using this script is using the button provided.

We actually render the button into an iframe, so it can be upgraded in future and customized for customers, to improve their experience and conversion. We also have brand requirements that only a certain set of PayPal buttons should be used.

Can I ask if there's a use-case you have that the existing buttons don't work for? It's good to have examples so we can figure out how to improve the range of buttons we have.

**Comment by yabdab** [comment]
I have a shopping cart platform (Saas) that we would like to use the button on. The buttons rendered are not very nice and do not match the UI on the rest of our checkout. Was just wanting more control over things as a developer. Is this solution geared more toward end users instead of devs?

**Comment by bluepnume** [comment]
Yeah, we're trying to strike a balance between developers, end-users, and our own branding.

We've ran a lot of AB tests on the buttons to determine which are the most recognizable, and which get the most clicks -- and this ends up being pretty good for merchants too, if more buyers end up checking out.

Any chance I could take a look at the button you were planning on using?

**Comment by yabdab** [comment]
Our button is nothing special, but does match the rest of our UI. Can be changed by seller to match their site color scheme etc...

http://cloud.yabdab.com/0v1y2U03283W

**Comment by bluepnume** [comment]
Yeah, so our brand requirements at the very least require the PayPal name / logo in the button. The idea is, customers recognize the button, and realize they can use their PayPal account to pay.

There are at least different options for size/color/shape, if that's helpful:

https://github.com/paypal/paypal-checkout/blob/master/docs/button.md#customizing-the-button

**Comment by yabdab** [comment]
Is that kinda thing overlooked with Shopify checkouts?

**Comment by bluepnume** [comment]
Shopify hasn't yet upgraded to the latest checkout.js integration. But yes, going forward, this is a requirement across the board.

**Comment by yabdab** [comment]
OK, good to know. Thanks for your quick replies. 
Up to this point support through normal channels in non existent.  ;-)

**Comment by bluepnume** [comment]
Yeah, this repo is probably the best place for questions around checkout.js. Appreciate the stuff you've pointed out so far! We're eager to make this as simple an integration as possible.
