### ISSUE TITLE
Using render in an iframe throws errors

### ISSUE THREAD

**Issue by yabdab** [paypal/paypal-checkout#140]
So I have a setup like so...

Parent Page -> iframe page -> rendered PP button iframe

Clicking the rendered button throws the following error...

` Error: Unable to delegate rendering. Possibly the component is not loaded in the target window.

Error: No ack for postMessage xcomponent_delegate_ppcheckout in 1000ms
    at https://www.paypalobjects.com/api/checkout.js:1037:43
    at https://www.paypalobjects.com/api/checkout.js:2007:21
    at runInterval (https://www.paypalobjects.com/api/checkout.js:1991:28)
    at Object.onError (https://www.paypalobjects.com/api/checkout.js:9073:31)
    at _loop2 (https://www.paypalobjects.com/api/checkout.js:1673:46)
    at SyncPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:1700:29)
    at SyncPromise.reject (https://www.paypalobjects.com/api/checkout.js:1653:18)
    at _loop2 (https://www.paypalobjects.com/api/checkout.js:1688:37)
    at SyncPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:1700:29)
    at SyncPromise.reject (https://www.paypalobjects.com/api/checkout.js:1653:18)
    at https://www.paypalobjects.com/api/checkout.js:1620:29
    at flush (https://www.paypalobjects.com/api/checkout.js:1515:32)
    at https://www.paypalobjects.com/api/checkout.js:1529:21`

If I use the rendered button in a page directly, no other iframe involved, the error is not thrown.

I think this error is related to drawing the overlay, as I have disableLightbox enabled.

**Comment by bluepnume** [comment]
You will need to include the checkout.js script in the parent (top level) page. Please let me know if that doesn't work.

**Comment by yabdab** [comment]
Yes, that seems to have fixed the issue. Thanks.

**Comment by bluepnume** [comment]
Awesome!

**Comment by omtinez** [comment]
Would like to re-open this issue as it is not possible to include the checkout.js script in the parent (top level) page if one is using AMP.

**Comment by omtinez** [comment]
Also, putting the script in the top-level (non-AMP) page fails in Safari when the iframe is sanboxed, the error shown in the console is: `The frame attempting navigation is sandboxed, and is therefore disallowed from navigating its ancestors.`

**Comment by bluepnume** [comment]
@omtinez Can you open new issues with details about these issues? Specifically:

- What causes the script to fail with AMP?
- In the Safari case, which iframe is sandboxed? If it's in the top-level page, I'm not sure which iframe you're referencing.

Thanks!

**Comment by omtinez** [comment]
Opened #440 for the AMP issue. I will open another issue for the Safari iframe problem when/if I get to it...

**Comment by herbertmilhomme** [comment]
Can we reopen this? I'm using a domain/url forward with masking, which loads page in an iframe. Not CORS, click-jacking or whatever. Merely, want sub-application to run off a secondary hostname without having to purchase a new webhost/server.

My issue is relevant to the original poster, as by default an iframe is created to render the page, and there's no logical way to reach top/parent-level of the webdesign.

**Comment by dilakshandc** [comment]
hello can you tell me specifically where to add the script. I have tried added to my index.html file didnt fixed the issue.
