### ISSUE TITLE
Re-Size the Mini-Browser Window

### ISSUE THREAD

**Issue by rythash** [paypal/paypal-checkout#142]
In many cases, when the mini-browser appears, the size is too small to fit all of the information inside the window.  This results in the user having to scroll to the bottom of the page to hit the submit button.

Can the mini-browser window dynamically adjust the size to fit all of the elements into the window, or at the very least, make the window larger to fit all of the elements without having to scroll to the bottom?

Thanks!

**Comment by bluepnume** [comment]
Thanks for highlighting this, appreciate it! We have plans to improve this, I'll update here.
