### ISSUE TITLE
Support related_resources in actions.payment.get

### ISSUE THREAD

**Issue by bluepnume** [paypal/paypal-checkout#143]
- [x] related_sources
- [x] custom

**Comment by sguryev** [comment]
Also other transaction data.
Here is the response body with the required `custom` field:
![image](https://cloud.githubusercontent.com/assets/6978458/21871798/9f49a4e6-d875-11e6-8f58-1ae89d6a2929.png)

And here is what I have in the `.then()` handler:
![image](https://cloud.githubusercontent.com/assets/6978458/21871819/bee4f9cc-d875-11e6-8ac7-efd25679a22a.png)

So I have to make the custom call (with Auth, tokens, etc., etc.)

**Comment by bluepnume** [comment]
Sure, will get that in too. Thanks for the heads up!

**Comment by bluepnume** [comment]
I've added in `custom`, this should be going out with the next release. `related_resources` looks like it's going to be a bit more tricky.

**Comment by snimavat** [comment]
@bluepnume any updated on the transactions data ? -- I am not seeing the customer field in transaction object either, we really need this..

**Comment by bluepnume** [comment]
@snimavat - can you confirm, when you call `actions.payment.get()` you see `related_resources` in the network tab? Do you have a link to your integration so I can try it out?

When I tried, `related_resources` was not populated, and my assumption was that was happening because I was not directly calling `/execute`. But if you have an example integration which returns that, that would be great.

**Comment by bluepnume** [comment]
OK, found a potential fix for the `related_resources` issue. 

The problem was, checkout.js was calling a different api to complete the payment, not `execute`. When I eventually got `execute` to work, `related_resources` started to show up.

I'll commit this fix after some testing, but given that this is a server side change, it may be next week before it can be deployed.

**Comment by snimavat** [comment]
@bluepnume my issue is custom field, i want to have access to custom field in javascript

**Comment by bluepnume** [comment]
@snimavat Right, sorry. That fix should be going out in the next 1-2 days.

**Comment by snimavat** [comment]
Thanks

**Comment by bluepnume** [comment]
Both `custom` and `related_resources` should now be passed back in live.
