### ISSUE TITLE
New design of PP Express Checkout page

### ISSUE THREAD

**Issue by DariaNam** [paypal/paypal-checkout#147]
Hi team, 

at this moment we have such design of EC page: https://www.evernote.com/shard/s406/sh/25841a61-2d92-49e5-947a-7b32f65c3ad9/7c0ea25b2d5bebdb but we would like to use the new one:
https://www.evernote.com/shard/s406/sh/7572fa08-fa6c-4cae-a4bc-70d1a406edcb/5dca1013161f3db6

I was informed by PP Integration Engineer that the new design is incompatible with the Digital Goods flow at this time. And he asked me to contact you for solving this issue.
Could you please assist us in this? Please inform me if you need additional information.

**Comment by bluepnume** [comment]
Digital goods is currently being ramped across from the legacy checkout app. 

For now, could you just use regular Express Checkout without digital goods?

**Comment by DariaNam** [comment]
Hi, thank you.
Would it be possible for us to use a new design along with Digital Goods in future?

**Comment by bluepnume** [comment]
You can use it right now -- my recommendation is just to use regular Express Checkout, and do not pass digital goods parameters.

If this isn't possible, then yes, in future your site will be auto-migrated over to the new PayPal checkout design.
