### ISSUE TITLE
Button not working when using ionic

### ISSUE THREAD

**Issue by brilvio** [paypal/paypal-checkout#150]
I am using this example with my server handling the REST calls, https://github.com/paypal/paypal-checkout/blob/master/docs/button.md#advanced-integration it works fine on the browser but if I build the app via ionic the button doesn't work. It happens with both iOS and Android apps.

**Comment by bluepnume** [comment]
Hi brilvio,

We don't currently have any plans to support ionic; personally I'm not totally familiar with the platform, and I'm not sure if it's designed to support iframes/popups/post-messages which are all necessary for paypal-checkout to work.

For mobile, we're have an SDK in the works, which may fit your use-cases better. @ pvenkatakrishnan may be able to provide any details we've publicized about that.

**Comment by brilvio** [comment]
The error that occurs in the app is that because is running on a webview, he (app) is using the `file://` protocol and then when we call the iframe it doesn't work throwing the error:          
```
01-04 13:51:45.765: I/chromium(18207): [INFO:CONSOLE(9394)] "Blocked a frame with origin "https://www.sandbox.paypal.com" from accessing a frame with origin "file://".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "file". Protocols must match.
```
I don't think it will ever work without a plugin made in java for ionic, so thanks for your time.
