### ISSUE TITLE
Add `paypal.Promise.denodeify`

### ISSUE THREAD

**Issue by bluepnume** [paypal/paypal-checkout#153]
This should help with integrations which allow a callback based method of creating a payment token. Example use-case is braintree:

```javascript
payment: function() {
    return paypal.Promise.denodeify(paypalInstance.createPayment, {
        flow:     'checkout',
        currency: 'USD',
        amount:   10.00,
        intent:   'sale'
    });
}
```

> **Note:** ended up going with `paypal.Promise.promisifyCall`

**Comment by crookedneighbor** [comment]
I assume you're calling it `denodeify` because it converts Node.js style callbacks to a promise? Is that the best name for it? Node is a bit of an overloaded term (Node the programming language, Dom Nodes, etc).

Most Promise libraries that I've used have a `promisify` method. Any reason to not call it that?

**Comment by bluepnume** [comment]
@crookedneighbor yeah, you're right, denodeify is a bit of a loaded term. Just the first thing which came to mind because I cut my teeth on q.js which used denodeify as the name.

`promisify` is a lot better. Although normally `promisify` in other libs like bluebird is used to actually mint a new function -- like:

`let promiseFoo = promisify(foo)`;

Which makes it feel a little less appropriate for calling inline, because it feels not so optimal to be converting the function on every invocation:

`return paypal.Promise.promisify(paypalInstance.createPayment)({ ... });`

Let me do a quick scan and see if there's a better parallel, would definitely rather use a name most people are familiar with.

**Comment by bluepnume** [comment]
Actually it was `Q.nfcall(<function>, [arg1] ... [argN])` I was thinking about. 

Not seeing any consistent naming for functions like these across promise libs. I'm thinking about just going with `promisifyCall`.

**Comment by crookedneighbor** [comment]
:+1:

**Comment by bluepnume** [comment]
Added to https://github.com/krakenjs/sync-browser-mocks -- this will be included in the release today.

**Comment by bluepnume** [comment]
Pushed!
