### ISSUE TITLE
How can one detect if the rendering of the button is finished?

### ISSUE THREAD

**Issue by drahkrub** [paypal/paypal-checkout#154]
Is there some kind of event or callback or resolved promise or ...?

**Comment by bluepnume** [comment]
Yeah, you can specify `onEnter` as a callback:

```
paypal.Button.render({

    onEnter: function() {
        ...
    }
});
```

Alternatively, `paypal.Button.render({ ... });` returns a promise, so you can just do `paypal.Button.render({ ... }).then(function() { ... });`

**Comment by JulienPradet** [comment]
For reference, it seems that it's `onRendered` now with the latest version of the API.

@bluepnume  Is that the case?
