### ISSUE TITLE
Conditional block before mini browser initiates.

### ISSUE THREAD

**Issue by roy-prasenjit** [paypal/paypal-checkout#158]
Hello, is there a way to stop paypal mini browser flow using a conditional block? V3 has a similar feature 

paypal.checkout.setup('Your-Merchant-ID', {
  environment: 'sandbox',
  buttons: 'myContainer',
    **condition: function () {
      return !!document.getElementById('paypal-option').checked;
    }**
});

Is there anyway whatsoever to block the flow based on a condition. Maybe an init or onFlow or an onClick function block which runs first?

**Comment by bluepnume** [comment]
Currently there is not a way of doing this. Because the button is loaded in an iframe, it's not currently possible to synchronously stop the checkout. We're trying to figure out a good way to achieve this.

This is being tracked here: https://github.com/paypal/paypal-checkout/issues/139
