### ISSUE TITLE
Lightbox Crashes on trying to change paypal user

### ISSUE THREAD

**Issue by roy-prasenjit** [paypal/paypal-checkout#165]
If PayPal's session is active the payment window loads up as a lightbox. When I try to change the user by clicking on "Not you?" link a pop up comes up, flickers and crashes. PayPal then takes over the entire tab. 

Error observed in console window: 
<code>
checkout.js:4617 ppxo_xc_ppcheckout_error Object {error: "Error: Unable to delegate rendering. Possibly the …://www.paypalobjects.com/api/checkout.js:2132:28)", timestamp: 1485331630550, windowID: "3bf83dc5e6", pageID: "c796985a3c", host: "www.sandbox.paypal.com"…} 
</code>

 Error: Unable to delegate rendering. Possibly the component is not loaded in the target window.

1. We are using an iframe. 
2. We are currently on checkout.js v3.5

**Comment by bluepnume** [comment]
Hi @roy-prasenjit,

Thanks for raising this. There was some discussion about a similar problem with iframes over here: https://github.com/paypal/paypal-checkout/issues/125

In your case, do you have control over the parent page, or only the iframe?

**Comment by roy-prasenjit** [comment]
Hello @bluepnume,

I don't have control over the parent page. I can load the script only on the iframe. 

The error comes up when the context is a lightbox, is it possible that I could set it to "popup"? Maybe a flag or variable assignment?

On a side note, I tried to integrate v4. The flow was fine but it seems to face the same problem. It throws a error while rendering if I don't put checkout.js on the parent page. If its possible could you address this issue too? Its outright impossible to generate a flow with v4 right now.

I used v3.5 as I could at least get the flow running.

**Comment by bluepnume** [comment]
OK, good to know. At least for v3.5 integrations, we should probably either disable lightbox inside iframes, or do not attempt to render to the top level window.

I'll keep you updated.

**Comment by roy-prasenjit** [comment]
Thanks for the reply. We'll be going to production mid February. Please update me as soon as possible.

**Comment by roy-prasenjit** [comment]
@bluepnume Any updates? Is there a way to assign the context at our end?

**Comment by bluepnume** [comment]
@roy-prasenjit I have a fix I'm testing, should be able to push at some point this week.

**Comment by roy-prasenjit** [comment]
@bluepnume Thanks.

**Comment by bluepnume** [comment]
Fix is pushed. Please try and let me know if you still see the issue.

**Comment by roy-prasenjit** [comment]
@bluepnume  Sorry for the delay. We've been testing extensively and found a few bugs. 

Behavior after closing the current issue:
1. On clicking "Not You?" the pop up window opens up correctly without any glitches. The transactions went through smoothly. 
We've not faced any glitch until yesterday. 

New Issues:
When I click on "Not You?" 
1. The screen just freezes. I don't see a pop up or any other behavior.
or sometimes 
2. I see a legacy PayPal "pay now" page. 

Issue observed on token: EC-80654731VE903793M, EC-7YR80683LS4459833 and many such.

We've tagged the code for production deployment assuming everything is working smoothly. Could you help me out?

Contact Email: prasenjit.roy@ig.com

**Comment by bluepnume** [comment]
Found the issue. Looks like a typo was introduced in a search+replace: https://github.com/paypal/paypal-checkout/commit/6f5202ab70860dd2956506c87b8d9a989b9447dd#diff-cd8c0aad420cde534aacdb9cc76bfa0aR391

Didn't get caught by any tests. Thanks for catching this. I'm putting out a fix as we speak, I'll add some tests tomorrow to make sure this is caught next time.

**Comment by bluepnume** [comment]
Fix is released, please clear your cache and try once more. Let me know if you still see any problems.

Thanks again!
