### ISSUE TITLE
Billing Agreement without sale button

### ISSUE THREAD

**Issue by bluepnume** [paypal/paypal-checkout#172]
Would be good to render a button for when there's no sale. Need to come up with some good content. Possibly "Link PayPal"?

**Comment by vishakha94** [comment]
Do we need to contact UED or the content team for this?

**Comment by bluepnume** [comment]
@bsweetnam any updates on the content for this?

**Comment by bluepnume** [comment]
This is now live!

```
style: {
    label: 'pay'
}
```
