### ISSUE TITLE
developer.paypal.com doc improvements

### ISSUE THREAD

**Issue by bluepnume** [paypal/paypal-checkout#176]
- [x] Example of `payment.execute()` with payment details returned in response
- [x] Better example of mark integration
- [x] Links to demo app, when deployed
- [x] Pass experience profile to payment.create

**Comment by louisgan** [comment]
It will be best to have a detailed error response structure and example response. For example, error message seems to return a javascript error instead of a human readable error.

`{  
    "name": "ERROR_NAME",
    "message": "ERROR_DESCRIPTION",
    "information_link": "ERROR_DOCUMENTATION_LINK",
    "details": "ERROR_DETAILS"
}`

https://developer.paypal.com/docs/api/errors/
