### ISSUE TITLE
Prevent PayPal from logging in the console.

### ISSUE THREAD

**Issue by benplummer** [paypal/paypal-checkout#180]
Using a REST API advanced integration, is there a property or config option that can be passed to disable everything from being logged in the browser console in a sandbox environment?

**Comment by bluepnume** [comment]
There isn't right now. We depend a lot on folk being able to share these logs, to triage and debug issues. Are the logs causing problems?

**Comment by benplummer** [comment]
Sure, that's understandable. They aren't causing problems as such although it can be inconvenient scrolling through all of the PayPal logs in order to find a different thing you are logging.

The logs are also outputted inside things like Jasmine tests if you do not mock PayPal immediately.

**Comment by bluepnume** [comment]
Makes sense. I'm going to look into at least adding a log-level option.

**Comment by yabdab** [comment]
+1

**Comment by roy-prasenjit** [comment]
Any updates on this?

**Comment by bluepnume** [comment]
This feature is built, will update here when it's fully pushed.

**Comment by bluepnume** [comment]
This is now pushed and should be working in prod. Please let me know if you see any logs creeping through.
