### ISSUE TITLE
"Subscribe" label on button

### ISSUE THREAD

**Issue by Miguelcldn** [paypal/paypal-checkout#182]
I need to render two buttons from Paypal, one for buying and another one to subscribe. Is there any way I could make the subscription button to print "Subscribe" instead of "Pay now"?

The only almost-related code in the source is [here](https://github.com/paypal/paypal-checkout/blob/master/src/components/button/component.js#L229) but setting `label` to `subscribe` makes no difference.

**Comment by bluepnume** [comment]
We're working on adding a button for billing agreements. It'll read something long the lines of 'Link PayPal' but we're working on finalizing the wording. https://github.com/paypal/paypal-checkout/issues/172
