### ISSUE TITLE
Add test for IE intranet mode

### ISSUE THREAD

**Issue by bluepnume** [paypal/paypal-checkout#187]

**Comment by vishakha94** [comment]
What kind of test?

**Comment by bluepnume** [comment]
So, here we force IE in intranet mode to full-page checkout rather than checkout in a popup:

https://github.com/paypal/paypal-checkout/blob/master/src/lib/eligibility.js#L12

Need to add a few tests to make sure this works as expected.

Can probably base it off these test:

https://github.com/paypal/paypal-checkout/blob/master/test/tests/legacy/setup.js#L72
https://github.com/paypal/paypal-checkout/blob/master/test/tests/legacy/customclick.js#L473
https://github.com/paypal/paypal-checkout/blob/master/test/tests/legacy/hybrid.js#L271

**Comment by vishakha94** [comment]
- By full page checkout, do you mean opening a new tab? Also, why not checkout in a popup?

**Comment by bluepnume** [comment]
IE in intranet mode doesn't work in a popup, or a new tab. The only thing that works is doing a full redirect to Checkout -- i.e. `window.location = 'paypal.com/...'`

**Comment by bluepnume** [comment]
@vishakha94 can this be closed?

**Comment by bluepnume** [comment]
Fixed and live.
