### ISSUE TITLE
IE - detect UA compatible header, emit warning if absent

### ISSUE THREAD

**Issue by bluepnume** [paypal/paypal-checkout#189]
If the user is on IE9-11, the merchant should drop `<meta http-equiv="X-UA-Compatible" content="IE=edge">` to ensure the browser is not running in compatibility mode.

Our script should detect this, and emit a warning.

**Comment by vishakha94** [comment]
Done, ready to push.

**Comment by bluepnume** [comment]
Fixed and live.
