### ISSUE TITLE
Lightbox does not load Incontext pop up when clicking "Not You?"

### ISSUE THREAD

**Issue by roy-prasenjit** [paypal/paypal-checkout#197]
#165

**Comment by bluepnume** [comment]
Found the issue. Looks like a typo was introduced in a search+replace: https://github.com/paypal/paypal-checkout/commit/6f5202ab70860dd2956506c87b8d9a989b9447dd#diff-cd8c0aad420cde534aacdb9cc76bfa0aR391

Didn't get caught by any tests. Thanks for catching this. I'm putting out a fix as we speak, I'll add some tests tomorrow to make sure this is caught next time.

**Comment by bluepnume** [comment]
Fix is released, please clear your cache and try once more. Let me know if you still see any problems.

Thanks again!

**Comment by roy-prasenjit** [comment]
@bluepnume testing it, will keep you posted. Thanks for the quick update.

**Comment by roy-prasenjit** [comment]
@bluepnume Something's up again, could you look into it? 

![snipimage](https://cloud.githubusercontent.com/assets/5620833/23013101/432a94a4-f44f-11e6-99fa-153cab4b9303.JPG)

**Comment by bluepnume** [comment]
Can you paste the complete console logs?

**Comment by roy-prasenjit** [comment]
The behavior is intermittent. I'll upload them when I encounter it. Could you give me some time.

**Comment by bluepnume** [comment]
Sure. If it's intermittent, it's likely this is a temporary problem on sandbox. But I can hopefully confirm when you hit it and get some logs.

**Comment by roy-prasenjit** [comment]
@bluepnume 
![1](https://cloud.githubusercontent.com/assets/5620833/23019068/8c7ab870-f466-11e6-8b24-57f453a39243.PNG)
![2](https://cloud.githubusercontent.com/assets/5620833/23019072/909fc224-f466-11e6-8fca-6fdea0882489.PNG)

I have the log file, how can I share it. Should I just copy it here entirely?

**Comment by roy-prasenjit** [comment]
VM1214 checkout.js:4879 ppxo_xc_ppcheckout_send_to_parent_xcomponent_hide Object {timestamp: 1487243228674, windowID: "d09f31db9a", pageID: "c95dda832a", host: "www.sandbox.paypal.com", path: "/checkoutnow"…}
VM1214 checkout.js:2333 [post-robot] iframe :: www.sandbox.paypal.com/checkoutnow 

	 #send request :: xcomponent_hide :: https://web-cpm.ig.com 

 Object {hash: "xcomponent_hide_746317cdb7", type: "postrobot_message_request", name: "xcomponent_hide", data: undefined, fireAndForget: undefined…}
VM1214 checkout.js:4879 ppxo_xc_ppcheckout_construct_parent Object {timestamp: 1487243228695, windowID: "d09f31db9a", pageID: "c95dda832a", host: "www.sandbox.paypal.com", path: "/checkoutnow"…}
VM1214 checkout.js:4879 ppxo_xc_ppcheckout_render_popup_to_win Object {element: null, context: "popup", timestamp: 1487243228703, windowID: "d09f31db9a", pageID: "c95dda832a"…}
VM1214 checkout.js:4879 ppxo_xc_ppcheckout_delegate_popup Object {timestamp: 1487243228706, windowID: "d09f31db9a", pageID: "c95dda832a", host: "www.sandbox.paypal.com", path: "/checkoutnow"…}
VM1214 checkout.js:2333 [post-robot] iframe :: www.sandbox.paypal.com/checkoutnow 

	 #send request :: xcomponent_delegate_ppcheckout :: * 

 Object {hash: "xcomponent_delegate_ppcheckout_dbc14a8eaf", type: "postrobot_message_request", name: "xcomponent_delegate_ppcheckout", data: Object, fireAndForget: undefined…}
VM1214 checkout.js:4879 ppxo_xc_ppcheckout_render_popup Object {context: "popup", element: null, loadUrl: "popup", timestamp: 1487243228719, windowID: "d09f31db9a"…}
VM1214 checkout.js:4879 ppxo_xc_ppcheckout_open_popup Object {element: null, windowName: "xcomponent__ppcheckout__4__pmrhk2leei5cem3bge2gmy3…hi4dthixs653xo4xhgylomrrg66boobqxs4dbnqxgg33nej6q", timestamp: 1487243228722, windowID: "d09f31db9a", pageID: "c95dda832a"…}
VM1214 checkout.js:4879 ppxo_xc_ppcheckout_resize Object {height: 850, width: 970, timestamp: 1487243228765, windowID: "d09f31db9a", pageID: "c95dda832a"…}
VM1214 checkout.js:2333 [post-robot] iframe :: web-cpm.ig.com/wt-payments-ui/paypal-payments/paypaliframe 

	 #receive request :: xcomponent_hide :: https://www.sandbox.paypal.com 

 Object {hash: "xcomponent_hide_746317cdb7", type: "postrobot_message_request", name: "xcomponent_hide", domain: "https://web-cpm.ig.com", sourceDomain: "https://www.sandbox.paypal.com"…}
VM1214 checkout.js:4879 ppxo_xc_ppcheckout_listener_hide Object {timestamp: 1487243228815, windowID: "163701ca67", pageID: "6d906f88b6", host: "web-cpm.ig.com", path: "/wt-payments-ui/paypal-payments/paypaliframe"…}
VM1214 checkout.js:2333 [post-robot] iframe :: web-cpm.ig.com/wt-payments-ui/paypal-payments/paypaliframe 

	 #send response :: xcomponent_hide :: https://www.sandbox.paypal.com 

 Object {target: undefined, hash: "xcomponent_hide_746317cdb7", name: "xcomponent_hide", type: "postrobot_message_response", ack: "success"…}
VM1214 checkout.js:4879 ppxo_xc_ppcheckout_call_prop_fallback Object {timestamp: 1487243228831, windowID: "163701ca67", pageID: "6d906f88b6", host: "web-cpm.ig.com", path: "/wt-payments-ui/paypal-payments/paypaliframe"…}
VM1214 checkout.js:4879 ppxo_paypal_legacy_fallback_handler Object {url: "https://www.sandbox.paypal.com/webapps/hermes/fall…ible&token=EC-0DR756786K9521327&useraction=commit", timestamp: 1487243228832, windowID: "163701ca67", pageID: "6d906f88b6", host: "web-cpm.ig.com"…}
print @ VM1214 checkout.js:4879
log @ VM1214 checkout.js:5006
error @ VM1214 checkout.js:5026
fallback @ VM1214 checkout.js:12950
value @ VM1214 checkout.js:9788
(anonymous) @ VM1214 checkout.js:6806
(anonymous) @ VM1214 checkout.js:3060
_loop2 @ VM1214 checkout.js:1847
SyncPromise.dispatch @ VM1214 checkout.js:1877
SyncPromise.then @ VM1214 checkout.js:1895
run @ VM1214 checkout.js:1618
(anonymous) @ VM1214 checkout.js:3059
(anonymous) @ VM1214 checkout.js:1657
_loop2 @ VM1214 checkout.js:1847
SyncPromise.dispatch @ VM1214 checkout.js:1877
SyncPromise.then @ VM1214 checkout.js:1895
run @ VM1214 checkout.js:1618
(anonymous) @ VM1214 checkout.js:1656
trycatch @ VM1214 checkout.js:1699
SyncPromise @ VM1214 checkout.js:1794
deNodeify @ VM1214 checkout.js:1649
(anonymous) @ VM1214 checkout.js:3334
_loop2 @ VM1214 checkout.js:1847
SyncPromise.dispatch @ VM1214 checkout.js:1877
SyncPromise.then @ VM1214 checkout.js:1895
run @ VM1214 checkout.js:1618
(anonymous) @ VM1214 checkout.js:3326
receiveMessage @ VM1214 checkout.js:1493
messageListener @ VM1214 checkout.js:1511
VM1214 checkout.js:4879 ppxo_xc_ppcheckout_destroy Object {timestamp: 1487243228834, windowID: "163701ca67", pageID: "6d906f88b6", host: "web-cpm.ig.com", path: "/wt-payments-ui/paypal-payments/paypaliframe"…}
VM1214 checkout.js:4879 ppxo_window_unload Object {timestamp: 1487243228839, windowID: "d09f31db9a", pageID: "c95dda832a", host: "www.sandbox.paypal.com", path: "/checkoutnow"…}
VM1214 checkout.js:5112 XHR failed loading: POST "https://www.sandbox.paypal.com/webapps/hermes/api/logger".
(anonymous) @ VM1214 checkout.js:5112
N @ VM1214 checkout.js:5313
h @ VM1214 checkout.js:5336
ajax @ VM1214 checkout.js:5090
immediateFlush @ VM1214 checkout.js:4952
(anonymous) @ VM1214 checkout.js:5685
(anonymous) @ VM1214 checkout.js:9419
run @ VM1214 checkout.js:5927
all @ VM1214 checkout.js:5939
(anonymous) @ VM1214 checkout.js:9281
_loop2 @ VM1214 checkout.js:1847
SyncPromise.dispatch @ VM1214 checkout.js:1877
SyncPromise.then @ VM1214 checkout.js:1895
syncPromiseTry @ VM1214 checkout.js:1940
destroy @ VM1214 checkout.js:9277
fallback @ VM1214 checkout.js:12953
value @ VM1214 checkout.js:9788
(anonymous) @ VM1214 checkout.js:6806
(anonymous) @ VM1214 checkout.js:3060
_loop2 @ VM1214 checkout.js:1847
SyncPromise.dispatch @ VM1214 checkout.js:1877
SyncPromise.then @ VM1214 checkout.js:1895
run @ VM1214 checkout.js:1618
(anonymous) @ VM1214 checkout.js:3059
(anonymous) @ VM1214 checkout.js:1657
_loop2 @ VM1214 checkout.js:1847
SyncPromise.dispatch @ VM1214 checkout.js:1877
SyncPromise.then @ VM1214 checkout.js:1895
run @ VM1214 checkout.js:1618
(anonymous) @ VM1214 checkout.js:1656
trycatch @ VM1214 checkout.js:1699
SyncPromise @ VM1214 checkout.js:1794
deNodeify @ VM1214 checkout.js:1649
(anonymous) @ VM1214 checkout.js:3334
_loop2 @ VM1214 checkout.js:1847
SyncPromise.dispatch @ VM1214 checkout.js:1877
SyncPromise.then @ VM1214 checkout.js:1895
run @ VM1214 checkout.js:1618
(anonymous) @ VM1214 checkout.js:3326
receiveMessage @ VM1214 checkout.js:1493
messageListener @ VM1214 checkout.js:1511
VM1214 checkout.js:4879 ppxo_redirect Object {url: "https://www.sandbox.paypal.com/webapps/hermes/fall…ible&token=EC-0DR756786K9521327&useraction=commit", timestamp: 1487243228884, windowID: "163701ca67", pageID: "6d906f88b6", host: "web-cpm.ig.com"…}
VM1214 checkout.js:4879 ppxo_window_beforeunload Object {timestamp: 1487243229180, windowID: "163701ca67", pageID: "6d906f88b6", host: "web-cpm.ig.com", path: "/wt-payments-ui/paypal-payments/paypaliframe"…}
VM1334 checkout.js:4879 ppxo_window_beforeunload Object {timestamp: 1487243229181, windowID: "6b16172254", pageID: "150534eebd", host: "www.sandbox.paypal.com", path: "/webapps/hermes/component-meta"…}
VM1334 checkout.js:5112 XHR finished loading: POST "https://www.sandbox.paypal.com/webapps/hermes/api/logger".
(anonymous) @ VM1334 checkout.js:5112
N @ VM1334 checkout.js:5313
h @ VM1334 checkout.js:5336
ajax @ VM1334 checkout.js:5090
immediateFlush @ VM1334 checkout.js:4952
(anonymous) @ VM1334 checkout.js:5681
VM1214 checkout.js:5112 XHR finished loading: POST "https://www.paypal.com/webapps/hermes/api/logger".
(anonymous) @ VM1214 checkout.js:5112
N @ VM1214 checkout.js:5313
h @ VM1214 checkout.js:5336
ajax @ VM1214 checkout.js:5090
immediateFlush @ VM1214 checkout.js:4952
(anonymous) @ VM1214 checkout.js:5131
C @ VM1214 checkout.js:5299
(anonymous) @ VM1214 checkout.js:5417
t @ VM1214 checkout.js:5223
VM1214 checkout.js:5112 XHR finished loading: POST "https://www.paypal.com/webapps/hermes/api/logger".
(anonymous) @ VM1214 checkout.js:5112
N @ VM1214 checkout.js:5313
h @ VM1214 checkout.js:5336
ajax @ VM1214 checkout.js:5090
immediateFlush @ VM1214 checkout.js:4952
(anonymous) @ VM1214 checkout.js:5681
VM1214 checkout.js:4879 ppxo_window_unload Object {timestamp: 1487243231922, windowID: "163701ca67", pageID: "6d906f88b6", host: "web-cpm.ig.com", path: "/wt-payments-ui/paypal-payments/paypaliframe"…}
VM1334 checkout.js:4879 ppxo_window_unload Object {timestamp: 1487243231923, windowID: "6b16172254", pageID: "150534eebd", host: "www.sandbox.paypal.com", path: "/webapps/hermes/component-meta"…}
VM1334 checkout.js:5112 XHR failed loading: POST "https://www.sandbox.paypal.com/webapps/hermes/api/logger".
(anonymous) @ VM1334 checkout.js:5112
N @ VM1334 checkout.js:5313
h @ VM1334 checkout.js:5336
ajax @ VM1334 checkout.js:5090
immediateFlush @ VM1334 checkout.js:4952
(anonymous) @ VM1334 checkout.js:5685
VM1214 checkout.js:5112 XHR failed loading: POST "https://www.paypal.com/webapps/hermes/api/logger".
(anonymous) @ VM1214 checkout.js:5112
N @ VM1214 checkout.js:5313
h @ VM1214 checkout.js:5336
ajax @ VM1214 checkout.js:5090
immediateFlush @ VM1214 checkout.js:4952
(anonymous) @ VM1214 checkout.js:5685

**Comment by bluepnume** [comment]
So, what you're seeing is a fallback, which happens during some error case. Unfortunately, this is more frequent on sandbox than production -- services go down, or get overloaded, and the app fails over to the legacy experience.

I checked your specific transaction, and looks like that's what happened here. The good news is, this should not happen in production. I'll pass on the failure to the relevant team though, so they can take a look.

**Comment by roy-prasenjit** [comment]
Ohk, thanks for the update. 

Regarding the initial issue, it's all working well. No glitch during the transaction. Thanks again for all the support.
