### ISSUE TITLE
Issues with trying to automate the checkout

### ISSUE THREAD

**Issue by luke-hill** [paypal/paypal-checkout#199]
Apologies if this is the wrong place, I searched the entire set of paypal repos and couldn't find one for ruby automation.

I'm having difficulty using selenium to try scrape the webpage of a test paypal integration. We have our own setup for our sandboxes (Test Environments). But when I get to the login page after being redirected from our checkout, there is part of the page that is unscrapeable.

Is this deliberate, and if so, can't we try do something about this as it is technically only a development site (And no real money is taken)

Using Selenium `2.53.4` webdriver Ruby Using any / all browsers on Windows 7 and Selenium Grid (Also using Macs)

**Comment by bluepnume** [comment]
Which part of the page is unscrapeable? I'm pretty sure we don't have any specific restrictions in place to prevent selenium testing on sandbox.

**Comment by luke-hill** [comment]
I'll post code code snippets. Showing the issues I'm having. Thanks for the speedy response

**Comment by bluepnume** [comment]
So, that entire section of the page is an iframe:

<img width="1264" alt="screen shot 2017-02-18 at 10 38 26" src="https://cloud.githubusercontent.com/assets/1219075/23095867/71952ef8-f5c6-11e6-903b-d18c18491976.png">

I'm not 100% familiar with selenium, but is there any way to reach down into an iframe and run `.find('#email')` in that context?

**Comment by luke-hill** [comment]
Yes there is. As it so happens that was going to be my next check.

Can we leave this open for the time being, give me say a week or so, and I'll get back to you.

Cheers for speedy reply

Luke

**Comment by luke-hill** [comment]
Good news and bad news.

Good news: That iframe worked. Had a bit of an issue hooking onto it but got there.

Bad news: It seems as though (After speaking to some of our seniors), that the sandbox gateway is very slow and prone to 502s, making testing the full e2e path not possible

**Comment by bluepnume** [comment]
Glad to hear the frame worked. Sorry that sandbox is so slow / error prone. I've passed on your note to the relevant team.

One option may be to run tests against production, but not execute the transaction and move the money -- if that's helpful.

**Comment by luftgekuhlt** [comment]
Hi, I am having a similar problem with the sandbox paypal-checkout in my Selenium automation flow.

The paypal check-out page I am led to contains the userid set earlier in my own website.
I am having problems thou inserting the password. Any action on password field (click, send keys) throws an ElementNotVisibleException error : 

```
Test Cases/Test Cases/z64 BOOKING PAYPAL FAILED because (of) org.openqa.selenium.ElementNotVisibleException: element not visible
  (Session info: chrome=64.0.3282.186)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:36.161Z'
System info: host: 'XXX077-PC034SPL', ip: '9.xx.xxx.179', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_102'
Driver info: com.kms.katalon.selenium.driver.CChromeDriver
Capabilities {acceptSslCerts: true, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.33.506120 (e3e53437346286..., userDataDir: C:\Users\A_AD~1\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 64.0.3282.186, webStorageEnabled: true}
Session ID: 6cb0cd3c763411139146fd10319440ff
```
