### ISSUE TITLE
Did token get changed to paymentToken ?

### ISSUE THREAD

**Issue by yabdab** [paypal/paypal-checkout#200]
My code expects "token" as the key returned onAuthorize. This morning that stopped and "paymentToken" was returned instead. Was this an announced change?

**Comment by bluepnume** [comment]
The button has always returned `paymentToken`... I checked the code history and it's always been that way. Are you sure it was working for you previously with `token`? 

Also, do you have a reference to the doc you used which specified `data.token`?

**Comment by yabdab** [comment]
Not sure, but I took apart the data object originally and the key was "token" , not "paymentToken". 

I am referring to the callback data returned for onAuthorize.  I am not sure this comes from the checkout.js script.

**Comment by bluepnume** [comment]
That's strange. I've triple checked the code history for both the button and the checkout component which call `onAuthorize` (in internal paypal repos), and they both show `paymentToken` being passed back, from the original point the code was implemented. 

Would love to find the cause of this one and see if anyone else is having the same problem. But I'm drawing blanks right now...
