### ISSUE TITLE
Need to enable CORS?

### ISSUE THREAD

**Issue by amedrz** [paypal/paypal-checkout#201]
I'm trying to integrate this on a Ruby on Rails app using the approach described [here](https://github.com/paypal/paypal-checkout/blob/master/docs/hybrid.md#create-and-execute-the-payment-on-your-server-side).

When I click on the Paypal payment button and right after a Payment ID returned, the browser (Chrome v56.0.2924.87) returns the following errors in the console and the next step never shows up.

```
Refused to display 'https://www.paypal.com/webapps/hermes/fallback?product=ec&fallback=1&token=PAY-XXXXXXXXXXX www.paypal.com/webapps/hermes/fallback?product=ec&fallback=1&token=PAY-XXXXXXXXXXX' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.
Unrecognized Content-Security-Policy directive 'reflected-xss'.
```

Any hint what's going on? Not sure how I could fix that on my end.

Thanks!

**Comment by bluepnume** [comment]
Could you please provide:

a) An example of a PAY-XXXXXX id
b) The approximate time it was created

That way I can look up some of the logs on our side. It looks like the transaction hit an error, but need to narrow that down.

Thanks!

**Comment by amedrz** [comment]
Hey @bluepnume, sure:

A) PAY-30N35375RE545225KLCU7ABA
B) 2017-02-19T19:20:36Z

Let me know if you need anything else.

Thank you!

**Comment by bluepnume** [comment]
OK, so looks like you're creating a payment id (PAY-XXXX) against sandbox.paypal.com, but then loading checkout on production paypal.com.

Do you have `env: 'sandbox'` set in your button?

Hope that helps!

**Comment by bluepnume** [comment]
https://github.com/paypal/paypal-checkout/issues/202

**Comment by amedrz** [comment]
Excelent! That made the trick.

Thanks for your help!

**Comment by bluepnume** [comment]
Glad it worked!
