### ISSUE TITLE
Closing lightbox/modal on failure

### ISSUE THREAD

**Issue by amedrz** [paypal/paypal-checkout#204]
Assuming the following  implementation:

```javascript
paypal.Button.render({

    payment: function(resolve, reject) {

        jQuery.post('/my-api/create-payment')
            .done(function(data) { resolve(data.paymentID); })
            .fail(function(err) { reject(err); });
    },
...
````
And that the server returns either 4xx or 5xx status, what kind of object I should pass to `reject` as parameter so that it can proceed and finally close the modal?

Just passing down `err` wouldn't work because it's an `jqXHR` object.

Thanks!

**Comment by bluepnume** [comment]
You should be able to pass any object to `reject` and it will be treated as an error. Alternatively, you can just pass down something like `reject(new Error('Create payment XHR failed'))`.

**Comment by amedrz** [comment]
Thanks @bluepnume 

It works as expected when I pass down `reject(new Error('Create payment XHR failed'))` (as you suggested).

On the other hand, when I pass down the coming `jqXHR` (`reject(err)`) object I get:
```
Uncaught Error: Can not reject promise with another promise
    at SyncPromise.reject (promise.js:186)
    at promise.js:147
    at flush (promise.js:12)
    at promise.js:27
    at Object.<anonymous> (27949:1347)
    at fire (jquery.self-c0aeac3….js?body=1:3049)
    at Object.fireWith [as rejectWith] (jquery.self-c0aeac3….js?body=1:3161)
    at done (jquery.self-c0aeac3….js?body=1:8238)
    at XMLHttpRequest.callback (jquery.self-c0aeac3….js?body=1:8779)
```
Not sure if that's the expected behavior on your end, but just wanted to put that clear.

**Comment by bluepnume** [comment]
Oh interesting, I guess that `jqXHR` object has a `.then` method and ends up looking like a promise. Seems kind of non-standard -- but anyway, yeah, the `new Error` approach will definitely work.

**Comment by evgrud** [comment]
Did something happen that this no longer works? I used to be able to close the PayPal popup with `return false` inside the `payment` callback. Now that doesn't work, and I tried doing `resolve(new Error('my error'))` inside the `payment` callback, and this doesn't work either (doesn't close the popup).

**Comment by bluepnume** [comment]
@evgrud you need to call `reject` not `resolve`

```
paypal.Button.render({

    payment: function(resolve, reject) {

        return reject(new Error('my error'))
    },
...
```

**Comment by evgrud** [comment]
My apologies! I meant that I'm calling `reject`. Edited the original post.

**Comment by evgrud** [comment]
Apologies! I meant that I'm calling `reject`. Edited my original post. I also tried your form of `return reject` and it displays the same behavior.

**Comment by superp** [comment]
Why my PayPal button was hiding when I call reject in inside payment method?
Popup closed successfully, but button disappeared (

**Comment by evgrud** [comment]
I got a mail notification of a new comment that since has been deleted, but its content correctly describes the current state of this issue for me too:

Now after calling `reject` the popup closes, but the PayPal button disappears. Is it by design?

**Comment by superp** [comment]
@evgrud Sorry for my comment. I have removed it, just saw really a problem. 
I use angular and, after form submit, it doesn't rebuild my PayPal button.

**Comment by bluepnume** [comment]
Hey @evgrud can you please clear your cache and try now?

@superp -- if you're seeing an issue with angular still, can you raise another issue for it?

**Comment by superp** [comment]
@bluepnume No, I find a problem and fixed them.
Therefore I removed my comment )

**Comment by evgrud** [comment]
:+1: It's all good now, even the old `return false` works as previously. I guess I'll change it to `return reject` to work by your guidelines.
