### ISSUE TITLE
Cancel and Return URL loading in In Context window during PayPal Credit application flow

### ISSUE THREAD

**Issue by jseebs** [paypal/paypal-checkout#206]
When a buyer is in the In Context window and selects Apply for PayPal Credit, on the PayPal Credit application page when clicking on Cancel and Return link the Cancel and Return URL loads within the In Context modal.  The correct functionality would be to click on Cancel and Return link then the In Context modal closes and loads the proper Cancel and Return URL within the primary browser window.

**Comment by jseebs** [comment]
I am able to reproduce in live, here is my EC Token and Cal ID
EC-4L030867CG520840W
3ee300e55dde5

**Comment by jseebs** [comment]
Can we receive any type of update of when this will be looked into and possibly resolved, this is preventing Large Enterprise merchant from moving traffic to > 25%

**Comment by bluepnume** [comment]
We've identified the problem, and we're looking into the right solve. Hopefully should be able to make a fix over the course of next week. Will update when I have a timeframe for releasing the fix.

**Comment by bluepnume** [comment]
Bulk of the work for this is done through https://github.com/paypal/paypal-checkout/issues/251. Just need to integrate into the credit app and get a pr merged.

Seems like this case has actually never worked for in-context. Guess that was a miss with the original credit app integration.

**Comment by bluepnume** [comment]
OK, PR made into the credit application app. It's in their hands now to merge and release, I'll update here when with progress.
