### ISSUE TITLE
Set payee ?

### ISSUE THREAD

**Issue by youradds** [paypal/paypal-checkout#210]
Hi,

Is this an option in this plugin? 

https://devblog.paypal.com/setting-payee/

I'm aware its quite a new feature, so just wanted to check. Would LOVE if it is, as it would get over a development hurdle I've come across. I did have a look over your docs, but couldn't see anything about how to pass it in (if its even possible)

Thanks

Andy

**Comment by yabdab** [comment]
I have been using the "payee" option for many months now. It was in the API docs. Maybe they are just now getting around to formally announcing it via the blog post?

**Comment by youradds** [comment]
Ah cool! Will give it a go in a bit then. 

I wish they had announced this back then, as I actually asked the question over a month ago (and had to go with another solution, as they didn't offer a way to send to other people)

Is there a way to get the buyers address details back with this method? We were using the Adaptive Payments system before, but that doesn't return the address info of the buyer (to go in the invoice). 

Otherwise, it sounds perfect! (and should really help with conversion rates)

**Comment by yabdab** [comment]
I believe that is returned after you execute the payment using the paymentID.

**Comment by youradds** [comment]
Ah ok. I thought I tried that before but maybe I didn't. Will give it another whirl over the weekend. 

Thanks! Thats made my day :)

**Comment by bluepnume** [comment]
Yep, payee should work perfectly with paypal-checkout. Please let me know if you have any problems! Thanks

**Comment by acomito** [comment]
@bluepnume should this be re-opened per the below issue?

https://github.com/paypal/paypal-checkout/issues/464
