### ISSUE TITLE
Checkout tiny button incorrectly rendered

### ISSUE THREAD

**Issue by vishakha94** [paypal/paypal-checkout#215]
The checkout tiny pill/rect button is incorrectly rendered in 
Firefox and Opera. Button gets cut off from the bottom.

**Comment by bluepnume** [comment]
Can you re-check this with the latest changes? Looks good in firefox to me. Haven't checked opera yet.

**Comment by vishakha94** [comment]
Opera is fine. The tiny button gets cut off in Firefox v30.0.
Used http://bluesuncorp.co.uk/icv4/allbutton.htm
to check with latest changes.
