### ISSUE TITLE
Support web-views for 3rd party merchants

### ISSUE THREAD

**Issue by bluepnume** [paypal/paypal-checkout#217]
Right now, if a merchant is loaded via a third-party app's webview -- like say, a user loads a merchant site in Facebook through a webview -- the paypal-checkout button does not work. This is because opening a popup window in a web-view without the support of the hosting app is not possible.

There's an SDK in the works to support first-party app/webview cases, but for third-party webviews we also need a solve. Adding this issue to track. Should be able to have something out to solve this in the next week.

**Comment by bluepnume** [comment]
Fixed and ready to push.

**Comment by bluepnume** [comment]
Fixed and pushed.

**Comment by sushiguru** [comment]
I see this was pushed on 9th Mar but I'm hitting this issue today (and it sucked 3h of my life trying to debug); did this get a PR and was it accepted? If so, how should it be implemented so that the checkout will work within a webview within the facebook app?

**Comment by bluepnume** [comment]
Hi @sushiguru -- there shouldn't be anything special you need to do. What's the specific problem you're seeing?

**Comment by sushiguru** [comment]
Hi Daniel

I'm seeing as described inside the fb app in windows 10; on click of the
paypal button I get the white screen of death instead of the popup.  Works
in browser exactly as expected.

Cheers,
Gary.

**Comment by bluepnume** [comment]
Does it work when you view this page from a FB webview? https://developer.paypal.com/demo/checkout/

**Comment by sushiguru** [comment]
Let me check - I'll have to post it in a test page I have in FB...

A curse on all FB devs.

**Comment by sushiguru** [comment]
Hi Daniel

Alas, no; same behaviour:

[image: Inline images 1]

**Comment by sushiguru** [comment]
Just now have a very, very (makes me want to shower) hacky workaround of
browser sniffing for the fb app and throwing up an alert dialogue to tell
users to open the page in a browser instead.

Cheers,
Gary.

**Comment by bluepnume** [comment]
OK, that's a little worrying then.

The issue with webviews is that we can't open popup windows. The fix in checkout.js is to detect the webview based on the user-agent, and load the checkout experience inside an iframe instead.

I'm wondering if the Facebook app changed its user agent and that detection broke. Any chance you could browse to http://www.useragentstring.com/ for me, and copy the user agent you see?

**Comment by sushiguru** [comment]
Just about to; for info, here's my browser sniff which works:

function isFacebookApp() {
    var ua = navigator.userAgent || navigator.vendor || window.opera;
    return (ua.indexOf("FBAN") > -1) || (ua.indexOf("FBAV") > -1);
}

if (isFacebookApp()) {
    window.alert("This page WILL NOT WORK within the Facebook App...

**Comment by sushiguru** [comment]
Mozilla/5.0 (Windows NT 10.0.15063.608; osmeta 9.3.1233)
AppleWebKit/602.1.1 (KHTML, like Gecko) Version/9.0 Safari/602.1.1
osmeta/9.3.1233 Build/1233
[FBAN/FBW;FBAV/93.0.0.64.0;FBBV/62624619;FBDV/WindowsDevice;FBMD/GL502VT;FBSN/Windows;FBSV/10.0.15063.608;FBSS/1;FBCR/;FBID/desktop;FBLC/en_GB;FBOP/45;FBRV/0]

**Comment by bluepnume** [comment]
Damn it, yeah, looks like this user agent isn't being detected as a web view. Guessing in that case FB must have changed its user-agent. I'll get a fix in for this. Thanks @sushiguru for the heads up!

**Comment by sushiguru** [comment]
You're welcome - hope the fix isn't too much pain for you.  Thanks for your
work on this - I've enjoyed playing with the javascript checkout today
(only used the pre-built buttons up until now but really needed to capture
a successful payment to write to db afterwards). Probably the worst
implementation of it, but my development was always ropey...

Cheers,
Gary..

**Comment by bluepnume** [comment]
No prob at all. Need to find a way to mitigate for this in future, if it changes again.

Opened https://github.com/paypal/paypal-checkout/issues/484 to track.

**Comment by leosek** [comment]
Hi, I'm facing the same problem. Will this be fixed somehow? I'm loading this script: https://www.paypalobjects.com/api/checkout.js and from FB app customers cannot pay.

**Comment by bluepnume** [comment]
@leosek -- which platform? Also windows phone?

**Comment by leosek** [comment]
Apple iOS

**Comment by bluepnume** [comment]
OK thanks -- same question, what's the user-agent you see when you hit http://www.useragentstring.com/ in the facebook app?

**Comment by leosek** [comment]
Would you like to test it? I have a website with sandbox account attached where this behaivour can be tested if you want.
Actually I can see two different behaviors. 1) We can pay, but the paypal form disappearing while typing credentials - see screenshots - cursor on the page, not in input field of paypal window. String: Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Mobile/14G60 [FBAN/FBIOS;FBAV/143.0.0.76.90;FBBV/73343453;FBDV/iPhone5,2;FBMD/iPhone;FBSN/iOS;FBSV/10.3.3;FBSS/2;FBCR/T-MobileCZ;FBID/phone;FBLC/cs_CZ;FBOP/5;FBRV/0] - iPhone 5s
![img_0268](https://user-images.githubusercontent.com/1538437/31093794-27b7abfe-a7b3-11e7-9278-91a03bfad58b.PNG)
![img_0269](https://user-images.githubusercontent.com/1538437/31093795-27b8f2fc-a7b3-11e7-9c21-985d590e6cd0.PNG)
![img_0270](https://user-images.githubusercontent.com/1538437/31093797-27cf5718-a7b3-11e7-8ba1-e32b500b1036.PNG)
![img_0271](https://user-images.githubusercontent.com/1538437/31093796-27cf59d4-a7b3-11e7-8669-1e5be566aa07.PNG)
![img_0272](https://user-images.githubusercontent.com/1538437/31093798-27da7274-a7b3-11e7-917e-34cb7a3929d2.PNG)

I will try to check it on iPhone of my colleague - he cannot at all.
