### ISSUE TITLE
Possible Legacy bug.  Condition not preventing default

### ISSUE THREAD

**Issue by trainerbill** [paypal/paypal-checkout#222]
In v3 when the condition: function returned false nothing was supposed to happen.  It is now going to the default functionality.  It still goes to the default functionality event if i set click: preventDefault

https://plnkr.co/edit/mVHsPCcTRyguKuoMo0rY?p=preview

It is navigating to the href instead of doing nothing since validation function failed.  I also tried this with a form tag and it is the same result.

This is probably affecting legacy integrations using the condition property.

**Comment by bluepnume** [comment]
Looks like a valid bug. Seems to only be happening for hijack cases, rather than initXO/startFlow. 

I think I see the issue, need to figure out why the tests weren't catching this already. Good find!

**Comment by bluepnume** [comment]
Fixed and ready to push.

For the record -- doesn't look like this particular case *ever* worked. Fixing it here though because it makes sense for `condition` to be able to block form/a tag integrations.

**Comment by bluepnume** [comment]
Fixed and pushed.
