### ISSUE TITLE
(bug|button): Iframe border showing after on click 

### ISSUE THREAD

**Issue by trainerbill** [paypal/paypal-checkout#225]
This is in chrome.

Before click:
![image](https://cloud.githubusercontent.com/assets/3578259/23597376/02c010d6-01f8-11e7-851e-f45dbf933f46.png)

Immediatlely after click there is a flash of the border.  Nothing during the flow.

![image](https://cloud.githubusercontent.com/assets/3578259/23597391/1dfd5bc4-01f8-11e7-91c9-f3b504fe0ab3.png)

Close down the popup

![image](https://cloud.githubusercontent.com/assets/3578259/23597404/348cf5a2-01f8-11e7-82ff-6f66e7047fc8.png)

Stays this way until you click again

**Comment by bluepnume** [comment]
Can you advise on the chrome version?

**Comment by trainerbill** [comment]
Version 56.0.2924.87 on Windows
Version 55 on Windows
Does not occur in firefox.
Version 56 in Ubuntu


Here is an image off of the sample app.
![image](https://cloud.githubusercontent.com/assets/3578259/23617404/a6e60e18-0252-11e7-9bec-c11894a9d00d.png)

**Comment by bluepnume** [comment]
OK. Pretty sure this is a chrome accessibility feature. I have a css fix in place ready to push.

**Comment by bluepnume** [comment]
Fix pushed. Please let me know if you see a re-occurence of this.
