### ISSUE TITLE
Turning off receiving limit

### ISSUE THREAD

**Issue by timmtrede** [paypal/paypal-checkout#227]
Probably I'm in the wrong repository, but I think this is the fastest way. The customer service is making me crazy and says there is no bug....

German Paypal, trying to to turn off the receiving limit. So what have I done:
Trying to set myself as the only owner of a capital company. At the first click nothing happens, at the second click I receive the error pop up.

(Browser: Firefox)

I hope someone can help.

Best regards
Timm

![grafik](https://cloud.githubusercontent.com/assets/17588971/23621957/00dc6062-029d-11e7-9d5c-fcf92be06573.png)

**Comment by bluepnume** [comment]
Hi,

This repo is more for javascript integrations, specifically, but I'm hoping @trainerbill can help triage this to the right folk.

**Comment by trainerbill** [comment]
@timmtrede I am asking around.  When I find someone is there an email that they can reach out to you at?

**Comment by timmtrede** [comment]
timm.trede@zipmend.com

Thanks

**Comment by trainerbill** [comment]
Thanks.  I am reaching out to some contacts in Germany but may not hear back till tomorrow.  I am going to close this issue.
