### ISSUE TITLE
Responsive PayPal Subscription Checkout?

### ISSUE THREAD

**Issue by AlexioVay** [paypal/paypal-checkout#234]
**About 90%+ of my website users are using the mobile page.** I offer a monthly membership subscription plan and just build the PayPal subscription form with PHP.

After all data is sent, it opens up the PayPal page and this big image appears in a tiny on Smartphone version, because it isn't responsive like the rest of my website:

[![enter image description here][1]][1]

Normal payments are responsive but subscriptions are not. I offer other payment services like GoCardless but need to offer the PayPal solution too. Many users would get confused and cancel the payment.

However, I kept searching for other solutions for some days now and there is this JavaScript option available: https://github.com/paypal/paypal-checkout/blob/master/docs/button.md

This opens up a popup on my site and it seems like to be the solution but I couldn't find an option for subscriptions also.

What alternatives do I have or did I overlook something? I just need a responsive solution for PayPal subscriptions to get monthly payments.

  [1]: https://i.stack.imgur.com/cjdFe.png

**Comment by bluepnume** [comment]
You should probably be able to set up recurring payments with EC, and use the EC token with the button provided here. @trainerbill can you point in the right direction?

**Comment by trainerbill** [comment]
@AlexioVay If you want to use this javascript library, it will be a little more complex than your current form setup.

First install the PHP REST SDK on your server:  https://github.com/paypal/PayPal-PHP-SDK.
Create a REST APP at developer.paypal.com and get your client / secret.
You will need to use the api to create new billing plans:  https://developer.paypal.com/docs/api/payments.billing-plans
Example: https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/billing/CreatePlan.php


Once you have a plan id, then you can use this library to subscribe people to your billing plan.

**Comment by AlexioVay** [comment]
Thank you for these instructions. I have to get into that to understand it more, but before that I wanted to ask first, if this javascript library is **the** (only) solution creating a responsive experience for the user to set up a new subscription?

Just to understand: Are these billing plans comperable to the form input variables I can set to define payment cycles, price, etc (a3, t3, ...) ?

**Comment by AlexioVay** [comment]
I studied the docs and understand the whole API more and more. I also created a billing, received a Plan ID, updated it, created an agreement and get the EC-token now. Because here #131 it's suggested that the EC-token should be the id to pass to `resolve`.

I tried it this way:
```
    payment: function(resolve, reject) {
        jQuery.post('https://vaysystem.com/paypal-sdk/billing_ag.php')
        .done(function(data) {
            resolve(data);
            console.warn(data);
        })
        .fail(function(err) {
            reject(err);
        });
    },
```

However this doesn't work since the popup just says I was inactive and my console log:

![pp](https://cloud.githubusercontent.com/assets/5759953/23780456/68ac0b82-0547-11e7-8c2d-a8884a37002a.jpg)

I also tried to pass the plan-id, but it didn't work either. What am I doing wrong?

**Comment by bluepnume** [comment]
When you do `console.warn(data);` what is logged? It should be a string, like `resolve('EC-XXXXXXXX')`. 

Can you also check you have the environment set correctly in the button, depending on where you're making the api calls -- `api.sandbox.paypal.com` or `api.paypal.com`

```
paypal.Button.render({
    env: 'sandbox'
}, '#container');
```

```
paypal.Button.render({
    env: 'production'
}, '#container');
```

**Comment by AlexioVay** [comment]
Thanks for your reply. I configured my .php file to just output the EC-token, so `data` is this for example:

![ec](https://cloud.githubusercontent.com/assets/5759953/23792321/bb5c90ce-0586-11e7-8936-03a2979044b7.jpg)

Then I put that string into `resolve`. Now I've added `env: 'sandbox'` like you suggested and this time the popup wants me to login to paypal.
However, all login details are wrong, even if they aren't. I have my login stored and if I go to paypal.com I can login there with the same login data, but not in the popup with the rendered PayPal button. Is this a known bug or do I have to add other things too?

Maybe there are hints in the console log? For example this says the host is `https://www.sandbox.paypal.com`. Should it be `https://api.sandbox.paypal.com` like you mentioned?

![sb](https://cloud.githubusercontent.com/assets/5759953/23792522/96d3a05c-0587-11e7-81c4-6c568b3a28e5.jpg)

**Comment by AlexioVay** [comment]
I just noticed that I have to use a sandbox client account and could login. Now I could accept the payment, but after that the popup just closes and my console log outputs this error 

> `Uncaught Error: Error: Client side execute is only available for REST based transactions
> Error: Client side execute is only available for REST based transactions` 

![pp](https://cloud.githubusercontent.com/assets/5759953/23795198/8a1c7de0-0594-11e7-90d2-d9027c8a6571.jpg)

What does this mean?

**Comment by trainerbill** [comment]
@AlexioVay That is why I suggested you do the REST api calls.  If you do classic, EC-XXXXXX token, then you can't do the execute in the javascript.  You would have to create another route on your server to do the classic API for doexpresscheckoutpayment

https://developer.paypal.com/docs/classic/api/merchant/DoExpressCheckoutPayment_API_Operation_NVP/

then use paypal.request.post to post to your route and execute.

**Comment by AlexioVay** [comment]
@trainerbill I'm sorry, but I'm a little bit confused. The whole PayPal API is completely new to me, so I don't know what's classic. I had followed your suggestion and used the link you posted https://github.com/paypal/PayPal-PHP-SDK. I went through the examples there, created an app in the sandbox and just passed the EC-token to the `resolve` function, because it was suggested in #131 but maybe this is a whole different case compared to mine.

So, do you mean I'm currently using the classic/wrong way when I'm aiming to have a responsive checkout page for subscriptions? Could you maybe give me an example of the steps you just suggested? I don't know where to begin with the API link you just posted.

I really appreciate your efforts and time, thank you!

**Comment by trainerbill** [comment]
@AlexioVay Sorry it looks like the REST method is not going to work for you.  Since you are getting an EC token EC-XXXXXXX then you just have to find a way to submit this API call on the serverside.

https://developer.paypal.com/docs/classic/api/merchant/DoExpressCheckoutPayment_API_Operation_NVP/

I am confused how you are getting the token in the firstplace.  You have to run an api call to get one, you can't just hard code it.

https://developer.paypal.com/docs/classic/api/merchant/SetExpressCheckout_API_Operation_NVP/

You are going to have to get familiar with the paypal server apis.

**Comment by AlexioVay** [comment]
@trainerbill Let me explain. I went through [these examples](http://paypal.github.io/PayPal-PHP-SDK/sample/#billing). The last one of them I used ([CreateBillingAgreement](http://paypal.github.io/PayPal-PHP-SDK/sample/doc/billing/CreateBillingAgreementWithPayPal.html)) gives me `$approvalLink` and this variable contains `&token=xxx`. I just exploded/split the string to seperately get this EC-Token. And this is the `data` I return and put into `resolve`.

Like I mentioned it works showing that dialogue:

![adsdp](https://cloud.githubusercontent.com/assets/5759953/23817881/ec06d9d0-05f6-11e7-96c7-75609e870519.jpg)

But after clicking "Agree & Pay" nothing happens and the error `Error: Client side execute is only available for REST based transactions` is shown in my console log I posted earlier. 
This has something to do with my code at `onAuthorize`:

```
    onAuthorize: function(data, actions) {
        return actions.payment.execute().then(function() {
            console.log('The payment was completed!');
        });
```

So the function `actions.payment.execute()` doesn't seem to work. Do I have to make another ajax call to a php file there that completes the billing? Is that what you meant earlier?

**Comment by bluepnume** [comment]
> Do I have to make another ajax call to a php file there that completes the billing? Is that what you meant earlier?

Yep. You would need to make an ajax call in `onAuthorize`, then call the paypal api from your server-side to complete the transaction.

**Comment by trainerbill** [comment]
@AlexioVay You need to do this api call specifically:

http://paypal.github.io/PayPal-PHP-SDK/sample/doc/billing/ExecuteAgreement.html

Also to use this functionality in production you have to apply for it.  Normally a sales person would help you through this but I will see what I can track down.

**Comment by AlexioVay** [comment]
Thank you, I already figured that out, but then tested it live and also found out that PayPal doesn't offer recurring payments in Germany (or for German PayPal accounts), which is weird since I'm paying automatically to Spotify for example and I do have a German PayPal account. Or is this only for bigger companies like Spotify?

This is also confusing because when I used the $_POST form-button-method (x_click-subscription) and you get redirected to the non-responsive checkout page I mentioned in my first post, you can complete this process.

Is it therefore possible that this might be the result of some programmatical errors by me or is this a fact that automatic/recurring payments are not allowed for German PayPal accounts?

**Comment by trainerbill** [comment]
@AlexioVay What is your email?  I will have someone from our German team contact you.  They know how to better support German accounts.

**Comment by AlexioVay** [comment]
@trainerbill alexiovay(at)gmail.com 

Thank you!

**Comment by bluepnume** [comment]
Going to close this issue if it's being discussed over email. Please add the resolution here for future people googling this, thanks.

**Comment by AlexioVay** [comment]
Well, I didn't receive anything yet.

**Comment by bluepnume** [comment]
@trainerbill can you please follow up on that?

**Comment by trainerbill** [comment]
Someone will be reaching out tomorrow.

**Comment by cmaceochaidh** [comment]
Just having one of my German tech's reachout now. Sorry for the delay.

**Comment by kspearrin** [comment]
Was there any solution here? Trying to do something similar...

**Comment by AlexioVay** [comment]
Yes, they told me that you or your company has to proof a certain amount of monthly revenue to enable that function. I don't know how high it has to be exactly.

**Comment by kspearrin** [comment]
Well that seems pretty unhelpful :(

**Comment by Gemorroj** [comment]
I'll just continue to use the classic api. Because this rest api looks like a huge pile of broken code.
