### ISSUE TITLE
TypeError: document.getElementById(...) is null 1 button.js:3026 (new checkout.js version)

### ISSUE THREAD

**Issue by BjoernSimon** [paypal/paypal-checkout#249]
I created a working integration with PayPal button and React.js yesterday, the same flow is broken today, no code change on my side, but I saw that the checkout.js version changed from "4.0.43" (working) to "4.0.47" (broken).
The attaching of eventHandler in button.js fails since today (new checkout.js version).

Error:
`10:59:50.915 TypeError: document.getElementById(...) is null 1 button.js:3026:26
	setup https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js:3026:26
	["../node_modules/xo-buttonjs/public/js/button/index.js"] https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js:3035:9
	__webpack_require__ https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js:10:9
	[0] https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js:21:23
	__webpack_require__ https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js:10:9
	<anonymous> https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js:17:12
	<anonymous> https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js:1:2
`

Code:
In index.html
`<script src="https://www.paypalobjects.com/api/checkout.js" data-version-4 data-log-level="error"></script>`

My React component:
`import React, {Component} from "react";

function executePayment(data) {
    //...
}

class PaypalButton extends React.Component {

    componentDidMount() {
        paypal.Button.render({
            env: "sandbox",
            client: {
                sandbox:    'xxxxxxxx',
                production: 'bla'
            },
            payment: function() {
                return paypal.rest.payment.create(this.props.env, this.props.client, {
                    transactions: [
                        {
                            amount: { total: '1.00', currency: 'USD' }
                        }
                    ]
                });
            },
            commit: true,
            onAuthorize: function(data, actions) {
                // Execute on the server side
                var ret = executePayment(data);
                console.log("### executePayment ret: ", ret);

            },
            onError: function(err) {
                console.log('### Payment error; ', err);
            },
            onCancel: function(data) {
                console.log("### Payment cancelled; data: ", data);
            }
        }, '#paypal_payment_button');

    }

    render() {
        return(
            <a id={this.props.id} href="/checkout" />
        );
    }
}

module.exports = PaypalButton;`

Usage of my React component:
`<PaypalButton id="paypal_payment_button" />`

By the way, I could not use the React example from [Frameworks](https://github.com/paypal/paypal-checkout/blob/master/docs/frameworks.md) as `paypal.Button.react` does not exist after loading the checkout.js

Is this a core issue with checkout.js and it's dependencies or am I missing something?

**Comment by bluepnume** [comment]
Can you please try to clear your browser cache and try once more? This is an issue a few others have faced with old versions of the code.

**Comment by BjoernSimon** [comment]
@bluepnume I did clear the cache (again), it is now working, thank you very much for your help.

Are there any plans to make this more robust (e.g. not using the include file name, but checksum based)? Otherwise we have to explain this to our users when they click the PayPal button and it does not work (if they don't leave without telling us).

**Comment by bluepnume** [comment]
Yep, we definitely have plans to make this more robust and cache-bust properly on new releases. Please see https://github.com/paypal/paypal-checkout/issues/242

Also please note this is only a problem for the sandbox version of the button.

Glad you got it working, and thanks for the bug report!

**Comment by jacobhalls** [comment]
This error TypeError: [document.getelementbyid(...) is null](http://net-informations.com/js/iq/error.htm) would seem to indicate that there is no such element with an ID passed to getElementById() exist. This can happen if the JavaScript code is executed before the page is fully loaded, so its not able to find the element. The solution is that you need to put your JavaScript code after the closure of the HTML element or more generally before < /body > tag.
