### ISSUE TITLE
onCancel is not being called when the user close the PayPal Overlay

### ISSUE THREAD

**Issue by danigomez** [paypal/paypal-checkout#250]
Hello, i'm experiencing the following issue when i close the PayPal Overlay using "keep me logged".
When i'm not logged in, a popup window is opened with a PayPal login, if i close the popup after the login, the onCancel is correctly called.

But, if i click the checkout again with the login remembered, an overlay is opened in this case, if i close the overlay the onCancel is not being called. 

I assume that the problem comes from the onClose definition:

```javascript
if (this.props.onCancel && [ CLOSE_REASONS.CLOSE_DETECTED, CLOSE_REASONS.USER_CLOSED ].indexOf(reason) !== -1) {

                        if (this.paymentToken && this.cancelUrl) {

                            $logger.info(`close_trigger_cancel`);

                            return this.props.onCancel({
                                paymentToken: this.paymentToken,
                                cancelUrl:    this.cancelUrl
                            });

} else {
...
```

It's possible that the CLOSE_REASON in the overlay case is not CLOSE_REASONS.CLOSE_DETECTED or CLOSE_REASONS.USER_CLOSED??

_**Browser logs:**_
> 
> **ppxo_xc_ppcheckout_close_child** Object { timestamp: 1489079742474, windowID: "59e5836301", pageID: "8d220a7926", host: "www.sandbox.paypal.com", path: "/checkoutnow", env: "sandbox", country: "US", lang: "en", uid: "21c29f96f5", ver: "4.0.47" }  checkout.js:7720:40
> 
> ppxo_xc_ppcheckout_send_to_parent_xcomponent_close Object { timestamp: 1489079742480, windowID: "59e5836301", pageID: "8d220a7926", host: "www.sandbox.paypal.com", path: "/checkoutnow", env: "sandbox", country: "US", lang: "en", uid: "21c29f96f5", ver: "4.0.47" }  checkout.js:7720:40
> [post-robot] iframe :: www.sandbox.paypal.com/checkoutnow 
> 
> 	 #send request :: xcomponent_close :: "https://www.sandbox.paypal.com" 
> 
>  Object { hash: "xcomponent_close_ebaf1e8dc5", type: "postrobot_message_request", name: "xcomponent_close", data: Object, fireAndForget: undefined, domain: "https://www.sandbox.paypal.com", sourceDomain: "https://www.sandbox.paypal.com", id: "9e4050658a", windowType: "iframe" }  checkout.js:7720:40
> 
> ppxo_xc_ppcheckout_listener_close Object { timestamp: 1489079742512, windowID: "f87e1ec7ce", pageID: "fa0ec85173", host: "www.sandbox.paypal.com", path: "/webapps/hermes/button", env: "sandbox", country: "US", lang: "en", uid: "ff20c558e9", ver: "4.0.47" }  checkout.js:7720:40
> 
> ppxo_xc_ppcheckout_close Object { reason: "child_call", timestamp: 1489079742520, windowID: "f87e1ec7ce", pageID: "fa0ec85173", host: "www.sandbox.paypal.com", path: "/webapps/hermes/button", env: "sandbox", country: "US", lang: "en", uid: "ff20c558e9", 1 más… }  checkout.js:7720:40
> 
> **ppxo_xc_ppcheckout_call_prop_onClose** Object { timestamp: 1489079742523, windowID: "f87e1ec7ce", pageID: "fa0ec85173", host: "www.sandbox.paypal.com", path: "/webapps/hermes/button", env: "sandbox", country: "US", lang: "en", uid: "ff20c558e9", ver: "4.0.47" }  checkout.js:7720:40
> [post-robot] iframe :: www.sandbox.paypal.com/webapps/hermes/button 
> 
> 	 #receive request :: xcomponent_close :: "https://www.sandbox.paypal.com" 
> 
>  Object { hash: "xcomponent_close_ebaf1e8dc5", type: "postrobot_message_request", name: "xcomponent_close", data: Object, domain: "https://www.sandbox.paypal.com", sourceDomain: "https://www.sandbox.paypal.com", id: "9e4050658a", windowType: "iframe" }
>

**Comment by danigomez** [comment]
I overlooked this line :

> ppxo_xc_ppcheckout_close Object { reason: "child_call"...

It seems that the close reason set when i close the overlay is not any of the used in onClose...

**Comment by bluepnume** [comment]
Thanks for the really detailed bug report! 

This issue is actually known and already being tracked here - https://github.com/paypal/paypal-checkout/issues/211

The fix is in, and should be released early next week. Thanks again for pointing this out!

**Comment by danigomez** [comment]
Great!, Thank you!
