### ISSUE TITLE
PayPal Button not Rendering in IE11 (Intermittent)

### ISSUE THREAD

**Issue by stefannew** [paypal/paypal-checkout#252]
I don't have steps to reproduce, nor a code example that I can provide, but we're seeing some strange, intermittent behaviour on IE11 and edge, involving `postMessage` coming out of `checkout.js`.

We're having a very hard time debugging from some of the error messages we get back from `checkout.js`.

Here's a screenshot:
<img width="1277" alt="pp_error" src="https://cloud.githubusercontent.com/assets/3951747/23809402/8cd94c96-059b-11e7-8aa8-626c9910aa6a.png">

We're using a fairly barebones set-up, we're using a script tag as outlined in the Usage notes, and calling `window.paypal.Button.render` to set up the PayPal button.

In the cases that the button is rendered, and the overlay is open, when the user selects "Continue", the overlay is closed, but there's no `xcomponent_destroy` called, as we've seen in other browsers (Chrome, Firefox, Safari), the lightbox iframe remains in the DOM:

<img width="1335" alt="screen shot 2017-03-10 at 2 18 42 pm" src="https://cloud.githubusercontent.com/assets/3951747/23809649/86492af8-059c-11e7-816b-61b91cc8dbdf.png">

**Comment by stefannew** [comment]
I should also mention this is occurring in the sandbox environment only, for now. Here's the code we're using to setup the PayPal button.

```
function* createCallbackChannel(outerChannel) {
  const env = PAYPAL_ENVIRONMENT;
  const locale = yield select(selectPayPalLocaleCode);

  return eventChannel(emit => {
    // https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/other-integrations/#in-context-with-form
    window.paypal.Button.render({
      env,
      locale,
      payment: (resolve, reject) => {
        outerChannel.take(({ token }) => {
          if (token) {
            return resolve(token);
          }
          return reject({ result: 'No valid token provided.' });
        });
        emit({
          type: PAYPAL.FETCH_TOKEN_CALLBACK,
        });
      },
      onAuthorize: data => {
        emit({
          type: PAYPAL.AUTHORIZATION_SUCCESS,
          payload: {
            token: data.paymentToken,
            payerID: data.payerID,
          },
        });
      },
      onCancel: () => {
        // noop
      },
      style: {
        color: 'gold',
        shape: 'rect',
        size: 'medium',
      },
    }, '#paypal-button');

    return () => {};
  });
}
```

**Comment by bluepnume** [comment]
Thanks for all of the details! When you say you're only seeing this issue on sandbox, do you mean you haven't yet tried in production mode, or that it works for you consistently in production mode?

**Comment by bluepnume** [comment]
Also, is the overlay visible on the page, or is it just the invisible iframe which isn't cleared up?

**Comment by stefannew** [comment]
We've not yet tested in production mode. The overlay is no longer visible, just the invisible iframe not being cleared up. If we set display to block on the iframe, we see the PayPal semi-transparent black background and logo.

**Comment by bluepnume** [comment]
OK thanks, that's a really useful data point. I'll take another look tonight when I get back to my laptop.

Can you just quickly let me know which version of the script you see, when you type `paypal.version`?

**Comment by stefannew** [comment]
Thanks again, i'll keep trying to drill down to the underlying issue. Reported version of PayPal version is 4.0.47.

Any chance we can either set the `postRobot.CONFIG.ACK_TIMEOUT` directly before calling render? Will that have an effect? Is there any chance we could manually call a `paypal.postRobot.send`?

**Comment by stefannew** [comment]
We've recently found that setting a delay before rendering the button offers promising results. Our URL changes as we're opening a cart overlay, so we're thinking that if the URL doesn't match exactly when the button renders, there's a domain mismatch, `postRobot` fails with an ACK timeout and the button unloads itself. Does that sound like a possible scenario?

**Comment by bluepnume** [comment]
Hi again @stefannew. So I tried this case again in IE11, and I was still unable to reproduce the problem. I'm inspecting the dom, and I see all of the element cleared up as they're supposed to be.

Can you please try with this reference implementation, and tell me if you see the issue: http://www.bluesuncorp.co.uk/icv4/sandbox.htm -- that should narrow down if it's happening due to something in your integration, or if we have different browser settings, or something.

> Any chance we can either set the postRobot.CONFIG.ACK_TIMEOUT directly before calling render?

I don't think the time-out itself is the problem here. If that timeout triggers after 1000ms, chances are the message will never go through.

> We've recently found that setting a delay before rendering the button offers promising results. Our URL changes as we're opening a cart overlay, so we're thinking that if the URL doesn't match exactly when the button renders, there's a domain mismatch, postRobot fails with an ACK timeout and the button unloads itself. Does that sound like a possible scenario?

I'm interested to hear more details about this use-case. Does the domain change, or just the url path? If it's the domain, there may be something to this theory. When the popup window is first rendered, we send down the domain of the rendering page, and then it tries to message up to that specific domain only.

**Comment by stefannew** [comment]
@bluepnume I've tried your suggested implementation a number of times, on virtual machines, and on my Windows machine and am unable to reproduce the issue, so I'd wager it's something to do with our implementation. 

With regards to our use-case, the domain doesn't change, just the URL path. We've had some luck in delaying the URL change, so we're going to forge ahead with that and run some more tests.

I appreciate your help, and I'll get back with any additional information I have if any further tests yield any more revealing results. Still seems a little suspicious that it's only occurring on IE, but I feel it's kind of par for the course with this particular browser.

Thanks again.

**Comment by bluepnume** [comment]
OK, thanks for the info -- definitely narrows it down a bit.

When you change the url path -- is that with html5 pushState, or a hash change, or is it a full location change? And if it's the latter, how do you keep the button rendered -- is the page not re-rendered entirely?

**Comment by stefannew** [comment]
We're using html5 `pushState`, from react-router - I guess the fallback is a hash change, but I'm pretty sure IE11 supports `pushState`. Hopefully the button is only rendered after the location changes.

**Comment by bluepnume** [comment]
Is there any chance the button iframe is being removed and re-added to the DOM?

**Comment by stefannew** [comment]
I don't think the iframe is being re-rendered, but i'll run some tests on my end to make sure. Delaying the button doesn't seem to have any effect on the invisible iframe. That issue is also intermittent, doesn't seem to have any errors associated with it, either.

**Comment by bluepnume** [comment]
Can I also just check -- did you see the invisible iframe at all with the reference implementation at http://www.bluesuncorp.co.uk/icv4/sandbox.htm ?

**Comment by stefannew** [comment]
I'll run some tests.

I have seen an issue sometimes in which the user cancels the transaction, the iframe is closed, but the lightbox is still present and no amount of interaction can remove it, save for a hard refresh:

<img width="1440" alt="screen shot 2017-03-11 at 12 15 35 pm" src="https://cloud.githubusercontent.com/assets/3951747/23825268/919e0028-0654-11e7-9135-64c3db6ab116.png">

Selecting "Continue" has no effect, and clicking the 'x' logs `ppxo_xc_ppcheckout_focus`, and in turn throws an error:

```
SCRIPT5022: Unspecified error.
Error: Unspecified error.
   at __BROWSERTOOLS_CONSOLE_SAFEFUNC (eval code:6:29)
   at print (https://www.paypalobjects.com/api/checkout.js:4910:21)
   at log (https://www.paypalobjects.com/api/checkout.js:5037:17)
   at info (https://www.paypalobjects.com/api/checkout.js:5068:13)
   at log (https://www.paypalobjects.com/api/checkout.js:4756:21)
   at Anonymous function (https://www.paypalobjects.com/api/checkout.js:9203:25)
   at _loop2 (https://www.paypalobjects.com/api/checkout.js:1077:25)
   at SyncPromise.prototype.dispatch (https://www.paypalobjects.com/api/checkout.js:1107:17)
   at SyncPromise.prototype.then (https://www.paypalobjects.com/api/checkout.js:1125:13)
   at syncPromiseTry (https://www.paypalobjects.com/api/checkout.js:1170:13)
```

IE version is 11.0.9:

<img width="460" alt="screen shot 2017-03-11 at 12 19 44 pm" src="https://cloud.githubusercontent.com/assets/3951747/23825299/0cff7a3a-0655-11e7-8508-8981b812653c.png">

Windows 7 VM.

Not sure if related?

**Comment by bluepnume** [comment]
Always fantastic when IE gives useful errors like "Unspecified Error". I also wasn't familiar with `__BROWSERTOOLS_CONSOLE_SAFEFUNC` but looks like this is being auto-added by the IE dev tools.

Elsewhere I have console logs in a try/catch because IE sometimes has a tendency to error out when logging, in some scenarios. I'll make sure this line is wrapped in a try/catch too, that ought to at least remove some of the noise here.

**Comment by bluepnume** [comment]
OK, published [krakenjs/beaver-logger](https://github.com/krakenjs/beaver-logger)@2.0.5 with catch-all for `console.log` errors. The next release of `checkout.js` will pick this up, I'll let you know here when that happens, probably early next week.

Still looking into reproducing other reported issues.

**Comment by bluepnume** [comment]
Hi @stefannew -- any new info on this one? Thanks!

**Comment by stefannew** [comment]
@bluepnume Hey, sorry for the lapse in response, we've resolved the iframe issue in sort of a roundabout way, by removing any remaining iframes ourselves when the auth callback occurs and they're still present.

As for the button sometimes not rendering on IE11, we've had absolutely no luck debugging - there's a postRobot error (typical ACK timeout) and that's that. It sometimes happens, it sometimes doesn't... we're going to continue looking into it, but I haven't had a chance to get a version of the app up somewhere for you to try and repro apologies.

I'll keep you posted with any more information.
