### ISSUE TITLE
can not detect paypal dialog closed event.

### ISSUE THREAD

**Issue by yuuk** [paypal/paypal-checkout#257]
I can not find a close event callback when I manually close paypal dialog.

**Comment by danigomez** [comment]
This is possibly related to #250  and #211

**Comment by bluepnume** [comment]
Are you using `onCancel` with the iframe modal? In that case, your issue is probably due to be released with #211

**Comment by yuuk** [comment]
I've used, but no effect. I don't know if i'm wrong.

![qq 20170314095359](https://cloud.githubusercontent.com/assets/9426456/23882556/62b35b7e-089c-11e7-8b60-1d8e2d486224.png)

**My situation is like this:** 
When I click the checkout button, our website will generate an order by showing a loading page and the loading page is also in paypal dialog. And now when I close the popup window I want to have a close callback to do some operations just like refreshing my checkout page.

**This is our loading page:**
![qq 20170314101554](https://cloud.githubusercontent.com/assets/9426456/23883078/aebf561e-089f-11e7-956a-f6b6e8aaba19.png)

After our loading page, there will show paypal's payment page
![qq 20170314102155](https://cloud.githubusercontent.com/assets/9426456/23883157/3428d852-08a0-11e7-8cb9-e5814abd4855.png)

When I close the window of paypal's payment page, there will have a default event to jump to another page, But when I close the window in our loading page, there will nothing happened.

**Comment by bluepnume** [comment]
Looks like you're using the legacy v3.5 integration. If you want to use `onCancel` you will need to upgrade to the v4 button -- please see the docs at https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/advanced-integration/

**Comment by yuuk** [comment]
thanks so much! I'll try it now.
