### ISSUE TITLE
actions.restart() calls onAuthorize again.

### ISSUE THREAD

**Issue by trainerbill** [paypal/paypal-checkout#276]
Most of the time a merchant will set an on click in onAuthorize to complete the order on click of a review button.  If you are doing actions.restart() on a funding error, 10486, then the onclick is duplicated since we are calling onAuthorize again.  Only way I got around it was setting boolean and checking it before setting my onclick, but I think that this is an odd issue that many merchants many not catch.  Couple options:

1.  Add a parameter to .restart() that would force onAuthorize to execute again.  I think the default should be to not do this since 90% of merchants have a confirmation section and are not doing an execute immediately.  But could be swapped.  Only breaking incompatibility would be if someone is doing payment.execute in the onAuthorized and using actions.restart()

2.  Document that onAuthorize will be called again if they call actions.restart, so anything they want to execute only once needs to be checked.

**Comment by bluepnume** [comment]
What if `onAuthorize(data)` contained `data.restart`? Then you could do `if (!data.restart) { /* register click event */ }`?

Documentation is a good idea at the very least. 👍

**Comment by trainerbill** [comment]
Yeah that would work if you documented it.

**Comment by bluepnume** [comment]
Closing this as an issue for now.
