### ISSUE TITLE
(bug): New Tab Bug

### ISSUE THREAD

**Issue by trainerbill** [paypal/paypal-checkout#278]
Reproduced on Mac only using chrome 57 and 56. You must have the browser maximized by click the green button.  This only occurs in the popup flow, however if you click "Not You" on the lightbox then it opens a new tab.

![image](https://cloud.githubusercontent.com/assets/3578259/24217910/63cc8f7a-0f0f-11e7-91af-5ad1e0a327d4.png)

![image](https://cloud.githubusercontent.com/assets/3578259/24217934/76820730-0f0f-11e7-93d0-a09e8a505a0d.png)

**Comment by bluepnume** [comment]
This is a limitation in Chrome -- if you're in full-screen mode, you can't open a popup window. The flow should still work the same way though, right?

**Comment by trainerbill** [comment]
Yeah it works.  I wouldn't say this is a limitation in chrome though.  I cannot reproduce it in linux or windows when in full screen mode (F11) or having the window maximized.  It is odd that this only happens on mac when you maximize the window or are in fullscreen mode.  But at least it works.

**Comment by trainerbill** [comment]
also you may want to have some sort of limitations doc in the repo to track stuff like this
