### ISSUE TITLE
feat(recovery): Add a token parameter to button component

### ISSUE THREAD

**Issue by trainerbill** [paypal/paypal-checkout#280]
For merchants using a form post to execute/finalize and get a funding error, could we add a token xprop that when set does not render the paypal button, but instead opens the light box?  This should be the same thing as we are currently doing for the REST executes fallback since the user should already be authed in this case.

I can't think of anything that would prevent us from doing this...

**Comment by bluepnume** [comment]
Yeah, just need to come up with a good interface for this. Agree this would be awesome.
