### ISSUE TITLE
Conflict with ESET Smart Security Banking Protection.

### ISSUE THREAD

**Issue by bblimke** [paypal/paypal-checkout#281]
My apologies if this issue should rather be raised with ESET, but I'd appreciate any
kind of input I can get before raising this with ESET support.

Feel free to close the issue if it doesn't fit here.

ESET, which is one of the most popular internet security suites for Windows,
has a feature called Banking Protection these days. http://support.eset.com/kb5657/?locale=en_US
This feature is enabled by default for all ESET installations.

I have received several complaints from customers, that Paypal Checkout payments
don't work for them. They see the popup with the spinning wheel, spinning forever.

After long investigation, I figured out that ESET Banking Protection is the problem.

Using the old deprecated Integration "Advanced In-Context JavaScript settings", https://developer.paypal.com/docs/classic/express-checkout/in-context/javascript_advanced_settings/ caused the paypal checkout popup just to close after timeout.

I have then migrated to the new Integration: https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/

Now people are at least get redirected to hermes/fallback after the timeout, and can complete the checkout. It's not the best experience though.

The error in the paypal popup window console is:
````
Mixed Content: The page at 'https://www.paypal.com/checkoutnow?uid=....&env=production&version=4&locale.x=en_EN&token=....&xcomponent=1#/checkout/login' was loaded over HTTPS, but requested an insecure resource 'http://eset.com/BPPRedirector/ESET-Redirect-Switch?token=....'. This request has been blocked; the content must be served over HTTPS.
````

I have found that most websites using Paypal Express checkout have the same problem.
You can easily reproduce it by trying to check out on any of the following websites (I have found them with builtwith.com):
https://www.aldoshoes.com/uk/en_UK/
http://www.hayneedle.com
https://www.riteaid.com
http://www.solesociety.com
https://www.chapters.indigo.ca
https://www.jysk.ca
michaelkors.com
https://www.carcovers.com
ashleyfurniturehomestore.com
abercrombie.com

To my surprise I have not been able to reproduce the issue on the following websites though, which also use express checkout:
http://precision-elec.com/
https://store.lukebryan.com/checkout/cart/
https://donate.torproject.org/
pledge.wfmu.org/

**Comment by bluepnume** [comment]
Hey @bblimke, thanks for all of the details!

Is this happening in a particular browser for you? I tried aldoshoes and I was able to get the popup to open without any problems.

**Comment by bblimke** [comment]
hey @bluepnume 

I have been testing on Chrome on Windows on my own, but I received the reports about Firefox as well.

According to ESET, they support: Internet Explorer (8.0.0.0+), Chrome (30.0.0.0+), and Firefox (24.0.0.0+).

I have sometimes been able to load the popup successfully, not sure why, but then when restarted the browser, tried again and I have been experiencing the problem almost always.

Please make sure that you do not have ESET Banking Protection disabled for paypal domain by any chance.

**Comment by bluepnume** [comment]
I should probably test with ESET installed. Sorry, I read your message and assumed it was something integrated into the sites you listed. I'll try with that, thanks

**Comment by bblimke** [comment]
Yes, that should help :)
I can confirm I have just tested Aldo and reproduced the issue.

It has to be ESET Smart Security or ESET Internet Security on Windows though. I don't think they support Banking Protection on other systems. 
ESET has 30 days trial.

**Comment by bluepnume** [comment]
Yeah I'm still not able to repro, even using the ESET browser. The popup loads fine:

<img width="1046" alt="screen shot 2017-03-23 at 4 43 15 pm" src="https://cloud.githubusercontent.com/assets/1219075/24274806/ffc67dc2-0fe7-11e7-94ec-fab45b6f86f7.png">

D'you know where I can check if it's disabled for paypal?

**Comment by bluepnume** [comment]
Tried adding paypal.com in the ESET config and now it's crashing my browser when I redirect to paypal.com :(

Can I ask -- are you using the secure browser from the start, or starting in chrome and having it redirect you to the custom browser?

**Comment by bblimke** [comment]
I'm starting in Chrome which then tries to load/redirect to ESET.
I believe the problem exists only when starting in normal browser, since the "redirect" to eset browser causes "Mixed Content:" error. Paypal is https and ESET is http.
I'm not really sure if this is a redirect or how loading secure browser works.
When one starts in the secure browser, there is no redirect, and everything should work fine.

I have just received a confirmation from a customer who experiences the same problem.

**Comment by bblimke** [comment]
btw. I had to restart Windows after installing ESET in order for the redirects from Chrome to ESET to be activated.

**Comment by bblimke** [comment]
Here are 3 screencasts demonstrating the problem:

Chrome. Screencast showing that Paypal Express Checkout fails to load, when ESET Banking Protection is enabled, due to Mixed Content error. It redirects to Paypal fallback page after timeout. 
https://www.screencast.com/t/0BZilouSn

Chrome. Screencast showing that Paypal Express Checkout works without ESET Banking Protection but doesn't work with ESET Banking protection enabled.
https://www.screencast.com/t/2m7q1480MrdE

Firefox. Screencast showing that Paypal Express Checkout works without ESET Banking Protection but doesn't work with ESET Banking Protection enabled.
https://www.screencast.com/t/GfQaPJXNdiU

**Comment by bluepnume** [comment]
I'm going to close this one -- apologies, but having tried multiple times, I couldn't find a good way to work with the restrictions ESET adds. Most of the time my browser just crashes when I use it. Think we're going to have to mark this as "Will not support"

**Comment by bblimke** [comment]
@bluepnume Sorry, I have not updated it. The problem is solved. ESET has fixed the issue and released the fix in the database update. I have been told by ESET support that ESET developers have been working with Paypal on this problem.

Thank you for all the efforts.

**Comment by bluepnume** [comment]
Great! Glad to hear it, thanks for the update.
