### ISSUE TITLE
Should we move the demo app to a new repo?

### ISSUE THREAD

**Issue by trainerbill** [paypal/paypal-checkout#285]
Doesn't really make sense to have it in here and it comes with a build process which slows the actual checkout.js build.  Also creates dependencies that we don't need.

**Comment by bluepnume** [comment]
Agreed. Now it's hosted, it's less valuable to have it part of this repo so anyone can spin it up.

**Comment by trainerbill** [comment]
You wanna create a new repo?  I can migrate it

**Comment by bluepnume** [comment]
Yeah, let me bug someone for access to set up a new repo. In the mean time if you wanna set up in your localhost, you can just push when I have the repo.

**Comment by bluepnume** [comment]
Done.
