### ISSUE TITLE
Support AngularJS strict-di

### ISSUE THREAD

**Issue by mpolichette** [paypal/paypal-checkout#288]
I'm not 100% sure this is the right place to put this issue.  I wanted to integrate with paypal-checkout, but in my angular application, we enforce strict-di mode and we minify.  
See https://docs.angularjs.org/guide/production for info about strict-di

I wanted to include checkout.js but the angular component it ships with... some kind of x-component? doesn't implement injection of its controller with strict-di injection.

I'm just wondering if you guys would be open to supporting that... It seems like it'd be a simple fix, but I can't see to find where the component generating code is :/

**Comment by mpolichette** [comment]
Another note, it is hard to use `checkout.js` from your hosting, because we bundle our application, and `xcomponent` checks if angular is on the window before registering its component.   This leads to the following issues:

1. I load my bundled app before `checkout.js` and my app will complain about the `paypal-button` module not being registered
2. I load `checkout.js` before my app (which bundles angular) and angular is not on the window. so the `isActive` check fails and xcomponent doesn't register the module...

I suppose I could find a way to delay bootstrapping. But i'm open to other ideas :)
Thanks again

**Comment by bluepnume** [comment]
Thanks for letting me know about the strict-di issue! I'll take a look into it

For the second issue, I'm tracking this over here: https://github.com/krakenjs/xcomponent/issues/72

**Comment by mpolichette** [comment]
Awesome, thanks. 

On another note, I decided to just manually build my own directive for now... I was still using this library for the Paypal payment code...  

However, I discovered that when I use the `Button.render` function, it basically creates an iframe to paypal which requests the `checkout.js` library all over again... So it seems like a silly idea to bundle up this code since the component is going to request it separately anyway.

I kind of wish I just had a tiny little component which would create  the iframe, but maybe thats a different issue. :)

Thanks for the quick reply though! :)

**Comment by bluepnume** [comment]
> However, I discovered that when I use the Button.render function, it basically creates an iframe to paypal which requests the checkout.js library all over again... So it seems like a silly idea to bundle up this code since the component is going to request it separately anyway.

Yeah, that's definitely the advantage of using it from the CDN, you end up with those kinds of caching benefits.

> I kind of wish I just had a tiny little component which would create the iframe, but maybe thats a different issue. :)

Yeah, we're working on reducing the size of this -- but the script is actually handling a lot more than just opening an iframe; it takes care of:

- Pre-rendering into the iframe to make the button render quickly
- Handling all communications to and from the frame, including a lot of compatibility code for IE
- Allowing the checkout window to be rendered to the parent page from the frame
- Rendering the overlay behind the popup
- A lot of other stuff that's needed to make the flow work

**Comment by bluepnume** [comment]
This is now fixed and released
