### ISSUE TITLE
Paypal express checkout customize button

### ISSUE THREAD

**Issue by dmitry-kostin** [paypal/paypal-checkout#295]
Hello, 
A few questions, could you please give me a fast consult?

1. Is there any way to implement custom paypal buttons, for example some of that exist on following  page: https://developer.paypal.com/docs/classic/api/buttons

You wrote:
>For new integrations, PayPal strongly recommends using Express Checkout JavaScript buttons.

That should mean we still have a chance to customize button in new express checkout?
but unfortunately didn't find any way except tiny,small and etc props

2. Is any option/property to remove "The safer, easier way to pay" text under the button?

**Comment by bluepnume** [comment]
1. We're going to remove that page. The range of customization that's available with the button is all up here: https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/customize-button/

If there's something you want to do that isn't covered by that page, we'd be happy to consider adding it to the iframe button, but our goal is to dramatically reduce the number of PayPal buttons that are used across the web.

https://medium.com/@bluepnume/less-is-more-reducing-thousands-of-paypal-buttons-into-a-single-iframe-using-xcomponent-d902d71d8875

2. We're running an experiment to remove this text. The theory is that it doesn't help drive clicks. If that theory holds true, the plan is to remove that text across the board.

**Comment by dmitry-kostin** [comment]
Thanks for your answer. I appreciate it.

If you don't tired of me may I ask one more question, Can you implement some kind of callback when button is displayed and ready to go, when onDisplay invoked - the loader spinner is showing, but no any other callback when button is showed?

**Comment by bluepnume** [comment]
`paypal.Button.render()` returns a promise, so you can do

```paypal.Button.render().then(function() {
    ...
})```

**Comment by dmitry-kostin** [comment]
thnaks

**Comment by bluepnume** [comment]
Hey @KES777 -- usually best to ask questions like this in a new issue so it doesn't get lost.

You can do something like this:

```javascript
<div id="paypal-button1" data-amount=30 data-currency="USD"></div>
<div id="paypal-button2" data-amount=10 data-currency="USD"></div>

<script>
    [
        {
            container: '#paypal-button1',
            amount: '30.00',
            currency: 'USD'
        },

        {
            container: '#paypal-button2',
            amount: '10.00',
            currency: 'USD'
        }

    ].forEach(function(opts) {

        paypal.Button.render({

            env: 'sandbox',

            client: {
                sandbox:    'AZDxjDScFpQtjWTOUtWKbyN_bDt4OgqaF4eYXlewfBP4-8aqX3PiV8e1GWU6liB2CUXlkA59kJXE7M6R'
            },

            payment(data, actions) {
                return actions.payment.create({
                    payment: {
                        transactions: [
                            {
                                amount: { total: opts.amount, currency: opts.currency }
                            }
                        ]
                    }
                });
            },
            
            onAuthorize() {

            }
            
        }, opts.container);
    });
</script>
```

**Comment by KES777** [comment]
thank you. As workaround it is ok and I will use it. But this solution still is not so clear as stripe.com checkout interface.

**Comment by BetaProg** [comment]
@bluepnume  While your solution holds good for 2 <div>s , it fails in the case where it is free input text field where the user can dynamically change the amount value. In that case without calling render every time, how the amount gets updated and passed to payment? Please clarify if I'm wrong somewhere.
