### ISSUE TITLE
Paypal Button does not work on IOS

### ISSUE THREAD

**Issue by bgreenacre** [paypal/paypal-checkout#297]
Button doesn't work likely due to paypal trying to open in a pop-up. Is there a way to force iframe on ios?

**Comment by DesaiAtKU** [comment]
Is your site being loaded in SFSafariViewController? I noticed we're getting more complaints about this as Google Maps and other apps are switching from webviews to the view controller.

**Comment by bgreenacre** [comment]
This ended up not being an issue when deployed to a production environment. It also seems it was only affecting any IOS device on the latest version of IOS that wouldn't working with paypal sandbox.

**Comment by bluepnume** [comment]
Glad it works in prod mode @bgreenacre. Any more details you have that would help us narrow down the issue in sandbox would be helpful. What was the error / behavior?
