### ISSUE TITLE
Refused to display 'https://www.paypal.com/webapps/hermes/process3DS' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

### ISSUE THREAD

**Issue by crossRT** [paypal/paypal-checkout#299]
I solved the pop-up force close issue when there's any internal error happened. 
But this time I get another issue which indicates `Refused to display 'https://www.paypal.com/webapps/hermes/process3DS' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

It's happened right after the bank asks the customer for the payment confirmation code.

**Comment by crossRT** [comment]
Attached with the screenshot, please have a look.
<img width="1254" alt="screen shot 2017-04-21 at 10 01 53" src="https://cloud.githubusercontent.com/assets/3617115/25259605/b566bfa0-2679-11e7-9b2a-7aa20675efb6.png">

**Comment by bluepnume** [comment]
Thanks, this is a good catch. I'll take a look

**Comment by crossRT** [comment]
Alright. Thanks ya. =)

**Comment by maxisam** [comment]
We experience the same thing last week. And the interesting thing is when we update from "4.0.95"  to "4.0.127", the problem goes away. Any thought?
