### ISSUE TITLE
How to Set Language used in Popover?

### ISSUE THREAD

**Issue by yabdab** [paypal/paypal-checkout#301]
I know we can set the locale for the render button, but how to set the language used in the popover window/modal?

**Comment by bluepnume** [comment]
Setting the locale for the button should also have the effect of setting the language of the popup -- at least until the user logs in. If that doesn't happen it's a bug.

That said, I'd recommend not setting the locale, then we can render a button in the specific language the user expects, from their browser preference. I'm almost considering deprecating the locale setting for this reason.

**Comment by yabdab** [comment]
Thanks Daniel.
