### ISSUE TITLE
Popup window not closed on reject

### ISSUE THREAD

**Issue by andywatson00** [paypal/paypal-checkout#302]
So not sure if this is a bug or if there is just a better way of doing what I want to achieve.

If the call to my backend which creates the payment object fails for any reason I want to show an error and cancel the payment flow, currently i'm just doing this.

  paypal.request.post(CREATE_PAYMENT_URL, postData)
                  .then(function(data) {
                    if (PaymentHandler.validPayment(data)) {
                      resolve(data.id);
                    } else {
                        throw new Error("Payment Creation Failed");
                    }
                  }).catch(function(err) {
                    reject(err);
                  });

This works fine when logged in and using the iframe, but when using the popup window the overlay closes but the window with the spinner does not and the PayPal button is removed from from my page so the user can't try again.

Any help would be appreciated.

**Comment by bluepnume** [comment]
I'm seeing the same problem. Hoping to get a fix out today. Thanks for letting me know!

**Comment by bluepnume** [comment]
This should be resolved now. Please clear your browser cache and try once more -- and let me know if you see any further issues.
