### ISSUE TITLE
iPhone - SecurityError (DOM Exception 18) ?

### ISSUE THREAD

**Issue by yabdab** [paypal/paypal-checkout#304]
Getting reports of this error from users on iPhones....

> SecurityError (DOM Exception 18): Blocked a frame with origin "https://www.mywebsite.com" from accessing a frame with origin "https://www.paypal.com". Protocols, domains, and ports must match.

Something we should be concerned about?

**Comment by bluepnume** [comment]
Hi @yabdab -- I just tested on ios safari and I'm not seeing the same issue. Can you please let me know:

- Which browser
- Which site

**Comment by yabdab** [comment]
It is from a clients site and it totally random.

Here is the user agent...

Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/58.0.3029.83 Mobile/14E304 Safari/602.1

**Comment by bluepnume** [comment]
I'm thinking this is just Safari. We have to run checks to see if one frame is on the same domain as another, and in Safari there's no way to suppress the error messages that result from this. In other browsers we can just `try/catch`

I assume they're not actually seeing any bug, just the error messages?

**Comment by perry** [comment]
FWIW, this is issue is related to this https://bugs.chromium.org/p/chromium/issues/detail?id=590375

**Comment by bluepnume** [comment]
Should be fixed now.
