### ISSUE TITLE
Paypal button style responsive

### ISSUE THREAD

**Issue by guillaumebreux** [paypal/paypal-checkout#305]
Hi :)

I just noticed that the option: 'responsive' and 'small' for the button style are no longer working.

You can reproduce it with your demo page: https://developer.paypal.com/demo/checkout/#/pattern/styles

Setting 'small' on line 20 does nothing and setting 'responsive'(or 'large') make the button wider for a second and then shrink to a smaller size.

**Comment by bluepnume** [comment]
Can you please clear your browser cache and try once more? There was a temporary issue that should be resolved now.

**Comment by guillaumebreux** [comment]
Nice! It's fixed :) 🥇
