### ISSUE TITLE
Update SECURITY.md contact reference

### ISSUE THREAD

**Issue by ErikMHummel** [paypal/paypal-checkout#314]
https://github.com/paypal/paypal-checkout/blob/master/SECURITY.md#contact-us tells to email an eBay DL. I am not sure of the correct DL, but this should be updated.

**Comment by ErikMHummel** [comment]
May this should reference the Bug Bounty program instead of an email DL?

https://www.paypal.com/bugbounty/

**Comment by bluepnume** [comment]
Either sounds good to me 👍

**Comment by ErikMHummel** [comment]
PR #327 opened for this.
