### ISSUE TITLE
IE 11 js fatal error (works in chrome)

### ISSUE THREAD

**Issue by gspro** [paypal/paypal-checkout#318]
![ie11](https://cloud.githubusercontent.com/assets/931475/25714934/a75fb1c0-30c7-11e7-8b9d-2c4192591e32.png)

I get this error when debugging a .net app. Works fine in Chrome, but in IE after this happens, the authorization fails. Looks like it's having an issue with the '=>' operator. I'm using this version of checkout.js
 <script src="https://www.paypalobjects.com/api/checkout.js" data-version-4></script>

**Comment by bluepnume** [comment]
Hi @gspro -- can you confirm when this error crops up -- is it on button render?

**Comment by gspro** [comment]
Yes, it appears to be. Is there an es5 script available I can use somehow?

**Comment by gspro** [comment]
Will changing this anonymous function into a full function resolve it? This is the code referenced in the error message:
let interval = setInterval(() => {
            if (elements.every(hasDimensions)) {
                clearInterval(interval);
                method();
                return;
            }
        }, 5);

**Comment by bluepnume** [comment]
Hey @gspro -- this issue should be resolved now, we rolled out a fix. I just tried the live button and I'm seeing a regular function rather than an arrow function. Could you check on your side?

**Comment by gspro** [comment]
Looks like that did it, thanks!

**Comment by gspro** [comment]
Are you able to do a complete payment approval flow in IE11? I can in
Chrome, but in IE11, after hitting continue to authorize the payment, the
popup just changes it's location to the return_url. It stays in the popup
and the test account is never charged. chrome charges the user, and
redirects the parent window appropriately.

**Comment by bluepnume** [comment]
I've seen this before -- is it possible IE11 is running in intranet mode? There's a known issue with compatibility between checkout.js and IE intranet mode that results in the described behavior.

Also -- could you copy the console logs from when the page loads?

**Comment by gspro** [comment]
This turned out to be my issue, sorry to have bothered you with it. The
'base url' variable had a trailing slash, and the 'return url' had a
preceding slash. So put together that double slash within the return_url
was preventing IE from calling the onAuthorize function. Chrome didn't seem
to care.
Thanks so much for looking at my issue and working through the EC6 thing!

**Comment by bluepnume** [comment]
That's strange. Can you give me an example of the return url? Glad it's working now anyway!

**Comment by gspro** [comment]
I had code cobbled together from various sources, most of which was
pre-lightbox code. In my server code, I had a function like this to build
the base url:

       private string GetBaseUrl() => Request.Url.Scheme + "://" +
Request.Url.Authority + Request.ApplicationPath.TrimEnd('/') + "/";

then in my repository code I built the return url like this:
private static RedirectUrls GetReturnUrls(string baseUrl, string intent)
        {
            var returnUrl = intent == "sale" ? "/Manage/Downloads" :
"/Cart";

            // Redirect URLS
            // These URLs will determine how the user is redirected from
PayPal
            // once they have either approved or canceled the payment.
            return new RedirectUrls()
            {
                cancel_url = baseUrl + "Cart",
                return_url = baseUrl + returnUrl
            };
        }

So the end result was http://localhost:3259//Manage/Downloads?<querystring
variables>. I looked at it many times in Fiddler without seeing that double
slash. When I ran in chrome, that session wasn't even present in fiddler!

**Comment by gspro** [comment]
If in the future you get any .net support requests, I'd be glad to help out.
Thanks - Greg
