### ISSUE TITLE
Supplying purchase_order in transaction object causes error

### ISSUE THREAD

**Issue by XcrossD** [paypal/paypal-checkout#319]
In the [API documentation](https://developer.paypal.com/docs/api/payments/#definition-transaction), it says purchase_order can be supplied as additional information in transaction object, but I'm getting error here. I tried changing the key to "custom" and it worked, but if possible I would like to have it recorded as "purchase_order". I am currently using the basic button integration as seen [here](https://github.com/paypal/paypal-checkout/blob/master/docs/button.md).

![1493957678028](https://cloud.githubusercontent.com/assets/6669029/25733516/79e829d2-318c-11e7-8e9e-4e5a8da424f1.jpg)
![1493957690650](https://cloud.githubusercontent.com/assets/6669029/25733521/8979fc86-318c-11e7-9470-2abbe7f50d65.jpg)

**Comment by bluepnume** [comment]
Do you get a more specific error back in your network tab, for the payment api response?

**Comment by trainerbill** [comment]
@XcrossD I personally have never used purchase_order property and I can't get any api calls to work when its included.  We almost always use the invoice_number property.  This property also shows up on the transaction.  Can you use invoice_number instead?

**Comment by trainerbill** [comment]
@XcrossD Understood.  I have submitted a request to either fix the underlying schema issue causing the error or remove the property from the documentation.  Thanks for letting us know!
