### ISSUE TITLE
REST response missing create_time

### ISSUE THREAD

**Issue by XcrossD** [paypal/paypal-checkout#321]
In regard to #320, I noticed that the response json obtained does not include create_time which is shown in the API document (create payment -> sample response), but in the network tab it shows that create_time has returned. Maybe I'm missing a option setting here? 

![1493782550745](https://cloud.githubusercontent.com/assets/6669029/25734771/e06ae3dc-3198-11e7-9a43-f640f7932a3d.jpg)

![1493782834605](https://cloud.githubusercontent.com/assets/6669029/25734775/e88a59f8-3198-11e7-9fa3-179d9d398101.jpg)

**Comment by bluepnume** [comment]
Hey @XcrossD so -- we have code in the button to dynamically map these fields on the front-end, to ensure we're only exposing fields we're expecting to. 

I can add `create_time` in there for you, and get it out with the next release.

**Comment by XcrossD** [comment]
@bluepnume Thank you very much, that would be very helpful as I can record when the customer has paid in my invoice. May I ask when is the next release expecting to come out?

**Comment by bluepnume** [comment]
Should be there now -- please let me know if you still don't see it. Thanks!
