### ISSUE TITLE
Error loop?

### ISSUE THREAD

**Issue by yabdab** [paypal/paypal-checkout#329]
http://cloud.yabdab.com/kN8M

Is this supposed to happen?

This is from an iPad running latest iOS and Mobile Safari.

**Comment by bluepnume** [comment]
This error is expected -- it's the only way to do cross-domain checks on a different frame or window. No way to suppress it in Safari.

I'm not sure it should be looping so much though. Do you have an example of the code for your integration?

**Comment by yabdab** [comment]
It is getting called from a second iframe actually. Maybe that is the cause?

parent -> iframe- >paypal iframe

**Comment by bluepnume** [comment]
This error is now suppressed.
