### ISSUE TITLE
invoice number in create transaction

### ISSUE THREAD

**Issue by RoederBernd** [paypal/paypal-checkout#330]
Hello,

for identification purposes of an authorization/payment i wanted to transfer the merchants invocie number during the payment.create transaction. Unfortunately the invoice number does not show up in the buyers account. i managed to transfer description item_list ....etc. but the invoice number i can#t get running. Help is appreciated... what am i doing wrong?

Here is my coding for payment.create:

                    return paypal.rest.payment.create(env, client, {

                        // payment options here
                        intent: 'authorize',

                        transactions: [{
                            amount: {
                                total: ngCart.totalCost(),
                                currency: 'EUR',
                                details: {
                                    subtotal: ngCart.getSubTotal(),
                                    tax: ngCart.getTaxRate(),
                                    shipping: ngCart.getShipping()
                                }
                            },
                            description: 'Deine Bestellung bei LChoice',
                            //Pass-through variable you can use to identify your invoice number for this purchase. Default — No variable is passed back to you.
                            invoice_number: '48787589673xbrr',
                            // purchase_order: '48787589673',
                            // CUSTOM: Pass-through variable for your own tracking purposes, which buyers do not see. Default — No variable is passed back to you. 
                            // custom: 'EBAY_EMS_90048630024435',
                            // soft_descriptor: 'ECHI5786786',

                            item_list: {
                                items: i2,
                            }

                        }],
                        // note_to_payer: 'Contact us for any questions on your order.',
                    }, {
                        // experience options here
                        input_fields: {
                            no_shipping: 1
                        }
                    })

A second independant question is related to the "onAuthorize" section:
In my scenario i want to create the actual sales order after the customer has given authorization. So i thought i can transfer the actual order number / invoice number in the "onAuthorize" section (see below). Is that actually possible?

                onAuthorize: function(data, actions) {
                    // if (error === 'INSTRUMENT_DECLINED') {
                    //     actions.restart();
                    // }
                    //return actions.redirect();
                    // Optional: display a confirmation page here
                    return actions.payment.execute({
                        transactions: [{
                            // purchase_order: 'xx',
                            // invoice_number: 'yyxt',
                        }]
                    }).then(function() {
                        // Show a success page to the buyer
                        console.log('The payment was completed-actions!', actions);
                        console.log('The payment was completed!', data);
                        // $scope.putOrder();
                    });
                },

**Comment by trainerbill** [comment]
@RoederBernd You are using intent authorize so the Invoice id won't show until you capture the payment.  Here is a screenshot showing it works after capture.

![image](https://cloud.githubusercontent.com/assets/3578259/26120773/7e344fda-3a37-11e7-872d-19ebadef554b.png)

For your second question, that is not functionality currently supported by this library.  You would have to create a webservice to run the following api:

https://developer.paypal.com/docs/api/payments/#payment_update

And then hit the webservice in the onauthorized callback.  On success of your update webservice call you can then do actions.payment.execute().

**Comment by trainerbill** [comment]
@RoederBernd Just thought of something that will be an issue with my recommendation above.  You have to call execute() to find out if the authorization is successful or not and we don't allow updating after execute() is called.

Do you have a process to get an internal order number on reserve, so you can pass it to create(), and then either create the order, with the reserved id, if execute() succeeds or release it if it fails?

**Comment by RoederBernd** [comment]
Hi,
thank you for replying and your suggestions. I create an internal number before i create the payment and befor onAuthrize, pass that number as invoice_id to the payment and to the backend as reference_no, that solves my problem.
Thank you for responding

**Comment by leotm** [comment]
Where can I find the documentation on how to use `paypal.rest.`...?
I'm not finding much here https://developer.paypal.com/docs/api/payments/v1/

**Comment by trainerbill** [comment]
@leotm Here is the documentation.  https://developer.paypal.com/docs/checkout/integrate/#1-get-the-code.

paypal.rest is outdated, you can now use actions.payment.create in the paymetn callback.
