### ISSUE TITLE
Size/color/shape props not available in react component

### ISSUE THREAD

**Issue by eXtreme** [paypal/paypal-checkout#331]
Am I missing something or it is not possible to set color/size/shape on a react button? Setting it via component props or "style" prop gives an error that color/size/shape are invalid. It is possible to set a "style" prop on the component but again, color/size/shape do not work there.

**Comment by bluepnume** [comment]
Just tried it and it worked for me. Could you paste your code? Here's what I tried:

```javascript
let opts = {

    env: 'production',

    client: {
        sandbox:    'AWi18rxt26-hrueMoPZ0tpGEOJnNT4QkiMQst9pYgaQNAfS1FLFxkxQuiaqRBj1vV5PmgHX_jA_c1ncL',
        production: 'AVZhosFzrnZ5Mf3tiOxAD0M6NHv8pcB2IFNHAfp_h69mmbd-LElFYkJUSII3Y0FPbm7S7lxBuqWImLbl'
    },

    style: {
        color: 'blue'
    },

    payment() {

        let env    = this.props.env;
        let client = this.props.client;

        return paypal.rest.payment.create(env, client, {
            transactions: [
                {
                    amount: { total: '1.00', currency: 'USD' }
                }
            ]
        });
    },

    commit: true, // Optional: show a 'Pay Now' button in the checkout flow

    onAuthorize(data, actions) {

        // Optional: display a confirmation page here

        return actions.payment.execute().then(function() {
            // Show a success page to the buyer
        });
    }
};

return (
    <div>
        <paypal.Button.react style={opts.style} env={opts.env} client={opts.client} payment={opts.payment} commit={opts.commit} onAuthorize={opts.onAuthorize} />
    </div>
);
```

**Comment by eXtreme** [comment]
oooook.. I must have had some sunspots that caused `style` not to work properly... It works after your comment! I don't know what happened... I tested every possible combination, empty style worked, providing color/size/shape failed. That was my last resort after digging through paypal-checkout and xcomponent code 🤦‍♂️

**Comment by bluepnume** [comment]
No worries, happens to the best of us :D glad it's working now
