### ISSUE TITLE
Guest Checkout Failed with 401 permission_denied Error

### ISSUE THREAD

**Issue by jehartzog** [paypal/paypal-checkout#335]
I was able to integrate this into my React application using [this code](https://github.com/paypal/paypal-checkout/issues/149#issuecomment-300882923) and it's working well when paying using a PayPal account.

However, all attempts to do guest checkout and pay by directly paying with a credit card fail after the payment is submitted by a 401 response with the content `{"ack":"permission_denied","message":"Permission Denied"}`.

The outgoing request contains `{{data: {payer_id: "ULWK7Y9ZHQNYU"}, meta: {}}`. I'm not going the post the full header as I'm not sure what may be sensitive in it.

Troubleshooting I've tried:

- Disabling my CSP
- Testing in both sandbox and production
- Verified that [accounts optional](https://www.paypal.com/us/webapps/mpp/account-optional) was enabled 
- Verified I have a business account
- Verified my account is not limited in any way that's displayed on my dashboard

Since the information I have to provide to this library is actually nice and simple (client_id + transaction data), and it's working well for me with a PayPal login, the only two options I can think of are:

1. Something else not visible on my account is causing paypal to reject guest checkouts. I've contacted tech-support to try to verify this, but nothing heard yet.
2. This library is not forming the request for guest checkouts properly.

At this point I'm waiting on tech support to get back to me and will update this if it's some configuration error on my part.

**Comment by bluepnume** [comment]
Can you let me know which exact request (method + url) is failing? Is it the `execute` call?

Also, if you can provide me the `paypal-debug-id` from the response headers of the failed response, I can dig in a little deeper (ideally from production)

**Comment by jehartzog** [comment]
@bluepnume Thanks for trying to help, here are some more details. I re-enabled account-optional and tried to pay using a CC in production and got this result again. The sandbox calls also fail in a similar way. Both sandbox and production work when paying with a paypal account.

It's the execute call that fails.

General header info
```
Request URL:https://www.paypal.com/webapps/hermes/api/payment/PAY-**REMOVED**/execute
Request Method:POST
Status Code:401 Unauthorized
Remote Address:104.64.52.212:443
Referrer Policy:no-referrer-when-downgrade
```
Request headers with a few things maybe sensitive taken out
```
POST /webapps/hermes/api/payment/PAY-**REMOVED**/execute HTTP/1.1
Host: www.paypal.com
Connection: keep-alive
Content-Length: 47
x-paypal-internal-euat: **REMOVED**
Origin: https://www.paypal.com
x-csrf-jwt: **REMOVED**User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Content-Type: application/json
Accept: application/json
X-Requested-With: XMLHttpRequest
DNT: 1
Referer: https://www.paypal.com/webapps/hermes/button?env=production&version=4.0.71&uid=4b76ac827d&locale.x=en_US&style.color=gold&style.shape=pill&style.size=small&style.label=checkout&xcomponent=1
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.8,la;q=0.6
Cookie: ectoken=47U69571S4024961L; X-PP-K=1494620568:5:NA; cookie_check=yes; dtCookie=**REMOVED**; ui_experience=home%3D3%26login_type%3DEMAIL_PASSWORD%26ot_terms_shown%3Dtrue; X-PP-ADS=**REMOVED**; AKDC=phx-origin-www-1.paypal.com; ectoken=**REMOVED**; id_token=; xppcts=c1ff6a0b4a249774; tsrce=unifiedloginnodeweb; 44907=GTEYESAJ8R8UC; 47364=US; tcs=%7CpomaSubmit; ts=**REMOVED**; login_email=avariodeveloper%40gmail.com; KHcl0EuY7AKSMgfvHl7J5E7hPtK=**REMOVED**; x-pp-s=**REMOVED**; LANG=en_US%3BUS; x-csrf-jwt=**REMOVED** X-PP-SILOVER=name%3DLIVE3.WEB.1%26silo_version%3D880%26app%3Dhermesnodeweb%26TIME%3D615585625%26HTTP_X_PP_AZ_LOCATOR%3Dslcb.slc; akavpau_ppsd=**REMOVED**
```
Request payload was `{"data":{"payer_id":"ULWK7Y9ZHQNYU"},"meta":{}}`
Some response headers with a few things maybe sensitive taken out
```
HTTP/1.1 401 Unauthorized
Server: Apache
X-Recruiting: If you are reading this, maybe you should be working at PayPal instead! Check out https://www.paypal.com/us/webapps/mpp/paypal-jobs
Paypal-Debug-Id: 183af03ec588c
Cache-Control: no-cache
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Security-Policy: default-src 'self' https://nexus.ensighten.com http://localhost.paypal.com:* https://*.paypal.com http://*.paypal.com https://*.paypalcorp.com https://www.paypalobjects.com https://ak1s.abmr.net https://akamai.mathtag.com https://*.akamaihd.net http://connect.facebook.net https://connect.facebook.net https://staticxx.facebook.com http://staticxx.facebook.com https://www.facebook.com https://m.facebook.com http://www.facebook.com https://*.cardinalcommerce.com 'unsafe-inline' 'unsafe-eval'; img-src *; block-all-mixed-content
X-Powered-By: Express
ETag: **REMOVED**
x-csrf-jwt: **REMOVED**
x-csrf-jwt-hash: **REMOVED**
HTTP_X_PP_AZ_LOCATOR: slcb.slc
Paypal-Debug-Id: 183af03ec588c
Content-Encoding: gzip
Cache-Control: max-age=0, no-cache, no-store, must-revalidate
Pragma: no-cache
Content-Type: application/json; charset=utf-8
DC: phx-origin-www-1.paypal.com
Content-Length: 71
X-EdgeConnect-MidMile-RTT: 67
X-EdgeConnect-Origin-MEX-Latency: 187
Date: Sun, 14 May 2017 01:21:41 GMT
Connection: close
Vary: Accept-Encoding
Set-Cookie:  **REMOVED**; Domain=.paypal.com; Path=/; HttpOnly; Secure
Set-Cookie: x-csrf- **REMOVED**; Domain=.paypal.com; Path=/; Expires=Sun, 21 May 2017 01:21:40 GMT; HttpOnly; Secure
Set-Cookie: X-PP-SILOVER=name%3DLIVE3.WEB.1%26silo_version%3D880%26app%3Dhermesnodeweb%26TIME%3D615585625%26HTTP_X_PP_AZ_LOCATOR%3Dslcb.slc; Expires=Sun, 14 May 2017 01:51:40 GMT; domain=.paypal.com; path=/; Secure; HttpOnly
Set-Cookie: X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT
Set-Cookie: akavpau_ppsd=**REMOVED** Path=/
Strict-Transport-Security: max-age=63072000
```
Response payload is `{"ack":"permission_denied","message":"Permission Denied"}`

It fails once, tries to retry and fails again the same way, with the below warning
```
index.js:529 api_retry_aborted 
Object {method: "post", uri: "/webapps/hermes/api/payment/PAY-**REMOVED**/execute", timestamp: 1494724899494, windowID: "9ce7da4ffa", pageID: "7cfbecc79f"}
```

The second failed call paypal debug id is `d3bedefc3a6b5`

**Comment by bluepnume** [comment]
I think I know what's causing this. Out of interest -- can you check to see if you have 3rd party cookies disabled? If so, my hunch is enabling them will fix this problem for you.

If that turns out to be the case, I'll need to make a fix in our guest checkout to make this work with 3pc disabled.

Thanks for passing across all of this info!

**Comment by jehartzog** [comment]
I don't think they are disabled, here are my chrome settings.

<img width="412" alt="screenshot 2017-05-13 21 43 36" src="https://cloud.githubusercontent.com/assets/14143246/26030578/4aa16c52-3825-11e7-8c05-50bdb80a465e.png">

I also tried with safari and got the same result,.

**Comment by bluepnume** [comment]
Hmm interesting. Let me dig into this some more...

**Comment by bluepnume** [comment]
OK I'm seeing the error with the latest debug id you passed. Looks like it's a CSRF failure. Should be pretty straightforward to find the root cause and make a fix -- I'll take a look at this first thing when I'm in the office on monday and let you know when we can roll out the fix.

Thanks again for pointing this out and providing so many details!

**Comment by bluepnume** [comment]
@jehartzog - could you try now? I've made a partial fix to at least get the retry working in case of CSRF failures. So it should at least work end-to-end now. Please let me know if not.

I'll keep this open while I track down the cause of the original CSRF failure.

**Comment by jehartzog** [comment]
@bluepnume Thanks again for the assist, but no dice yet.

Here is are the debug ID's from the attempt, second one was the auto-retry, ran against production
```
Paypal-Debug-Id:446f5bfef1dbf
Paypal-Debug-Id:845ec95f85c3a
```

**Comment by bluepnume** [comment]
Did your clear your cache? Can you let me know the paypal.version?

**Comment by jehartzog** [comment]
I'm silly, forgot that I had previously fixed my paypal version at 4.0.71. I upgraded to 4.0.72 and am getting different results, but still no closer to accepting direct CC payments.

Running this against sandbox, the client never even made the execute call, after I entered the info my onCancel(data) gets called. My debug ID on the successful payment call was `18e00636c45fc`. Here is the data from the onCancel callback (token removed):
```
 data: '{"paymentToken":"EC-**REMOVED**","intent":"sale","cancelUrl":"https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&xo_node_fallback=true&force_sa=true&fallback=1&token=EC-**REMOVED**"}',
```
Thanks again for the responsiveness, it's been a bit of a struggle getting payments to just work :).

**Comment by bluepnume** [comment]
So -- I tried this use case on both sandbox and production.

- Production - worked fine for me (did you manage to get this to work in prod using `4.0.72`?)
- Sandbox - I saw the same error you did. Dug into it, and it looks like one of the services the guest app uses is down in our sandbox env. I'm raising a ticket to get that service restarted, I'll let you know as soon as it's up again. But I don't think it's a code issue this time.

Sorry about all of the problems. I'm sure you can't be getting the best impression of our integration right now, but I really do appreciate you taking the time and helping me track down these issues.

**Comment by jehartzog** [comment]
I didn't try it out on production previously since it completely failed on sandbox, but after you responded I went ahead and gave it a shot.

I still got the 401 on the first execute call, but the second one went through, so yay!

I'll be honest, I already implemented the [braintree drop-in ui](https://developers.braintreepayments.com/guides/drop-in/javascript/v3) in a half day and was keeping the effort on this hoping to get payments working for our customers while waiting for the merchant account approval. I guess both products are under the PayPal umbrella, so kinda on the same team, right?

Thanks again for the quick responses and troubleshooting help.

**Comment by bluepnume** [comment]
OK, my ticket was resolved, and the sandbox issue seems to be resolved -- it's working for me now.

> I still got the 401 on the first execute call, but the second one went through, so yay!

Next step for me is to narrow down the cause of this.

Thanks!

**Comment by bluepnume** [comment]
Fix for this was made a while ago, but still waiting on a code push.
