### ISSUE TITLE
Tiny size gone? 

### ISSUE THREAD

**Issue by james-ingold** [paypal/paypal-checkout#336]
Using tiny for size in the styles property is showing the same as small size. Is the tiny size option gone? 

https://developer.paypal.com/demo/checkout/#/pattern/styles

**Comment by bluepnume** [comment]
Hi @james-ingold -- this was a legacy option that was carried over from the old integration. Nobody was yet using it in production with `paypal.Button.render` from our logs, so we removed the option and defaulted it to small.

Along with usage for the tiny button being extremely low even on the old integration, with the iframe button we're hoping to use the additional space to display more information to the buyer - like their current PayPal balance.

**Comment by james-ingold** [comment]
Thanks @bluepnume  for the quick reply, I see the commit now where the changes were made. That makes sense, but it's unfortunate, I was working on a site where the 80px width button without text underneath it was perfect. I'll rework things for the 148px button.

**Comment by bluepnume** [comment]
Ah, I'm really sorry for the inconvenience. It was bad timing on our part.
