### ISSUE TITLE
Merchant wants timeout over 10 sec

### ISSUE THREAD

**Issue by shekharparkhi** [paypal/paypal-checkout#339]
The checkout.js script is causing a timeout for a merchant scentbird.com after 10000ms
His 3rd party PayPal API calling server (Vindicia) takes between 11-13 sec to execute the SetEC call and it is out of his hands. He would ideally like a timeout of 15+ sec.
Let me know as and when there's a solution for this merchant.

**Comment by trainerbill** [comment]
https://github.com/paypal/paypal-checkout/pull/360

This PR added timeout support.  should be able to do paypal.request.get(url, { timeout: 10000 })

**Comment by bluepnume** [comment]
Not quite. Fixing this issue would involve removing this timeout: https://github.com/paypal/paypal-checkout/blob/master/src/components/button/component.js#L160

I'm still on the fence about this, though, as it's a lot of time for the user to wait with just a spinner. Ideally the merchant should have a separate call if they need to kick off some really long-running process, but calling paypal to set up a payment should never take more than 10 seconds.

**Comment by trainerbill** [comment]
I would just have them fire off the request for the token when the page loads and return the promise in the payment callback.  they can save the token in sessionStorage and clear it in the onAuthorize callback to prevent it from firing on refresh.

**Comment by bluepnume** [comment]
Going to close this as haven't yet heard a scenario where we're causing this slowdown.

**Comment by voltairebiton** [comment]
Is it possible to increase the timeout during create payment? In my case, during php rest sdk `$this->payment->create($apiContext);`, it randomly executes around 5 - 13 seconds. so when it reaches 10 seconds, the request will fail.
