### ISSUE TITLE
Angular >2 compatability ?

### ISSUE THREAD

**Issue by justinkohlenberg** [paypal/paypal-checkout#346]
The documentation only mentions a native implementation for AngularJS,
we were wondering if there will be an official implementation that can be used with Angular (not AngularJS)

**Comment by bluepnume** [comment]
Hey @justinkohlenberg -- please check here for progress on Angular2: https://github.com/krakenjs/xcomponent/issues/23

We have it planned, just needs to find some priority. If you follow that thread I'll update when it's released.
