### ISSUE TITLE
XC button - server side REST API: How to properly close lightbox on create payment error?

### ISSUE THREAD

**Issue by bbabic** [paypal/paypal-checkout#351]
What is the proper way to handle create payment errors on server side without producing a lot of errors/warnings in console?

I can not find anything in docs or examples.

This is how I do it, but errors are shown in console:
...
payment: function(resolve, reject) {
	return paypal.request.post(URL).then(function(res) {
		if (res.errorCode > 0)
			return reject(new Error(res.errorText));
		else
			return res.paymentID;
	});
...

**Comment by avemar** [comment]
Hi @bluepnume ,
I'm experiencing the same issue.
It looks like `checkout.js` simply wraps the reject argument (since I'm getting `Error: Error: whatever_message_passed_in_error_constructor` in console) and throws another Error. The problem is that this one is unhandled, thus it's shown in console (but indeed the lightbox is closed, no matter what).
Is it possible to handle it somehow, and more importantly is it possible to simply avoid it?
Thank you and kind regards

**Comment by bluepnume** [comment]
@avemar you can handle the error by specifying an `onError` prop and doing something there like redirecting to an error page.

**Comment by avemar** [comment]
Thank you @bluepnume .
The `onError` is actually called, but something is still broken in `checkout.js` when I call reject. I'm using jQuery `ajax` , with `resolve` called inside `done` callback, and `reject` inside `fail` callback.
While resolve works flawlessly, reject simply throws an unhandled error and I keep getting errors on console.
It looks like this anonymous function:
`_RECEIVE_MESSAGE_TYPE[__WEBPACK_IMPORTED_MODULE_1__conf__.a.POST_MESSAGE_TYPE.RESPONSE] = function(source, origin, message)`
throws an error here: 
`if (message.ack === __WEBPACK_IMPORTED_MODULE_1__conf__.a.POST_MESSAGE_ACK.ERROR) return options.respond(new Error(message.error));`
and this error it's simply not handled in the caller.

Thanks

**Comment by trainerbill** [comment]
@avemar Do you have an example somewhere we can try?  You could try creating a new window.paypal.Promise and returning that, then calling reject/resolve in the jquery success/error.  Promises in checkout.js are a little different than native promises and the Promises that jquery uses internally.  If you want to do some realtime troubleshooting head over to the gitter room.

https://gitter.im/paypal/paypal-checkout

**Comment by bluepnume** [comment]
Hey @avemar -- sorry I didn't respond to this at the time. I've actually fixed checkout.js in the latest version so if you specify `onError`, the error should *not* also be thrown globally. Can you clear your cache and see if it's working ok for you now with the latest version?

**Comment by avemar** [comment]
Hi @bluepnume ,
Sorry If didn't get back earlier.
I still get this, and onError is still actually executed:
![console_error](https://user-images.githubusercontent.com/5948354/27516910-ad154d02-59ba-11e7-96cb-0730be37ec03.png)

**Comment by bluepnume** [comment]
Hmm, strange. I'll take a look. Thanks for the heads-up.

**Comment by Yottster** [comment]
Im running in to the same issue.

This is my code
```
payment: function(resolve, reject) {
	return paypal.request.post(CREATE_PAYMENT_URL, formValues).then(function (result) {

		if (result.hasOwnProperty('paymentID') && result.paymentID) return result.paymentID;

		throw new Error("some error");
	}).catch(function (err) {
		console.log("Catch: ", err);
		reject(err);
	});
},

onError: function(err) {
	console.log("onError: ", arguments);
},
```

![screen shot 2017-06-28 at 10 20 45](https://user-images.githubusercontent.com/828281/27627839-7379248a-5bed-11e7-871c-6d06f1730931.png)

**Comment by Yottster** [comment]
Cannot reproduce anymore.

**Comment by ildar-aim** [comment]
I have the same issue. The code is like https://github.com/paypal/paypal-checkout/issues/351#issuecomment-311594626

**Comment by ildar-aim** [comment]
PS
I use https://www.paypalobjects.com/api/checkout.min.js

**Comment by bluepnume** [comment]
This should now be resolved.
