### ISSUE TITLE
Button has no effect when clicking on certain versions of Chrome / Safari.

### ISSUE THREAD

**Issue by bluepnume** [paypal/paypal-checkout#352]
Details here: http://stackoverflow.com/questions/44088790/paypal-checkout-js-throws-blocked-iframe-access-error

> I'm on  the first step  of integrating  Express Checkout, where  you add
> `checkout.js` to the  page in order to render the  button. However, with
> the minimal script exactly like the [example][1] provided:
> 
>     paypal.Button.render({
>         env: 'sandbox',
>         commit: true,
>         payment: function() {},
>         onAuthorize: function(data, actions) {}
>     }, '#paypal-button');
> 
> I already get  an error (and not  only one, but multiple. As  long as my
> processor is working, new errors are generated) for the iframe:
> 
> > Blocked  a  frame  with origin  "https://www.sandbox.paypal.com"  from
> > accessing  a  frame  with  origin  "https://mysite.local".  Protocols,
> > domains, and ports must match.
> 
> Note that I even  have `https` on my localhost for  testing things in an
> environment as  close to production  as possible, but of  course domains
> will never match.
> 
> How am I supposed to make this work?
> 
> At the [demo page][2], the same happens:
> 
> [![PayPal checkout.js causing blocked iframe error][3]][3]
> 
> 
>   [1]: https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/add-paypal-button/
>   [2]: https://developer.paypal.com/demo/checkout/
>   [3]: https://i.stack.imgur.com/kDmDa.png

**Comment by kalabro** [comment]
Hi @bluepnume! We can reproduce the same issue on older iPhones: https://www.dropbox.com/s/7hjhf89oqw87fh3/Screenshot%202017-05-30%2017.10.01.png?dl=0
Please let me know if you need any extra information. Thank you.

**Comment by bluepnume** [comment]
@kalabro do you actually see a bug, or just the error messages?

**Comment by kalabro** [comment]
@bluepnume -  just the error messages so far. We will keep testing.

**Comment by bluepnume** [comment]
@kalabro OK. The error message is actually expected -- it's impossible to suppress it in Safari. This bug is actually about the button not being clickable in some cases, which was reported on StackOverflow.

**Comment by bluepnume** [comment]
Closing this as haven't found any way to repro.

**Comment by jonnyxe** [comment]
I have the same problem but I know how to get this fixed.
The Problem is on the PayPal site itself. PayPal configured their Apache server not correctly for using the frame thing.

They set the "X-Frame-Options" header option to "SAMEORIGIN" on their production and development environment/websites.

For us developer with newer browsers have no chance to get the frame according to policies to work.

It would be a pleasure if you could tell that PayPal.

**Comment by nehabajoria** [comment]
I have the same problem with chrome version 67.0.3396.79.
Got the solution => I checked the Paypal site and found to add style which was missing in my code. Paypal popup starts working on click of the Paypal button.
https://developer.paypal.com/demo/checkout/#/pattern/generic
// Specify the style of the button

        style: {
            label: 'paypal',
            size:  'medium',    // small | medium | large | responsive
            shape: 'rect',     // pill | rect
            color: 'blue',     // gold | blue | silver | black
            tagline: false    
        },
