### ISSUE TITLE
Paypal checkout popup not working properly

### ISSUE THREAD

**Issue by rflorat07** [paypal/paypal-checkout#354]
I am trying to integrate Paypal using Braintree PayPalClient-Side Implementation, when i click on the Button it open the popup window, show this on mobile screen

https://developer.paypal.com/demo/checkout/#/pattern/client

![schermata 2017-05-23 alle 14 03 45](https://cloud.githubusercontent.com/assets/6424228/26353811/780ab500-3fc2-11e7-9d04-2e21095c28f3.png)

**Comment by bluepnume** [comment]
Yikes, thanks for the report. Looking into this right away.

**Comment by bluepnume** [comment]
This should now be resolved -- please clear your browser cache and try once more. Thanks again for the report.
