### ISSUE TITLE
Can't scroll in lightbox

### ISSUE THREAD

**Issue by sshimizupp** [paypal/paypal-checkout#358]
Can't scroll down to the Pay button in lightbox with the latest checkout.js (v.4.0.78). It worked with v.4.0.74.
Tested with Chrome, Safari, Firefox on Mac.

**Comment by bluepnume** [comment]
Thanks for the report -- sorry for the late response, just back from vacation. I'm taking a look

**Comment by bluepnume** [comment]
This should now be resolved. Please clear your browser cache and let me know if you still see the issue.
