### ISSUE TITLE
Provide a way to check if locale is supported before calling paypal.Button.render

### ISSUE THREAD

**Issue by crookedneighbor** [paypal/paypal-checkout#359]
There may be cases where it is useful to check if a locale is supported before calling paypal.Button.render. 

Real world use case: Braintree got a pull request for adding a Hungarian translation to braintree-web-drop-in: https://github.com/braintree/braintree-web-drop-in/pull/187

This locale is not currently compatible with checkout.js, so the PayPal setup fails. Would be great to have the rest of Drop-in support the locale, and just fall back to the customer's browser settings for the PayPal flow.

**Comment by bluepnume** [comment]
Should be able to rely on https://github.com/paypal/paypal-sdk-constants/blob/master/src/locale.js#L448 -- if it's part of this array, it's supported by paypal web sdks.
