### ISSUE TITLE
INTERNAL_SERVICE_ERROR on demo site

### ISSUE THREAD

**Issue by yeetien** [paypal/paypal-checkout#361]
Hi 

I'm testing out on https://developer.paypal.com/demo/checkout/#/pattern/client and keep getting INTERNAL_SERVICE_ERROR error.

I've replaced sandbox and production client_id. Here's the full error:

debug_id: "54785d4862331"
information_link: "https://developer.paypal.com/docs/api/payments/#errors"
message: "An internal service error has occurred"
name: "INTERNAL_SERVICE_ERROR"

https://developer.paypal.com/demo/checkout/#/pattern/server is also having the same error: Internal Service Error, Internal Server Error

Could advise how to make this works? Thanks!

**Comment by bluepnume** [comment]
Looks like this was a temporary connection error on the sandbox site. Sorry for the inconvenience -- I think it should be resolved now. Can you please let me know if you still see the problem?

**Comment by yeetien** [comment]
It's working now. Thanks!

**Comment by bluepnume** [comment]
Great!

**Comment by vsinghjodhpur** [comment]
Yes its still have issue, I'm using Sandbox and trying to capture payment to saved credit card token but its always shows "INTERNAL_SERVICE_ERROR" while cut the payment.
