### ISSUE TITLE
(Accessibility) Paypal focus window overlay tab input is leaking to merchant's page

### ISSUE THREAD

**Issue by abarco** [paypal/paypal-checkout#363]
Tabing on the overlay is sending input to the merchant's page. Ideally, the input should be contained within the overlay until the transaction is completed or canceled. 

![image](https://cloud.githubusercontent.com/assets/3922193/26805756/4768a3d6-4a02-11e7-9e21-4293a888d225.png)

**Comment by vschs007** [comment]
can u send the vulnerable link??

**Comment by bluepnume** [comment]
@khanghoang  could you take a look? thanks!
