### ISSUE TITLE
Hybrid App  Working Issue

### ISSUE THREAD

**Issue by honey93** [paypal/paypal-checkout#364]
I have been using paypal-checkout xcomponent to create Hybrid App using Ionic Framework. It is working for android but once I switch between the apps and again come back to the app having paypal butto, it does not work.

Also, it is not working for the iOS app built using ionic.

Could anyone suggest me the solution ?

**Comment by bluepnume** [comment]
Ionic isn't officially supported, so you're a little on your own for now. That said, if you can track down or debug any specific issues, I'd be happy to help you resolve them.
