### ISSUE TITLE
Unexpected token < in JSON at position 1939     at JSON.parse (<anonymous>)     at XMLHttpRequest.<anonymous> (https://www.paypalobjects.com/api/checkout.js:11001:39)

### ISSUE THREAD

**Issue by jericopulvera** [paypal/paypal-checkout#365]
```
index.js:536 ppxo_xc_ppcheckout_error Object {error: "Error: SyntaxError: Unexpected token < in JSON at …://www.paypalobjects.com/api/checkout.js:2401:13)", timestamp: 1496880443689, windowID: "7bc0a752a7", pageID: "69cd277e7c", referer: "http://holiday-homes.app"…}country: "US"env: "sandbox"error: "Error: SyntaxError: Unexpected token < in JSON at position 1215↵    at JSON.parse (<anonymous>)↵    at XMLHttpRequest.<anonymous> (https://www.paypalobjects.com/api/checkout.js:11001:39)↵    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:2477:118)↵    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:2381:73)↵    at messageListener (https://www.paypalobjects.com/api/checkout.js:2401:13)"host: "www.sandbox.paypal.com"lang: "en"pageID: "69cd277e7c"path: "/webapps/hermes/button"referer: "http://holiday-homes.app"timestamp: 1496880443689uid: "187999bea3"ver: "4.0.82"windowID: "7bc0a752a7"__proto__: Object 

 Error: SyntaxError: Unexpected token < in JSON at position 1215
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.<anonymous> (https://www.paypalobjects.com/api/checkout.js:11001:39)
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:2477:118)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:2381:73)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:2401:13)
__webpack_require__.i.window.console.window.console.(anonymous function) @ index.js:536
print @ logger.js:53
log @ logger.js:161
error @ logger.js:214
error @ logger.js:36
Component.logError @ index.js:496
(anonymous) @ index.js:1177
(anonymous) @ promise.js:224
SyncPromise.dispatch @ promise.js:254
SyncPromise.then @ promise.js:279
SyncPromise.try @ promise.js:335
ParentComponent.error @ index.js:1175
(anonymous) @ decorators.js:24
(anonymous) @ promise.js:224
SyncPromise.dispatch @ promise.js:254
SyncPromise.then @ promise.js:279
SyncPromise.try @ promise.js:335
descriptor.value @ decorators.js:23
(anonymous) @ index.js:65
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ index.js:1149
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:251
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:319
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:319
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:319
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:319
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:251
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:147
flush @ promise.js:12
(anonymous) @ promise.js:27
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:251
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:251
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:147
flush @ promise.js:12
(anonymous) @ promise.js:27
options.respond @ client.js:93
_RECEIVE_MESSAGE_TYPE.(anonymous function) @ types.js:122
receiveMessage @ index.js:94
messageListener @ index.js:119
types.js:122 Uncaught Error: SyntaxError: Unexpected token < in JSON at position 1215
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.<anonymous> (https://www.paypalobjects.com/api/checkout.js:11001:39)
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.<anonymous> (https://www.paypalobjects.com/api/checkout.js:11001:39)
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:2477:118)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:2381:73)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:2401:13)
```

What happen?

**Comment by bluepnume** [comment]
Sandbox or production? And does the same problem happen after you clear your cookies for paypal.com?

**Comment by jericopulvera** [comment]
Sandbox. yesterday it was working

**Comment by bluepnume** [comment]
- Can you check the response in the chrome network tab for the /payment call? See if there's any clue there as to why you're not getting valid json back?

- Do you have the same issue in production mode?

**Comment by jericopulvera** [comment]
this is the response
```
{
	"intent": "sale",
	"payer": {
		"payment_method": "paypal"
	},
	"redirect_urls": {
		"return_url": "http://my-site.app/webapi/paypal/create",
		"cancel_url": "http://my-site.app/webapi/paypal/cancel"
	},
	"transactions": [{
		"amount": {
			"total": "415.00",
			"currency": "EUR"
		},
		"description": "Booking for property!",
		"item_list": {
			"items": [{
				"name": "Item 1",
				"price": "190.00",
				"currency": "EUR",
				"quantity": 2
			}, {
				"name": "Item 2",
				"price": "20.00",
				"currency": "EUR",
				"quantity": 1
			}, {
				"name": "Item 3",
				"price": "15.00",
				"currency": "EUR",
				"quantity": 1
			}]
		},
		"related_resources": []
	}],
	"id": "PAY-5G8543620F0718756LE4LJPI",
	"state": "created",
	"create_time": "2017-06-08T02:21:48Z",
	"links": [{
		"href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-5G8543620F056874ULE4LJPI",
		"rel": "self",
		"method": "GET"
	}, {
		"href": "https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-34T39564U0127913C",
		"rel": "approval_url",
		"method": "REDIRECT"
	}, {
		"href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-5G8543620F071874U564LJPI/execute",
		"rel": "execute",
		"method": "POST"
	}]
}
```

Same issue in production. didn't know what  happened yesterday it was working.

**Comment by bluepnume** [comment]
This is really strange. The json looks totally valid, and when I test this myself, I don't get the same issue.

Does the same thing happen in any different browsers?

**Comment by jeffbrody** [comment]
I'm just starting to learn how to use the express checkout, getting same issue.

**Code:**
 payment: function() {
		    	
		        // Set up the payment here
		    	var urls = document.getElementsByName('authorizePaypalURL');
		    	var CREATE_URL = urls[0].value; 
		    	console.log("URL: " + CREATE_URL);
		    			    	
                // Make a call to your server to set up the payment
		    	// Test code to see what we're getting back!
		    	var xhttp = new XMLHttpRequest();
		    	xhttp.onreadystatechange = function() {
		    	    if (this.readyState == 4 && this.status == 200) {
		    	      console.log("Response: " + this.responseText);
		    	    }
		    	};
		    	xhttp.open("POST", CREATE_URL, true);
		    	xhttp.send();		    	
		    	
//		    	console.log(paypal.request.post(CREATE_URL));
/*		    	
                return paypal.request.post(CREATE_URL)
                    .then(function(res) {
                    	//return "PAY-0J356327TH335450NK56Y2PQ";
                    	console.log(res.paymentID);
                        return res.paymentID;
                    });
*/                                    		  
		    },

**Response:** 
Response: {"id":"PAY-0J356327TH335450NK56Y2PQ"}
index.js:536 ppxo_xc_ppcheckout_error Object {error: "Error↵    at Object._RECEIVE_MESSAGE_TYPE.(anonymo…://www.paypalobjects.com/api/checkout.js:2401:13)", timestamp: 1497034701463, windowID: "03d8049eec", pageID: "703b8197ff", referer: "http://brody-ols.gmfsh.state.nm.us"…} 

 Error
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:2477:118)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:2381:73)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:2401:13)
__webpack_require__.i.window.console.window.console.(anonymous function) @ index.js:536
print @ logger.js:53
log @ logger.js:161
error @ logger.js:214
error @ logger.js:36
Component.logError @ index.js:496
(anonymous) @ index.js:1177
(anonymous) @ promise.js:224
SyncPromise.dispatch @ promise.js:254
SyncPromise.then @ promise.js:279
SyncPromise.try @ promise.js:335
ParentComponent.error @ index.js:1175
(anonymous) @ decorators.js:24
(anonymous) @ promise.js:224
SyncPromise.dispatch @ promise.js:254
SyncPromise.then @ promise.js:279
SyncPromise.try @ promise.js:335
descriptor.value @ decorators.js:23
(anonymous) @ index.js:65
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ index.js:1149
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:251
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:319
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:319
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:319
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:319
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:251
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:147
flush @ promise.js:12
(anonymous) @ promise.js:27
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:251
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:251
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:147
flush @ promise.js:12
(anonymous) @ promise.js:27
options.respond @ client.js:93
_RECEIVE_MESSAGE_TYPE.(anonymous function) @ types.js:122
receiveMessage @ index.js:94
messageListener @ index.js:119
types.js:122 Uncaught Error
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:2477:118)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:2381:73)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:2401:13)
_RECEIVE_MESSAGE_TYPE.(anonymous function) @ types.js:122
receiveMessage @ index.js:94
messageListener @ index.js:119

**Comment by jeffbrody** [comment]
Never mind - when I use the PayPal sample code
                return paypal.request.post(CREATE_URL)
                    .then(function(res) {
                    	console.log(res.paymentID);
                        return res.paymentID;
                    });
it works correctly.

**Comment by dkns** [comment]
Same issue here. What I don't understand is why it shows env: production when I inspect error object in chrome dev tools when I have it set to env: sandbox.

country:"US"
env:"production"
error:"SyntaxError: Unexpected end of JSON input↵    at JSON.parse (<anonymous>)↵    at XMLHttpRequest.<anonymous> (https://www.paypalobjects.com/api/checkout.js:11001:39)"
host:"localhost"
lang:"en"

**Comment by trainerbill** [comment]
@dkns The default is production so I am guessing the error is throwing before the configuration is set.  If you want to head over to the gitter room I can help you troubleshoot.

https://gitter.im/paypal/paypal-checkout

**Comment by dkns** [comment]
@trainerbill I'm good actually. Turned out that unexpected JSON was entirely my fault. I was using paypal.request.post to post data to my php script and from what I understand that function expects JSON to be returned. I wasn't returning any JSON so I think it was just returning my whole php script hence the unexpected '<' as it's first character of any php file: <?php

And what you say about showing env: production makes a lot of sense.

**Comment by bluepnume** [comment]
@jericopulvera -- can we close this out, or is it still failing for you? If so could you provide a url where I can try your integration?

**Comment by jericopulvera** [comment]
Anyone using laravel and getting this error. 
It was probably because of Laravel Debugbar messing with the json response.

**Comment by aespinosaMD** [comment]
I haved this problem, I solve using: https://jsonlint.com/
to validate the json, the problem are a TAB in json file, im from mexico, my english level is low sorry :' )

**Comment by LoveChase** [comment]
> Sandbox or production? And does the same problem happen after you clear your cookies for paypal.com (or use incognito mode)?

Hey Thank you so much for your comment, I have been trying to figure out an odd bug that did not exists in incognito. 
Really appreciate you!
