### ISSUE TITLE
PayPal Token

### ISSUE THREAD

**Issue by FabioSapienza** [paypal/paypal-checkout#369]
Hello 

More than an issue this is a question. Once the PayPal token is generated for a customer's payment will it expire at some point? for instance with our CC process after 2 weeks the authorization will expire. Because the PayPal payment is already taken I would think the token would not expire but I need to know for sure before I start coding on a project.

Thank you in advance for any help

Fabio

**Comment by bluepnume** [comment]
Yes, the EC token is valid for 72 hours.

**Comment by FabioSapienza** [comment]
Thank you for  your prompt response!
