### ISSUE TITLE
question: How does the javascript minification works with angular?

### ISSUE THREAD

**Issue by david-gang** [paypal/paypal-checkout#371]
Hi all,

As i am aware the angular dependency injection works either:
* by name - Angular examines the names of the parameter and injects the variables by name
* by the $inject property of the function: fun.$inject=['$scope']

As i see here:
https://raw.githubusercontent.com/paypal/paypal-checkout/master/dist/checkout.min.js
The word $scope does not occur.

How angular knows to inject $scope?

If it does not work it may be useful to annotate the angular file either manuallly or using https://www.npmjs.com/package/gulp-ng-annotate
If this is the case maybe this should be done right at https://github.com/krakenjs/xcomponent/blob/master/src/drivers/angular.js

Thanks,
David

**Comment by bluepnume** [comment]
Thanks again for the fix -- doing a release later today which should pick it up

**Comment by david-gang** [comment]
This issue was fixed by the new release of paypal-checkout due to it's use of the new release of xcomponent.

Thanks,
David
