### ISSUE TITLE
reason_code missing from response

### ISSUE THREAD

**Issue by Klavius** [paypal/paypal-checkout#372]
When a transaction is sent to pending status the response does not include the reason_code

Example
`"related_resources": [
	{
		"sale": {
			"id": "1GB488962W8790300",
			"state": "**pending**",
			"payment_mode": "INSTANT_TRANSFER",
			"protection_eligibility": "INELIGIBLE",
			"parent_payment": "PAY-086351365L183535GLFBPOCY",
			"amount": {
				"total": "599.00",
				"currency": "MXN",
				"details": {
					"subtotal": "599.00"
				}
			},
			"transaction_fee": {
				"value": "32.07",
				"currency": "MXN"
			}
		}
	}
]`

**Comment by bluepnume** [comment]
Hey @Klavius -- let me get this added in. Thanks for the report.

**Comment by bluepnume** [comment]
This should now be resolved, please let me know if you still don't see the field.
