### ISSUE TITLE
Error: No value passed to payment

### ISSUE THREAD

**Issue by cfengineers** [paypal/paypal-checkout#373]
Cant even get the online demo to work correctly.

 Error: Error: No value passed to payment
    at Object.onSuccess (https://www.paypalobjects.com/api/checkout.js:8035:52)
    at https://www.paypalobjects.com/api/checkout.js:3636:82
    at SyncPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:3651:19)
    at SyncPromise.resolve (https://www.paypalobjects.com/api/checkout.js:3614:18)
    at https://www.paypalobjects.com/api/checkout.js:3597:33
    at flush (https://www.paypalobjects.com/api/checkout.js:3520:43)
    at err (https://www.paypalobjects.com/api/checkout.js:3528:21)
    at Object.onSuccess (http://scrubin.d3.wris.net/ernie/test2.cfm:36:25)
    at https://www.paypalobjects.com/api/checkout.js:3636:82
    at SyncPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:3651:19)
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:2477:118)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:2381:73)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:2401:13)
__webpack_require__.i.window.console.window.console.(anonymous function) @ index.js:536
print @ logger.js:53
log @ logger.js:161
error @ logger.js:214
error @ logger.js:36
Component.logError @ index.js:496
(anonymous) @ index.js:1177
(anonymous) @ promise.js:224
SyncPromise.dispatch @ promise.js:254
SyncPromise.then @ promise.js:279
SyncPromise.try @ promise.js:335
ParentComponent.error @ index.js:1175
(anonymous) @ decorators.js:24
(anonymous) @ promise.js:224
SyncPromise.dispatch @ promise.js:254
SyncPromise.then @ promise.js:279
SyncPromise.try @ promise.js:335
descriptor.value @ decorators.js:23
(anonymous) @ index.js:65
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ index.js:1149
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:251
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:319
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:319
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:319
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:319
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:251
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:147
flush @ promise.js:12
(anonymous) @ promise.js:27
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:247
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:251
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:251
(anonymous) @ promise.js:227
SyncPromise.dispatch @ promise.js:254
SyncPromise.reject @ promise.js:199
(anonymous) @ promise.js:147
flush @ promise.js:12
(anonymous) @ promise.js:27
options.respond @ client.js:93
_RECEIVE_MESSAGE_TYPE.(anonymous function) @ types.js:122
receiveMessage @ index.js:94
messageListener @ index.js:119
types.js:122 Uncaught Error: Error: No value passed to payment
    at Object.onSuccess (https://www.paypalobjects.com/api/checkout.js:8035:52)
    at https://www.paypalobjects.com/api/checkout.js:3636:82
    at SyncPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:3651:19)
    at SyncPromise.resolve (https://www.paypalobjects.com/api/checkout.js:3614:18)
    at https://www.paypalobjects.com/api/checkout.js:3597:33
    at flush (https://www.paypalobjects.com/api/checkout.js:3520:43)
    at err (https://www.paypalobjects.com/api/checkout.js:3528:21)
    at Object.onSuccess (http://scrubin.d3.wris.net/ernie/test2.cfm:36:25)
    at https://www.paypalobjects.com/api/checkout.js:3636:82
    at SyncPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:3651:19)
    at Object.onSuccess (https://www.paypalobjects.com/api/checkout.js:8035:52)
    at https://www.paypalobjects.com/api/checkout.js:3636:82
    at SyncPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:3651:19)
    at SyncPromise.resolve (https://www.paypalobjects.com/api/checkout.js:3614:18)
    at https://www.paypalobjects.com/api/checkout.js:3597:33
    at flush (https://www.paypalobjects.com/api/checkout.js:3520:43)
    at err (https://www.paypalobjects.com/api/checkout.js:3528:21)
    at Object.onSuccess (http://scrubin.d3.wris.net/ernie/test2.cfm:36:25)
    at https://www.paypalobjects.com/api/checkout.js:3636:82
    at SyncPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:3651:19)
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:2477:118)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:2381:73)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:2401:13)
_RECEIVE_MESSAGE_TYPE.(anonymous function) @ types.js:122
receiveMessage @ index.js:94
messageListener @ index.js:119

**Comment by bluepnume** [comment]
Could you share the code you're using? Thanks!

**Comment by cfengineers** [comment]
<!DOCTYPE html>
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<script src="https://www.paypalobjects.com/api/checkout.js"></script>
</head>
<body>
<div id="paypal-button"></div>
<script>
paypal.Button.render({
env: 'production', // Or 'sandbox',
client: {
sandbox: 'xxxxx',
production: 'xxxxx'
},
commit: true, // Show a 'Pay Now' button
env: 'sandbox',
payment: function(resolve, reject) {
var CREATE_PAYMENT_URL = 'http://scrubin.d3.wris.net/ernie/testjson.cfm';
paypal.request.post(CREATE_PAYMENT_URL, {
// js object used to create payment
transactions: [
{
amount: { total: '20.00', currency: 'USD' }
}
]
}).then(function(data) {
resolve(data.paymentID);
}).catch(function(err) {
reject(err);
});
},
onAuthorize: function(data) {
var EXECUTE_PAYMENT_URL = 'http://scrubin.d3.wris.net/ernie/testjson.cfm';
paypal.request.post(EXECUTE_PAYMENT_URL, {
// js object used to complete payment
// needs to include properties for paymentID and payerID
}).then(function(data) {
// process results after transaction is completed
}).catch(function(err) {});
},
onCancel: function(data) {}
}, '#paypal-button');
</script>
</body>

___________________________________________________________________
Ernest E. Breau Jr.
Senior Coldfusion Developer
      cell: (508) 264-9856
   email: ernest.breau@gmail.com
resume: http://cfengineers.com
  twitter: http://twitter.com/cfengineers

**Comment by trainerbill** [comment]
@cfengineers come over to the gitter room and I can help you with your integration questions.

https://gitter.im/paypal/paypal-checkout

**Comment by bluepnume** [comment]
@cfengineers I tried sending a POST request to your url, I got this back:

```json
{"COLUMNS":["ID","TITLE","POSTED"],"DATA":[["905D9689-0130-1A16-62272F586A771C0C","mmm","May, 15 2007 10:31:00"],["905DAAED-E300-3B9D-7E25E43985CA9507","nn","May, 15 2007 10:31:00"],["905DE931-B8DB-B1AD-F77FC505851C2E9A","j","May, 15 2007 10:31:00"],["905E0C6A-99B8-97EC-4862D9064B9EC659","mmmmm","May, 15 2007 10:31:00"],["905E5910-0E2D-C566-5DCD39E6FD48ED06","NUMBER 11","May, 15 2007 10:32:00"]]}
```

This doesn't seem to include a `paymentID` field...
