### ISSUE TITLE
ExpressCheckout: Pay With Credit / Debit doesn't call onAuthorize

### ISSUE THREAD

**Issue by BrokenWits** [paypal/paypal-checkout#376]
**Environment**: Sandbox
**Version**: Latest available here https://www.paypalobjects.com/api/checkout.js (4.0.82). Also tested with Latest available on Github (4.0.84 at time of writing)

I'm using the client side REST option, and up until a few days ago, everything had been working fine. Now, when I pay selecting 'Pay with Credit / Debit' option; and enter the card number listed under my sandbox account, onCancel is called after filling out the form, and submitting 'Pay Now.

This happens even on the demo page; https://developer.paypal.com/demo/checkout/#/pattern/client when I use my sandbox and production credentials.

The Logged In Pay Flow works fine; and onAuthorize is called without issue, it's only in Guest Checkout that this has occurred in.

**Comment by trainerbill** [comment]
@BrokenWits sometimes our sandbox has issues when you use the same CC over and over.  Try getting a random card number from getcreditcardnumbers.com.

**Comment by BrokenWits** [comment]
@trainerbill Thanks for the reply. I tried a few numbers on getcreditcardnumbers.com that didn't seem to work. I finally just created a new developer buyer account, and then it worked.

Thanks for the help!
