### ISSUE TITLE
lightbox stuck on loading / processing in angular SPA after onAuthorise call

### ISSUE THREAD

**Issue by jpduckwo** [paypal/paypal-checkout#377]
Hi I've got a paypal button in an angular app that is mostly working except when the onAuthorize method is called the modal isn't closing. It just sits there saying 'Processing'.

I noticed that there was a actions.close() method on the actions argument that is passed in, so I tried to call that after executing the transaction, however it only half closes it and leaves an overlay with a spinner.

Gets stuck on this
![image](https://user-images.githubusercontent.com/13150911/27273895-6d5c9508-5514-11e7-942f-b57b4d29016e.png)

I can't find anything else in the documentation. My onAuthorize method does this:

``` 
       function paypalAuth(resp, actions) {
            var data = {
                payerID: resp.payerID,
                paymentID: resp.paymentID,
            };
            return api.paypalExecute(data) // my server that executes transaction
                .then(function(resp) {
                    // Close the paypal lightbox
                    actions.close();
... etc
```

**Comment by jpduckwo** [comment]
I solved this by using a paypal.Promise() instead of standard ones... odd
```
             return new $window.paypal.Promise(function(resolve, reject) {
                api.paypalExecute(data)
                    .then(function(resp) {
                        resolve();
                    })
                    .catch(function(err) {
                        reject();
                    });
            });
```

**Comment by trainerbill** [comment]
@jpduckwo Our internal promise is a bit different from native promises.  Glad you found a workaround!
