### ISSUE TITLE
Fallback on PAYEE_ACCOUNT_INVALID

### ISSUE THREAD

**Issue by trainerbill** [paypal/paypal-checkout#379]
https://www.sandbox.paypal.com/webapps/hermes/fallback?product=ec&fallback=1&incontext=1&reason=unhandled_contingency&token=EC-4XM32196HH591260P&useraction=commit

![image](https://user-images.githubusercontent.com/3578259/27294078-ee627604-54dd-11e7-8b76-035b716435db.png)

Use the following client id: AVD0w3jYeb6LA5J-tGacAk8vE-Dvz9g2fL-hlwzvbAansqx17UuFpJ9EN6entt4i-1LnW4XzQzOTB5_V

Happens when the account isn't verified.  Should have a proper Hermes error message.

**Comment by bluepnume** [comment]
Unverified accounts aren't valid for in-context. But since legacy can handle them, no harm in falling back right?

**Comment by trainerbill** [comment]
Sandbox is very finicky and there are tons of times when the sandbox account is created and not set to valid.  I think it would be best to just add the error in Hermes for PAYEE_ACCOUNT_INVALID so people aren't confused.  Otherwise they may go the entire development experience in legacy.  IMO it would be best to land on a Hermes error page, with a proper error, and then have a button that is clickable for fallback.  Or a quick timer and then fallback.

**Comment by bluepnume** [comment]
Going to close this since fallbacks are being phased out in Hermes, but it's an orthogonal concern to checkout.js
