### ISSUE TITLE
Trigger function before the popup is opened? (Act like submit button?)

### ISSUE THREAD

**Issue by sharazam** [paypal/paypal-checkout#383]
Hi,

I have a question regarding the checkout flow. I have a form which I want to validate first (using HTML5 validation), before the user is even gets the popover to log in with PayPal. Basically so that once the button is clicked, it's similar to a submit button, from the users perspective.

What I am doing right now is that I am triggering the input validation in the payment callback function. But this is called after the popover is created, which is not what I want.

How can I call a function before the popover is triggered? Is this available in the current version of checkout.js?

**Comment by bluepnume** [comment]
Yeah, it's definitely not ideal doing this in the `payment()` function. We provide the following mechanism to do validation and enable/disable the button: https://developer.paypal.com/demo/checkout/#/pattern/validation
