### ISSUE TITLE
"400" error / no message

### ISSUE THREAD

**Issue by kiliandr** [paypal/paypal-checkout#386]
using the express checkout javascript. most of the time i get the message

`Failed to load resource: the server responded with a status of 400 (Bad Request)`

but not always... sometime it seems to work.. but even then it does not call my own success function paypal_thankyou() which is included in the javascript.

Now i switched back to

`window.alert("Danke für Ihre Paypal-Zahlung!");`

but even this does not work...

I tried the interactive demo but its not working on my own webspace...

i googled a lot and i waited some days (because i read that this might help) - no change. Just not working.

**Comment by bluepnume** [comment]
Can you share your full code?

**Comment by kiliandr** [comment]
yes. i just replaced it here

**Comment by bluepnume** [comment]
Could you please share the code with the client ids, so I can try it? They're totally safe to share.

**Comment by kiliandr** [comment]
sandbox Ab3fN0ev3AvoYBYR8kgsXBLV8YTx7tu4beh2LmHLrUFYsDKU2DWA0Y_CGO-cWodF_fKXPdsioW4gHHUh

**Comment by bluepnume** [comment]
I tried your client id here: http://bluesuncorp.co.uk/icv4/test.htm

It seems to work pretty consistently for me. Can you try on that page?

**Comment by kiliandr** [comment]
hello,
yes it works on that page and even on the paypal test page.
but not on my own page. maybe an ssl issue?

**Comment by bluepnume** [comment]
Do you have a live version of that page I can try?

Do you see any javascript errors in the console?

**Comment by kiliandr** [comment]
no, sorry, there is no life version at the moment.

I get the error that i mentioned above.


funny... because now, after about a week, its working... without a change.
I have to improve the paypal_thankyou() function now and hope that it will work.
thanks therefore!

**Comment by bluepnume** [comment]
Awesome! Going to close this issue. Please let me know if you run into any more.

**Comment by kiliandr** [comment]
the reason is probably that the "invoice number" cannot be used twice or more.

**Comment by alamin3000** [comment]
Thanks @kiliandr I was going crazy with this same problem.  It turns out you are right.  In the testing site I was same invoice so it works once and then doesn't work.
