### ISSUE TITLE
Bug - Close button on checkout modal not working 

### ISSUE THREAD

**Issue by sumitsavla** [paypal/paypal-checkout#389]
Close button on the checkout modal is not working.. but close button on far top-right works
Its critical as many users might not even discover second close button and not now button. 

I marked close button thats not working on screen
 
![incontext checkout modal bug](https://user-images.githubusercontent.com/1326949/27502831-e964df2e-582b-11e7-86cd-db1c142d36dc.jpeg)

**Comment by bluepnume** [comment]
@vishakha94 could you take a look?

**Comment by vishakha94** [comment]
@sumitsavla Could you send in any error log you might be getting?

**Comment by sumitsavla** [comment]
I didn't see any error in console log
Can u try sample txn for in-context checkout to launch interestitilal ?

Best,
Sumit

**Comment by vishakha94** [comment]
So, we are not facing this error  on our standard checkout integration. Would you mind pointing us to any sample integration where you were facing this issue? Thanks.

**Comment by sumitsavla** [comment]
I can help in reproducing, r u in SJ office ?

**Comment by sumitsavla** [comment]
[www.paypal.com-1498628481112.txt](https://github.com/paypal/paypal-checkout/files/1107674/www.paypal.com-1498628481112.txt)
Attached error log.. rename file to .log if cant open

**Comment by sumitsavla** [comment]
this is resolved when I tested yesterday. 
Popup is getting closed

**Comment by JekaPolihovic** [comment]
how do I add this modaw window to my page and link it to the product?
