### ISSUE TITLE
Force to open in a modal, not in a popup

### ISSUE THREAD

**Issue by orianweste** [paypal/paypal-checkout#393]
Hi,

I have the problem, that the PayPal login form always opens in a popup. But I want to have it in a modal like the payment overview:
![modal](https://github.com/paypal/paypal-checkout/raw/master/docs/img/checkout.png)

Is it possible?

If not, is there another way to use this PayPal Button in a Cordova app? Because the popup doesn't work there.

Thank you.

**Comment by bluepnume** [comment]
Is there a way to identify Cordova from the client-side?

**Comment by orianweste** [comment]
Yes for example:
`var isCordovaApp = !!window.cordova;`

**Comment by orianweste** [comment]
@bluepnume Any idea ? 
Thank you

**Comment by bluepnume** [comment]
@orianweste The problem is, we only allow the iframe when we can detect that it's legitimately being loaded in a context where popups don't work. `window.cordova` could easily be faked. Is there a custom user agent for cordova? What's `window.navigator.userAgent`?

**Comment by bluepnume** [comment]
We can track the cordova support feature request here: https://github.com/paypal/paypal-checkout/issues/420
