### ISSUE TITLE
Web-view issue for Telegram APP

### ISSUE THREAD

**Issue by dynalz** [paypal/paypal-checkout#396]
If a user tries to purchase from our shop from an Apple mobile device (ipad or iphone) through Telegram in-app browser and attempts to pay with Paypal all they'll get is a blank white screen.
Mostly our costumers come all from telegram and since 50% of them are apple users this issue is recurrent. Does anyone experience the same?

![image](https://user-images.githubusercontent.com/12519753/27765902-fa6fe46c-5eb6-11e7-9b30-19e7406645a8.png)

**Comment by bluepnume** [comment]
Is the in-app browser a web-view or a SafariViewController?

**Comment by dynalz** [comment]
Sorry my bad, it's actually the SFSafariViewController.

**Comment by bluepnume** [comment]
OK. There's a discussion over here for this issue: https://github.com/paypal/paypal-checkout/issues/347

**Comment by George-cb** [comment]
I don't use PayPal for security reasons. Why don't you send me the security practices for PayPal.
