### ISSUE TITLE
Error: WeakMap expected key, angular implementation

### ISSUE THREAD

**Issue by Planet910** [paypal/paypal-checkout#399]
I'm implementing playpayl-button into my angularJS application and i started with this example:
https://github.com/paypal/paypal-checkout/blob/master/demo/angular.htm

But I get this error "Error: WeakMap expected key".

I just copy-pasted that example into my app without modifying anything, I have no idea what to do, can someone help me?

**Comment by bluepnume** [comment]
- Can you share the full error with stack trace?
- Does the error occur here too? http://krakenjs.com/xcomponent/demo/frameworks/angular/index.htm
- Which browser(s)?
- Can you share your full code?

**Comment by bluepnume** [comment]
Please let me know if you have the above details and if you're still seeing the same issue. Thanks!

**Comment by binhbbui411** [comment]
I faced the same problem. Here's my code: https://codepen.io/SlashBunny/pen/BweENY?editors=1000  
Would appreciate if someone can give me an explanation
