### ISSUE TITLE
PayPal button refused to load the image (CSP)

### ISSUE THREAD

**Issue by Fowowski** [paypal/paypal-checkout#401]
### Description

After the page being loaded the button looks fine for 1-2 seconds (probably depends on the Internet connection) and then an error is produced in the developer console plus the button itself looses the images that were first displayed.

![paypal-button-csp](https://user-images.githubusercontent.com/2796226/28112003-c0cf25ee-66f7-11e7-8984-c233c205c594.png)

![paypal-button-csp-error](https://user-images.githubusercontent.com/2796226/28112168-5329ed3e-66f8-11e7-8460-71f64d2a8050.png)

### Steps to reproduce

While having a developer console open go to the url: https://developer.paypal.com/demo/checkout/#/pattern/client

Or simply implement the same version of paypal-checkout via eg. npm repository to your page.
I was also able to reproduce this on previous versions: 4.0.87, 4.0.88 no only the latest 4.0.89

This error occurs on:
Chrome Version 59.0.3071.115 (Official Build) (64-bit)
Firefox 54.0 (64-bit)

I don't have the option to check other browsers currently.

**Comment by bluepnume** [comment]
Thanks for the heads up. There was a roll out with some new CSP rules which affected the button, I'm kicking off a roll back now.

**Comment by bluepnume** [comment]
This is now fixed. Thanks for your patience.

**Comment by Fowowski** [comment]
Sure thanks for the really fast fix!
