### ISSUE TITLE
Logging into Paypal Express Checkout Crashes Firefox on iOS

### ISSUE THREAD

**Issue by mcstover** [paypal/paypal-checkout#405]
### Description

When logging in via the Paypal Express dialog, Firefox on iOS crashes. I think this has to do with pop up blockers being enabled by default in the browser though that may not be the full story.

Testing from a real device is important as launching Firefox for iOS via XCode and the Simulator do not consistently hit this issue. However, real devices fail every time.

*My apologies for not providing a video or code. Videos of this process would expose accounts and credentials. Code is unnecessary as it occurs in the demo site as well. Should these be needed feel free to contact me and we can work out a way to share info privately.

- [ ] Screenshots or videos that show the issue
- [ ] Your code
- [ ] The version of checkout.js (https://www.paypalobjects.com/api/checkout.js)
- [ ] A link to your page with the issue, if possible
- [ ] All console logs during the time of the issue, especially error messages
- [X] Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
YES

### Steps to reproduce

Go to Developer demo page above using Firefox on iOS, attempt to log in.

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [x] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [x] iOS

**Comment by bluepnume** [comment]
Thanks for raising the issue! I'll try to repro and let you know what I find.

**Comment by bond1126** [comment]
Yes, the login dialog box also crashes in Chrome, Safari and Edge. It works in IE but typing in the password requires hitting the keyboard multiple times. Needs a fix big time.

**Comment by bond1126** [comment]
I forgot to mention that everything works perfectly in the Sandbox mode.

**Comment by bluepnume** [comment]
+ @crookedneighbor 

@vishakha94 any luck reproducing this one?

**Comment by vishakha94** [comment]
@mcstover @bond1126 
I tried reproducing this issue. Went to the developer demo page and tried logging on in the production env. For me, nothing crashed. 
Are you still facing this issue or some other issue I am not seeing?

**Comment by mcstover** [comment]
Hi @vishakha94 + @bluepnume 

Sorry I missed the notice to review the status of this issue. 
I've just checked functionality on the current release of FFiOS and the issue is fixed!

Guess some other work along the way cleared up the issue.

Keep up the good work!

**Comment by vishakha94** [comment]
Thanks. Closing it now.
