### ISSUE TITLE
Token mismatch error always logged in console

### ISSUE THREAD

**Issue by Millais** [paypal/paypal-checkout#407]
With Checkout.js, a token mismatch error is always logged in the browser console when _payment()_ is called in Sandbox. This is present for integration methods via client-side REST, server-side REST and the Braintree SDK. For instance: 
![image](https://user-images.githubusercontent.com/7149113/28361084-75499244-6c6f-11e7-88b7-811c41fc8dc6.png)

You can reproduce this error message by selecting each of the integration types on the [interactive demo page](https://developer.paypal.com/demo/checkout/#/pattern/client) on PayPal developer, and invoking _payment()_ by clicking the rendered PayPal button.

This could be a design decision to log the EC token and payment ID. However, this should probably appear as an informational message on the console, rather than an error – as it does not appear to be an error, and may be confusing for developers.

This appears with the latest version of Checkout.js loaded from the [PayPalObjects](https://www.paypalobjects.com/api/checkout.js). Tested in Sandbox on Chrome, Safari and Firefox.

**Comment by bluepnume** [comment]
We have a fix for this in place, going out with the next code push. Totally agreed that it's confusing.

**Comment by bluepnume** [comment]
Fix pushed.
