### ISSUE TITLE
Add user scalable setting in doc for mobile experience

### ISSUE THREAD

**Issue by shoaibmir** [paypal/paypal-checkout#408]
Hi Daniel,

As discussed, creating this tracker item for doc changes to add user scalable setting like an example below for mobile web:

<meta name=“viewport” content=“width=device-width, user-scalable=no”>

This is to make sure buyers get an overlay on mobile device for a OneTouch/Cookied user scenario. 

Thanks,
Shoaib

**Comment by vishakha94** [comment]
Docs added.
https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/best-practices/#improve-the-mobile-experience-with-the-viewport-tag
