### ISSUE TITLE
Incorrect z-index in Sandbox mode

### ISSUE THREAD

**Issue by zeronone** [paypal/paypal-checkout#410]
### Description

Please provide a short description of the issue here, along with:

Sandbox mode has incorrect syles. `zIndex` should be `z-index`
Source code [link](https://github.com/paypal/paypal-checkout/blob/e479db048f7225c326e741b85db99a866eedb411/src/components/checkout/templates/container/template.jsx#L41)

**Comment by zichi** [comment]
I have the same issue.

**Comment by bluepnume** [comment]
Fixed and pushed. Please clean your cache and you should see the fix.
