### ISSUE TITLE
Sometimes paypal not return sale id, when payment is success

### ISSUE THREAD

**Issue by superp** [paypal/paypal-checkout#411]
### Description

I have a lot of payments by day, and sometimes paypal don't receive sale id after successful payment (money charge from credit card).

```
onAuthorize: (data, actions) ->
        actions.payment.execute().then((payment) =>
          captureID = payment?.transactions[0]?.related_resources[0]?['sale']?['id']
```

Sometimes captureID id is undefined.
What can I do with this?

**Comment by bluepnume** [comment]
Hi @superp, thanks for the issue. Can you copy the `paypal-debug-id` response header from the execute http call so I can check? Thanks!

**Comment by superp** [comment]
Unfortunately, I don't have a response, because this issue happens on the client side with my customers.

**Comment by superp** [comment]
I think that this issue comes in when user payment goes to hold and check by paypal on fraud.
We decided to create paypal webhooks and check all payments twice.
Thanks for attention!

**Comment by bluepnume** [comment]
Thanks @superp, glad it got resolved.
