### ISSUE TITLE
Possible to double-click on the paypal button

### ISSUE THREAD

**Issue by bluepnume** [paypal/paypal-checkout#412]

**Comment by AdeAttwood** [comment]
It looks like there is a fix in place for this but I'm getting `ppxo_button_mutliple_click_debounce` log on double click. This is after the reject method has been called in the payment function. Should this activate the button again?

**Comment by bluepnume** [comment]
@AdeAttwood you're right, this is broken for the `reject()` case. I have a fix and I should be able to push it today.

**Comment by AdeAttwood** [comment]
As far as i can tell this is fixed

**Comment by bluepnume** [comment]
Yep, fix is pushed. Thanks again for the report!
