### ISSUE TITLE
Android Firefox presents obscured modal view

### ISSUE THREAD

**Issue by crookedneighbor** [paypal/paypal-checkout#413]
### Description

When starting the flow with Android Firefox, it presents the modal iframe (even though Android Firefox _should_ support popups). When it does, it looks like this:

![screenshot_20170721-110051](https://user-images.githubusercontent.com/2916945/28477753-1902b40e-6e1b-11e7-9062-7b1ed1c6105f.png)

Latest version of checkout.js.

- [x] Screenshots or videos that show the issue
- [ ] ~~Your code~~
- [x] The version of checkout.js you're using (or the paypalobjects url)
- [ ] ~~A link to your page with the issue, if possible~~
- [ ] ~~All console logs during the time of the issue, especially error messages~~
- [ ] ~~Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?~~

### Steps to reproduce

Download Firefox on an Android device. Start the PayPal flow.

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [x] Firefox (Android only)
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by alexstanbury** [comment]
I have just tried this on my Galaxy S7 running Nougat 7.0 with latest Firefox 54.0.1 and I get the popup and it works as expected. I am however seeing this issue in my Cordova app #420. Seems there is something not right in the browser/environment detection.

**Comment by bluepnume** [comment]
Should be fixed. Please let me know if you see the issue again.
