### ISSUE TITLE
IE9 has shrunken window

### ISSUE THREAD

**Issue by crookedneighbor** [paypal/paypal-checkout#415]
### Description

When opening the flow in IE9, the width of the login and logged in window is not 100%. The logging in spinner is centered correctly.

Using version 4.0.94.

![screen shot 2017-07-24 at 9 59 26 am](https://user-images.githubusercontent.com/2916945/28529734-ef2b6098-7056-11e7-9365-b3aeb30c7a8b.png)
![screen shot 2017-07-24 at 9 56 33 am](https://user-images.githubusercontent.com/2916945/28529743-f22ec186-7056-11e7-9903-7a80b46b2d40.png)

### Steps to reproduce

Open the PayPal flow in IE9.

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [x] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Added a page here to get to Hermes in IE9 mode: http://bluesuncorp.co.uk/icv4/sandbox.htm

**Comment by bluepnume** [comment]
Closing as the new login experience should be ramped up by now.
