### ISSUE TITLE
Paypal Button renders then immediately disappears

### ISSUE THREAD

**Issue by mcstover** [paypal/paypal-checkout#416]
### Description

Over the weekend something changed in the operation of the paypal express checkout button on kiva.org's payment page. The button initially renders then quickly disappears.

While attempting to debug this using Chrome's dev tools, I noticed that the instance fell into a "sacrificialIframe" state and triggered the "hideElement" method. I believe this code was in the drivers.js.

I could not determine what set this in motion as we had not made any changes to our code over the weekend.

- [x] https://drive.google.com/file/d/0B-nF0MgqRt4wSHhvWVJPY0Z4MUk/view?usp=sharing
- [x] https://www-kiva-org.global.ssl.fastly.net/rgit2e969457aa8884f7fa081b0de7339ebe19865461/views/Basket/ReviewBasketView.js
- [x] https://www.paypalobjects.com/api/checkout.min.js
- [x] See Notes in Reproduction Section
- [x] No console log messages were reported
- [ ] Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?

### Steps to reproduce

Visit Kiva.org
Click "Lend" in the top Navigation
Select any Loans  and click "Lend $25" to add it to your Basket
Click "Proceed to Checkout" to visit the Basket, then Click Continue
Log In or Register to be sent to the payment page.
* We had to turn off the button to the public, Paste this link in the address bar to trigger usage of the Paypal Express flow ( https://www.kiva.org/basket/payment?kexpn=paypal_express_checkout.checkout_paths&kexpv=b )

### Affected browsers

- [x] Chrome
- [x] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Thanks for the report. Taking a look.

**Comment by bluepnume** [comment]
I'm seeing the button is being hidden by your code, but I can't see the reason:

<img width="974" alt="screen shot 2017-07-25 at 10 57 27 am" src="https://user-images.githubusercontent.com/1219075/28578718-8dd75522-7128-11e7-84d7-2251b11ce49f.png">

Can you please look at the un-minified code and figure out why this `.hide()` line would be triggered?

**Comment by mcstover** [comment]
@bluepnume How did you find that?!?! I tried to break on changes to that attribute or element but couldn't get to the stack trace you found.

You were absolutely correct. This was an unplanned interference from a different 3rd party lib.

Thank you so much for looking at this and I apologize for taking up your time with something we did.

I think it's safe to close this issue.

**Comment by bluepnume** [comment]
Haha no problem at all! Glad to hear you managed to track it down.

You can set a breakpoint on changes to an element like so:

<img width="475" alt="screen shot 2017-07-25 at 2 21 56 pm" src="https://user-images.githubusercontent.com/1219075/28587321-c5dba664-7144-11e7-9754-08aeadb74caa.png">
