### ISSUE TITLE
Paypal Express Checkout not firing onCancel when minibrowser Closed!!

### ISSUE THREAD

**Issue by Azhar-Baig-Cat** [paypal/paypal-checkout#418]
From few days back i have been working on express checkout with paypal, at that time when i close the mini browser the onCancel callback was fired with no issues.
But today with same code when i clicked the close button of mini browser, the onCancel callback didn't fired

Actual Behavior 
Not firing the onCancel callback

Expected Behavior
Should fire onCancel callback

# **My Code**

<!DOCTYPE html>

<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <script src="https://www.paypalobjects.com/api/checkout.js"></script>
</head>

<body>
    <div id="paypal-button-container"></div>

    <script>
        paypal.Button.render({

            env: 'sandbox', // sandbox | production

            // PayPal Client IDs - replace with your own
            // Create a PayPal app: https://developer.paypal.com/developer/applications/create
            client: {
                sandbox:    'AZDxjDScFpQtjWTOUtWKbyN_bDt4OgqaF4eYXlewfBP4-8aqX3PiV8e1GWU6liB2CUXlkA59kJXE7M6R',
                production: '<insert production client id>'
            },

            // Show the buyer a 'Pay Now' button in the checkout flow
            commit: true,

            // payment() is called when the button is clicked
            payment: function(data, actions) {

                // Make a call to the REST api to create the payment
                return actions.payment.create({
                    payment: {
                        transactions: [
                            {
                                amount: { total: '0.01', currency: 'USD' }
                            }
                        ]
                    }
                });
            },

            // onAuthorize() is called when the buyer approves the payment
            onAuthorize: function(data, actions) {

                // Make a call to the REST api to execute the payment
                return actions.payment.execute().then(function() {
                    window.alert('Payment Complete!');
                });
            },
  	     onCancel : function(data){
				console.log(data);
				window.alert("cancelled");
			}

        }, '#paypal-button-container');

    </script>
</body>

- Latest version of checkout.js (<script src="https://www.paypalobjects.com/api/checkout.js"></script>) which will automatically download the latest
- [x] Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?

Yes the issue also occurs at the demo provided.

**Comment by bluepnume** [comment]
Thanks for the heads-up. Got a fix which is ready to push in the next release.

**Comment by bluepnume** [comment]
The fix is pushed and your issue should now be resolved -- please let me know if you still see the problem. Thanks!
