### ISSUE TITLE
Include PayPal Debug ID in Client side responses

### ISSUE THREAD

**Issue by Austin57129** [paypal/paypal-checkout#419]
Whenever an unexpected issue occurs, PayPal technical support asks for the Debug ID to troubleshoot the error. Currently the Debug ID is only provided on server side REST calls so this extends the PayPal review process and time to resolve issues.

Occurs on V4 of the checkoutJS for all client side calls.

**Comment by bluepnume** [comment]
Would it be helpful to log this in the console and just have merchants copy and paste everything from there?

**Comment by Austin57129** [comment]
It would need to be able to be logged so when consumers report payment issues they can pull that Debug ID and reach out to PP support for assistance. I'm thinking it would have to be returned in the payload.

**Comment by bluepnume** [comment]
The `paypal-debug-id` is already returned as a response header in the payload right? So the checkout.js script could pull that and console log it to make it easier to copy and paste

**Comment by bluepnume** [comment]
Plan is to add this to any http response error messages, so merchants should be able to do something like:

```javascript
return actions.payment.create(...).catch(function(err) {
    log(err.message);
    throw err;
});
```

**Comment by bluepnume** [comment]
Change is in and ready to push! Should go out today ideally

**Comment by bluepnume** [comment]
This is pushed.
