### ISSUE TITLE
Error when lightbox is triggered from an iFrame

### ISSUE THREAD

**Issue by edbird-pp** [paypal/paypal-checkout#421]
### Description

`Uncaught Error: Unable to find window by ref` is triggered when the lightbox experience is triggered from an iFrame. This also means that return and cancel URLs are loaded in the main window, instead of triggering the callbacks.

### Steps to reproduce

You can reproduce it by adding `<iframe src="https://developer.paypal.com/demo/checkout/#/pattern/client"></iframe>` to the demo site

### Affected browsers

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
FYI with the latest push the lightbox is disabled by default for logged in users. Still need to figure out the root cause but that should mitigate for now. Clean cache and you should see the fix.

**Comment by bluepnume** [comment]
Managed to get some time to look into this and figured out the root cause. Thanks again for pointing this out! Fix will go out with the next push.

NB: Iframe mode is still disabled, so this fix won't have any immediate effect.
