### ISSUE TITLE
MALFORMED_REQUEST issue with payer.payer_info.phone and phone_type

### ISSUE THREAD

**Issue by JerrodV** [paypal/paypal-checkout#422]
Using https://www.paypalobjects.com/api/checkout.js
Where the user has the option to checkout as guest. Form requires Contact Information/Phone. Attempting to send payment.payer.payer_info.phone or .phone_type causes:

"name":"MALFORMED_REQUEST","message":"Incoming JSON request does not map to API request","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST"

The following issue discussed the same issue when using the .Net SDK:
https://github.com/paypal/PayPal-NET-SDK/issues/258
It suggests that the phone should be passed as a property of payment.payer.payer_info.billing_address. When providing the phone there, I no longer get the error, but it does not populate the field on the form as one would expect.

Also, it does not seem logical that this is where the property would exist. The email field (checkout form) in the same Contact Information section, which populates just fine, is not part of payment.payer.payer_info.billing_address, but instead is part of payment.payer.payer_info. Why would properties displayed in the Contact Information section of the checkout be in separate objects in the parameter JSON?

Thanks for any help you can offer.

**Comment by bluepnume** [comment]
Thanks for the report. @sinhanurag could you comment on this one?

**Comment by bluepnume** [comment]
Assigning to @bluelnkd to help triage and get the question to the right people.

**Comment by bluepnume** [comment]
Actually @JerrodV can you please raise this issue over here? https://github.com/paypal/PayPal-REST-API-issues
