### ISSUE TITLE
"related_resources" is unpopulated with payment.get()

### ISSUE THREAD

**Issue by tfulton** [paypal/paypal-checkout#426]
### Description

When creating a payment ("intent: order"), the order ID is critical when later authorizing.  Server REST call returns this id in a "related_resources" node.  The checkout.js payment.get() method returns the same node empty.  This is a problem, and prevents a pure javascript solution when intent=order is used.

Please see attached server and checkout.js payment.get responses for same payment at same state :  
[payment-get-checkoutjs.txt](https://github.com/paypal/paypal-checkout/files/1191109/payment-get-checkoutjs.txt)
[payment-get-server-rest.txt](https://github.com/paypal/paypal-checkout/files/1191110/payment-get-server-rest.txt)

Server REST URI

```
https://api.sandbox.paypal.com/v1/payments/payment/PAY-40R65933AT480002CLGAJRHI
```

Client code post-execute used to output the ''payment-get-checkoutjs.txt" payload above:

```
        const onAuthorize = (data, actions) => {
            console.log("onAuthorize actions: .......", actions)
            console.log("onAuthorize data: .......", data)

            return actions.payment.execute().then((response) => {
                console.log('onAuthorize payment.execute().  Data: ', response)
                let auth = {};
                auth.paid = true;
                auth.cancelled = false;
                auth.payerID = data.payerID;
                auth.paymentID = data.paymentID;
                auth.paymentToken = data.paymentToken;
                auth.returnUrl = data.returnUrl;

                actions.payment.get().then((payment) => {
                    console.log("onAuthorize payment.get(): ", JSON.stringify(payment))
                    return onSuccess(auth);
                })

            }).catch(e => onError(e))
        }
```

**Comment by bluepnume** [comment]
Thanks for the details. Code change made, will let you know when the checkout app gets a release window.

**Comment by tfulton** [comment]
Thank you Daniel!!

**Comment by bluepnume** [comment]
This should now be resolved, please let me know if you still don't see the field.
