### ISSUE TITLE
Lightbox experience getting redirected to return URL

### ISSUE THREAD

**Issue by shoaibmir** [paypal/paypal-checkout#427]
On https://developer.paypal.com/demo/checkout/#/pattern/client 

For lightbox experience:

<img width="780" alt="screen shot 2017-08-03 at 9 42 20 am" src="https://user-images.githubusercontent.com/1455536/28902387-343752d2-7831-11e7-81cc-de7dcc5aa4e5.png">

When I click cancel, it takes me to return URL https://www.sandbox.paypal.com/businessexp/summary?token=EC-0FH626669S832971M but in case of non-lightbox experience, context is taken back to main site. 

This is happening both for Sandbox and Production environment. 

Thanks,
Shoaib

**Comment by bluepnume** [comment]
@shoaibmir can you check the `paypal.version` in your console? And if you're not getting at least `4.0.99` can you clear cache and try again?

Lightbox should actually be disabled in sandbox/production right now, so you shouldn't be seeing that experience unless you're in a webview or a browser which does not support popups.

**Comment by shoaibmir** [comment]
We already have it discussed offline. Thank you so much for your support on this, please let me know when fix is live and I will test it again.

**Comment by bluepnume** [comment]
Fix is live now. Please clear your cache and give it a shot.

**Comment by shoaibmir** [comment]
Hi Daniel, 

It all looks good with version 102 and no more return URL problem but I can still see the light box and few errors in console:

<img width="1406" alt="screen shot 2017-08-03 at 3 06 07 pm" src="https://user-images.githubusercontent.com/1455536/28910013-8650dea4-785d-11e7-8314-e25e67087849.png">

Thanks,
Shoaib

**Comment by bluepnume** [comment]
OK, closing this. I'll relay the CSP errors on. Thanks!
