### ISSUE TITLE
Error: Unable to delegate rendering

### ISSUE THREAD

**Issue by minzojian** [paypal/paypal-checkout#429]
same problem like https://github.com/paypal/paypal-checkout/issues/140

my payment page which using new paypal check.js is placed in an iframe
i can success render a pay button,however, as i click that paypal pay button,i got the error below,and paypal popup just close automatic
how to solove the problem?

Uncaught Error: Unable to delegate rendering. Possibly the component is not loaded in the target window.

Error: No ack for postMessage xcomponent_delegate_ppcheckout in 1000ms
    at cycle (client.js:171)
    at cycle (client.js:171)
    at index.js:597
    at promise.js:158
    at ZalgoPromise.dispatch (promise.js:183)
    at ZalgoPromise.reject (promise.js:111)
    at promise.js:153
    at ZalgoPromise.dispatch (promise.js:183)
    at ZalgoPromise.reject (promise.js:111)
    at promise.js:179
    at promise.js:158
    at ZalgoPromise.dispatch (promise.js:183)

**Comment by bluepnume** [comment]
Do you have checkout.js loaded in the top-level window? That's a requirement for rendering the button inside an iframe.

**Comment by bluepnume** [comment]
Closing this, since didn't hear a response. Please let me know if you still have trouble with this.

**Comment by dilakshandc** [comment]
hi what do you mean top level window and where is this checkout.js
