### ISSUE TITLE
Security Error (DOM Exception 18)

### ISSUE THREAD

**Issue by PKMTracker** [paypal/paypal-checkout#430]
![dom](https://user-images.githubusercontent.com/22338421/28999319-6b934626-79ff-11e7-901b-fc73a500bc5b.PNG)

With Paypal Express Rest, on a wide range of devices, most reports related to mobile chrome.

Any idea if an error on my side? And if so, what's best solution to fix?

Thanks!

**Comment by bluepnume** [comment]
Hi, could you please copy the full error message and stack trace? And let me know which browsers you see this error in? Thanks!

**Comment by PKMTracker** [comment]
Sorry, I can't. These are on mobile phones and as much as I can grab. Mostly happens on iPhones and Chrome. I can't replicate to debug it tho.

**Comment by bluepnume** [comment]
Do you see any bugs resulting from this error or do you just see the error?

**Comment by PKMTracker** [comment]
Bug: The paypal button will only randomly work, after this error is shown. 
Line: Only shows line as "5".
Reproduce: Hit or miss. Majority of the reports come from newest IOS version and newest Chrome.

**Comment by bluepnume** [comment]
> Reproduce: Hit or miss. Majority of the reports come from newest IOS version and newest Chrome.

At what stage does the error occur? On button render, button click..?

> Bug: The paypal button will only randomly work, after this error is shown.

Can you elaborate on "not work" -- does the button click do nothing, or does something else unexpected happen?

**Comment by PKMTracker** [comment]
Errors on: Button Render, which is called from JS after the DOM is ready.

Not work: When you click the button, it may or may not load the paypal popup.

**Comment by bluepnume** [comment]
I'm still unable to repro. Any chance of a link to your site so I can try there?
