### ISSUE TITLE
Closing popup window before initialization breaks the functionality

### ISSUE THREAD

**Issue by mrharel** [paypal/paypal-checkout#432]
### Description
If the user clicks on the pay button and immediately close the popup button, there is no way to re-open it again by clicking on the button. the user need to refresh the page to fix it. 

Here is an example from your own [demo site](https://developer.paypal.com/demo/checkout/#/pattern/client):
![paypal api](https://user-images.githubusercontent.com/473889/29017023-459792fe-7b55-11e7-987b-b8c803715577.gif)

- [x] Screenshots or videos that show the issue
- [ ] Your code
- [ ] The `paypal.version` from your browser console
- [x] A link to your page with the issue, if possible
- [ ] All console logs during the time of the issue, especially error messages
- [x] Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?

### Steps to reproduce
1. Click on the pay button
1. close the popup window
1. click again on the pay button

### Affected browsers

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Thanks for the report @mrharel! There's a fix ready in `master` branch, we just need to deploy it. Should be deployed today.

**Comment by bluepnume** [comment]
Pushed, please let me know if you still see the issue. Thanks again.

**Comment by mrharel** [comment]
👍 
The eBay dev team in Berlin thank you :)

**Comment by MaxDBN** [comment]
@bluepnume Hello, I'm having the exact same issue.

**Comment by mrharel** [comment]
@bluepnume we are experiencing this bug again. it appeared back in the last few days (maybe recent release?)

To reproduce, you need to click on the pay button, close the popup window and click on the layer. I reproduce it on your demo page again. 

![paypal-bug](https://user-images.githubusercontent.com/473889/44518256-18887200-a6ca-11e8-8134-23fde60d0d4a.gif)

can you please have a look and maybe re-open this issue?

**Comment by bluepnume** [comment]
Can you please raise a new issue with all requested details.

**Comment by mrharel** [comment]
@bluepnume just did https://github.com/paypal/paypal-checkout/issues/845
