### ISSUE TITLE
PayPal button not rendering in WebViews

### ISSUE THREAD

**Issue by andreabondi** [paypal/paypal-checkout#433]
### Description

Hi,
the PayPal button doesn't render anymore inside a WebView, leaving just a blank space. Tested also with https://developer.paypal.com/demo/checkout/ and get the same issue.

On the console log of a WebView I see the error below, which doesn't appear on the console of a normal Chrome page. Here's a screenshot of the console:

![screen shot 2017-08-09 at 12 02 25](https://user-images.githubusercontent.com/1085145/29118627-a5a07f2a-7cfa-11e7-9c70-3614f458cfa6.png)

Looking at recent commits, seems the most relevant related change is the introduction of Bowser to detect browser version.

### Steps to reproduce

Load any page with a PayPal button generated via checkout.js

### Affected browsers

- [X] Web View

**Comment by andreabondi** [comment]
Just to add more context, to recreate the issue I generated a new device using Chrome Developer Tools with this WebView User Agent:
`Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Mobile/14G60` (most recent UA from iOS WkWebView)

**Comment by bluepnume** [comment]
Thanks again for the report. Fix is pushed, should be able to see it after a cache clean.

**Comment by Kaushik0704** [comment]
@andreabondi @bluepnume Still I'm Getting Issue, Can you please help me.

**Comment by bluepnume** [comment]
Can you please raise a new issue with all requested details? Thanks

**Comment by kumarranganath** [comment]
Users are not able to see pay now button.  Please see the attachment
![payment-screen-not-loading-not-showing-pay-button](https://user-images.githubusercontent.com/5340883/44893504-12694580-ad09-11e8-813a-f74fce9e39c8.png)

All our customers/users are facing problem in completing payment process and not able to fill up credit/debit card information and do payment.

Page is not loading completely and having issue in doing payment.  This is happening in Google chrome 

Please find the attached screen which not loading properly and I am able to reproduce issue

Please check and do the needful ASAP and advice?

**Comment by kumarranganath** [comment]
Unsafe JavaScript attempt to initiate navigation for frame with origin 'https://www.radreviewmhe.com' from frame with URL 'https://payflowlink.paypal.com/? '. The frame attempting navigation is targeting its top-level window, but is neither same-origin with its target nor has it received a user gesture. See https://www.chromestatus.com/features/5851021045661696.

init @ pflPayments.js:80
(anonymous) @ ? :1102
pflPayments.js:80 Uncaught DOMException: Failed to execute 'replace' on 'Location': The current window does not have permission to navigate the target frame to 'https://payflowlink.paypal.com/?'.
    at Object.init (https://payflowlink.paypal.com/js/pflPayments.js:80:26)
    at https://payflowlink.paypal.com/? :1102:36
init @ pflPayments.js:80
(anonymous) @ ? :1102
