### ISSUE TITLE
Invalid property on documentation

### ISSUE THREAD

**Issue by delissonjunio** [paypal/paypal-checkout#434]
### Description

On the documentation about Angular integration, there's a wrong property name, which causes the client to fail to render the paypal pay button.

Where there is 'onAuthorize', there should be 'on-authorize', or else Angular doesn't find the property

### Steps to reproduce

https://github.com/paypal/paypal-checkout/blob/master/docs/frameworks.md 

### Affected browsers

- [x] Chrome

**Comment by bluepnume** [comment]
Good catch, thanks for the heads up! Fixed

**Comment by delissonjunio** [comment]
Heh, the commit changed the react code, I was talking about Angular. More specifically, [line 98 on the same file](https://github.com/paypal/paypal-checkout/blame/master/docs/frameworks.md#L98)

**Comment by bluepnume** [comment]
Whoops - clearly I was half asleep yesterday. Fixed!
