### ISSUE TITLE
ppxo_unhandled_error / Uncaught Error: Detected close during init

### ISSUE THREAD

**Issue by stevedeighton** [paypal/paypal-checkout#435]
### Description

I'm using the paypal button with checkout.js inside an angular 4 app.  When the payment component initialises it loads in the checkout.js script, then creates the button. Everything works as expected, apart from if I move away from the component whilst the paypal button is initialising, then i get the following error:

`ppxo_unhandled_error ` from `logger.js`

and then

`Uncaught Error: Detected close during init` from `subscriber.js`

See http://i.imgur.com/B4JhLTg.png for screenshot of error

I just want to handle the error and probably just ignore it, but my global error handler is picking it up :/

Any ideas?

### Steps to reproduce

As above, cannot provider repo or plunker etc, sorry.

### Affected browsers

- [X] Chrome
- [?] Safari
- [?] Firefox
- [?] Edge
- [?] IE
- [?] Chrome Mobile/Tablet
- [?] Safari Mobile/Tablet
- [?] Web View / Safari ViewController
- [?] Other

**Comment by jsgphd** [comment]
I am getting a similar error.  It isn't calling the onAuthorize.  Any help I am pretty stuck at this point...

Object {stack: "Error: Detected close during init    at eval (web…/~/paypal-checkout/dist/checkout.lib.js?:1302:32)", errtype: "[object Error]", timestamp: 1502390905846, windowID: "0b6d2a91bd", pageID: "65c3666459"}errtype: "[object Error]"pageID: "65c3666459"stack: "Error: Detected close during init↵    at eval (webpack:///./~/paypal-checkout/dist/checkout.lib.js?:5353:88)↵    at check (webpack:///./~/paypal-checkout/dist/checkout.lib.js?:1302:32)"timestamp: 1502390905846windowID: "0b6d2a91bd"__proto__: Objectconstructor: function Object()hasOwnProperty: function hasOwnProperty()isPrototypeOf: function isPrototypeOf()propertyIsEnumerable: function propertyIsEnumerable()toLocaleString: function toLocaleString()toString: function toString()valueOf: function valueOf()__defineGetter__: function __defineGetter__()__defineSetter__: function __defineSetter__()__lookupGetter__: function __lookupGetter__()__lookupSetter__: function __lookupSetter__()get __proto__: function __proto__()set __proto__: function __proto__()
print @ checkout.lib.js:326
log @ checkout.lib.js:419
error @ checkout.lib.js:454
(anonymous) @ checkout.lib.js:12431
dispatchPossiblyUnhandledError @ checkout.lib.js:7604
(anonymous) @ checkout.lib.js:7683
checkout.lib.js:5353 Uncaught Error: Detected close during init
    at eval (checkout.lib.js:5353)
    at check (checkout.lib.js:1302)
(anonymous) @ checkout.lib.js:5353
check @ checkout.lib.js:1302


```

**Comment by bluepnume** [comment]
@stevedeighton -- yeah, this is something we need to consider. Sometimes the iframe being destroyed during init is an error case, sometimes it's legitimate (like in your case, changing view during render.) I'm leaning in the direction of just removing this error.

@jsgphd can you elaborate on your use case? Ideally please raise a separate issue with steps to reproduce.

**Comment by bluepnume** [comment]
OK, this error is removed. Will go out with the next push.

**Comment by bluepnume** [comment]
Fix pushed. Please clear your cache, and let me know if you still see the issue.
