### ISSUE TITLE
Pass access token on restart flow

### ISSUE THREAD

**Issue by bluepnume** [paypal/paypal-checkout#436]
To ensure lightbox can authenticate. 

Problem: old versions of checkout.js don't have `accessToken` prop. How do we pass this without causing errors?

**Comment by Chavezo** [comment]
[bugreport.zip](https://github.com/paypal/paypal-checkout/files/1386308/bugreport.zip)

**Comment by digitalidentit4d** [comment]
Request to resarvetion funding mone
