### ISSUE TITLE
After completing a checkout, button doesn't respond to clicks

### ISSUE THREAD

**Issue by georgiosd** [paypal/paypal-checkout#437]
Hi folks,

After going through a full checkout, clicking the button no longer brings up the dialog. 
I see it making a request to the hermes logger but that's it.

Any ideas? Using it with the React component.

**Comment by bluepnume** [comment]
Hi @georgiosd -- did you see the checklist for submitting an issue? Without those details it's pretty difficult to replicate bugs. Thanks!

**Comment by georgiosd** [comment]
Apologies. I thought it would a straight-forward answer but I guess it's not. Here I go :)

Code excerpts:

```
const PayPalButton = paypal.Button.driver('react', { React, ReactDOM });

<PayPalButton
                                    env={this.state.paypalMode}
                                    locale={'en_US'}
                                    style={ { size: 'responsive', color: 'gold', shape: 'rect' } }
                                    commit={true}
                                    validate={validate}
                                    onClick={gotoValidationStep}
                                    payment={createPayment}
                                    onAuthorize={executePayment}
                                    onCancel={cancelPayment} />
```
Version:
```
"paypal-checkout": "^4.0.84",
```

Description:

- I click checkout, go through a full checkout, all works OK
- I click checkout again, button does nothing

No error messages in console. I just see the requests to the hermes logger.
This is on Chrome latest. Haven't tried on anything else.

I am happy to give a link to a staging server where you can try this but I wouldn't like to post that publicly.

**Comment by bluepnume** [comment]
Hi,

`"paypal-checkout": "^4.0.84",`

If you do an `npm ls paypal-checkout` what version do you get? Can you please make sure you're on at least `4.0.110`

**Comment by georgiosd** [comment]
I upgraded to .110 and now I'm getting the window cleanup error @ https://github.com/paypal/paypal-checkout/issues/404 

I will see if I can work around it to determine if the original problem persists.

**Comment by georgiosd** [comment]
I didn't find any workarounds that are not affected by #404. I will close this until #404 is fixed and will reopen if the problem persists.
