### ISSUE TITLE
4.0.110 checkout.js is not found

### ISSUE THREAD

**Issue by MrBlaise** [paypal/paypal-checkout#438]
### Description

Please provide a short description of the issue here, along with:

- [X] A link to your page with the issue, if possible

### Steps to reproduce

Install paypal-checkout using npm (latest 4.0.110 version)
It will try to fetch https://www.paypalobjects.com/api/checkout.4.0.110.js
But this link returns 404

### Affected browsers

- [X] Chrome
- [X] Safari
- [X] Firefox
- [X] Edge

**Comment by bluepnume** [comment]
Thanks @MrBlaise, good catch. Seems like this file failed to upload to the CDN properly. I've kicked it off again, should be up very soon.

**Comment by MrBlaise** [comment]
Thanks it loads correctly now! :)
