### ISSUE TITLE
When did disableLightbox get dropped?

### ISSUE THREAD

**Issue by yabdab** [paypal/paypal-checkout#441]
Starting today I get the error "Invalid prop: disableLightbox". This prevents the button from rendering.

**Comment by bluepnume** [comment]
Hi @yabdab -- are you explicitly passing this prop in your `Button.render()` call?

**Comment by yabdab** [comment]
`paypal.Button.render({ disableLightbox: true ... });`

Like so.

**Comment by bluepnume** [comment]
OK. This was an internal, undocumented flag that was only intended to be used by the `checkout.js` script itself. I would recommend removing this from your integration.

**Comment by yabdab** [comment]
How can I then disable Lightbox and force the window popover?

**Comment by bluepnume** [comment]
Lightbox is disabled by default, in the latest build -- hence why this internal option was removed. So you should always get the popup unless you're in a browser which doesn't support popups (like web-views)

**Comment by yabdab** [comment]
Daniel,

Thanks for the clarification. 

I cannot remember when I had such good developer support and feedback from PayPal. You are doing an awesome job and you should be commended. Great job.

**Comment by bluepnume** [comment]
Thanks @yabdab, appreciate it!
