### ISSUE TITLE
Refuse to get unsafe header "paypal-debug-id"

### ISSUE THREAD

**Issue by limaneto** [paypal/paypal-checkout#444]
Hi, every the paypal screen opens I get this error: can someone help ? Thanks !
![image](https://user-images.githubusercontent.com/6009780/29429227-4ed03506-8366-11e7-98ca-9752fe0e7b3a.png)

**Comment by bluepnume** [comment]
Thanks for the heads-up! Getting a fix out for this asap.

**Comment by bluepnume** [comment]
This should now be resolved, please clear your cache, make sure `paypal.version === '4.0.112'` and you should be good.

**Comment by voltairebiton** [comment]
I am encountering this too. It always happens during paypal create payment when using php rest sdk under this code

```
            payment: function() {

                // Set up a url on your server to create the payment
                var CREATE_URL = '/demo/checkout/api/paypal/payment/create/';

                // Make a call to your server to set up the payment
                return paypal.request.post(CREATE_URL)
                    .then(function(res) {
                        return res.paymentID;
                    });
            },
```

![image](https://user-images.githubusercontent.com/32069198/30548328-e923d3ba-9ca2-11e7-9f8c-0c2e743f45b5.png)

**Comment by tabularaza27** [comment]
Is there any progress on this one ? Same happens for me using the node rest sdk

![image](https://user-images.githubusercontent.com/17277529/31549907-db860098-b02f-11e7-8a03-751b4cdbfb70.png)

**Comment by bluepnume** [comment]
Can you advise what `paypal.version` shows in your console? Thanks

**Comment by victordidenko** [comment]
Have same issue
<img width="985" alt="screen shot 2017-10-13 at 22 14 00" src="https://user-images.githubusercontent.com/15016227/31562390-e4228bc0-b063-11e7-9e24-fcf05731cd68.png">

**Comment by ggdeal-wojtek** [comment]
Same issue with version 4.0.136:

![unsafe-header-paypal](https://user-images.githubusercontent.com/32768112/31684457-2943383e-b380-11e7-9ead-a16353a1da20.png)

**Comment by bluepnume** [comment]
Going to reopen this issue while I investigate. Thanks for the heads up.

**Comment by oilee80** [comment]
Hey all this is a CORS issue not a JS issue
The response from your payment URL needs the following header even if the header isn't being set `Access-Control-Expose-Headers: paypal-debug-id`
I can also see that this is wrapped in a `try/catch` in my version but still outputs an error in the console but doesn't stop execution

**Comment by bluepnume** [comment]
Thanks @oilee80 

Do others on this thread actually see the flow being blocked by this error? Or do you just see the error in the console without any other effects?

**Comment by victordidenko** [comment]
@bluepnume no, flow wasn't blocked by this error, it was just red error in console, in my case, didn't affect anything I aware of.
But I don't see such error recently, it disappeared. Guess it was fixed, or you changed smth...
`paypal.version` is `4.0.157`

**Comment by bluepnume** [comment]
Yep! This was fixed in the latest release.
