### ISSUE TITLE
Newest commits broke responsive

### ISSUE THREAD

**Issue by PKMTracker** [paypal/paypal-checkout#445]
![pay1](https://user-images.githubusercontent.com/22338421/29459432-c1329a1a-83e0-11e7-878f-51b363c4b9f3.PNG)
![pay2](https://user-images.githubusercontent.com/22338421/29459436-c3d5058c-83e0-11e7-8260-e899a030537d.PNG)

The max-width is set to 200, at all media sizes (0px). Button size is set to response.

It would be nice to have an option that sets width/height to 100% and does not set max width/height, so we can control the size on our end, instead of trying to make hacks with !important to override features as well. (If not already possible?)

Thanks for reading!

**Comment by bluepnume** [comment]
Hi @PKMTracker -- did you see the template for raising issues? I really need an example of your code, and the css on your parent page, to reproduce this.

**Comment by bluepnume** [comment]
@PKMTracker please let me know if you can provide some more info here.
