### ISSUE TITLE
Add Docs / Examples for new button styles

### ISSUE THREAD

**Issue by bluepnume** [paypal/paypal-checkout#448]
https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/customize-button/

- color: black
- label: generic
- tagline: false
- example of responsive button with media query

https://developer.paypal.com/demo/checkout/

- label: generic
- tagline: false
- page for responsive button with media query

### Media query: 

(button displays 100% on mobile, 250px on desktop)

```javascript
<style>
    @media screen and (max-width: 400px) {
        #paypal-button-container {
            width: 100%;
        }
    }
    
    @media screen and (min-width: 400px) {
        #paypal-button-container {
            width: 250px;
        }
    }
</style>

<div id="paypal-button-container"></div>

<script>
    paypal.Button.render({
        
        style: {
            size:  'responsive'
        },
        
        payment: function() {

        },
        
        onAuthorize: function(data, actions) {
            
        }

    }, '#paypal-button-container');

</script>
```

**Comment by bluepnume** [comment]
Also there's a bug on the page:

> Note: The minimum width of the button is 80px.

should be 

> Note: The minimum width of the button is 100px.

**Comment by vishakha94** [comment]
Generic button demo is already in the code.

**Comment by vishakha94** [comment]
can we add `tagline: false` demo once its live? Do not want to break the demo page.

**Comment by bluepnume** [comment]
It's live now :)

**Comment by PWaddict** [comment]
Nothing is actually changed on the width. The button's max-width is still 500px :( Why you are not letting us have 100% width?????

**Comment by yabdab** [comment]
I don't see any "new" styles on the docs? Black is not listed as possible color, etc etc...

**Comment by bluepnume** [comment]
@PWaddict we're looking at the issue you posted. It's a feature request and we're debating whether it's something we want to include.

@yabdab this issue is to get the new styles into the docs.

**Comment by vishakha94** [comment]
Docs live.
