### ISSUE TITLE
10486 redirect does not work when intent:authorize or intent:order

### ISSUE THREAD

**Issue by umulla** [paypal/paypal-checkout#449]
### Description

Please provide a short description of the issue here, along with:

10486 redirect, aka insufficient funds recovery,  does not work when intent:authorize or intent:order,

In Basic client Integraion
- does not trigger open the pop up 

In Advanced Server Integration
- calling actions.restart() does open the pop up but does not show the error message nor does it remove the funding source which had insufficient funds.. It merely restarts the PP checkout process.

- [ ] Screenshots or videos that show the issue
- [ ] Your code
- [ ] The `paypal.version` from your browser console
- [ ] A link to your page with the issue, if possible
- [ ] All console logs during the time of the issue, especially error messages
- [x] Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?

### Steps to reproduce

Please provide each individual step required to reproduce the issue

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Can you please check with the payments team. `checkout.js` just responds to the success/error code in the response, and for `authorize` we're getting a success on execute so we treat the transaction as being complete.

**Comment by umulla** [comment]
i tested this out.. i was able to get the instrument declined on the execute .. REST SB is down now.. will test again and let you know
