### ISSUE TITLE
checkout doesn't work with property “payee”

### ISSUE THREAD

**Issue by imkimchi** [paypal/paypal-checkout#451]
I'm new to paypal APIs so I'm kind of confused right now. creating transaction only works when I don't specify payee property, but how would paypal know who to send the money when there's no payee specified?

Here's the code

```js
$(function() {
    paypal.Button.render({
        env: 'sandbox', // Or 'sandbox'
        client: {
            sandbox:    'xxxxxx',
            production: 'xxxxxx'
        },

        commit: false, // Show a 'Pay Now' button

        payment: function(data, actions) {
            return actions.payment.create({
                payment: {
                    transactions: [
                        {
                            amount: { total: '5.00', currency: 'USD' },
                            description: "TEST",
                            payee: { email: "seller-inventory@gmail.com" }
                        }
                    ]
                }
            });
        },

        onAuthorize: function(data, actions) {
            return actions.payment.execute().then(function(payment) {
                console.log("payment", payment)
            });
        }

    }, '#paypal');
}) 
```

![image](https://user-images.githubusercontent.com/13452168/29937975-30ed737a-8ec2-11e7-8aa6-6d179c8a97d4.png)

**Comment by bluepnume** [comment]
We use the client id to figure out which account to send the money to, by default.

That said, not sure why you're getting this 400 error. Can you check the response for `/payment` in your network tab for a more detailed error?

**Comment by imkimchi** [comment]
@bluepnume I'm not trying to send request to `/payment` yet and didn't even send any request to my server. I just wanted to see it works with Paypal Express Checkout on client side with paypal server.

I'm making a marketplace like ebay, so people can pay for stuffs each other, not like a website for single seller. so I had to use `payee` property but couldn't figure out how to do it.

**Comment by bluepnume** [comment]
`actions.payment.execute()` makes the request for you, and according to the log you sent it's returning a 400. So you should see that failed request in your Chrome network log.

**Comment by imkimchi** [comment]
@bluepnume then how does it work when there's no `payee` property in the function when there's no router for handling payment request?

**Comment by bluepnume** [comment]
As I mentioned:

> We use the client id to figure out which account to send the money to, by default.

So in your case, we look at:

```
        client: {
            sandbox:    'xxxxxx',
            production: 'xxxxxx'
        },
```

And we link `xxxxxx` back to the account which created the client id, and the money is sent there.

**Comment by bluepnume** [comment]
Did you manage to check the error response in the network tab?

**Comment by MaxSwank** [comment]
Does this mean a "payee" email address cannot be directly added to the payment object?

Using my sandbox when I run this payment (minus payee): 

`payment: {
          transactions: [{
            amount: {
              total: this.data.amount,
              currency: 'USD'
            }
          }]
        }`

I get this success response: 

`{id: "PAY-3DX79834V91758101LJ2WR3I", intent: "sale", state: "approved", cart: "15795713CX4932608", create_time: "2018-02-03T07:47:14Z", …}
cart
:
"15795713CX4932608"
create_time
:
"2018-02-03T07:47:14Z"
id
:
"PAY-3DX79834V91758101LJ2WR3I"
intent
:
"sale"
payer
:
{payment_method: "paypal", status: "VERIFIED", payer_info: {…}}
state
:
"approved"
transactions
:
[{…}]`

As soon as I add payee:

`payment: {
          transactions: [{
            amount: {
              total: this.data.amount,
              currency: 'USD'
            } ,
            payee: {
              email: this.data.paypalEmail
            } 
          }]
        }`

If fails:

`ppxo_unhandled_error {stack: "Error: Error: Payment could not be executed↵    at…://www.paypalobjects.com/api/checkout.js:3080:13)", errtype: "[object Error]", timestamp: 1517644484889, windowID: "4a79d6fada", pageID: "71e0f8ba4a", …}country: "US"env: "production"errtype: "[object Error]"host: "localhost:4200"lang: "en"pageID: "71e0f8ba4a"path: "/level3/17452"prev_corr_ids: ""referer: "localhost:4200"stack: "Error: Error: Payment could not be executed↵    at handleExecuteError (https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js?`

What's the proper way to create a payee payment?  Is there a good example somewhere?

**Comment by imkimchi** [comment]
@MaxSwank Have you solved this problem yet?

**Comment by bluepnume** [comment]
This is a known issue on our side, please see https://github.com/paypal/paypal-checkout/issues/464 for updates as they come.
