### ISSUE TITLE
Paypal checkout page text scramled in safari

### ISSUE THREAD

**Issue by battem** [paypal/paypal-checkout#452]
Hi,

Paypal checkout page text is scramled in safari... see screenshot.

Not in Firefox and Chrome.

I am using the WP eStore shopping card plugin.

Any idea what the problem can be?

Thanks, JB

![screen shot 2017-08-31 at 21 20 35](https://user-images.githubusercontent.com/367393/29942459-3c46aec0-8e96-11e7-970b-8ef59bcdaa9e.png)

**Comment by bluepnume** [comment]
Assigning to @bluelnkd to help triage -- looks like a potential problem with the guest app.

**Comment by bluelnkd** [comment]
@battem Can you share a few more details so we can work on a fix?

- [ ] Version of Safari/OSX
- [ ] All console logs during the time of the issue, especially error messages

I'm trying to see what I can do to run into the same on our test devices here, and make sure we can see the same issue your reporting.

As an FYI the fonts used to render the checkout experience (along with most of PayPal) is set to: `font-family: HelveticaNeue-Light, Helvetica Neue Light, Helvetica, Arial, sans-serif;`

**Comment by battem** [comment]
Hi blueInkd,

Here is the link to the shoppingcard: http://letsgotothebeach.org/product/swim-sarong/

Im using WP eStore shopping card plugin + addon eStore Credit Card Default PayPal Checkout Option 

- Safari Version 10.1.1 
- OSX 10.11.6 El Capitan
- font: https://fonts.googleapis.com/css?family=Oxygen+Mono

I did not get any error messages.

Hope you can find out whats the problem... cant imagine my font is the cause?

Thanks, Jan.
