### ISSUE TITLE
PayPal do not answer with error

### ISSUE THREAD

**Issue by KES777** [paypal/paypal-checkout#457]
### Description

Making query to PayPal with wrong URL just hungs up

### Steps to reproduce

curl -v -X GET https://api.sandbox.paypal.com/notifications/webhooks-events/WH-2YK56274DW464652K-38041688MS2505840 -H "Content-Type:application/json" -H "Authorization: Bearer \<TOKEN\>"

Here `/v1` is missed at URL

### Affected browsers

Any

### EXPECTED

PayPal should return `404 Not Found` error

**Comment by bluepnume** [comment]
Thanks for the report. Unfortunately this repo is for the client side checkout.js integration only. I'll pass on the report to the right team.

**Comment by KES777** [comment]
thank you. May you supply URL so I can track progress. thank you.

**Comment by KES777** [comment]
Also, please give me a link where I can report bugs and/or feature requests

**Comment by bluepnume** [comment]
@trainerbill do we have a portal for external folk to raise bugs/issues for anything other than checkout.js?

**Comment by trainerbill** [comment]
You can submit rest related issues here:

https://github.com/paypal/PayPal-REST-API-issues

**Comment by KES777** [comment]
Ok. thank you. Also I got some troubles in dashboard
