### ISSUE TITLE
Pass paymentID to onCancel

### ISSUE THREAD

**Issue by KES777** [paypal/paypal-checkout#459]
### Steps to reproduce

Make two payments. First time cancel the payment and second time complete it.

In case of 'success' I got next url:

    ?paymentId=PAY-1U642214T1634025CLGZFFCI&token=EC-68Y47422RG6762610&PayerID=4JB7936RRMUUQ

In case of 'cancel' I got next url:

    ?token=EC-68Y47422RG6762610

Because of different URL, handlers can not do same job.  
In my case I can not mark that payment was canceled because of lack of `paymentId` argument for cancel URL

### Affected browsers

All

### Expected

all `redirect_urls` should be called with same arguments

**Comment by KES777** [comment]
Also from [DOC](https://developer.paypal.com/docs/integration/direct/express-checkout/get-payment-approval/) it is not clear where customer will be redirected when payment is canceled 

>The approval action redirects the buyer to the return URL with the payer ID and payment ID values appended.
>For example:
>http://return-url?paymentId=PAY-6RV70583SB702805EKEYSZ6Y&token=EC-60U79048BN7719609&PayerID=7E7MGXCWTTKK2

**Comment by bluepnume** [comment]
Assigning to @bluelnkd to help triage -- this seems like a reasonable request, but it's a downstream which generates the return and cancel urls so we'd need to get this internally prioritized.

**Comment by bluelnkd** [comment]
@KES777 FYI the paymentID and PayerID will only come back w/ valid IDs after a transaction completes.

See: https://developer.paypal.com/docs/integration/direct/payments/paypal-payments/#get-payment-approval

For the cancel use case -- what would be your preferred recommendation for what it comes back with for a value? We can't set a value on them that could potentially be interpreted as an ID, and likewise I'm uncertain if there's a semantic difference between:

- Explicitly setting NULL, which might be accidentally interpreted as an ID by some systems:
  `?paymentId=NULL&token=EC-68Y47422RG6762610&PayerID=NULL`
- Setting it as an empty string, which would be evaluated as NULL by most systems `?paymentId=&token=EC-68Y47422RG6762610&PayerID=`
- Implicitly setting it as NULL as we do right now, by excluding the value`?token=EC-68Y47422RG6762610`

If you can share a bit about the handling you've got right now I'm also happy to provide helpers/suggestions if you're running into problems as a result of the argument being undefined.

**Comment by bluepnume** [comment]
> We can't set a value on them that could potentially be interpreted as an ID

Why can't we? Normally `PayerID` is used to infer a successful transaction.

**Comment by KES777** [comment]
1. The `paymentId` is available when I create payment (`data.paymentID`):
```
	payment: function( resolve, reject ) {
		paypal.request.post( '<%= url_for( "paypal_payment_create" ) %>' )
				.then(function(data) { resolve(data.paymentID); })
				.catch(function(err) { reject(err); });
	},
```
_NOTICE_: `payment` is called two times by you. And this behavior nowhere is documented.

2. After this **paypal checkout** window is opened, `onAuthorize` method is invoked and call to execute payment is made:
```
        onAuthorize: function(data, actions) {
            paypal.request.post( '<%= url_for( "execute_paypal_payment" ) %>',
                    { paymentID: data.paymentID, payerID: data.payerID })
                .then(function(data) { /* Go to a success page */ actions.redirect(); })
                .catch(function(err) {  /* Go to an error page  */ actions.redirect(); });
        },
```
3. In the **paypal checkout window** customer may click 'pay now' or ['Cancel and return to test facilitator's Test Store'](https://www.sandbox.paypal.com/paypal/payment_cancel?token=EC-2UE13104M60460718)
and here you do:
a. call the callback /*go to success page */  #callback1

b. call the 'onCancel' event below #callback2

In both cases control is received from **paypal checkout window**, so you can call both callbacks 1 and 2 with same arguments, can not?

At lease `onAuthorize` event occur before `onCancel` event. You have `data.paymentId` on first step, so you can pass it also in the second too.

**Comment by KES777** [comment]
@bluelnkd [FYI](https://developer.paypal.com/docs/api/payments/#payment_execute) payment approval is the second step in checkout process:
first is: create payment
then client is redirected to **paypal checout window** and then one of two ways occur:
a) customer authorize and our server get additionally payerID so we execute payment
b) customer cancel and our server get request to 'cancel_url' with token=EC-**** 

Because `paymentId` is known on first step you can and **should** pass it at `cancel_url` so our server will understand which payment is canceled.

**Comment by KES777** [comment]
Here you can see that before customer `authorize` or `cancel` we have _paymentId_  `PAY-IDXXXX`
http://joxi.ru/D2PEpdQIdaEvNA

**Comment by bluepnume** [comment]
@KES777 -- definitely understand the need. I think we're powerless to change the return url at this point for fear of breaking any existing integrations, but I'm going to keep this open as a feature-request, to pass back `data.paymentID` in the payload passed to the `onCancel` callback. That should help for your use-case, and preserve backwards compatibility.

**Comment by KES777** [comment]
>data.paymentID in the data payload passed to the onCancel callback

yes. thank you. that will be sufficient, I think.

It will be more handy if you implement flag for `.redirect` when it is passed the `return_urls` will be with additional arguments:

    onCancel: function(data, actions) {
            console.log('The payment was cancelled!');
            actions.redirect( 'pass paymentID flag' ); # because of argument is TRUE, it will redirect to URL with additional query parameter `paymentID`
    }

**Comment by bluepnume** [comment]
This way you will be able to extend the redirect url yourself, if you need:

```
onCancel(data, actions) {
    actions.redirect(window, `${ data.cancelUrl }&paymentId=${ data.paymentID }`);
}
```

**Comment by KES777** [comment]
excelent.

one question, please. is anywhere documentation about events and arguments for this script?

sadly I found only small bits of information about that in different parts checkout integration guides.
and did not get whole picture what data is passed and how to work with that.

for example: 
 what `actions` are, which methods it has and how to work with them. I never see before the `redirect` is called with parameters.

**Comment by bluepnume** [comment]
@khanghoang -- can you please take this one up -- the fix should just be to pass back `data.paymentID` in the `onCancel` callback.

**Comment by khanghoang** [comment]
@KES777 it's live on the latest version so I will close this issue.
