### ISSUE TITLE
Problem with Angular 1.6

### ISSUE THREAD

**Issue by HDDinnova** [paypal/paypal-checkout#462]
I'm trying to insert a button in my AngularJS application but appears the following error:

> Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module paypal-button due to:
Error: [$injector:nomod] Module 'paypal-button' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.6.6/$injector/nomod?p0=paypal-button
    at http://terres.info/intranet/scripts/vendor-0bdef6ccc4.js:6:1280
    at http://terres.info/intranet/scripts/vendor-0bdef6ccc4.js:6:11606
    at t (http://terres.info/intranet/scripts/vendor-0bdef6ccc4.js:6:11067)
    at http://terres.info/intranet/scripts/vendor-0bdef6ccc4.js:6:11380
    at http://terres.info/intranet/scripts/vendor-0bdef6ccc4.js:6:19468
    at o (http://terres.info/intranet/scripts/vendor-0bdef6ccc4.js:6:1712)
    at f (http://terres.info/intranet/scripts/vendor-0bdef6ccc4.js:6:19316)
    at http://terres.info/intranet/scripts/vendor-0bdef6ccc4.js:6:19500
    at o (http://terres.info/intranet/scripts/vendor-0bdef6ccc4.js:6:1712)
    at f (http://terres.info/intranet/scripts/vendor-0bdef6ccc4.js:6:19316)

At index.htmlI insert the script line
`<script async src="https://www.paypalobjects.com/api/checkout.js"></script>`

**Comment by bluepnume** [comment]
Can you please provide an example of your unminified code?

Also -- does it help to remove the `async` from `<script async`?

**Comment by HDDinnova** [comment]
**The main index.html code:**

```
<!doctype html>
<html>
  <head>
    <base href="/intranet/">
    <meta charset="utf-8">
    <title>terres Catalunya International Eco & Tourism Film Festival</title>

    <meta name="viewport" content="width=device-width">
    <link rel="icon" type="image/png" href="favicon-32x32.png" />

    <meta name="description" content="terres Catalunya International Eco & Tourism Film Festival">
    <meta name="keywords" content="film,festival,nature,corporate,terres,tortosa,ebre,delta">
    <meta name="author" content="Filmsnòmades - terres Catalunya">
    <meta http-equiv="content-type" content="text/html;charset=UTF-8">

    <!-- build:css({.tmp,src}) styles/vendor.css -->
    <!-- bower:css -->
    <!-- run `gulp inject` to automatically populate bower styles dependencies -->
    <!-- endbower -->
    <!-- endbuild -->

    <!-- build:css({.tmp,src}) styles/app.css -->
    <!-- inject:css -->
    <!-- css files will be automatically insert here -->
    <!-- endinject -->
    <!-- endbuild -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="css/simple-lines-icons.css">
  </head>


  <body ng-app="app">
    <ui-view></ui-view>
  </body>

  <!-- build:js({.tmp,src}) scripts/vendor.js -->
  <!-- bower:js -->
  <!-- run `gulp inject` to automatically populate bower script dependencies -->
  <!-- endbower -->
  <!-- endbuild -->

  <!-- build:js({.tmp,src}) scripts/app.js -->
  <!-- inject:js -->
  <!-- js files will be automatically insert here -->
  <!-- endinject -->
  <!-- inject:partials -->
  <!-- angular templates will be automatically converted in js and inserted here -->
  <!-- endinject -->
  <!-- endbuild -->
  <script async src="https://www.paypalobjects.com/api/checkout.js" data-version-4></script>
</html>

```

**And the index.js:**

```
angular
  .module('app', ['ui.router', 'ngResource', 'ui.bootstrap', 'pascalprecht.translate', 'ngCookies', 'ngSanitize', 'angularSpinner', 'ngPassword', 'textAngular', 'ngFileUpload', 'paypal-button'])
  .constant('AUTH_EVENTS', {
    loginSuccess: 'auth-login-success',
    loginFailed: 'auth-login-failed',
    logoutSuccess: 'auth-logout-success',
    notAuthenticated: 'auth-not-authenticated'
  })
  .config(function ($translateProvider) {
    $translateProvider
      .registerAvailableLanguageKeys(['en', 'es', 'ca'], {
        'en_*': 'en',
        'es_*': 'es',
        'ca_*': 'ca'
      })
      .determinePreferredLanguage()
      .fallbackLanguage('ca')
      .useLocalStorage()
      .useStaticFilesLoader({
        prefix: 'i18n/locale-',
        suffix: '.json'
      })
      .useSanitizeValueStrategy(null);
  });
```

Without the `async` tag the result is the same

**Comment by bluepnume** [comment]
A few thoughts:

1. It looks like you're loading `checkout.js` after `app.js`, which means the `paypal-button` module wouldn't have a chance to be loaded before it's included in your script. Can you try loading `checkout.js` first?

2. Can you also try registering the angular driver, like so: https://github.com/paypal/paypal-checkout/blob/master/demo/angular.htm#L5 -- this should make sure the `paypal-button` module is available for your app to use.

Please let me know if that helps!

**Comment by bluepnume** [comment]
Are you still having any problems?

**Comment by lordvee** [comment]
Hey,
I am using angular-fullstack and have the issue described above. In my app it definitely loads before but ti seems like it does not become available to the app.
To be sure that it's loaded in the app it should provide an export namespace to the angularjs framework i suppose. Has anyone managed to make it work?

Thanks.
