### ISSUE TITLE
Button has no effect when clicking on certain versions of Chrome / Safari

### ISSUE THREAD

**Issue by jonnyxe** [paypal/paypal-checkout#463]
### Description

Details here: http://stackoverflow.com/questions/44088790/paypal-checkout-js-throws-blocked-iframe-access-error

Followed these instructions: https://developer.paypal.com/demo/checkout/#/pattern/client

Got following error when clicking the button:

"Blocked a frame with origin "https://domain.dev" from accessing a frame with origin "https://www.sandbox.paypal.com". Protocols, domains, and ports must match."

I know that there are a lot of more people having the problem. Please have a look at the Apache configuration with its X-Frame-Options. 

### Possible Solution

I have the same problem but I know how to get this fixed.
The Problem is on the PayPal site itself. PayPal configured their Apache server not correctly for using the frame thing.

They set the "X-Frame-Options" header option to "SAMEORIGIN" on their production and development environment/websites.

For us developer with newer browsers have no chance to get the frame according to policies to work.

### Steps to reproduce

https://developer.paypal.com/demo/checkout/#/pattern/client

- Laravel Valet on a Mac
- local site domain.dev
- follow instructions mentioned in the documentation of PayPal

### Affected browsers

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Web View / Safari ViewController

**Comment by bluepnume** [comment]
Hi @jonnyxe -- thanks for the report. I'm having a little trouble reproing though.

- Which specific url do you see the `X-FRAME-OPTIONS` header being sent with
- What do you see when you visit that url in a new tab rather than in an iframe
- Can you pass over the `paypal-debug-id` header from the response

**Comment by jonnyxe** [comment]
Clicking the button should open the frame containing https://www.sandbox.paypal.com/

> Blocked a frame with origin "https://domain.dev" from accessing a frame with origin "https://www.sandbox.paypal.com". Protocols, domains, and ports must match.

When I visit the URL - yes I am getting to PayPal 😃 

I dont know how I can give you further Information, because the "Blocked a...." is the only message I get when I click on the button.

I found a "Paypal Debug Id" for the button frame that will be included.

Paypal-Debug-Id	1897a5ec7b89b, 1897a5ec7b89b

Hopefully I could help you!

**Comment by bluepnume** [comment]
Hi @jonnyxe --

> Clicking the button should open the frame containing https://www.sandbox.paypal.com/

`https://www.sandbox.paypal.com/` is the domain, but what's the full url which is failing to load? Is it `https://www.sandbox.paypal.com/webapps/hermes/button`

> When I visit the URL - yes I am getting to PayPal

When you visit `https://www.sandbox.paypal.com/webapps/hermes/button` in a new tab what specifically do you see? Is it the button, or something else?

**Comment by jonnyxe** [comment]
OK, well I think I got the error. I set the button to "display: none" and performed the click by jQuery. The error came from jQuery directly. After I set the display  to visible and clicked the button directly.

I really did not expect that.

**Comment by bluepnume** [comment]
Ah right. Yeah, that's not going to work -- we don't support programmatically clicking on the button. The button is in an iframe on a different domain to the parent page, and on top of that we need an actual click from the user, otherwise the popup window gets blocked by most browsers' popup blockers.
