### ISSUE TITLE
Business name shows on expanding incontext window

### ISSUE THREAD

**Issue by shoaibmir** [paypal/paypal-checkout#465]
On expanding incontext window, business name for the seller shows up:

![screen shot 2017-09-18 at 4 24 16 pm](https://user-images.githubusercontent.com/1455536/30533831-f6dc3264-9c8d-11e7-874f-857f662bf3f1.png)

Default behaviour is that, if logo is not setup during checkout then business name will show up. checkout.js does not give an option to pass a logo which means seller can not setup a logo and every time consumer expands the incontext window, we will have business name on checkout page.

This is reproducible on https://developer.paypal.com/demo/checkout/#/pattern/client

Thanks,
Shoaib

**Comment by bluepnume** [comment]
> checkout.js does not give an option to pass a logo

It's still totally possible to pass a merchant logo in the api call -- checkoutjs doesn't prohibit this. The logo is just not shown for the default window size.
