### ISSUE TITLE
TAXID and INSTALLMENTS return on JSV4 Client version pairity

### ISSUE THREAD

**Issue by aalonso-ariel** [paypal/paypal-checkout#467]
### Description

Please provide a short description of the issue here, along with:

ECJSV4 basic client version does not return the tax_id for the buyer nor the installments plan selected by the user on the PayPal checkout.
Both returns are expected for BR and MX, as for the default which was build for REST GET PAYMENTS.

Sample for the REST GET PAYMENTS below:

TAXID:
"payer_info": {
            "email": "alonso_user_br@paypal.com",
            "first_name": "Ariel",
            "last_name": "Alonso",
            "payer_id": "NT3Q3UK6P4VE8",
            "shipping_address": {
                "recipient_name": "Teste Name",
                "line1": "Araguaia  492  Apto 21",
                "line2": "Vila Curuça",
                "city": "Santo André",
                "state": "Sao Paulo",
                "postal_code": "09291230",
                "country_code": "BR",
                "normalization_status": "UNKNOWN"
            },
            "tax_id_type": "TAX_ID",
            "tax_id": "30949017787",
            "country_code": "BR"
        }

INSTALLMENTS:
"credit_financing_offered": {
        "term": 3,
        "monthly_payment": {
            "value": "17.33",
            "currency": "BRL"
        }
    }, 

### Steps to reproduce

Create a payment using ECJSV4 client version. Then call the GET function.

### Affected browsers

- ALL

**Comment by bluepnume** [comment]
FYI: `credit_financing_offered` is actually already added and should be going out with the next hermes release. I'll work on getting `tax_id_type` / `tax_id` added.

**Comment by bluepnume** [comment]
- The credit_financing object was added and released. Can you please validate if you do not see this or you see any specific issues with the response?
- The tax id and tax id type params were added, but haven't yet made it into a release. They should go out with the next Checkout release, and I'll let you know.

**Comment by bluepnume** [comment]
Both tax id and tax id type are live.

**Comment by aalonso-ariel** [comment]
Hello Daniel,

Just did a sandbox test and the result was not positive. Neither the actions.payment.get() function nor actions.payment.execute() returns the TAXID and TAXIDTYPE.

Can you check if this made to sandbox as well ?

**Comment by bluepnume** [comment]
Yep, sorry, miss on our side. Looks like this got pushed out for order api but not payments. I've made sure payments is staged for the next release.
