### ISSUE TITLE
ppxo_close_no_token_cancelurl error when closing the popup while loading

### ISSUE THREAD

**Issue by MaxDBN** [paypal/paypal-checkout#469]
### Description

When a user closes the Checkout popup while it's loading I get the warning ppxo_close_no_token_cancelurl 

- [x] Screenshots or videos that show the issue
![paypalbug](https://user-images.githubusercontent.com/16654524/30609332-cd8b2158-9d83-11e7-8d8b-9a74df7f0771.png)

- [x] Your code
```
    CREATE_PAYMENT_URL  = 'http://localhost:3000/paypal/create_payment';
    EXECUTE_PAYMENT_URL = 'http://localhost:3000/paypal/execute_payment';

    paypal.Button.render({
      locale: 'en_US',
      env: 'sandbox',

      payment: function() {
        return new paypal.Promise(function(resolve, reject) {
          $('.paypal-overlay').fadeIn();
          $.post(CREATE_PAYMENT_URL)
            .done(function(data) { resolve(data.paymentID); })
            .fail(function(err)  { $('.paypal-overlay').fadeOut(); });
        });
      },

      onAuthorize: function(data) {
          console.log('The payment was authorized!');
          console.log('Payment ID = ',   data.paymentID);
          console.log('PayerID = ', data.payerID);

          $.post(EXECUTE_PAYMENT_URL, { paymentID: data.paymentID, payerID: data.payerID })
            .done(function(data) {
              window.location = '/payments/summary'
            })
            .fail(function(err)  {
              window.location = '/payments/cancelled'
            });
      },

      onCancel: function(data) {
        window.location = '/payments/cancelled'
      }

    }, '#paypal-buynow');
```
- [x] The `paypal.version` from your browser console
4.0.130
- [x] All console logs during the time of the issue, especially error messages
https://pastebin.com/m6gttHna
- [x] Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
Yes

### Steps to reproduce

1. Click on Checkout
2. Close the Checkout popup before it finishes loading

### Affected browsers

- [x] Chrome
- [x] Firefox

**Comment by bluepnume** [comment]
Thanks for the report. This is definitely an issue -- ideally I'd like to call `onCancel` in these scenarios. There are a few internal reasons why this adds a little complexity to the checkout.js script, but I'll keep this open since I'd like to get this prioritized at some point.

**Comment by MaxDBN** [comment]
@bluepnume Thank you for the answer. Can you please tell me if I can somehow catch this error myself and handle it? Or I'd there's any alternative to integrate PayPal like checkout js? I wouldn't know if the user closed the pop-up and I'm afraid this issue will affect user experience

**Comment by bluepnume** [comment]
I'm afraid I don't have any short term solves at the moment. My advice for now, would be to give the buyer sufficient options on the page with the PayPal button, so they aren't blocked from doing whatever they want to do when they close the popup.

If it helps, looking at the logs on our side, the number of times this situation happens is pretty low.

**Comment by klibis** [comment]
@bluepnume Is there an ETA for resolution?

**Comment by ionSolutions** [comment]
@bluepnume i would also need a fix for this issue - is there any update on this?

**Comment by bluepnume** [comment]
This should be resolved now. Please clear your browser cache and let me know if you still see the issue. Thanks!
