### ISSUE TITLE
paypal-checkout-overlay disappear too early

### ISSUE THREAD

**Issue by MaxDBN** [paypal/paypal-checkout#470]
### Description

paypal-checkout-overlay disappear before before the post request on onAuthorize
it should disappear after there is a response from execute_payment_api

Is it possible that it's happening because the sandbox servers are slower? Sometimes it takes as long as 5 seconds to get a response (either create_payment or execute_payment)

- [x] Your code

```
    CREATE_PAYMENT_URL  = 'http://localhost:3000/paypal/create_payment';
    EXECUTE_PAYMENT_URL = 'http://localhost:3000/paypal/execute_payment';

    paypal.Button.render({
      locale: 'en_US',
      env: 'sandbox',

      payment: function() {
        return new paypal.Promise(function(resolve, reject) {
          $('.paypal-overlay').fadeIn();
          $.post(CREATE_PAYMENT_URL)
            .done(function(data) { resolve(data.paymentID); })
            .fail(function(err)  { $('.paypal-overlay').fadeOut(); });
        });
      },

      onAuthorize: function(data) {
          console.log('The payment was authorized!');
          console.log('Payment ID = ',   data.paymentID);
          console.log('PayerID = ', data.payerID);

          $.post(EXECUTE_PAYMENT_URL, { paymentID: data.paymentID, payerID: data.payerID })
            .done(function(data) {
              window.location = '/payments/summary'
            })
            .fail(function(err)  {
              window.location = '/payments/cancelled'
            });
      },

      onCancel: function(data) {
        window.location = '/payments/cancelled'
      }

    }, '#paypal-buynow');
```
- [x] The `paypal.version` from your browser console
4.0.130

- [x] Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?

Hard to say, the script stops because of the alarm

### Steps to reproduce

If you'd like to reproduce this issue I guess you should artificially make the response from execute_payment_api really slow and see that the overlay disappears before that.

### Affected browsers

- [x] Chrome
- [x] Firefox

**Comment by bluepnume** [comment]
You can actually return a promise in `onAuthorize`, and the overlay should only close after the promise resolves. Assuming `$.post` returns a promise, you should just be able to return that -- otherwise you can use the `paypal.request.post` utility instead.

**Comment by MaxDBN** [comment]
@bluepnume Ended up using `paypal.request.post` and it worked, thank you!

**Comment by bluepnume** [comment]
Awesome!
