### ISSUE TITLE
IE 11 - Unable to load in-context window

### ISSUE THREAD

**Issue by Chaithi** [paypal/paypal-checkout#474]
### Description

What happens is, after you get on the confirmation page, the Paypal window opens but it closes after a few seconds with no action from the shopper.

https://store.kaspersky.fr/order/checkout.php?PRODS=4711615&QTY=1&CART=1&CARD=1&SHORT_FORM=1&LANGUAGES=fr&LANG=fr&CURRENCY=EUR&DCURRENCY=EUR&ARN=0&OPTIONS4711615=2a,4pc

Console log:
SCRIPT5: Access is denied.

File: component-meta, Line: 1, Column: 1
SEC7118: XMLHttpRequest for https://ing-district.clicktale.net/ctn_v2/wr/?1405346876354903&35&10&12&0&8&264&subsid=119933&fSchBi+Eu1nfNQvbfFBEfNBBIfFBPfFBgfFBIfNBCPfNBCJfNBCIfNBCIfFBIfNBCIfNBB7/fNBBIfNlh8BJmJlh9BB3fyCXCPAlF8MQfyIJFUAfNBCHfFCIftDDRftCCHftCBIftCBIftCBIfFBIfoBIftCCJftKHqftCCGftDCHftHCJfoELftEBEftFBJfoDIftPBhfoCGfoDIfoDIlJ8KGfphMAfoC8JcfoDGfpFBKIUCHTHLKqJq&KlUAfpNBAfpLBHfoLGfpNBJfoNHCjABAQU&CN4HLKTCJ&LljAfoOAfpwBwfocBfoHGfpFBGfpJBSfpHBGfpCBIfpECIfoDIfpCBJfpCBIfoCJfpCBGlU8JXfJBFAfJJOhIRCHTH1KoJq&DlRAfJQRAfJGFjIQCHTHBCByJqtEBJKhgA&OlQAfJxdAfJgOElNvfJQIAlFZfRBhZAfJUBAkSeAG5SdvG5CdvUECdvG5A9DBoP_(%7B%22a%22%3A%5B%7B%22a%22%3A%7B%22s%22%3A%22l%3A1px%3Bt%3A136px%3B%22%7D%2C%22n%22%3A%22div157%22%7D%2C%7B%22a%22%3A%7B%22s%22%3A%22l%3A0px%3Bt%3A0px%3Bw%3A1903px%3Bh%3A1284px%3B%22%7D%2C%22n%22%3A%22div155%22%7D%5D%7D)&Dm9BzaCkEUAQKcUAACUAAA0BA&CL/D/CBoE+&9J8ylkBf2EBEiAlh8CSfWP0BYAfFB8T9fFBEfFBKfFCGfFBGfFBQmBCl&ACUEdvtEBAhBA&GllAfNBDAfFBNfFCIfFBGfFCGfFBJfFCGfFCIfFCIfFCIfFBIfFDIfFBIfFBLfFEIfFFbfFBEfFBNfFDEfFCLfFCFfFCJfFDGfFCJfFZ8E5fFBXfFBQfFB1fFB8DpfFBQfFBHeC8GMeKbeKOeHNeEQeGJeEQeDIeEKeDReENeGaeHUeHOeEN&1086553995 required Cross Origin Resource Sharing (CORS).
File: verify.php
ppxo_paypal_legacy_multiple_init_paypal_checkout {"timestamp":1505847286059,"windowID":"2ff05774a0","pageID":"2d54f37567","referer":"store.kaspersky.fr","host":"store.kaspersky.fr","path":"/order/verify.php","env":"production","country":"US","lang":"en","uid":"ce81c458cd","ver":"4.0.130"}
SEC7118: XMLHttpRequest for https://ing-district.clicktale.net/ctn_v2/wr/?1405346876354903&35&10&13&3&0&105&subsid=119933 required Cross Origin Resource Sharing (CORS).
File: verify.php
ppxo_unhandled_error {"stack":"Error: Function expected\n   at stringifyError (https://www.paypalobjects.com/api/checkout.js:3436:13)\n   at Anonymous function (https://www.paypalobjects.com/api/checkout.js:2853:17)\n   at Anonymous function (https://www.paypalobjects.com/api/checkout.js:8075:37)\n   at ZalgoPromise.prototype.dispatch (https://www.paypalobjects.com/api/checkout.js:8062:26)\n   at ZalgoPromise.prototype.then (https://www.paypalobjects.com/api/checkout.js:8105:17)\n   at _RECEIVE_MESSAGE_TYPE[] (https://www.paypalobjects.com/api/checkout.js:2835:13)\n   at receiveMessage (https://www.paypalobjects.com/api/checkout.js:2770:25)\n   at messageListener (https://www.paypalobjects.com/api/checkout.js:2791:13)","errtype":"[object Error]","timestamp":1505847356215,"windowID":"7548e6d64d","pageID":"c75691c8cb","referer":"www.paypal.com","host":"www.paypal.com","path":"/webapps/hermes/component-meta","env":"production","country":"US","lang":"en","uid":"559ab5a8f6","ver":"4.0.130"}
SCRIPT5002: Function expected
File: checkout.js, Line: 7967, Column: 21

paypal.version responds with "4.0.130"

An attempt was made at 8:29AM Central on 9/20/17. It generated EC Token EC-7UB27141KD736245U
ppxo_paypal_legacy_component_error {"error":"Error: Error: No ack for postMessage xcomponent_init in 1000ms","timestamp":1505914145143,"windowID":"dfee8c9334","pageID":"742ca30a37","referer":"store.kaspersky.fr","host":"store.kaspersky.fr","path":"/order/verify.php","env":"production","country":"US","lang":"en","uid":"262eabce1d","ver":"4.0.130"}
ppxo_paypal_legacy_render_error_hijack_revert_target {"timestamp":1505914145150,"windowID":"dfee8c9334","pageID":"742ca30a37","referer":"store.kaspersky.fr","host":"store.kaspersky.fr","path":"/order/verify.php","env":"production","country":"US","lang":"en","uid":"262eabce1d","ver":"4.0.130"}
### Steps to reproduce

What happens is, after you get on the confirmation page, the Paypal window opens but it closes after a few seconds with no action from the shopper.

Test link:
https://store.kaspersky.fr/order/checkout.php?PRODS=4711615&QTY=1&CART=1&CARD=1&SHORT_FORM=1&LANGUAGES=fr&LANG=fr&CURRENCY=EUR&DCURRENCY=EUR&ARN=0&OPTIONS4711615=2a,4pc

Steps to reproduce: 
•             Open link in IE 11 (windows 7 preferably)
•             Insert billing info
•             Choose paypal and click continue
•             Click on Paypal pay button

Result:
Paypal window closes few seconds after it appears.

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [X] IE (Reproduced in version 11.0.9600.18762)
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Thanks so much for providing all of these details.

One quick follow up question -- do they see the same issue when testing with IE11 on https://developer.paypal.com/demo/checkout/ ?

**Comment by Chaithi** [comment]
I do not experience the same issue at https://developer.paypal.com/demo/checkout/

**Comment by Chaithi** [comment]
Confirmed with the initial reporter the same. They do not experience the issue at developer.paypal.com, but do at the kapersky site.

**Comment by bluepnume** [comment]
Good to know, thanks. I'll keep trying to narrow this down.

**Comment by Chaithi** [comment]
An additional merchant is reporting similar issue:
https://origin1.tsc.ca

Seeing this in the console:
` No handler found for post message response for message: postrobot_ready from https://origin1.tsc.ca in https://www.paypal.com/webapps/hermes/button`


[6:00 PM] 
`File: checkout.js, Line: 2865, Column: 27`

**Comment by Chaithi** [comment]
Here is the code the tsc.ca uses to get the token:

       protected readonly postHeaders: Headers = new Headers({ 'Content-Type': 'application/x-www-form-urlencoded' });
       protected paypalSandboxBaseUrl = "https://api.sandbox.paypal.com";
      protected paypalLiveBaseUrl = "https://api.paypal.com";
       protected paypalBaseUrl = this.paypalLiveBaseUrl;
protected paymentUrl = this.paypalBaseUrl + "/v1/payments/payment";
/*
        Use postman to create authorization key using clientid and secretkey
        */
    protected createAccessToken(): Observable<any> {
        let postheader = this.postHeaders;

        if (this.paypalEnv == 'production') {
            /* TSC live paypal account */
            postheader.append("Authorization", "Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
        } else {
            /* Dev sandbox account */
            postheader.append("Authorization", "Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
        }

        let body = /*'userName=' + this.clientId + '&password=' + this.secretKey + */ 'grant_type=client_credentials';
        let url = this.paypalBaseUrl + this.accessTokenUrl;
        return this.http
            .post(url, body, { headers: postheader });
    }

**Comment by bluepnume** [comment]
@Chaithi thanks so much for all of the details to help repro this one! It was difficult to track down, but I've made a series of fixes and I'm not able to repro any of these issues any more. Can you please clear your browser cache, make sure `console.log(paypal.version)` gives you `4.0.152`, and let me know if you still see any issues in IE11? Thanks again!
