### ISSUE TITLE
Implement actions.payment.update in onAuthorize callback

### ISSUE THREAD

**Issue by trainerbill** [paypal/paypal-checkout#476]
### Description
We should implement the payment update api and provide a function on actions.payment in order to help facilitate cart integrations.  Merchants will need to calculate shipping/tax information after using actions.payment.get() to receive the shipping information.  Currently the only way to make the update to the payment would be to expose a web service to do the REST payment update and use the paypal.request to hit the service.  This is quite a bit extra work and will be needed for most merchants.

**Comment by trainerbill** [comment]
I always for get you can pass that to execute... though I think providing an update function makes sense and would reduce questions.

**Comment by mcntsh** [comment]
Hey @trainerbill, I know this is a really old issue. This use-case is going to be covered by the Callback API feature which should be released soon :)
