### ISSUE TITLE
Support React v16.0

### ISSUE THREAD

**Issue by hossein-** [paypal/paypal-checkout#482]
Hi, apparently createClass removed in React v16.0 and therefor we can't use this package in react 16, any plans to remove createClass and extend React.Component ? sorry about my English.

**Comment by bluepnume** [comment]
Yeah, this is a good callout. I'll try to get round to this asap.

**Comment by hossein-** [comment]
any update on this?

**Comment by MatteCarra** [comment]
+1

**Comment by wildlingjill** [comment]
I just submitted a PR for this issue: https://github.com/krakenjs/xcomponent/pull/122

**Comment by bluepnume** [comment]
This is now released.
