### ISSUE TITLE
"Not you?" button closes paypal popup.

### ISSUE THREAD

**Issue by alt-123** [paypal/paypal-checkout#485]
### Description

I am developing a cordova application (both on android & ios). I'm rendering paypal button in popup. when i'm clicking "not you?" link, paypal popup closes and user doesn't logout. 

Issue is reproducing on android & ios with sandbox env & production env.

Connect checkout in app.html in head section:
`<script src="https://www.paypalobjects.com/api/checkout.js" data-version-4 data-log-level="info"></script>`

Render checkout button:
<pre><code>paypal.Button.render({
	env   : 'sandbox',
	client: {
		sandbox:    paypalConfig.sandbox,
		production: paypalConfig.production
	},
	commit: true,
	payment: function(data, actions) {
		return paypal.request({
			method: 'post',
			url   : CREATE_PAYMENT_URL
		}).then(function(data) {
			return data.id;
		});
	},
	onAuthorize: function(paymentData, actions) {
		var data = {}
		data.paymentID = paymentData.paymentID;
		data.payerID   = paymentData.payerID;
		return paypal.request.post(EXECUTE_PAYMENT_URL, data).then(function(res) {
			alert('PAYPAL_SUCCESS');
		}).catch(function(e) {
			alert('PAYPAL_REJECT');
		});
	}
}, '#buyPaypal');</code></pre>

Console errors:
<pre><code>types.js:19 Uncaught Error: No handler found for post message ack for message: xcomponent_delegate_ppcheckout from file:// in https://www.sandbox.paypal.com/checkoutnow</code></pre>
<pre><code>types.js:101 Uncaught Error: No handler found for post message response for message: xcomponent_delegate_ppcheckout from file:// in https://www.sandbox.paypal.com/checkoutnow</code></pre>
<pre><code>exceptions.js:14 Uncaught TypeError: Cannot read property 'auth' of undefined</code></pre>

paypal.version from console: 4.0.131

When i'm starting my project in browser, logout button works fine. All payments with any env or browser work fine

Full console Log from the moment of paypal button rendering until user clicks "not you?" is available here: [log.txt](https://github.com/paypal/paypal-checkout/files/1352577/log.txt)
Issue occures consistently.

### Steps to reproduce

1. Click Paypal Button
2. Log in
3. Close paypal popup
4. Open it again
5. Click "Not you?" link

### Affected browsers
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [X] Web View / Safari ViewController
- [ ] Other

Screenshot of my console:
![_](https://user-images.githubusercontent.com/14822306/31129748-266168a2-a85e-11e7-8a74-313e51674f5f.png)

**Comment by bluepnume** [comment]
Thanks for the report! I'll take a look

**Comment by bluepnume** [comment]
This is fixed and ready to go out in the next release.

**Comment by bluepnume** [comment]
Pushed. Please let me know if you still see this issue.
