### ISSUE TITLE
Legacy startFlow hangs on iPhone

### ISSUE THREAD

**Issue by grydstedt** [paypal/paypal-checkout#486]
### Description
Legacy startFlow hangs on Safari/Chromeon iOS device (iPhone)

Please provide a short description of the issue here, along with:
Using initXO and then startFlow works in most contexts, but on iOS/iPhone and Safari, it hangs and never redirects anywhere. Weird thing is with Sandbox turned on, it seems to work, but once in production it fails and hangs.

- Screenshots or videos that show the issue
- Your code
- The `paypal.version` from your browser console
4.0.131
- A link to your page with the issue, if possible
- All console logs during the time of the issue, especially error messages
- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
- Does the issue occur consistently, or intermittently?

### Steps to reproduce

Please provide each individual step required to reproduce the issue

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [X] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Can you share your full integration code please? And do you have a link to the page with the issue?

**Comment by grydstedt** [comment]
This was a user error, sorry about that. But while I have you here. I'd like to upgrade to the new flow. Is there a way to use a custom button and activate the popup/lightbox from a click event on one of my own buttons?

**Comment by bluepnume** [comment]
Unfortunately not -- some rationales here: https://medium.com/@bluepnume/less-is-more-reducing-thousands-of-paypal-buttons-into-a-single-iframe-using-xcomponent-d902d71d8875
