### ISSUE TITLE
404 on paypalobjects.com/api/checkout.4.0.133.js

### ISSUE THREAD

**Issue by tzusman** [paypal/paypal-checkout#488]
Locally, I'm able to successfully run a Capybara & Rspec test suite which goes through the flow of using paypal-checkout with Braintree processing the transaction.  However, on CircleCI, when I run the same suite, I get the following:

`https://www.paypalobjects.com/api/checkout.4.0.133.js - Failed to load resource: the server responded with a status of 404`

This occurs on every capybara spec which goes through the paypal checkout flow. And happens when trying to find the `.paypal-button-content` element:

```
within_frame find('.paypal-button iframe') do
  find('.paypal-button-content').click
end
```

Since the iframe is found, something is loading from paypal, but between turning the container into an iframe and finding the button, it fails to load `checkout.4.0.133.js`.

The test suite is being run on a headless version of chrome. Ruby `2.3.5` is running the backend, and Node `6.6.0` is running webpack `2.1.0-beta.27` to build the frontend.

Both locally and on CircleCI, I'm using the Braintree & PayPal sandbox.

I'm using npm packages `braintree-web` version `3.22.2`, and `paypal-checkout` version `4.0.125`.

Happy to provide more details, but I'm not quite sure which details would be helpful since so much of the login is inside those two packages.

**Comment by bluepnume** [comment]
Hi @tzusman, thanks for the heads up. Looks like there was a deploy issue with https://www.paypalobjects.com/api/checkout.4.0.133.js, I kicked off another and the file should be up now.
