### ISSUE TITLE
onAuthorize callback is not firing

### ISSUE THREAD

**Issue by harshdoshi999** [paypal/paypal-checkout#490]
I am using following script 
<script src="https://www.paypalobjects.com/api/checkout.js" data-version-4></script>

And after the process done using Paypal Dialog Box, it doesn't call onAuthorize. 

It does not even work in the demo you have on this library -- https://developer.paypal.com/demo/checkout/#/pattern/client

**Comment by bluepnume** [comment]
Hi @harshdoshi999 -- can you please re-open an issue with all of the requested details. Please do not delete the issue template.
