### ISSUE TITLE
Venmo and Credit buttons should land in correct experience

### ISSUE THREAD

**Issue by bluepnume** [paypal/paypal-checkout#493]
- Venmo button should redirect directly to Venmo app (or app store)
- Credit button should trigger credit experience, without needing to pass `external_selected_funding_instrument_type` in `payment()`

**Comment by bluepnume** [comment]
@vishakha94 / @khanghoang -- could you guys figure out how to split this one between you?

**Comment by bluepnume** [comment]
Clue to help with this -- when those buttons are pressed, you'll get:

- `req.query.fundingSource === 'venmo'` or `req.query.fundingSource === 'credit'` on the server-side
- `window.xprops.fundingSource === 'venmo'` or `window.xprops.fundingSource === 'credit'` on the client-side

**Comment by bluepnume** [comment]
@khanghoang -- just had a thought on this -- did you add any logic to `xo-landing-router` to make sure `fundingSource=credit` goes to Hermes? Otherwise I'm worried that the transaction could go straight to xoonboarding and skip the client-side checks you added.

**Comment by khanghoang** [comment]
@bluepnume no, I didn't make any change `xo-landing-router`. But I tested and it worked well. However, I think we need to talk about it on Monday.
