### ISSUE TITLE
get done of actions.payment.execute()

### ISSUE THREAD

**Issue by ThakkarKhushbu** [paypal/paypal-checkout#498]
### Description
I have integrate paypal checkout in my angular 4 project , paypal checkout works fine but I want to make one api call after successful execution of actions.payment.execute() ,

but in return actions.payment.execute() not allow me to assess any outside object of scope , 

How can i get confirmation of successful execution of actions.payment.execute() ?

### Steps to reproduce

Please provide each individual step required to reproduce the issue

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
I'm confused about what exactly you're asking. Are you asking how to know when `actions.payment.execute()` is complete?

If so you can do:

```
return actions.payment.exectute().then(function() {
   // something
});
```

**Comment by ThakkarKhushbu** [comment]
Thanks for your quick response , actually i want to make one API call after successful payment execute . 

this is my code:

  return actions.payment.execute().then(function () {
                                debugger
                                this.authService.UpadateBrokerLeadStatus(property, status).subscribe((result) => {
                                    if (property.LeadInfo.ReferredUserId != null) {
                                        var commissiondata = {
                                            UserId: property.LeadInfo.ReferredUserId,
                                            LeadId: property.LeadInfo.ID,
                                            Amount: 35,
                                            Type: 1,
                                            Remark: "Payment for acquired lead",
                                            PaymentStatus: 1,
                                            CreditedOn: new Date(),
                                            CreditedBy: this.currentuser.ID
                                        }
                                        this.authService.CreditUserPaymentInfo(commissiondata).then((result) => {

                                        }).catch((err) => {
                                        });
                                    }
                                }, (err) => {

                                    this.authService.HideLoader();
                                    this.authService.LogException(JSON.stringify(err))
                                    console.log(err);
                                });

                                window.alert("payment Done Successfully");
                            });

but the problem is my code inside 
return actions.payment.exectute().then(function() {
   // something
});
is not executing , it is not allow me use outside object , I cant even use outside variable .

can you give me any workaround this ? I want an API call on success of Payment .


Thanks in Advance
khushbu

**Comment by bluepnume** [comment]
That's strange. So it never reaches your `debugger` statement?

Can you try running the following and seeing if there's any error:

```
return actions.payment.exectute().then(function() {
   // something
}).catch(function(err) {
    console.error('execute error:', err);
});
```

Can you also check your network tab for the `/execute` call, and make sure it comes back with a 200 response?

**Comment by ThakkarKhushbu** [comment]
It reaches , If I only do alert then it shows alert but it does not execute below code

  this.authService.UpadateBrokerLeadStatus(property, status).subscribe((result) => {
                                if (property.LeadInfo.ReferredUserId != null) {
                                    var commissiondata = {
                                        UserId: property.LeadInfo.ReferredUserId,
                                        LeadId: property.LeadInfo.ID,
                                        Amount: 35,
                                        Type: 1,
                                        Remark: "Payment for acquired lead",
                                        PaymentStatus: 1,
                                        CreditedOn: new Date(),
                                        CreditedBy: this.currentuser.ID
                                    }
                                    this.authService.CreditUserPaymentInfo(commissiondata).then((result) => {

                                    }).catch((err) => {
                                    });
                                }
                            }, (err) => {

                                this.authService.HideLoader();
                                this.authService.LogException(JSON.stringify(err))
                                console.log(err);
                            });

and if i declare any variable outside and try to access inside this method , I am not able to

**Comment by bluepnume** [comment]
I see you're trying to reference `this` (e.g. `this.authService`). If you want that to work, you're going to need to either use `var self = this` in the parent, then reference `self.authService`, or you'll need to use an arrow function, like:

```javascript
return actions.payment.exectute().then(() => {
   // something
});
```

Otherwise you lose the value of `this` in the callback for `execute()`

**Comment by ThakkarKhushbu** [comment]
I have tried with return actions.payment.exectute().then(() => {
});
It is not executing this method also .


![image](https://user-images.githubusercontent.com/30835218/31532750-c59f7d7c-b00c-11e7-95ee-78d8770eba86.png)

**Comment by bluepnume** [comment]
OK. It's difficult to say without seeing the entirety of your code -- do you have this live somewhere I could try? In the meantime, closing this issue since `checkout.js` doesn't handle `this` any differently to any other library when dealing with callbacks.

**Comment by madhurirahane** [comment]
**Description :** I am facing with the similar problem,Calling the payment execute function inside onAuthorize

 onAuthorize: function(data, actions,payment_for) {
        var paymentID = data.paymentID;
        var payerID   = data.payerID;
        var execute_payment_json = {
          payer_id: payerID,
        };
        return actions.payment.execute(paymentID, execute_payment_json).then((response) => {
      	  console.log("response");
        }); 
      console.log(this.dumpPaypalResponse);
    },  

but,after successful execution of return actions.payment.execute(paymentID, execute_payment_json).then((response) => {});
 I am not able to access response outside of that.
