### ISSUE TITLE
popup doesn't open on Mac OSX webview

### ISSUE THREAD

**Issue by maxisam** [paypal/paypal-checkout#499]
### Description

Please provide a short description of the issue here, along with:

- The `paypal.version` from your browser console

^4.0.133

### Steps to reproduce

We have a unique situation to use PayPal on a Webview of Mac OSX. However, the popup doesn't open.

The same page works on ISO Webview.

Any thought?

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [X] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Can you share the user-agent for the webview?

**Comment by maxisam** [comment]
The Useragent format is like 

`ApplePhotosExtension v{APP_VERSION} MacOS {OS_VERSION}`

**Comment by abezydar** [comment]
Here's a user agent for a WKWebView in Mac OS X

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/604.3.4 (KHTML, like Gecko)  
`

I noticed in src/lib/device.js it's not doing a test for Macintosh in isWebView()

```
export function isWebView() : boolean {
    let userAgent = getUserAgent();
    return (/(iPhone|iPod|iPad).*AppleWebKit(?!.*Safari)/i).test(userAgent) ||
        (/\bwv\b/).test(userAgent) ||
    (/Android.*Version\/(\d)\.(\d)/i).test(userAgent);
}
```

**Comment by bluepnume** [comment]
Thanks! Added detection for webviews on `Macintosh` for the next release.

**Comment by bluepnume** [comment]
This has now been released. @maxisam / @abezydar can you let me know if you still see any issues here?

**Comment by maxisam** [comment]
@bluepnume sure, I'll let you know probably next week. Thx!

**Comment by maxisam** [comment]
It works. Thanks!

**Comment by bluepnume** [comment]
Awesome, thanks for verifying!
