### ISSUE TITLE
Guest payments

### ISSUE THREAD

**Issue by verysimplenick** [paypal/paypal-checkout#500]
Hi. I found some strange issue with guest payments.
### Description
I try use guest payments for my site and found, that in FF I can pay as guest, but in same page in chrome-based browser can't do this.

![difference](https://user-images.githubusercontent.com/922660/31537694-b6dec992-b00b-11e7-8310-bc94b23b2080.png)

- Server-side rest integrations
- `paypal.version` "4.0.131"
- FF - 56.0 (x64)
- Chromium - 64.0.3240.0

my web experience profile:

```json
[
  {
    "id": "XP-T3FE-52A5-G85Y-NUAW",
    "name": "_",
    "temporary": false,
    "flow_config": {
      "landing_page_type": "Billing",
      "user_action": "commit"
    },
    "input_fields": {
      "allow_note": false,
      "no_shipping": 1,
      "address_override": 0
    },
    "presentation": {
      "brand_name": "Akweet",
      "locale_code": "US"
    }
  }
]
``` 

### Steps to reproduce

Open in different browsers

### Affected browsers

- [x ] Chrome
- [ ] Safari
- [ x] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by verysimplenick** [comment]
If I set ` locale: 'en_US',`  pages are same.

**Comment by bluepnume** [comment]
Thanks for the report. We can track this over here: https://github.com/paypal/paypal-checkout/issues/510 -- I've added @bluelnkd to comment on the decisioning logic for the guest flow.
