### ISSUE TITLE
Unstable GET link

### ISSUE THREAD

**Issue by PKMTracker** [paypal/paypal-checkout#502]
### Description

Please provide a short description of the issue here, along with:

The following GET is intermittently working and causes errors on website load:
https://www.paypal.com/webapps/hermes/api/button/funding?country=US

### Steps to reproduce

Hit the link, 50/50 if it loads or errors.

### Affected browsers

Any GETters.

**Comment by bluepnume** [comment]
Thanks for the report. We've been having some deploy issues lately, and chances are you landed on a box as it was deploying, and before that api was available. This issue should be totally resolved by now, but please let me know if you still see the problem.

Many thanks as always for promptly reporting issues like this!
