### ISSUE TITLE
Unable to recover focus on popup window in Firefox

### ISSUE THREAD

**Issue by hlynursmari1** [paypal/paypal-checkout#503]
### Description

When initiating the checkout process in Firefox, if you click back on the main window after the popup has appeared you cannot recover focus on the popup window by clicking the 'Continue' link.

This is due to a Firefox specific setting, `dom.disable_window_flip`, which blocks scripts from changing the z-order of windows. This setting is turned on by default.

More details:
- reproducible using the PayPal Checkout demo code [here](https://developer.paypal.com/demo/checkout/#/pattern/client), see steps below
- `paypal.version` at time of testing is `4.0.131`
- tested on version 56.0 of Firefox, but should affect all releases since version 23.0 (this is the version in which the setting was introduced, could affect older versions too)

I suggest a few workarounds which need your input:
1. Add a setting to `paypal.Button.render` to specify whether the PayPal Checkout should be opened as a new window or as a new tab (can this distinction be made?). It's far more difficult to click away from a full tab than a popup window. The implementer could check the browser in use and only use new tabs for Firefox.
2. Have checkout.js make this decision for the implementer by only opening new tabs in Firefox (again, dependent on being able to actually specify new window vs new tab).
3. Change the 'Continue' link on the main window overlay to a 'Retry' link and have checkout.js reinitialise the payment flow when it is pressed. This feels a bit heavy-handed, but I think it is better for that button to do something rather than nothing at all.

### Steps to reproduce

- go to the PayPal Checkout demo [here](https://developer.paypal.com/demo/checkout/#/pattern/client)
- click the PayPal Checkout button to initiate the payment process
- once the popup appears, click back on the main window
- try to use the 'Continue' button to bring the popup back into focus

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [x] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Thanks for the report! I'll consider your suggestions -- thanks for detailing those out!

I have a potential workaround for this that I'd like to try -- calling `window.open()` with the existing window name sometimes has the effect of re-focusing the window. The only problem is this changes the `window.opener` in the child which may cause some issues here. So 
I want to make sure that doesn't have any side-effects.

I'll keep you posted.

**Comment by ballawzi-pp** [comment]
The issue #514 is partially duplicated. It only occurs on mobile web with Safari. The continue link doesn't work. But you are still able to click the `x` on the right top corner. The fix for #514 might be different. 
Safari web on desktop works fine.

**Comment by bluepnume** [comment]
@hlynursmari1 this issue should at least be fixed in firefox now. Can you clear your cache and try again?

Unfortunately the same fix didn't seem to work for safari on ios. I'll keep thinking about how to resolve it, but this may not be a fixable issue if that browser doesn't respond to calls to .focus().

**Comment by hlynursmari1** [comment]
This issue is resolved on Firefox now. Tested both in the checkout demo and my own implementation.

Thanks for the fix @bluepnume !

**Comment by bluepnume** [comment]
Going to close this issue as there doesn't appear to be a clean fix in iOS. Open to suggestions if anyone has any. For now I'm going to add a message for the user to manually switch tab -- not ideal, but the best I have right now.
