### ISSUE TITLE
Ensure that even when `actions.payment.execute` errors out, the promise is only rejected when the payment is not successfully executed

### ISSUE THREAD

**Issue by bluepnume** [paypal/paypal-checkout#505]

**Comment by PKMTracker** [comment]
Just to note, there may be several other cases that happen. I get roughly 1/20 transactions that get processed on paypal side, but do not properly return onAuthorize for. I havn't been able to track down how to replicate it, but it does not appear to be related to a specific browser/environment.

Thanks again for the prompt fix on the related issue.

**Comment by bluepnume** [comment]
That's interesting. At least in those cases, if `onAuthorize` is never called then `execute` should also never be called, and the payment should never be executed.

If you come across any way to consistently track it down, please let me know. In the mean time I'll add some additional logging to determine how many of these calls are missing.

**Comment by bluepnume** [comment]
Added some additional safety around this.
