### ISSUE TITLE
color: 'creditblue' no longer supported

### ISSUE THREAD

**Issue by edbird-pp** [paypal/paypal-checkout#506]
### Description

Including `color: 'creditblue'` in the `style` parameter is now causing the following error when you click the button: `exceptions.js:14 Uncaught Error: Unexpected color for credit button: credit`

```
 // Specify the style of the button

        style: {
            label: 'credit',
            size:  'small', // small | medium | large | responsive
            shape: 'rect',  // pill | rect
            color: 'creditblue'
        },
```

`paypal.version = "4.0.131"`
Chrome Version 61.0.3163.100

Full error logs:
```
Uncaught Error: Unexpected color for credit button: credit
    at Object.validateButtonStyle [as validate] (validate.js:72)
    at validateProp (validate.js:51)
    at validateProps (validate.js:101)
    at ParentComponent.setProps (index.js:382)
    at new ParentComponent (index.js:49)
    at Component.render (index.js:398)
    at Function.ZalgoPromise.try (promise.js:373)
    at Component.descriptor.value [as render] (decorators.js:25)
    at callOriginal (checkout.js:21514)
    at hacks.js:52
```

### Steps to reproduce

The issue occurs 100% on https://developer.paypal.com/demo/checkout/#/pattern/credit by adding in the `color: 'creditblue'` style to the `style` parameter.

### Affected browsers

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by MaxTwentythree** [comment]
I have the same issue for label: 'generic' (in Chrome, FF, Safari)!
First it's no longer possible to style the button as we want, and then the few options left are taken away too, without any notification or warning?

**Comment by bluepnume** [comment]
@MaxTwentythree -- can you please confirm

- The `console.log(paypal.version)` you see in your browser console
- The specific error you see
- Whether you still see the issue after clearing cache

Thank you so much.

**Comment by MaxTwentythree** [comment]
Hi bluepnume,

thanks for your quick response!
So I guess this is a bug and the generic label should still work?

The console output for paypal.version is **4.0.136**

The error I get: 
```
Uncaught Error: Invalid button label: generic
    at validateButtonStyle (validate.js:35)
    at Object.validate (component.jsx:588)
    at validateProp (validate.js:52)
    at validateProps (validate.js:113)
    at ParentComponent.setProps (index.js:426)
    at new ParentComponent (index.js:91)
    at Component.init (index.js:410)
    at Object.componentDidMount (react.js:52)
    at Object.chainedFunction [as componentDidMount] (modules.js?hash=487f884ae98a68b8cca795981b456a1d3ee2307b:22555)
    at modules.js?hash=487f884ae98a68b8cca795981b456a1d3ee2307b:11846
```

Unfortunatelly clearing the cache doesn't solve the issue.

**Comment by bluepnume** [comment]
Yes, this is a bug - I'm trying to narrow it down bit right now I'm not able to reproduce.

For now as a quick fix can you try using label: 'paypal' and let me know if that works? Thanks!

**Comment by MaxTwentythree** [comment]
The other labels ('pay', 'checkout', 'buynow') seem to work.
When I tried the label 'credit' I got the same error as edbird-pp (I'm also using color blue):
> Unexpected  color for credit button: blue

As this issue seems to be a matter of color/label combination I tested all possible ones:

**Working:**
pay (all colors)
checkout (all colors)
buynow (all colors)
credit+black

**Not working:**
generic (all colors)
credit+blue, credit+silver, credit+gold

**Comment by bluepnume** [comment]
Does label: 'paypal' work for you?

**Comment by MaxTwentythree** [comment]
Yes, label 'paypal' did work, too :)

**Comment by bluepnume** [comment]
@MaxTwentythree just had a thought. How are you rendering the button? Is it with `paypal.Button.render()` or with one of the framework driver?

**Comment by MaxTwentythree** [comment]
I use the React driver:
`PayPalButton = paypal.Button.driver('react', {React, ReactDOM});`

**Comment by bluepnume** [comment]
OK that explains it perfectly :) rolling out a fix shortly. Thanks for all the details!

**Comment by MaxTwentythree** [comment]
Thank you! :)

**Comment by bluepnume** [comment]
This issue should now be resolved. Please make sure to do a cache clean, and let me know if you still see the problem.

Thanks again for your time helping triage this @edbird-pp and @MaxTwentythree! As always, really appreciate the reports the moment you see something acting up.
