### ISSUE TITLE
Overlay Paypal login close automaticaly in Intel XDK Cordoba/PhoneGap

### ISSUE THREAD

**Issue by SistemasAvanzadosIntegrales** [paypal/paypal-checkout#507]
Hello, I am currently using the Intel XDK tool to develop an ordering app, and to a final step to finish, I am trying to integrate Paypal payments but still without success, I already tried the cordoba / phonegap plugin and it did not work.

Now that I am trying to use the payment button integration on a pop up it appears.

Testing in the paypal emulator, with sandbox account and in the web version everything works correctly, but when emulating the application in Intel XDK the following error appears.

VM456 checkout.js: 5690 Uncaught Error: Unable to delegate rendering. Possibly the component is not loaded in the target window.

Error: No ack for postMessage xcomponent_delegate_ppcheckout in 1000ms
    at cycle (VM456 checkout.js: 3624)
    at cycle (VM456 checkout.js: 3624)
    at VM456 checkout.js: 5690
    at VM456 checkout.js: 8134
    at ZalgoPromise.dispatch (VM456 checkout.js: 8148)
    at ZalgoPromise.reject (VM456 checkout.js: 8108)
    at VM456 checkout.js: 8130
    at ZalgoPromise.dispatch (VM456 checkout.js: 8148)
    at ZalgoPromise.reject (VM456 checkout.js: 8108)
    at VM456 checkout.js: 8146
    at VM456 checkout.js: 8134
    at ZalgoPromise.dispatch (VM456 checkout.js: 8148)

The paypal login window opens and closes.

Doing the same test but already in an android compile, the paypal window still does the same.

I am not using any extra files, only the checkout.js api

https://www.paypalobjects.com/api/checkout.js

Then attach the entire sheet.

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
            /* following two viewport lines are equivalent to the meta viewport statement above, needed for Windows */
            /* see http://www.quirksmode.org/blog/archives/2014/05/html5_dev_conf.html and http://dev.w3.org/csswg/css-device-adapt/ */
            @-ms-viewport { width: 100vw ; zoom: 100% ; }  @viewport { width: 100vw ; zoom: 100% ; }
            @-ms-viewport { user-zoom: fixed ; }           @viewport { user-zoom: fixed ; }
        </style>
        
        
        <link rel="stylesheet" href="css/bootstrap.css" />
        <link rel="stylesheet" href="css/main.css" />
        <link rel="stylesheet" href="css/font-awesome.css" />
        <link rel="stylesheet" href="css/menu.css" />
        <link rel="stylesheet" href="css/main-ordena.css" />
        <link rel="stylesheet" href="css/modal.css" />
        
        <script src="https://www.paypalobjects.com/api/checkout.js"></script>
    </head>
    
    <body onclick="afuera();">
        
        <div class="col-12 float-left modal-background hidden"></div>
        
        
        <header id="menu"></header>
        
         
        <section class="col-12 no-padding" id="header">
            <div class="col-5 no-pl logo float-left">
                <img src="img/imgLogo.png" />
            </div>
            <div class="col-7 text-center mt-2 float-left no-padding">
                <h1>ORDENA</h1>
            </div>
        </section>
        
        
        <section id="nav-indicador" class="col-12 float-left"> 
            <a href="ordenaFormaPago.html" class="pull-left"><i class="fa fa-arrow-circle-left"></i></a>
            <span>Paso 3 de 3 "Confirmación"</span>
            
        </section>
        
        <section class="main-wrapper col-12 float-left no-pt no-mt" id="entrega">
            <h2 class="text-md text-color-default text-center text-bold margin-v-sm">Resumen de tu pedido</h2>
            
            
            <table class="table table-striped table-hover table-condensed text-center">
                <tbody id="tablaEstadoCuenta">
                    <tr class="headers">
                        <th>No.</th>
                        <th>Articulo</th>
                        <th>Precio</th>
                        <th></th>
                    </tr>
                </tbody>
            </table>
            
            <h2 id="average" class="text-md text-center text-bold margin-v-md"></h2>
            
            <p class="margin-v-sm-top">Tu pedido será entregado en:</p>
            <a id="deliver" href="ordenaEntrega.html"></a>

            
            
            <form class="margin-v-md-top">
                <label for="">Comentarios:</label>
                <textarea id="comentarios" name="comentarios" placeholder="Comentarios e indicaciones adicionales" class="form-control" rows="10" cols="10"></textarea>
                
                <h2 class="text-nm  text-center text-bold margin-v-md-top">¿Tienes un código de promoción?</h2>
                <div class="margin-v-sm">
                    <input class="form-control" type="text" id="promocion" name="promocion" placeholder="Ingresa aquí el código">
                </div>
                
                <section class="col-8 offset-2 no-padding text-center mt-5 mb-3">
                    <a href="#" onclick="modal();" class="btn btn-primary btn-fill btn-block mt-2">
                        REALIZAR PAGO
                    </a>
                </section>
            </form>
            
            <div id="fade" class="overlay" onclick="document.getElementById('light').style.display='none'; document.getElementById('fade').style.display='none'; document.getElementById('light2').style.display='none'; document.getElementById('light3').style.display='none'"></div>
            

             
            <div id="light" class="modalOrdena text-center">
                <h2 class="text-md text-color-default text-center text-bold margin-v-sm">¡Confirmación del pedido!</h2>

                <p class="mt-4">Se hara el cargo a tu cuenta de Paypal por <br>
                <b id="average-modal"></b>
                <br>

                <p class="margin-v-md text-center"><b>¿Deseas Continuar?</b></p>

                
                <section class="col-8 offset-2 float-left mb-3 no-padding">
                    <div id="paypal-button"></div>
                </section>
                <section class="col-8 offset-2 float-left mb-3 no-padding">
                    <a href="#" onclick="cerrar_modal();" class="btn btn-primary btn-fill btn-block">
                        CANCELAR
                    </a>
                </section>
            </div>
            
            
             
            <div id="light3" class="modalOrdena text-center">
                <h2 class="text-md text-color-default text-center text-bold margin-v-sm">¿Seguro que quieres eliminar el articulo?</h2>

                
                <section class="col-12 float-left mb-3 no-padding">
                    <div class="col-6 float-left no-pl">
                        <a id="deleteRow" href="#" class="btn btn-primary btn-fill btn-block">
                            SI
                        </a>
                    </div>
                    <div class="col-6 float-left no-pr">
                        <a href="#" onclick="cerrar_modal();" class="btn btn-primary btn-fill btn-block">
                            NO
                        </a>
                    </div>
                </section>
            </div>
            
        </section>

        
        <div class="nav-inf" id="menus">
            <a href="#">
                <span class="fa fa-bars"></span>
            </a>
        </div>
        
        
        <script type="text/javascript" src="js/jquery-1.9.1.min.js"></script>
        <script type="text/javascript" src="js/bootstrap.min.js"></script>
        <script type="text/javascript" src="js/prefixfree.min.js"></script>
        <script type="text/javascript" src="js/localstorage.js"></script> 
        <script type="text/javascript" src="js/comun.js"></script>
        <script type="text/javascript" src="js/menu.js"></script>
        
        <script type="text/javascript">
            function modal() {
                document.getElementById('light').style.display='block';
                document.getElementById('fade').style.display='block';
            }
            
            function cerrar_modal() {
                document.getElementById('light').style.display='none';
                document.getElementById('fade').style.display='none';
                document.getElementById('light3').style.display='none';
            }
            
            function modal3(id, consecutivo) {
                document.getElementById('light').style.display='none';
                document.getElementById('light3').style.display='block';
                document.getElementById('fade').style.display='block';
                   
                $( "#deleteRow" ).attr('onclick', 'deleteRow("'+id+'", "'+consecutivo+'")');
            }
            
            setShoppingSummary();
            
            paypal.Button.render({
				env: 'sandbox', // Or 'sandbox',
				
				locale: 'es_MX',
				
				style: {
					size:  'responsive',
					color: 'blue',
					shape: 'pill',
					label: 'generic'
				},
				
				client: {
					sandbox:    'AVjidpyq3AChF8N-XVSZWruvzR458hl_WwHrSUmtQf7ngpCHUWA17lNnUb89WCTdfXUYsKxCINhaiuj5',
					production: 'ASOuYaPFJfF02GiT8CsoPDsol_yO_rObixTr9jBcPBrtfFvvrLkO9EcBMPxiALfipoYFbmiNB_oaYlwh'
				},
				
				commit: true, // Show a 'Pay Now' button
				
				payment: function(data, actions) {
					return actions.payment.create({
						payment: {
							transactions: [{
								amount: { total: '1.00', currency: 'USD' }
							}]
						}
					});
				},
                
				//onAuthorize: function(data, actions) {
				onAuthorize: function(data) {
					return actions.payment.execute().then(function(payment) {
                        setPedido(); //Function insert data order
                        localStorage.setItem("paymentData", JSON.stringify(payment));   //Insert answer in localstorage
                        window.location = "ordenaCompletado.html";  //redirect
					});
				},
                
                onCancel: function(data) {
                    window.location = 'ordena.html';
                }
			}, '#paypal-button');
        </script>
        <script src="https://www.paypalobjects.com/api/checkout.js"></script>
    </body>
</html>

I hope I can help, or guide me on something concrete to use in intel xdk.

Best regards.

**Comment by bluepnume** [comment]
Hi -- we don't currently have any official support for Cordova in checkout.js. The current recommendation is to do a manual redirect to `paypal.com` and pass a `return_url` when setting up the payment. Does that work for your use-case? You can do something like:

```javascript
var env = 'production';

var client = {
    sandbox:    'AVjidpyq3AChF8N-XVSZWruvzR458hl_WwHrSUmtQf7ngpCHUWA17lNnUb89WCTdfXUYsKxCINhaiuj5',
    production: 'ASOuYaPFJfF02GiT8CsoPDsol_yO_rObixTr9jBcPBrtfFvvrLkO9EcBMPxiALfipoYFbmiNB_oaYlwh'
}

paypal.rest.payment.create(env, client, {
    payment: {
        transactions: [{
            amount: { total: '1.00', currency: 'USD' }
        }]
    }
}).then(function(token) {
    // redirect to 'https://www.paypal.com/checkoutnow?token=' + token;
});
```

**Comment by SistemasAvanzadosIntegrales** [comment]
Hello bluepnume thank you very much for the advice, it works perfect.

Greetings.
