### ISSUE TITLE
IE11 Express Checkout not working

### ISSUE THREAD

**Issue by frontegi** [paypal/paypal-checkout#509]
Hi, 
I was integrating checkout express on my new website.
Obviously i tested the integration against all browsers (Chrome,Edge,Firefox, Opera), and, at the end, the infamous IE11.
After 2 nights troubleshooting, dead end.
Then I tried the demo site, with same results:
https://developer.paypal.com/demo/checkout

IE Version is the latest on Windows 10 11.674.15063.0
![image](https://user-images.githubusercontent.com/10157050/31797148-2256db4e-b52d-11e7-8f69-7e06cbe82d00.png)
The problem appears immediately. The page background obscured, after a few seconds, turn back normal.
in Javascript console appear:
ppxo_close_no_token_cancelurl 

Then if you proceed in the frame, errors comes up and at the end the shop page load into the iframe ! (that doesn't close automagically).

I hate IE 11 :-)

**Comment by bluepnume** [comment]
Hi! Can you share any of the console errors you were seeing?

**Comment by frontegi** [comment]
Sure ! Sorry for the delay.
Directly from https://developer.paypal.com/demo/checkout
IE Settings resetted to defaults before testing. 

![image](https://user-images.githubusercontent.com/10157050/31865355-1fd5bfc8-b76e-11e7-87ef-60544927133d.png)

ineligible {"timestamp":1508699673169,"windowID":"e8c8386264","pageID":"e369d0d4e3"}
ie_intranet_mode {"timestamp":1508699673169,"windowID":"e8c8386264","pageID":"e369d0d4e3"}
ppxo_close_no_token_cancelurl {"timestamp":1508699687197,"windowID":"e8c8386264","pageID":"e369d0d4e3","referer":"https://developer.paypal.com","host":"www.sandbox.paypal.com","path":"/webapps/hermes/button","env":"sandbox","country":"US","lang":"en","uid":"7db663ee11","ver":"4.0.141"}

**Comment by bluepnume** [comment]
Hmm. Looks like IE is in intranet mode, for some reason.

Can you try following the doc here and let me know if any of the suggestions work? https://github.com/paypal/paypal-checkout/blob/master/docs/debugging/ie-intranet.md

**Comment by frontegi** [comment]
It worked ! However, don't know why it entered Intranet Mode ...
Thanks a lot for the suggestion !

**Comment by bluepnume** [comment]
Great! Out of interest which specific setting did you change to fix it?

**Comment by frontegi** [comment]
![image](https://user-images.githubusercontent.com/10157050/31867381-e3c12182-b78e-11e7-9b66-39ebbbc79774.png)
This one was flagged.
I think it is a default, never touched this setting :-) .
cit. 👍  ->>> IE 11 is a vodoo entity

**Comment by bluepnume** [comment]
Thanks! Yep, voodoo is putting it mildly :D
