### ISSUE TITLE
Option "Pay with Debit or Credit Card" is missing

### ISSUE THREAD

**Issue by markb-trustifi** [paypal/paypal-checkout#510]
### Description
Option "Pay with Debit or Credit Card" is missing

````JS
paypal.Button.render({
    env: 'production',
    locale: 'en_US',
    style: {
        label: 'buynow', 
        fundingicons: true,
        size:  'small',    
        shape: 'rect',     
        color: 'gold',      
        branding: true
    },
    commit: true,
    payment: function() {
        ...
        return data.payment_id;
    },
    onAuthorize: function(data) {
        console.log('onAuthorize', data);
        ...
    }
}, '#paypal-button').then(function () {}, function(err) {
    console.error('The payment error', err);
});
````

paypal.version: "4.0.141"
Chrome: 60.0.3112.113 
OS: Mac, El-Capitan

### Steps to reproduce
Click on Checkout button

### Affected browsers
Chrome

### Screenshots
![screen shot 2017-10-22 at 18 12 50](https://user-images.githubusercontent.com/29097494/31863654-1d2bce4e-b759-11e7-96fa-74d75ee3823e.png)

**Comment by braff54** [comment]
Same issue here with Chrome, v  56.0.2924.87. Mac OS El Capitan 10.11.6
Also Safari v11.0 (11604.1.38.1.7)
Problem does not exist with Firefox 56.0

**Comment by verysimplenick** [comment]
I solved a similar problem by setting locale.
Maybe duplicate #500

**Comment by bluepnume** [comment]
@bluelnkd could you comment on the decisioning here?

**Comment by bluelnkd** [comment]
A bug was introduced accidentally to the live site affecting the content on Monday 10/23 affecting some volume of express checkout and website payment standards integrations. 

The content reads "Sign Up" on the button despite Guest and Credit Card payments still working on the following billing page. We're working to get a fix out shortly in the next ~24 hours. Apologies for the issue.

**Comment by bluelnkd** [comment]
@markb-trustifi @verysimplenick @braff54 The fix for the issue should be live at this point. Let me know if you're still running into the issue. 

If you do encounter an additional scenario where you're seeing forced signup, please include the full URL of the page to help us access the logs at the time of the transaction. There should be a URL parameter similar to `token=EC-9YK04208NJ789232T` that we can reference to access the system logs at the time of the transaction to better understand the application logic at the time of the transaction.

**Comment by markb-trustifi** [comment]
The fix should be available in https://www.paypalobjects.com/api/checkout.js?

Sometimes it shows "Pay with...": https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-2JW164850S703744Y
And sometimes "Create an Account": https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-33556603DE366944E

**Comment by bluelnkd** [comment]
@markb-trustifi Can you share a few more examples from your integration or actual tests? I checked through our system logs and other than displaying that the transaction "This transaction has expired. Please return to the recipient's website to complete your transaction using their regular checkout flow.", there's no records of those two URLs in the last 2-3 months.

The fix went live on 10/26 around 1:00pm PST separate from checkout.js changes and commits.

**Comment by markb-trustifi** [comment]
Sorry for being late. Please reopen the bug.

payment_id: "PAY-8PH425808X023013ELICCKCY", 
ref_link: "https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-04B58867NT223182A"

**Comment by zaakV8** [comment]
Hello @bluelnkd , I am very new on this platform. Please help me get the above issue resolved. My paypal credit card payment option goes on and off and i cant figure out what the issue is.
