### ISSUE TITLE
issue paypal in context

### ISSUE THREAD

**Issue by sgodard202** [paypal/paypal-checkout#511]
Hi,

I have an error, when i try used in context. I make official paypal module on prestashop addons.

- The exact browser version
Version 61.0.3163.100 (Build officiel) Built on Ubuntu , running on Ubuntu 16.04 (64 bits)
- A link to your page with the issue, if possible
https://paypal_422.work.202-ecommerce.com (user : paypal / pwd : support_paypal)
- All console logs during the time of the issue, especially error messages
VM1721 checkout.js:327 ppxo_xc_ppcheckout_unexpected_listener_init {origin: "https://www.sandbox.paypal.com", domain: "https://www.paypal.com", timestamp: 1508938424619, windowID: "7e19c85a00", pageID: "c1fed88b25", …}
print @ VM1721 checkout.js:327
log @ VM1721 checkout.js:423
error @ VM1721 checkout.js:458
error @ VM1721 checkout.js:7810
Component.logError @ VM1721 checkout.js:4658
(anonymous) @ VM1721 checkout.js:3958
(anonymous) @ VM1721 checkout.js:2836
ZalgoPromise.try @ VM1721 checkout.js:8263
_RECEIVE_MESSAGE_TYPE.(anonymous function) @ VM1721 checkout.js:2832
receiveMessage @ VM1721 checkout.js:2765
messageListener @ VM1721 checkout.js:2786
VM1721 checkout.js:327 ppxo_paypal_legacy_component_error {error: "Error: Unexpected init message from domain https:/…://www.paypalobjects.com/api/checkout.js:2786:13)", timestamp: 1508938424622, windowID: "7e19c85a00", pageID: "c1fed88b25", referer: "paypal_422.work.202-ecommerce.com", …} 

 Error: Unexpected init message from domain https://www.sandbox.paypal.com -- expected message from https://www.paypal.com
    at Object.handler (https://www.paypalobjects.com/api/checkout.js:3962:41)
    at https://www.paypalobjects.com/api/checkout.js:2836:32
    at Function.ZalgoPromise.try (https://www.paypalobjects.com/api/checkout.js:8263:37)
    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_request] (https://www.paypalobjects.com/api/checkout.js:2832:70)
    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:2765:77)
    at messageListener (https://www.paypalobjects.com/api/checkout.js:2786:13)
print @ VM1721 checkout.js:327
log @ VM1721 checkout.js:423
error @ VM1721 checkout.js:438
(anonymous) @ VM1721 checkout.js:13182
(anonymous) @ VM1721 checkout.js:14576
(anonymous) @ VM1721 checkout.js:7836
ZalgoPromise.try @ VM1721 checkout.js:8263
(anonymous) @ VM1721 checkout.js:7835
resultValue @ VM1721 checkout.js:6095
(anonymous) @ VM1721 checkout.js:7532
(anonymous) @ VM1721 checkout.js:6030
(anonymous) @ VM1721 checkout.js:8124
ZalgoPromise.dispatch @ VM1721 checkout.js:8148
ZalgoPromise.then @ VM1721 checkout.js:8166
ParentComponent.error @ VM1721 checkout.js:6029
(anonymous) @ VM1721 checkout.js:5339
(anonymous) @ VM1721 checkout.js:8134
ZalgoPromise.dispatch @ VM1721 checkout.js:8148
ZalgoPromise.reject @ VM1721 checkout.js:8108
(anonymous) @ VM1721 checkout.js:6026
ZalgoPromise.try @ VM1721 checkout.js:8263
ParentComponent.error @ VM1721 checkout.js:6022
(anonymous) @ VM1721 checkout.js:3962
(anonymous) @ VM1721 checkout.js:2836
ZalgoPromise.try @ VM1721 checkout.js:8263
_RECEIVE_MESSAGE_TYPE.(anonymous function) @ VM1721 checkout.js:2832
receiveMessage @ VM1721 checkout.js:2765
messageListener @ VM1721 checkout.js:2786
VM1721 checkout.js:327 ppxo_paypal_legacy_render_error_redirect_using_url {timestamp: 1508938424624, windowID: "7e19c85a00", pageID: "c1fed88b25", referer: "paypal_422.work.202-ecommerce.com", host: "paypal_422.work.202-ecommerce.com", …}
print @ VM1721 checkout.js:327
log @ VM1721 checkout.js:423
warn @ VM1721 checkout.js:435
(anonymous) @ VM1721 checkout.js:13190
(anonymous) @ VM1721 checkout.js:8124
ZalgoPromise.dispatch @ VM1721 checkout.js:8148
ZalgoPromise.then @ VM1721 checkout.js:8166
(anonymous) @ VM1721 checkout.js:13189
(anonymous) @ VM1721 checkout.js:14576
(anonymous) @ VM1721 checkout.js:7836
ZalgoPromise.try @ VM1721 checkout.js:8263
(anonymous) @ VM1721 checkout.js:7835
resultValue @ VM1721 checkout.js:6095
(anonymous) @ VM1721 checkout.js:7532
(anonymous) @ VM1721 checkout.js:6030
(anonymous) @ VM1721 checkout.js:8124
ZalgoPromise.dispatch @ VM1721 checkout.js:8148
ZalgoPromise.then @ VM1721 checkout.js:8166
ParentComponent.error @ VM1721 checkout.js:6029
(anonymous) @ VM1721 checkout.js:5339
(anonymous) @ VM1721 checkout.js:8134
ZalgoPromise.dispatch @ VM1721 checkout.js:8148
ZalgoPromise.reject @ VM1721 checkout.js:8108
(anonymous) @ VM1721 checkout.js:6026
ZalgoPromise.try @ VM1721 checkout.js:8263
ParentComponent.error @ VM1721 checkout.js:6022
(anonymous) @ VM1721 checkout.js:3962
(anonymous) @ VM1721 checkout.js:2836
ZalgoPromise.try @ VM1721 checkout.js:8263
_RECEIVE_MESSAGE_TYPE.(anonymous function) @ VM1721 checkout.js:2832
receiveMessage @ VM1721 checkout.js:2765
messageListener @ VM1721 checkout.js:2786

- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
- Does the issue occur consistently, or intermittently?
consistently

### Steps to reproduce
Add a product to cart
go to checkout
Create an account
valide your address
choose a shipping
Select paypal and click on 
![capture du 2017-10-25 18-13-50](https://user-images.githubusercontent.com/17830050/32009913-9b2f8d4a-b9b0-11e7-9204-db5f0e459a88.png)

### Affected browsers

- [X] Chrome
- [ ] Safari
- [X] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Looks like you have the following code:

```
window.paypalCheckoutReady = function() {
        paypal.checkout.setup(merchant_id, {
            environment: environment,
            container: 'paypal_in_context_container'
        });
    };
```

This is being called when the paypal button is clicked, but really you need to call this and set `window.paypalCheckoutReady` when the page is loaded. Otherwise the `environment` is not set soon enough.

Also -- this is an old, deprecated integration pattern. Ideally you should be using the new style checkout.js button which avoids many of this problems: 

https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/add-paypal-button/
https://developer.paypal.com/demo/checkout/#/pattern/server
