### ISSUE TITLE
Problem importing paypal-checkout xcomponent_delegate_paypal_checkout_login.

### ISSUE THREAD

**Issue by jmoguelruiz** [paypal/paypal-checkout#516]
When I import **paypal-checkout** show me the follow error in console:

![captura de pantalla 2017-10-26 a la s 19 43 25](https://user-images.githubusercontent.com/10202219/32083119-fe846bd8-ba85-11e7-92ae-08a50c4bf738.png)

And my project dies.

I'm trying to implement a ButtonComponent in react.

![captura de pantalla 2017-10-26 a la s 19 48 48](https://user-images.githubusercontent.com/10202219/32083217-bbe4ae40-ba86-11e7-90ed-b08efb78b7ad.png)

Thank you for your help!!!

**Comment by bluepnume** [comment]
Hmm. Is it possible the paypal script is being pulled in multiple times? Do you have a script tag which loads paypalobjects.com/api/checkout.js?

**Comment by jmoguelruiz** [comment]
No, that place is the only place when im import it, that is weird.

**Comment by jmoguelruiz** [comment]
I went to the **checkout.lib. js** file to verify the error, and printed the **existingListener** variable, I don't know why the listener is duplicated but is there any way to remove the duplicate?

![captura de pantalla 2017-10-28 a la s 13 40 59](https://user-images.githubusercontent.com/10202219/32137483-8821d9fa-bbe6-11e7-9616-59fe5da49cdc.png)

![captura de pantalla 2017-10-28 a la s 13 41 24](https://user-images.githubusercontent.com/10202219/32137484-8b61d7e6-bbe6-11e7-914a-02f07f8619be.png)



Im using:

"react": "15.3.2",
"react-dom": "15.3.2",
"webpack": "1.12.11"

**Comment by bluepnume** [comment]
Can you add a console.trace there so you can see why it's being registered the first time? I think we're gonna have to figure that out to get around this, as it could cause more problems even if we work around this specific instance.

```javascript
if (name === 'xcomponent_delegate_paypal_checkout_login') {
    console.warn('Registering xcomponent_delegate_paypal_checkout_login on', window.location.href);
    console.trace();
}
```

**Comment by jmoguelruiz** [comment]
Hello again, @bluepnume Here is the result. What do you think? thanks.
![captura de pantalla 2017-10-28 a la s 15 25 28](https://user-images.githubusercontent.com/10202219/32138210-44dc755c-bbf4-11e7-8b05-2a2af3ac490a.png)

![captura de pantalla 2017-10-28 a la s 15 24 23](https://user-images.githubusercontent.com/10202219/32138202-2c24c410-bbf4-11e7-8857-ac3e06831121.png)

**Comment by bluepnume** [comment]
Can you do the trace when `(name === 'xcomponent_delegate_paypal_checkout_login')`? In your screenshot you're only getting a trace for the call which we know about. I'm interested to know why this listener was registered the first time.

**Comment by jmoguelruiz** [comment]
Ok, look @bluepnume, I appreciate your help..
![captura de pantalla 2017-10-28 a la s 16 46 31](https://user-images.githubusercontent.com/10202219/32138830-99e1d2f8-bbff-11e7-9153-ded07c54c3e8.png)


![captura de pantalla 2017-10-28 a la s 16 42 01](https://user-images.githubusercontent.com/10202219/32138804-28fe8eaa-bbff-11e7-9279-574f3f63a9bf.png)
======
![captura de pantalla 2017-10-28 a la s 16 42 42](https://user-images.githubusercontent.com/10202219/32138805-2fd617e8-bbff-11e7-8dac-6ff3acaffc8b.png)
======
![captura de pantalla 2017-10-28 a la s 16 42 58](https://user-images.githubusercontent.com/10202219/32138806-37398240-bbff-11e7-8db9-46b132bf8472.png)

**Comment by bluepnume** [comment]
OK so -- looks like it's running through the exact same points in your own `bundle.js` and `PaypalButton.js` multiple times. Is it possible `PaypalButton.js` is being loaded multiple times in the page?

If you have an example of this up somewhere I'll be happy to help debug.

**Comment by jmoguelruiz** [comment]
Ohh, it's my mistake @bluepnume!!, I hadn't noticed that I had used the script tag before and between the tests I added it again and this last one was the one that I removed and which I was sure that only that put, but well I eliminated the missing script tag and solved the problem, thank you very much for your time and support. ;), Thank you very much!!.
