### ISSUE TITLE
experience options(presentation) doesn't work when integrate express checkout client side

### ISSUE THREAD

**Issue by Lei-YT** [paypal/paypal-checkout#518]
### Description
I want to integrate express checkout using client side, try to set the pages in english, but it still always in chinese.
`input_fields` and `flow_config` works, but `presentation` not.
Here's my code in https://developer.paypal.com/demo/checkout/#/pattern/experience : 
```js

<script src="https://www.paypalobjects.com/api/checkout.js"></script>

<div id="paypal-button-container"></div>

<script>

    // Render the PayPal button

    paypal.Button.render({

        // Set your environment

        env: 'sandbox', // sandbox | production

        // PayPal Client IDs - replace with your own
        // Create a PayPal app: https://developer.paypal.com/developer/applications/create

        client: {
            sandbox:    'AZDxjDScFpQtjWTOUtWKbyN_bDt4OgqaF4eYXlewfBP4-8aqX3PiV8e1GWU6liB2CUXlkA59kJXE7M6R',
            production: '<insert production client id>'
        },

        // Wait for the PayPal button to be clicked

        payment: function(data, actions) {

            // Make a client-side call to the REST api to create the payment

            return actions.payment.create({
                payment: {
                    transactions: [
                        {
                            amount: { total: '0.01', currency: 'USD' }
                        }
                    ]
                },

                experience: {
                    input_fields: {
                        no_shipping: 1
                    },
                    presentation: {
                        locale_code: 'US'
                    },
                    flow_config:{
                        user_action: "commit" 
                    }
                }
            });
        },

        // Wait for the payment to be authorized by the customer

        onAuthorize: function(data, actions) {

            // Execute the payment

            return actions.payment.execute().then(function() {
                window.alert('Payment Complete!');
            });
        }

    }, '#paypal-button-container');

</script>
    
```

### Affected browsers

- [x] Chrome
- [ ] Safari
- [x] Firefox
- [x] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other  

Haven't try other browers.

**Comment by ErikMHummel** [comment]
Try setting locale at the button create like [this doc notes](https://github.com/paypal/paypal-checkout/blob/2f6a7706f0c26f8ee7725371dd4621d5c452455e/docs/button.md#customizing-the-button). 

Also use the language plus country locales. So `en_US` Rather than just `US` in your example.

**Comment by Lei-YT** [comment]
Thanks for your reply.
`locale` in render() is work for the button, but iframe pages not help.
I found `US` is valid value for `locale_code` from  [here](https://developer.paypal.com/docs/api/payment-experience/#definition-presentation). Try `en_US` too, nothing different.

Or is there any way to pass `experience_profile_id` when create?

**Comment by Lei-YT** [comment]
Thanks for your reply.
`locale` in render() is work for the button, but iframe pages not help.
I found `US` is valid value for `locale_code` from  [here](https://developer.paypal.com/docs/api/payment-experience/#definition-presentation).

Or is there any way to pass `experience_profile_id` when create?

**Comment by bluepnume** [comment]
> locale in render() is work for the button, but iframe pages not help.

Can you elaborate on what you mean by this? Which page is not being displayed in `en_US`?

**Comment by Lei-YT** [comment]
Sorry about my english.
I can Customize the Button by : 
```js
paypal.Button.render({
    ...
    // Specify the language displayed on your button
    locale: 'en_US',
   ...
}, '#myContainerElement');
```
But is not I want.
My problem is the PayPal checkout page always in chinese even my code set `locale_code: "US"` : 
```js
                experience: {
                    presentation: {
                        locale_code: 'US'
                    }
                }
```

**Comment by bluepnume** [comment]
Is the login page in chinese, or is this after you have logged in?

**Comment by Lei-YT** [comment]
after login
Can it be forced to display english?

**Comment by bluepnume** [comment]
Normally after you log in, it will display the language set in your account. You should be able to change that preference in your account settings.

**Comment by Lei-YT** [comment]
Thanks a lot.
I get it. Set the button in en_US, the login page will be correctly in english.

**Comment by bluepnume** [comment]
No problem!
