### ISSUE TITLE
Timeout Problem on production environment (Timed out waiting 10000ms for payment)

### ISSUE THREAD

**Issue by capsulejj** [paypal/paypal-checkout#520]
Recently i developed an platform with paypal checkout.
However when it comes to production, very often the payment dialog disappeared immediately right after clicking the checkout button.
I tried various solution and none of them works.
Then i tried to search for the exception that caught and shown on the console of the browser in 
https://www.paypalobjects.com/api/checkout.js
and i found this:
------------------------------------------------------------------------------------------
checkout.js
line 8859

this.props.env !== __WEBPACK_IMPORTED_MODULE_5__config__.d.PRODUCTION || Object(__WEBPACK_IMPORTED_MODULE_6__lib__.i)("disable_payment_timeout") || (this.memoizedToken = this.memoizedToken.timeout(**## 50, new Error("Timed out waiting 10000ms for payment")**));

------------------------------------------------------------------------------------------

Finally i fixed this problem by modifying the timeout from 50 to a longer span like 10000 which should be representing 10000ms.

May i know if the way that i did to fix this is correct or not? Does the 50 serves some other purposes?

Hope someone could answer me soon. thanks a lot.

**Comment by bluepnume** [comment]
Can you please try clearing your browser cache? This should be fixed in the latest release. Thanks!

**Comment by capsulejj** [comment]
Yes, It was fixed, thanks for helping to fix this.
