### ISSUE TITLE
Accessibility: Add alternative text for the overall button

### ISSUE THREAD

**Issue by Millais** [paypal/paypal-checkout#521]
### Description

checkout.js currently provides alt text in two locations: _pp_ for the PayPal monogram, and _paypal_ for the PayPal logo on the button.

We should provide alternative text for the button as a whole – for instance 'Check out with PayPal'. Although the rendered button strictly isn't an image, the rendered elements may be considered as such and adding an alt tag would help support accessibility.

### Steps to reproduce

Version: 4.0.146 (All browsers)
See https://developer.paypal.com/demo/checkout

**Comment by bluepnume** [comment]
Hi @Millais, thanks for the suggestion! Do you mean, if the button iframe itself fails to load, we should show some alt-text? Normally in these scenarios we don't render anything, and we expect the merchant to point the buyer to an alternative. If the iframe entirely fails to load, there's nothing clickable or interactive, so there's not much a customer can do at that point.

**Comment by bluepnume** [comment]
Makes sense 👍 for now I've added `aria-label` attributes to the buttons with the name of the selected funding source. Will go out in the next release.

**Comment by Millais** [comment]
Great, thanks Daniel.
