### ISSUE TITLE
Any way to trigger the checkout without the user clicking on the button?

### ISSUE THREAD

**Issue by alexturpin** [paypal/paypal-checkout#522]
### Description

Forgive me if this isn't the right place to ask; if it isn't, could someone direct me to an appropriate support form?

I am using the Express Checkout version 4.0.152 in Chrome 62. I have my button setup and all is well, but I am wondering if there is a way to trigger the flow myself, without the user having to click on a button?

My scenario is as follows: user can choose between various payment providers, one of them being PayPal. This is done through radio buttons. I'd like there to be a single button to continue to payment, but for that I need to be able to trigger the PayPal Express Checkout flow myself. Essentially, I'm looking for the ["Mark" interactive example](https://developer.paypal.com/demo/checkout/#/pattern/mark) but where all scenarios present the same gray "Continue" button (or a button of my choice). Is this at all possible?

Thanks

**Comment by bluepnume** [comment]
Hi @alexturpin, thanks for the question! We don't offer that right now, there have been a few discussions on this already for context:

https://github.com/paypal/paypal-checkout/issues/512
https://github.com/paypal/paypal-checkout/issues/287

https://medium.com/@bluepnume/less-is-more-reducing-thousands-of-paypal-buttons-into-a-single-iframe-using-xcomponent-d902d71d8875

**Comment by alexturpin** [comment]
Unfortunate. Thanks for the answer!
