### ISSUE TITLE
iPhone iOS11 issue

### ISSUE THREAD

**Issue by SCAllday** [paypal/paypal-checkout#523]
This was noticed on a Braintree integration, but resides in a Paypal library.

On iPhone’s running iOS 11, in Safari, at the point of selecting payment, if you click to pay by Paypal, the Paypal console loads in a new browser window.

Once loaded, if you then click “back”, the checkout page loads back up, but the Paypal button disappears. No amount of refreshing the page will bring the Paypal button back. Only when you close the window and reopen it, will you then get the button back.

We've removed all our code and the issue still happens. Braintree Dev have also been able to replicate this issue stating:

**
First things first, I was able to replicate the refresh issue on a mobile device as well. I can see the specific error response can't find variable paypal, and it seems that this is happening across multiple SDK versions. However, it's only happening in the Safari mobile browser, Chrome was acting as expected upon refreshing the page.

After some digging I was able to find that the ultimate source of the issues as originating in the PayPal Checkout.js library. That library is what our paypal-checkout.js integration communicates with when handling these customer checkout flows. We have no direct insight or control over that library, it's managed directly through PayPal's internal development team.
**

I can provide screenshots, but it's my belief this is an inherent problem of any Paypal/Braintree integration.

Any help much appreciated
Steve
Co-op Mobility

**Comment by bluepnume** [comment]
Thanks for the report! I'll try to take a look. Do you have a link to the specific integration so I can try it out?

**Comment by SCAllday** [comment]
Hi Daniel,

 

Thanks for your email.

 

I didn’t want to post the URL to Github because we’re currently on a conversion drive and the idea having a lot of developers testing the checkout without buying would’ve scuppered that!!

 

So, as long as you’re happy to not post the URL for all to see, please feel free to test out https://www.co-opmobility.co.uk

 

You’ll need to add something to your basket and go through the checkout

 

Specifically, the issue is found on the 

 

https://www.co-opmobility.co.uk/checkout/your-details page

 

But we also set up a stand alone version here:

https://www.co-opmobility.co.uk/braintreetest.asp

 

Cheers, all the best and good luck!

Steve

**Comment by SCAllday** [comment]
Hi Daniel,

 

You’re welcome!

 

The website is https://www.co-opmobility.co.uk

 

You’ll need to add something to your basket and go through the checkout

 

Specifically, the issue is found on the 

 

https://www.co-opmobility.co.uk/checkout/your-details page 

 

Cheers, all the best and good luck!

Steve

**Comment by bluepnume** [comment]
Hey, just fyi your email response was added as a github comment. I edited out the URLs for you.

Thanks!

**Comment by SCAllday** [comment]
Much appreciated!

Did you get an email with a test, "standalone integration" URL as well?

Sorry, you may be able to tell I haven't used Github before... :)

**Comment by bluepnume** [comment]
I think I've managed to repro the issue. Looks like Safari is doing something funky and trying to load the URL of the parent page in the pop-up when you hit back. Hopefully should be able to figure out a solve soon.

**Comment by bluepnume** [comment]
@SCAllday -- can you please clear the safari cache on your phone and try this once more? I've fixed the issue with the PayPal button not re-rendering when you hit the back button.

There seems to be a Safari bug here; when you hit back, it doesn't actually close the popup window, it just loads the previous url in the popup, rather than switching back to the parent window. There may be a fix to get around this, but I'm planning on raising this as a bug with Apple. 

In the mean time, at least, the button should render and the experience should be a lot better. Please let me know if you continue to see the problem!

Thanks again for the heads up.

**Comment by SCAllday** [comment]
That's great. We've tested it here and the button is now appearing as it should. Thanks for all your help and all the best, Steve

**Comment by bluepnume** [comment]
Great, thanks for testing!
