### ISSUE TITLE
Payment could not be executed 

### ISSUE THREAD

**Issue by reggarcia** [paypal/paypal-checkout#524]
Express checkout on my sandbox has been failing since yesterday:

I click on the Paypal Button, enter my login my credentials on the modal and hit the "Pay Now" button and I keep getting this error:
<img width="458" alt="screen shot 2017-11-05 at 12 31 50 pm" src="https://user-images.githubusercontent.com/3925319/32418833-93058ebc-c225-11e7-8f2f-1698dae33989.png">
<img width="1143" alt="screen shot 2017-11-05 at 12 32 03 pm" src="https://user-images.githubusercontent.com/3925319/32418834-931cf35e-c225-11e7-98f2-dc90efb54683.png">

 Payment could not be executed at https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js?build=2.0.2_20171027121328293.unx:4224:35 at https://www.paypalobjects.com/api/checkout.js:8202:46 at ZalgoPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:8216:27) at ZalgoPromise.reject (https://www.paypalobjects.com/api/checkout.js:8176:22) at https://www.paypalobjects.com/api/checkout.js:8209:91 at ZalgoPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:8216:27) at ZalgoPromise.reject (https://www.paypalobjects.com/api/checkout.js:8176:22) at https://www.paypalobjects.com/api/checkout.js:8198:45 at ZalgoPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:8216:27) at ZalgoPromise.reject (https://www.paypalobjects.com/api/checkout.js:8176:22)

**Comment by bluepnume** [comment]
Can you check the network tab for the /execute call and copy the response? Should give a clue what the actual error was.

**Comment by reggarcia** [comment]
Here's the response:

{"ack":"contingency","contingency":"INTERNAL_SERVICE_ERROR","meta":{"calc":"8c1c7943efa3","rlog":"ubUu18doUwN8Ql3%2BEj48vx6R1c6nn7fBLBKWz%2B8RZk7EjvCk9rDD5IF4V%2Foy53Eh5DeTgS3ZLB2Txcx5YHqhRQ_15f8df1dce4"},"server":"MUHW0i1tqbcp3z3xShC_ur4Ba-hez2NAzEGGfIOkRmPcrsFt0dA0ch4kGOKLkJdymqT_ZojLdbXO0wMAa61FbpRufzc7NAJvA0GmkadCmhdacHq3ixyHO8ey1_0WVfShZsrxTeQeA16S_dShSVW7c8rVgEaFaujDLIgmy4b9CKyZipTa9UZntaN_v4EQcZKRvitl79GaV-5jl2PvRZ19Vo0UAwS9-UVLohRTUnp_oN1ac7sAXeDTMl9prLf9Ys_k4MTOrAS71EG"}

**Comment by reggarcia** [comment]
<img width="1437" alt="screen shot 2017-11-05 at 12 50 00 pm" src="https://user-images.githubusercontent.com/3925319/32418987-de4f171a-c227-11e7-87b8-d26c576f3208.png">

**Comment by bluepnume** [comment]
I'm looking at the internal logs for this failure, but not seeing any clear cause. Can you try with different seller/buyer sandbox accounts and let me know if you see the same issue?

**Comment by reggarcia** [comment]
I tried a different account but now I'm getting a different error:

{ack: "contingency", contingency: "INSTRUMENT_DECLINED", meta: {calc: "4d310302f19a4",…},…}
ack
:
"contingency"
contingency
:
"INSTRUMENT_DECLINED"
meta
:
{calc: "4d310302f19a4",…}
server
:
"_9LZtG95qTQ5G2acbqMOitfgIz2CrAuMMzzUaoWwFWVuIDA24XxRym4Y7rBLL-EFZ-PMBOkQBjAd7CayYrpUXcGEuSRNpXiXWLAm2X8LoOhjzm4-KTO5b5scOA3s3mtTgFvIsF0R9fopUowigwflEF3OoWNJvdzcdCb29GMPZnYMQ1uoMTHSL7kw_nFZ6zvHtgUV7gDWxVa1iGm0Sz9FgQrh2QiSuLLFlw5TbCGrOZxGrNroy6uqfX7o2mD1sN_ZR3fldel_93O"

**Comment by reggarcia** [comment]
any updates on this? the error happened so suddenly and i'm kinda stuck.

**Comment by bluepnume** [comment]
This seems to be the result of an internal sandbox issue. The team is currently looking into it, I'll get back to you when I know more. Thanks!

**Comment by bluepnume** [comment]
Can you please check again? From my side, I'm testing and seeing a success.

**Comment by bluepnume** [comment]
Sounds like there was a load-balancer which had come down. It was restarted and that fixed the issue. Thanks for checking!

**Comment by acomito** [comment]
@bluelnkd I'm getting the same error in our production account.

We're an invoicing app, where our users send their clients invoices. Our users do a paypal auth (so we have their info), and their clients can pay them via paypal. Is this use case not supported? Is our account not green-lighted by paypal yet (if so, how do we do that)? We're basically at a standstill trying to contact paypal for an answer.
