### ISSUE TITLE
Amount not showing in the paypal pooup window

### ISSUE THREAD

**Issue by electrozed** [paypal/paypal-checkout#525]
I created an app with React Version : 16.0.0 and using this package version : 4.0.130
when the paypal popup appears i cant see any amount any where  .. so the user cant see what he is going to pay on 

example for using paypal checkout in react : 

```javascript 

import React, {Component} from 'react';
import paypal from 'paypal-checkout';
import ReactDOM from 'react-dom';

const PayPalButton = paypal.Button.driver('react', {React, ReactDOM});
class PaypalButton extends Component {

    payment = (data, actions) => {
        return actions.payment.create({
            payment: {
                transactions: [
                    {
                        amount: { total: '0.01', currency: 'USD' }
                    }
                ]
            }
        });

    };
    onAuthorize = (data, actions) => {
        return actions.payment.execute()
            .then(() => {
                this.props.addPayment(this.props.paymentMethod)
            })

    };
    onCancel= (data, actions)=> {
    };
    onError = (err) =>{

    };
    render() {
        const {env, locale, style, client} = this.props.paypalBtnConfig;
        return (
            <PayPalButton
                env={env}
                locale={locale}
                style={style}
                onCancel={(data,action)=>this.onCancel(data,action)}
                onError={(err)=>this.onError(err)}
                payment={(data, action) => this.payment(data, action)}
                onAuthorize={(data, action) => this.onAuthorize(data, action)}
                client={client}

            />
        );
    }
}

export default PaypalButton;
```
i tired to search in paypal docs and found nothing 
also here 
would like to know if there is any other configs that i need to pass this paypal button component 

thanks !

**Comment by bluepnume** [comment]
Can you try passing `commit={true}`?

**Comment by electrozed** [comment]
@bluepnume yup working !!! thanks alot !!!

why not to write it in the docs ?

**Comment by electrozed** [comment]
@bluepnume  i setup the amount like that : { total : 0.01 , currency : 'ILS'}
and i can see the amount in the popup but in UDS

**Comment by bluepnume** [comment]
I see it correctly:

<img width="916" alt="screen shot 2017-11-06 at 11 19 57 am" src="https://user-images.githubusercontent.com/1219075/32459410-726905d4-c2e4-11e7-9e22-00c71745fccd.png">

Can you share the full code you're using with `ILS`?

**Comment by electrozed** [comment]
sorry was my mistake working good !! thanks alot

**Comment by bluepnume** [comment]
Awesome!
