### ISSUE TITLE
Token validation on Server

### ISSUE THREAD

**Issue by oscarcalvo** [paypal/paypal-checkout#526]
Hi:

How can I to validate if a payment/sale is ok on Server? I use checkout express, a button with an onauthorize callback where I exececute the payment and Paypal answer me ok, I can validate response and until here ok. 
But at the end I have to send this info to server and mark payment done. Obviously in server I need to verificate that payment exists and is really done. Do I need to call to Paypal with a web request getting the payment or maybe I can avoid this request and validate in some way the token with my secretId?

Thanks.

**Comment by bluepnume** [comment]
> Do I need to call to Paypal with a web request getting the payment or maybe I can avoid this request and validate in some way the token with my secretId?

Right now yes -- calling paypal to get the payment details is the recommended path.

**Comment by oscarcalvo** [comment]
Thanks
