### ISSUE TITLE
Horizontal Buttons are cropped in "Medium/large" size option

### ISSUE THREAD

**Issue by rafiaabk** [paypal/paypal-checkout#527]
If i switch the layout from vertical to horizontal, the button wording are cropped. 
**Horizontal buttons displaying properly** --- if the size as "responsive". 
**Horizontal buttons text cropped**           --- if the size is "Medium/large".

![horizontal](https://user-images.githubusercontent.com/29918983/32481695-7dc4c144-c3ba-11e7-9953-6e1f06df7c86.png)

**Comment by bluepnume** [comment]
Can you please share the browser info?

**Comment by rafiaabk** [comment]
Firefox - 56.1

**Comment by bluepnume** [comment]
Fixed and ready to push in the next release.
