### ISSUE TITLE
Paypal input field issue in in-app browser

### ISSUE THREAD

**Issue by brijendratiwari** [paypal/paypal-checkout#528]
I have an ionic app which uses paypal in-app browser for checkout. As soon as the user is redirected to the paypal page and they to click on email field or the password field, cursor to add, edit email or entering password dont show up. The issue happens at the selected area of the text fields, means if I click on the top selected area as in the screenshot. 
This seems to happen only on Android. 

![screen shot 2017-11-07 at 5 43 22 pm](https://user-images.githubusercontent.com/2110054/32494514-ea636936-c3e7-11e7-96fb-ad88b09a5c63.png)

To reproduce the issue, just load the paypal in in-app browser on android device and try to click on the top area of the text field or password field.

**Comment by bluepnume** [comment]
@walmik can you take a look?

**Comment by walmik** [comment]
@brijendratiwari Hello Brijendra, could you please help me understand the issue correctly... is the email or password cut off visually at all times? Or is it something that happens only when you click in the input field to edit or enter an email or password. 

Typically iframe integrations on devices seem to have quirks that are not easily identifiable just with a screenshot. Would it be possible for you to create a video/animated gif of the issue? It can help me seeing the exact issue and the way to solve it. (Android has free apps to record screen activity)

Also please share the integration pattern used to initiate checkout - @bluepnume it seems like the older integration pattern for login is served.

**Comment by brijendratiwari** [comment]
Hello @walmik ,
This is a random issue which users are facing with paypal when used in in-app browser. The issue is with certain click area. As mentioned in the screenshot, if by any chance user click in that area, cursor dont appear and whole page is freezed. If user click on below area, cursor appears and user is able to type in the email address.

**Comment by brijendratiwari** [comment]
I figured out the issue. The issue was with the old version of in-app browser plugin for Ionic.

**Comment by walmik** [comment]
That’s good to know @brijendratiwari :) Thanks for sharing the root cause.

**Comment by bluepnume** [comment]
Great, thanks!
