### ISSUE TITLE
Papal integration on Ionic 1 App fails

### ISSUE THREAD

**Issue by fazilmk2014** [paypal/paypal-checkout#529]
![paypal-bug-1-continue](https://user-images.githubusercontent.com/7526015/32722007-7a0152ba-c88e-11e7-85ec-81ec4729ce1a.png)
### Description
My paypal integration fails when I click on paypal button from my ionic mobile app. I'm can transact using paypal when I test from laptop. Please see the attached screenshot. 
![paypal-bug-1](https://user-images.githubusercontent.com/7526015/32721987-6edb142a-c88e-11e7-9227-57e4f0fff979.png)

**Comment by bluepnume** [comment]
We don't officially support ionic, but if you can figure out the issue this entire module and its dependencies are open source, so please feel free to PR in a fix. Sorry I can't offer you more than that -- my recommendation for now would be to go with the [Braintree SDK](https://developers.braintreepayments.com/guides/paypal/overview/android/v2)
