### ISSUE TITLE
"Continue to PayPal" link in overlay opens a new tab

### ISSUE THREAD

**Issue by edbird-pp** [paypal/paypal-checkout#530]
### Description
There is an issue where the "Continue to PayPal" link from the overlay opens a new blank tab. The following log is shown in the console:
```
index.js:574 ppxo_close_no_token_cancelurl { country: "US", env: "sandbox", host: "www.sandbox.paypal.com", lang: "en", pageID: "9f3e9e203b", path: "/webapps/hermes/button", referer: "http://localhost:3000", timestamp: 1510578849699, uid: "ddc9c0015b", ver: "4.0.161", windowID: "da6da5107f" }

parent.js:172 Unsafe JavaScript attempt to initiate navigation for frame with URL 'about:blank' from frame with URL 'https://www.sandbox.paypal.com/webapps/hermes/button?version=4&env=sandbox&style.size=responsive&style.shape=rect&style.label=credit&sessionID=ddc9c0015b&funding.disallowed=venmo&funding.remembered=paypal&locale.x=en_US&logLevel=warn&uid=f6d8cf1b75&xcomponent=1'. The frame attempting navigation is neither same-origin with the target, nor is it the target's parent or opener.
```
This is a bit of edge case but would be good to catch it in the JS.
Video of behaviour: http://recordit.co/nqhph32Wgw

```
paypal.version="4.0.161"
Google Chrome: Version 61.0.3163.100
```

### Steps to reproduce

You can reproduce this on https://developer.paypal.com/demo/checkout/#/pattern/client

1. Click the PayPal button
2. Close the PayPal window
3. Immediately click the "Continue to PayPal" button

### Affected browsers

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Thanks for the heads-up! We have a fix in for the next release.

**Comment by edbird-pp** [comment]
Great, thanks!

**Comment by rewb0rn** [comment]
Is this fixed yet? I can reproduce the behavior in Firefox if I click the overlay just in the moment when the payment has finished before the redirect kicks in.

**Comment by bluepnume** [comment]
@rewb0rn can you open a new issue with details if you're still seeing a problem here? Thanks
