### ISSUE TITLE
Popup location is not stable in Edge

### ISSUE THREAD

**Issue by benzookapi** [paypal/paypal-checkout#532]
### Description

In-context checkout should be central in the screen but in Edge,  it appears on  the left part.

- Screenshots or videos that show the issue 
![image006](https://user-images.githubusercontent.com/899580/32872230-fdb39d02-cac8-11e7-92c0-701328e09ffa.jpg)

- Your code 
   Demo site one and mine.
   https://github.com/benzookapi/BraintreeSDKNodeDemo/blob/master/views/index.jade#L131
- The `paypal.version` from your browser console
  4.0.163
- The exact browser version
  Microsoft Edge 38.14393.1066.0
  Microsoft EdgeHTML 14.14393
- A link to your page with the issue, if possible
  https://developer.paypal.com/demo/checkout/#/pattern/client
  http://jo-pp-node-demo.herokuapp.com/
- All console logs during the time of the issue, especially error messages
 Not console but full URL of this checkout page.
 https://www.sandbox.paypal.com/checkoutnow?version=4&locale.x=en_US&fundingSource=paypal&sessionID=3310da19ea_gaztumbyhi2di&buttonSessionID=3310da19ea_gaztumbyhi2di&env=sandbox&logLevel=warn&uid=fb9a5d2589&token=PAY-76A36080VW361874GLIGQCUY&xcomponent=1#/checkout/login
 
  
- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
 Yes
- Does the issue occur consistently, or intermittently?
 Almost consistently
### Steps to reproduce
  Just click PP button.  Most of the 1st appearance has this bug, 2nd and 3rd one sometimes not.
  2 or 3 times out of 10 testing shows this issue by opening/closing Edge browser.

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
This is an Edge issue. We are correctly passing the position values to window.open and Edge is not respecting the values we pass. Leaving this open so we can raise an issue with microsoft.
