### ISSUE TITLE
Issue with trying to click on PayPal Checkout button inside the iframe

### ISSUE THREAD

**Issue by mannus-nisum-com** [paypal/paypal-checkout#533]
### Description
Issue with trying to click on PayPal Checkout button inside the iframe  
![image](https://user-images.githubusercontent.com/32070510/32896267-5f6cef36-cb04-11e7-8b1c-a37e7c1853f0.png)

### Steps to reproduce

When I try execute testcase on chrome browser and click on paypal button inside the iframe. Selenium prompt exception that : org.openqa.selenium.WebDriverException: unknown error: Element <iframe class="xcomponent-component-frame xcomponent-visible" frameborder="0" allowtransparency="true" name="xcomponent__ppbutton__4__pmrhk2leei5cem3bge3deojtgaygeirmej2gczzchirhaylzobqwyllcov2hi33oeiwcey3pnvyg63tfnz2faylsmvxhiir2pmrhezlgei5ce5dpoarh2lbcojsw4zdfojigc4tfnz2ceot3ejzgkzrchirhi33qej6syitqojxxa4zchj5se5dzobsseorcojqxoirmej3gc3dvmurdu6zcozsxe43jn5xceorcgqrcyitqmf4w2zlooqrdu6zcl5pxi6lqmvpv6ir2ejpv6ztvnzrxi2lpnzpv6it5fqrg63sbov2gq33snf5gkir2pmrf6x3upfygkx27ei5cex27mz2w4y3unfxw4x27ej6syitfnz3ceorconqw4zdcn54celbconsxg43jn5xesrbchirgiobsgmywmzjygazf6z3fgjshk3lkovugs6teomrcyitcov2hi33oknsxg43jn5xesrbchirdcmdggjrgcyjtmztf6z3fgjshk3lkovugsmtunercyittn52xey3fei5ce3lbnz2wc3bcfqrha4tfmzsxiy3ijrxwo2loei5gmylmonssyitgovxgi2lom4rdu6zcmfwgy33xmvsceos3luwcezdjonqwy3dpo5swiir2lmrhmzlonvxsexjmejzgk3lfnvrgk4tfmqrduw25fqrhezlnmvwwezlsei5hwis7l52hs4dfl5pseorcl5pwm5lomn2gs33ol5pse7l5fqrgg33nnvuxiir2mzqwy43ffqrg63ssmvxgizlsei5hwis7l52hs4dfl5pseorcl5pwm5lomn2gs33ol5pse7jmejxw4q3bnzrwk3bchj5sex27or4xazk7l4rduis7l5thk3tdoruw63s7l4rh2lbcn5xeg3djmnvseot3ejpv65dzobsv6xzchirf6x3govxgg5djn5xf6xzcpuwce3dpmnqwyzjchirgk3s7i5bcelbcon2hs3dfei5hwitdn5wg64rchirgo33mmqrcyittnbqxazjchirha2lmnqrcyittnf5gkir2ejzw2ylmnqrcyitmmfrgk3bchirgg2dfmnvw65lueiwceztvnzsgs3thnfrw63ttei5gmylmonsx2lbcmruxg4dmmf4vi3zchirgc3dmeiwce3dpm5ggk5tfnqrduitxmfzg4irmejyg64dvobbhe2lem5sseot3ejqxoyljorhxazlomvzceot3ejpv65dzobsv6xzchirf6x3govxgg5djn5xf6xzcpv6syitumvzxiir2pmrgcy3unfxw4ir2ejrwqzldnnxxk5bcpuwce5ljmqrduirtge2tczbrmrqtezjcpv6syitjmqrduitfgmzwezdchfrdomjcfqrgi33nmfuw4ir2ejuhi5dqhixs6mjzgixdcnryfyytslrsgi5dimrqgarh2__" scrolling="no" allowpaymentrequest="allowpaymentrequest" src="https://www.sandbox.paypal.com/webapps/hermes/button?version=4&amp;env=sandbox&amp;sessionID=d8231fe802_ge2dumjuhizds&amp;buttonSessionID=10f2baa3ff_ge2dumjuhi2ti&amp;funding.disallowed=venmo&amp;locale.x=en_GB&amp;style.color=gold&amp;style.shape=pill&amp;style.size=small&amp;style.label=checkout&amp;style.fundingicons=false&amp;logLevel=warn&amp;uid=3151d1da2e&amp;xcomponent=1" style="background-color: transparent;" cd_frame_id_="a329c1dd0515d61258bb123f3372dea9"></iframe> is not clickable at point (1271, 713). Other element would receive the click: <div _ngcontent-c1="" class="row">...</div>

### Affected browsers

- [* ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Hi -- I'm not sure how much I'll be able to help you, as we're not doing anything especially non-standard here other than rendering the button inside an iframe. It may be best to raise a question with Selenium for how to get a click working for an element inside an iframe.

**Comment by mannus-nisum-com** [comment]
Basically it is a compatibility issue on chrome browser. I check on Firefox v.46 it is working fine.

**Comment by bluepnume** [comment]
Ah great -- glad you at least have a workaround to get your tests running 👍
