### ISSUE TITLE
Hi, Problem viewport when clicking on the input username and password fields on iPhone

### ISSUE THREAD

**Issue by davysorn** [paypal/paypal-checkout#534]
### Description
- PayPal checkout on iPhone 4 and iPhone with iOS 11.1.1 (the latest iOS version) has a problem. Clicking to input username and password in order to login, the viewport becomes overlap; it shows a small viewport but for android device it is working ok.

- Another problem is when checking out PayPal from Facebook Messenger Webview on Desktop using Chrome, the checkout window cannot be displayed because of iframe. How to solve it?

### Steps to reproduce
Just applying the standard PayPal checkout script and run on iPhone devices or on Desktop using Chrome Browser.

**Comment by bluepnume** [comment]
Can you share a screenshot of what the page looks like for both these cases?

**Comment by davysorn** [comment]
Hi!

Here are my screenshots
![5c6eb1b3-8e9c-4188-af04-1653843c78ca](https://user-images.githubusercontent.com/6076857/33155544-ed4faf5e-d023-11e7-85b3-30b2c2a79d1c.png)
![57f5fe5c-8b05-4f33-9ac0-9e2f0446be5f](https://user-images.githubusercontent.com/6076857/33155545-ed93ca40-d023-11e7-8034-a7f7df6e07cd.png)
![87db2b07-97e6-4d6e-a2ae-5246cc3cb1ec](https://user-images.githubusercontent.com/6076857/33155547-edd317a4-d023-11e7-8aae-d1d350a3f623.png)
