### ISSUE TITLE
Paypal 400 bad Request error

### ISSUE THREAD

**Issue by Fabrianne** [paypal/paypal-checkout#535]
Hi, I'm currently using paypal-checkout v4 and...

whenever I do some test transactions using env: 'sandbox' mode; 
the 'onAuthorize' function is not ran after each transaction. Instead I get a 400 (bad request error):

POST https://www.sandbox.paypal.com/webapps/hermes/api/payment/PAY-0J4924319V637245MLIJJCNY/execute 400 (Bad Request)

in the 'networks tab' the 'execute' request sends back this response:

{
  "ack":"contingency",
  "contingency":"INTERNAL_SERVICE_ERROR",
  "meta":{"calc":"70f84a213d00c","rlog":"vXI%2B4gQUrxwCiVMALQvwUqhPh05ROMrPYw%2BUata62JEnHpB%2FGxnc1hqgUwh%2B2%2FzLf1paYLwOHSvWImJc%2F1HtmA_15fd8884d36"},"server":"b6YBtp2w1Ffw9ag22nJX-wUoZt2NVNDtj0RvdXrCgNSRcEXQfdd6lLcaN7HxlDZCMC19ds3MkggnVthDSFySPhf8DXx-BjkRWZi-fTCmS0VVsjiPoqSBBuHUllWr6LSIDlLJHZgbWGBekTmakCb3Wuc-YJGZ9P7OSNTYzjV_AxuLtLfFO565gKTr2UbMNqB8a9uQaT0HlSvPVnmIh6r-oc0GSjQmQq6zVbFDYjXMkqC1fAubx1vA9YPzVe6lj07k"
}

everything seems to be working fine at first but after a few more test transactions I started getting these errors.

the Javascript code I'm using is the same as the one provided in the example documentation.

What can I do to fix this? Thank you so much!

**Comment by bluepnume** [comment]
Hi -- I'll take a look, but chances are this is an intermittent problem with sandbox. In the mean time can you try clearing your cookies just to be sure? At the very least, this shouldn't affect your integration when you switch to production mode.

**Comment by bluepnume** [comment]
Are you still seeing this problem?

**Comment by Fabrianne** [comment]
Everything is working now, Thank you so much Daniel!

**Comment by janzheng** [comment]
Seems the PayPal Sandbox accounts system goes down from time to time. For anyone else getting these Bad Request issues, just check your sandbox account on their demo page at: https://developer.paypal.com/demo/checkout/. If you get errors on their demo page, you know they screwed up again, as which is what seems to be the norm lately.

<img width="1102" alt="screen shot 2018-02-14 at 12 55 21 am" src="https://user-images.githubusercontent.com/3868520/36189910-066088f2-1123-11e8-97c4-4a064ceceb14.png">

**Comment by moonshineBoy** [comment]
@bluepnume  Hi, brother, I have this issue too, and I cleared the application's paypal cookies, and try again still not work. How to solve this?
