### ISSUE TITLE
frameworks.md does not reflect React16 changes

### ISSUE THREAD

**Issue by emeidell** [paypal/paypal-checkout#537]
Frameworks.md displays an old version of how to implement paypal-checkout into React. 

Path to requested change: paypal-checkout/docs/frameworks.md

Biggest indicator of this not being updated is the 'React.createClass'

**Comment by bluepnume** [comment]
Thanks for the issue @emeidell! Fancy making a PR to fix the example?

**Comment by Shahid4183** [comment]
anyone have good example how to do it with react 16, please help!!!

**Comment by bluepnume** [comment]
@Shahid4183 -- can you take a look at https://github.com/paypal/paypal-checkout/blob/master/demo/react.htm
