### ISSUE TITLE
Button disappeared on error

### ISSUE THREAD

**Issue by msaccone** [paypal/paypal-checkout#539]
### Description

When the payment returns an error, for example DUPLICATE TRANSACTION, then the button is no longer available.

I've used the demo https://developer.paypal.com/demo/checkout/ and just added an invoice number after the transaction amount, like this 

**amount: { total: '0.01', currency: 'USD' },
                                invoice_number: 1**

![image](https://user-images.githubusercontent.com/19209362/33134700-2f584032-cf7f-11e7-9a1c-b06625b22f3e.png)

paypal.version "4.0.166"

- The exact browser version

Google Chrome | 62.0.3202.94 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | 4fd852a98d66564c88736c017b0a0b0478e885ad-refs/branch-heads/3202@{#789}
OS | Windows
JavaScript | V8 6.2.414.42

- All console logs during the time of the issue, especially error messages

**VM1194 button.js?build=2.0.2_20171113102955322.unx:3113 POST https://www.sandbox.paypal.com/webapps/hermes/api/payment/PAY-7P834789V4227915JLIKZJDI/execute 400 (Bad Request)**

- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?

**YES, it does**

- Does the issue occur consistently, or intermittently?

**consistently**

### Steps to reproduce

**add an invoice number to generate a DUPLICATED TRANSACTION error**

### Affected browsers

Verified on Chrome, Edge, and FireFox. Didn't try more browsers.

**Comment by bluepnume** [comment]
Thanks for the report -- definitely looks like a bug. The button should stay rendered / re-clickable.

**Comment by bluepnume** [comment]
Found the cause and added a fix for the next release. Thanks!

**Comment by msaccone** [comment]
Good to hear @bluepnume !! Thanks for your great job,

**Comment by stansongman** [comment]
Is there a suitable workaround in the meantime?  I'm encountering this as well.  Thanks!
