### ISSUE TITLE
No automatic height in responsive vertical style

### ISSUE THREAD

**Issue by hamzaydia** [paypal/paypal-checkout#540]
There is no automatic relative height to the width for the `.xcomponent-outlet` div when:
`style: {
            size:  'responsive',
            layout: 'vertical'
        }`
which causes the hiding of a part of the button:
![ppp](https://user-images.githubusercontent.com/32816199/33136229-a5bc7460-cf9c-11e7-92c7-ca6fdda43c1d.png)

Browser: `Google Chrome Version 62.0.3202.94`

**Comment by hamzaydia** [comment]
Also as a user experience suggestion it would be better if you merge the credit card brands in one button like Paypal to be like this:
"Paypal" => Login Page
"Pay with credit card" => Billing Page

**Comment by bluepnume** [comment]
Can you please let me know if you still see this issue?
