### ISSUE TITLE
Sandbox works, live production results in "This transaction is invalid".

### ISSUE THREAD

**Issue by will8211** [paypal/paypal-checkout#542]
Hi! 

I have everything set up using the REST API and Python SDK with flask on the backend. Everything worked well on the test server with the Sandbox account. I made several test payments. Deployed to production and changed to 'live' and 'production' with the live keys. On the prod server, I get this in the popup, instead of a client paypal login prompt:

"This transaction is invalid. Please return to the recipient's website to complete your transaction using their regular checkout flow. At this time, we are unable to process your request. Please return to merchant and try another option."

The 'create' request goes through without a problem, and I get a payment id. Before deploying to production, I tried out the live settings on the test server. Was this a mistake? 

*Now, it works from the test server with the live keys, but not the prod server.*

Is paypal suspicious since it's receiving requests from a new location?

Not sure what to try next, could you point me in the right direction?

Thanks!
Will

Testing on Chrome.
paypal.js version "4.0.166"
Here's my code with some data replaced by '...'

```javascript

paypal.Button.render({

  env: 'production',
  commit: true,

  payment: function(resolve, reject) {

    // var data = {...}

    return paypal.request.post(CREATE_URL, data)
      .then(function(res) {
        if (res.errorCode > 0) {
          //alert(...);
          return reject(new Error(res.errorText));
        } else {
          return res.paymentID;
        }
      });
  },

  onError: function(err) {
    //alert('...');
  },

  onAuthorize: function(data, actions) {

    var EXECUTE_URL = '/paypal/execute/';

    var data = {
      paymentID: data.paymentID,
      payerID: data.payerID
    };

    return paypal.request.post(EXECUTE_URL, data)
      .then(function (res) {
        //window.location.replace("...");
      });
  }

}, '#paypal-button');
```

```python
def create(post):
    ... = post['...']
    ... = post['...']
    ... = ...
    ... = post['...']

    paypalrestsdk.configure({
        'mode': 'live',
        'client_id': '...',
        'client_secret': '...'})

    payment = paypalrestsdk.Payment({
        "intent": "sale",
        "payer": {
            "payment_method": "paypal"
        },
        "redirect_urls": {
            "return_url": "/paypal/execute/",
            "cancel_url": "/"
        },
        "transactions": [{
            "item_list": {
                "items": [
                    {
                    "name": "...",
                    "sku": "001",
                    "price": "7.00",
                    "currency": "USD",
                    "quantity": 1
                    },
                    {
                    "name": "...",
                    "price": ...,
                    "currency": "USD",
                    "quantity": 1
                    },
                    {
                    "name": "...",
                    "price": ...,
                    "currency": "USD",
                    "quantity": 1
                    }

            },
            "amount": {
                "total": ...,
                "currency": "USD"
            },
            "description": "..."
        }]
    })

    if payment.create():
        return flask.jsonify({'paymentID': payment['id']})
    else:
        return flask.jsonify(payment.error)

```

**Comment by bluepnume** [comment]
Hi! Can you share an example of a payment id which is erroring out? Thanks!

**Comment by will8211** [comment]
Hi!

I just tried, and got this one:

{
  "paymentID": "PAY-14G75855NP862013JLILGXLQ"
}

**Comment by bluepnume** [comment]
Strange. The payment id is a valid production id. Not sure why it's not working for you.

Can you try two things:

1. Can you copy the entire url from the popup window? (ideally before it redirects to the error page) -- the url should be paypal.com/checkoutnow?....

2. Instead of `return reject(new Error(res.errorText));` can you try `throw new Error(res.errorText);`

**Comment by will8211** [comment]
Well, the popup URL was in fact https://www.sandbox.paypal.com/checkoutnow
Turns out in my enthusiasm to go live, I forgot to empty my browser
cache... :$

Problem solved! Thanks a lot for your time, and quick replies! A+

**Comment by bluepnume** [comment]
Great!
