### ISSUE TITLE
Shipping address validation?

### ISSUE THREAD

**Issue by timomitt2610** [paypal/paypal-checkout#543]
### Description

Hi,

I am using paypal-checkout script from https://www.paypalobjects.com/api/checkout.js and I have following config:

```
paypal.Button.render({
    env: 'sandbox',
    client: {
        sandbox: 'AZDxjDScFpQtjWTOUtWKbyN_bDt4OgqaF4eYXlewfBP4-8aqX3PiV8e1GWU6liB2CUXlkA59kJXE7M6R',
        production: '<insert production client id>'
    },
    commit: true,
    payment: function(data, actions) {
        var experience = {
            input_fields: {
                address_override: 1
            }
        };
        var payment = {
            transactions: [{
                amount: {
                    total: '10.00',
                    currency: 'EUR',
                },
                item_list: {
                    shipping_address: address
                }
            }]
        };
        return actions.payment.create({ payment: payment, experience: experience });
    },

    // onAuthorize() is called when the buyer approves the payment
    onAuthorize: function(data, actions) {

        // Make a call to the REST api to execute the payment
        return actions.payment.execute().then(function() {
            window.alert('Payment Complete!');
        });
    }
}, '#paypal-button-container');
```

When I set address object as follows, it works fine and directs to checkout where shipping address is set accordingly: [Screenshot](https://i.gyazo.com/09db91ae8173185646cede2cbfcfcae9.png)
```
 var address = {
 	recipient_name: 'John Maverick',
 	line1: 'Random address 1',
 	city: 'San Jose',
 	state: 'CA',
 	postal_code: '95131',
 	country_code: 'US'
 };
```

But when I change address variable to following, it results in: [Screenshot](https://i.gyazo.com/7738246c1f009fa613ad80029ea90b7e.png)
```
var address = {
	recipient_name: 'John Maverick',
	line1: 'Random address 1',
	city: 'Tallinn',
	state: 'Harjumaa',
	postal_code: '10115',
	country_code: 'EE'
};
```
Although second address is just as valid as the first one (city, state, postcode and country code match), it does not get the same result. I used this link for testing: https://developer.paypal.com/demo/checkout/#/pattern/client

Is this some kind of validation issue? If so, is it possible to turn off the validating function?

If I log in to shop account, I can't see any restrictions that may be blocking payments from outside of US. Here are the settings: [Screenshot](https://i.gyazo.com/c2f310cfe7ccfcd3e73590fbb417709f.png)

### Steps to reproduce

Copy the code from above to https://developer.paypal.com/demo/checkout/#/pattern/client

### Affected browsers

Probably not a browser specific issue.
- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge
- [x] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Thanks for the report. I think somewhere cross-border shipping must be disabled. Can you please raise a ticket with paypal developer support? https://developer.paypal.com/support/
