### ISSUE TITLE
Login/Password input fields work wrong in Facebook Messenger WebView 

### ISSUE THREAD

**Issue by YaTree** [paypal/paypal-checkout#544]
### Description

Hello there.

I am not sure to whom I should address question about this problem.
I try to integrate express checkout "Buy now" button in a facebook messenger bot. 
In my case (I dont live in USA) to integrate the button I have to use webview.

When I use browser on PC - everything is fine, but when I try to do the same with phone I got issues.
1) Login/password inputs are not shown
2) Sometimes inputs are shown but I can write nothing inside. 

I also tried to use "ready buttons" that is generated from PayPal dashboard and got almost the same problem with inputs. 

[Link](https://smartquestfbbot.herokuapp.com/checkout?amount=100&currency=ILS)
The link is opened inside FB-bot in webview. 
To reproduce the issue inside fb-messenger I have to add there "testers", because bot is not released.

**HTML Code**
```

<html>
<head>
    <title>Purchase</title>
</head>
<script src="https://www.paypalobjects.com/api/checkout.js"></script>

<body>

<div>
    <h4>Express </h4>
    <div id="paypal-button-container"></div>
</div>

<div>
    <h4>Pregenaration Button</h4>
    <form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post" target="_top">
        <input type="hidden" name="cmd" value="_s-xclick">
        <input type="hidden" name="hosted_button_id" value="CJSSJYVZEWYXE">
        <input type="image" src="https://www.sandbox.paypal.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
        <img alt="" border="0" src="https://www.sandbox.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1">
    </form>
</div>

</body>


<script>

    // Render the PayPal button

    paypal.Button.render({

        // Set your environment

        env: 'sandbox', // sandbox | production

        // Specify the style of the button

        style: {
            label: 'buynow',
            fundingicons: true, // optional
            branding: true, // optional
            size: 'responsive', // small | medium | large | responsive
            shape: 'rect',   // pill | rect
            color: 'gold'   // gold | blue | silve | black
        },

        // PayPal Client IDs - replace with your own
        // Create a PayPal app: https://developer.paypal.com/developer/applications/create

        client: {
            sandbox:    'AZDxjDScFpQtjWTOUtWKbyN_bDt4OgqaF4eYXlewfBP4-8aqX3PiV8e1GWU6liB2CUXlkA59kJXE7M6R',
            production: '<insert production client id>'
        },

        // Wait for the PayPal button to be clicked

        payment: function (data, actions) {
            return actions.payment.create({
                transactions: [
                    {
                        amount: {total: '{{amount}}', currency: '{{currency}}'}
                    }
                ]
            });
        },

        // Wait for the payment to be authorized by the customer

        onAuthorize: function (data, actions) {
            return actions.payment.execute().then(function () {
                window.alert('Payment Complete!');
              
            });
        }

    }, '#paypal-button-container');

</script>
</html>
```

**This is how looks page with action from "checkout.js"** 
![photo5821280527494261516](https://user-images.githubusercontent.com/13405431/33229344-ba6ef744-d1d5-11e7-8d2b-37d22ad6fdd1.jpg)

**This is how looks page with action with button that was generated in paypal dashboard** 
![photo5821280527494261517](https://user-images.githubusercontent.com/13405431/33229345-ba8ebe44-d1d5-11e7-88bb-df28d5ca4c11.jpg)
 

Please provide a short description of the issue here, along with:

- Screenshots or videos that show the issue
- Your code
- The `paypal.version` from your browser console
- The exact browser version
- A link to your page with the issue, if possible
- All console logs during the time of the issue, especially error messages
- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
- Does the issue occur consistently, or intermittently?

### Steps to reproduce

Please provide each individual step required to reproduce the issue

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Thanks for the report! I've looked in the devs on our login team, we'll take a look.

**Comment by YaTree** [comment]
Hey there.
Any news?

**Comment by bluepnume** [comment]
Do you see the same issue in production mode?
