### ISSUE TITLE
How to change PayPal button background to none when using paypal.Button.driver() method?

### ISSUE THREAD

**Issue by czelusniakdawid** [paypal/paypal-checkout#545]
Hello,

I am using `paypal.Button.driver()` to generate PayPal button. I know that when using `paypal.Button.render()` I can use `style` object, but is there any similar functionality when using `paypal.Button.driver()`?

I have tried to change background manually with CSS, but with no successfull result:
https://codepen.io/anon/pen/MOBjXp

Thank you for help!

**Comment by czelusniakdawid** [comment]
OK, I checked, we can also define `style` when using `paypal.Button.driver()`, but there are only a few predefined colors like: `gold | blue | silver | black`. Can we use custom colors on PayPal button or set `background: none` ?

**Comment by bluepnume** [comment]
Hi! Right now customization/style options are limited to what's in this doc: https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/customize-button/

**Comment by czelusniakdawid** [comment]
Thank you for your answer!
