### ISSUE TITLE
PayPal payment options are invalid

### ISSUE THREAD

**Issue by Barabasse88** [paypal/paypal-checkout#546]
Hello,

I have the following errors when I click on the Paypal Pay button:

Error: Error: PayPal payment options are invalid. at Object._RECEIVE_MESSAGE_TYPE. (anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:2936:122) at receiveMessage (https://www.paypalobjects.com/api/checkout .js: 2835: 77) at messageListener (https://www.paypalobjects.com/api/checkout.js:2856:13)

Can you explain to me how to solve these errors?

In addition when I make payment by credit card, I refresh the page and I have a "Paypal Error" that appears ...

Thank you a lot for your help.

Have a nice day.

Regards.

**Comment by bluepnume** [comment]
Can you please share your code?

**Comment by Barabasse88** [comment]
Could you tell me where I find the code in my site prestashop website please?

**Comment by bluepnume** [comment]
How did you enable the PayPal button? I'm not totally familiar with prestashop

**Comment by bluepnume** [comment]
Maybe you could point me to your site so I can try it?

**Comment by Barabasse88** [comment]
Yes, of course : https://hubert-boutique.com

For enable PayPal Button, I active a modul from back office of Website prestashop

**Comment by bluepnume** [comment]
Here's the error I see:

```{"error":{"errorName":"AUTHORIZATION_ERROR","errorMessage":"Authorization error --- REFUSED_MARK_REF_TXN_NOT_ENABLED:This merchant account is not permitted to create Merchant Initiated Billing Agreement","debugId":"653493b0b879e, 653493b0b879e","paypalHttpStatus":403}}```

Looks like you're set up using Braintree -- you should probably talk to Braintree support to help get your account enabled for billing agreements.
