### ISSUE TITLE
ppxo_pptm_script_error in wechat browser

### ISSUE THREAD

**Issue by littleWeber** [paypal/paypal-checkout#548]
### Description
![qq 20171128101817](https://user-images.githubusercontent.com/17610895/33299718-db6e8514-d427-11e7-95b5-a12f07491e08.png)

the picture show the error is appeared when open my web page in wechat on my iphone,but use browser to open this web page is ok,by the way,in android phone also no problem, please look at this error,thank you~

paypal.version is 4.0.x

**Comment by bluepnume** [comment]
Do you see any specific problems, or just the error message?

**Comment by bluepnume** [comment]
@littleWeber can you elaborate on my question?

@brunops I don't see the cause here -- but I wonder if there's a CSP rule for paypalobjects but not paypal... maybe we could log a little less noisily for pptm failures given that it's a best-effort component in most cases.

**Comment by littleWeber** [comment]
@benmurden i had solved this problem, but wechat app maybe forbid the iframe tag shown, anyway, thank you very much.

**Comment by alfredrumss** [comment]
I have the same problem... did you solve this?

**Comment by bluepnume** [comment]
@alfredrumss -- can you share the specific error you get?

**Comment by tinyjacky** [comment]
<img width="509" alt="screenshot 2018-02-12 17 35 20" src="https://user-images.githubusercontent.com/8316315/36131704-1cab83e8-10ae-11e8-9858-7a7792c9ddc5.png">
I'm having similar issues as well...

**Comment by brunops** [comment]
@bluepnume my guess would be it's related to CSP as well, don't see a problem with logging it less noisily

@alfredrumss / @tinyjacky do you see the error also in WeChat or somewhere else?

**Comment by tinyjacky** [comment]
@brunops Yes. Wechat in-app browsers in iOS. Saw the log via Wechat's [debugging tools](http://open.wechat.com/cgi-bin/newreadtemplate?t=overseas_open/docs/oa/web/debug-tools)

**Comment by galvanu** [comment]
Wee are facing the same issue on our website. Can you please explain what is the issue? there is any solution? workaround?
Thanks

**Comment by brunops** [comment]
Thanks for the feedback, will look into this tonight.

@bluepnume feel free to solve it before though

**Comment by jinixx** [comment]
@littleWeber did you successfully make the button appear in wechat browser? 

@bluepnume this problem is still there, and the button does not appear, when inspecting on Wechat Dev tools, the contents of iFrame appears to be not loaded.

**Comment by scaryterry** [comment]
This happens to me as well in Chrome. 
Although I do get the error, the button shows up just fine and the checkout flow works as intended.
Something that may be of help, by disabling the Ublock Origin extension on Chrome, the error goes away
