### ISSUE TITLE
Cannot instantiate inside node, breaks server side react rendering

### ISSUE THREAD

**Issue by develerltd** [paypal/paypal-checkout#551]
When we try to run a server side rendered react route via node, and that route contains paypal-checkout code - the node server fails to start due to an undefined window. Then due to required for userAgent, location.href in post-robot, and finally:

\node_modules\paypal-checkout\dist\checkout.lib.js:8182
                if (!global) throw new Error("Could not get local global");

**Comment by bluepnume** [comment]
Can you guard this for now with a `(typeof window !== 'undefined') && <PayPalButton ... />`?
