### ISSUE TITLE
withCredentials in XHR

### ISSUE THREAD

**Issue by tobsn** [paypal/paypal-checkout#552]
I need to send a cross domain request from frontend to different backend to set the token. 
I see that paypal.request.post() doesn't send the correct cookies which normally means it needs to have withCredentials: true set in the XHR object. I looked into the source but couldn't find a switch for it - is there any way to make this happening?

Thank you!

**Comment by tobsn** [comment]
@bluepnume yeah I figured out i can just use jquery to get the payment id and return it - would still be nice to just do it directly :D, simple crossDomain: true or something

**Comment by bluepnume** [comment]
Totally agree.

**Comment by bluepnume** [comment]
Closing this as we'll likely be removing support for `paypal.request.post` in future versions. I would recommend making use of more fully-featured ajax libraries to achieve this.
