### ISSUE TITLE
Stores/Checkout Page embedded in iFrames

### ISSUE THREAD

**Issue by ballawzi-pp** [paypal/paypal-checkout#553]
### Description

Problem statement: when the PayPal checkout jsv4 tries to render the checkout experience from within an iFrame, it throws a "unable to delegate rendering" error and closes the pop-up. 

There are 2 use cases to consider: 

**Use Case 1** being the merchant has ownership of the parent page. eg. for security reasons the merchant hosts the payment page on another domain. (included for completeness; aware of existing solve by including js in parent) 

**Use Case 2** being the merchant doesn't have ownership of the parent page. eg. Facebook embedded store. (unable to include js in parent) 

The following is quick demo: https://borma6.wixsite.com/testpp 

### Affected browsers

- [x ] Chrome
- [x ] Safari
- [x ] Firefox
- [x ] Edge
- [x ] IE
- [x ] Chrome Mobile/Tablet
- [x ] Safari Mobile/Tablet
- [x ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
This is now resolved.
