### ISSUE TITLE
Incorrect text "You’ll be able to review your order before you complete your purchase"

### ISSUE THREAD

**Issue by mobitar** [paypal/paypal-checkout#554]
Using the v3 checkout vault flow for recurring payments, the window shows "You’ll be able to review your order before you complete your purchase" but this is not the case. After I hit Agree & Continue, the window closes, I get a nonce, and charge the user successfully.

<img width="451" alt="screen shot 2017-12-07 at 1 14 19 pm" src="https://user-images.githubusercontent.com/3277844/33734644-b4ba0f60-db52-11e7-9e49-31f7c5e84ca8.png">

See this thread for more: https://github.com/braintree/braintree-web/issues/340#issuecomment-350068629

**Comment by bluepnume** [comment]
Please pass `commit: true` when calling `paypal.Button.render()`
