### ISSUE TITLE
TypeError: Cannot read property 'post' of undefined

### ISSUE THREAD

**Issue by shime** [paypal/paypal-checkout#555]
I'm trying to set up the client for the Checkout API as specified in the documentation here: https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/execute-payment/

I'm trying to execute the payment on the server but the client errors out with the message: `TypeError: Cannot read property 'post' of undefined`.

This is coming from an `onAuthorize` method here: 

```javascript
<div id="paypal-button"></div>

<script src="https://www.paypalobjects.com/api/checkout.js"></script>

<script>
  paypal.Button.render({
      payment: function(data, actions) {
        return actions.request.post('/my-api/create-payment')
          .then(function(res) { return res.id; });
      },

      onAuthorize: function(data, actions) {
        return actions.request.post('/my-api/execute-payment', {
          paymentID: data.paymentID,
          payerID: data.payerID
        }).then(function(res) {
          console.log('Payment complete!')
        });
      }
  }, '#paypal-button');
</script>

```

Looks like the `onAuthorize` doesn't get `request` property for the `actions` param. 

Can you give me a workaround? This is a blocker for me.

**Comment by bluepnume** [comment]
Thanks for the heads up -- this is a bug. For now can you use `paypal.request.post`

**Comment by shime** [comment]
Wow, thank you for the lightning fast response. ⚡ That fixes it, closing.

**Comment by bluepnume** [comment]
No prob! I'm going to keep this open to track the original issue.

**Comment by bluepnume** [comment]
Added fix for the next release.
