### ISSUE TITLE
failed to npm install paypal-checkout 

### ISSUE THREAD

**Issue by orangemi** [paypal/paypal-checkout#556]
### Description
When I process `npm install --save paypal-checkout`. It throws error about `braintree-paypal-client-config`. I think it should be a  `devDependecy` for the repo.

### Steps to reproduce
```
npm install --save paypal-checkout
> braintree-paypal-client-config@1.0.2 postinstall /Users/Orange/projects/teambition/pay-ui/node_modules/braintree-paypal-client-config
> flow-typed install

sh: flow-typed: command not found
npm WARN demo@0.3.6 No description
npm WARN demo@0.3.6 No repository field.
npm WARN demo@0.3.6 No license field.

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! braintree-paypal-client-config@1.0.2 postinstall: `flow-typed install`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the braintree-paypal-client-config@1.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Environment
Node 9.2.0 MacOS 10.13.1

### Note
It works with previous version of paypal-checkout@4.0.89

**Comment by MrBlaise** [comment]
Same here:

```
error /Users/xxx/node_modules/braintree-paypal-client-config: Command failed.
Exit code: 127
Command: flow-typed install
Arguments: 
```

**Comment by zlk89** [comment]
same, it seems it is caused by https://github.com/paypal/paypal-checkout/commit/62db93fd0e86bdc5ba8c9a0ae0cbdc6f96921b07

**Comment by bluepnume** [comment]
Thanks for the heads-up all. I'll have a fixed published for this shortly.

**Comment by bluepnume** [comment]
This should be resolved -- please let me know if you continue to see the same issue. Thanks again!
