### ISSUE TITLE
[Request] Open express checkout in new tab / window if popup fails to load

### ISSUE THREAD

**Issue by bryancboyd** [paypal/paypal-checkout#559]
### Description

Certain antivirus software (ex. Kaspersky Smart Money) require sites where payment info is submitted to be executed in a "protected browser" sandbox.  Customers with this software have reported to me that they see the following error after clicking the paypal button, where the popup opens temporarily then immediately closes:  `Request to post https://www.paypal.com/v1/oauth2/token failed with 499 error.  Correlation ID = unknown`

I've managed to catch the error in order to display an alert to the user, like this:

```
<paypal.Button.react
  ...
  payment={(resolve, reject) => {
    return paypal.rest.payment.create(env, client, {
      transactions: [...]
    }).then(
      result => resolve(result),
      error => {
        alert('Something went wrong with the payment process.');
        reject(error);
      }
    )
  }}
  ...
/>
```

What I'd prefer is to, after catching an error, open the express checkout flow in a new window (or tab) so that users can complete the checkout without messing with their antivirus or security software.  Is this possible?

**Comment by bluepnume** [comment]
Hi @bryancboyd -- the problem here is, the api.paypal.com request to generate the payment id is failing. So at this point, there's not even a token we can use to redirect to paypal.com with. 

Honestly, the fact that Kaspersky is blocking legitimate requests from the browser to paypal.com is extremely worrying to me, and seems like it could potentially cause even more problems further through the checkout app. Have you tried raising a ticket with the Kaspersky team to try to unblock this?

**Comment by bryancboyd** [comment]
Thanks for the quick response @bluepnume!  From what I recall from looking at a user's session last week (I don't have Kaspersky myself and haven't attempted to reproduce with it) the Chrome debugger showed the `POST v1/oath2/token` API call responding with some HTML from Kaspersky saying "Now opening a protected browser..."

It looks like Kaspersky (and others, similar behavior was reported with Norton) has a blacklist of payment websites like paypal.com, and intercepts the response of APIs to these routes with HTML source that will open a new window and call the API again.  It's just that in this case, the `/token` API is called asynchronously.

Have you seen anyone else report this?  I'd assume this would be a common issue with express checkout and antivirus software.

**Comment by bluepnume** [comment]
I guess Kaspersky is assuming the `/v1/oauth2/token` call is a full page request, and it's hijacking that request to return its own html and break the page out into its own protected browser. The thing is though, this is an ajax POST request, and it's expecting json to be returned. So this fundamentally breaks what the checkout.js script is trying to do.

I've heard of similar things in the past, but this is the first issue that's been raised for Kaspersky. I don't see a lot that can be done on our side to resolve this, so I'd recommend raising a ticket with Kaspersky to blacklist this behavior for calls to `api.paypal.com`. I don't know if anything else will be broken though, even if the popup successfully opens.

**Comment by bryancboyd** [comment]
Thanks, I'll do that.  Is there an alternate checkout flow that is similar to express, but can be done entirely from a www.paypal.com domain?  Something like a paypal.com route where I can pass the production token and transactions array in the URL, but have the entire checkout flow from that point take place in paypal's domain?

**Comment by bluepnume** [comment]
Sorry for the late response -- no, there's no way to get around the api.paypal.com calls. This will definitely need to be fixed on the Kaspersky side.
