### ISSUE TITLE
PayPal button not showing

### ISSUE THREAD

**Issue by coderintherye** [paypal/paypal-checkout#560]
Going to come back and report more as I gather details, but many users are writing in today telling us the paypal button is not showing up. Was there a release today of the express checkout code?

Just want to get this on the radar in case something changed with today's release that we can check against to see if it may have caused the issue for these users.

Please provide a short description of the issue here, along with:
PayPal button doesn't show

- The exact browser version
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

- Screenshots or videos that show the issue
![zlg9ccrwtieirl1jzrimmg](https://user-images.githubusercontent.com/313805/34180246-d4820eaa-e4c2-11e7-9882-271e4193ef5a.png)

- The `paypal.version` from your browser console
4.0.169

- A link to your page with the issue, if possible
www.kiva.org/lend, choose loan, checkout, happens on review & pay page

- Does the issue occur consistently, or intermittently?
Consistently for users who wrote in

### Affected browsers
Chrome on Windows 7

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Thanks for the report. This is not a known issue, and there hasn't been a release in the last 4 days. Are all the people seeing this problem using chrome? And are there any console errors?

**Comment by coderintherye** [comment]
so far the reports were with chrome. However, we haven't been able to reproduce it, so for now we're going to assume some temporary blip. I'll close this out and then if we get more reports I'll come back and fill in with more details. thanks @bluepnume
