### ISSUE TITLE
Express checkout on my sandbox throwing error on payment.execute()

### ISSUE THREAD

**Issue by MuneeswaranA** [paypal/paypal-checkout#561]
Express checkout on my sandbox throwing error

I click on the PayPal Button, enter my login my credentials and hit the "Pay Now" button and I am getting this error:

Error Message:
Payment could not be executed
    at https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js?build=2.0.2_20171113102955322.unx:4230:35
    at https://www.paypalobjects.com/api/checkout.js:8953:46
    at ZalgoPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:8967:27)
    at ZalgoPromise.reject (https://www.paypalobjects.com/api/checkout.js:8927:22)
    at https://www.paypalobjects.com/api/checkout.js:8960:91
    at ZalgoPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:8967:27)
    at ZalgoPromise.reject (https://www.paypalobjects.com/api/checkout.js:8927:22)
    at https://www.paypalobjects.com/api/checkout.js:8949:45
    at ZalgoPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:8967:27)
    at ZalgoPromise.reject (https://www.paypalobjects.com/api/checkout.js:8927:22)

![paypal error](https://user-images.githubusercontent.com/33286059/34206796-02897f72-e5ae-11e7-8254-e5970ef8a8e6.png)

Response: 
{"ack":"contingency","contingency":"INTERNAL_SERVICE_ERROR","meta":{"calc":"8d303eacb056a","rlog":"%2F%2Bfgnb4E9JlKa2t8At%2BmOxuxFBbNZCAFs5HlTVI7QFJU2XfIzNUqgWQE%2BZSt%2FeWEmlR8gpjHW3xPOpS2y4mhMQ_16073d490db"},"server":"mMiwe3mnifdw2jd2t2DyPyaN6-CObm_X7KtbsXYAzbCmP_SISyaxge0EgonE2KhgvdgjZ5zco-4SY_hFXqag8JDB1fh-O6YhXboCrUGSHFnq63JvefzCVkdEsAwKWrsYHjJmLnRsXd-SWX5FExII8DOVs3E0PqBL3H81O0KpewA6eJPkH92kLjuWB4b7CZFAMyQtTBgYHrKgcAcbAW0fR6JPBw_BTbAGyZLhUqmrw04z37c7oc2TLxLNov9vTUu2"}

**Comment by thisisalexis** [comment]
Hello! Did you solve  this issue? I'm having exactly the same problem in my application since yesterday.

**Comment by thisisalexis** [comment]
Hello, I was having the same issue, but it was not a problem with the API itself, but with the request I was sending to it.

In my case, in the payment object, in the transactions array, I was sending the invoice_number attribute with the same number of invoice. When I changed the invoice_number attribute's value to a new one, it worked fine. As I could see, the invoice number must be unique for every transaction or payment in Paypal.

Anyway, I think the service's error response should be more explicit to help us determine this kind of errors.

**Comment by bluepnume** [comment]
Did you confirm if the problem was `invoice_number`?
