### ISSUE TITLE
Cancel Url Populates a link in "Cancel and return to [Merchant Name]" even though it doesn't actually use the link

### ISSUE THREAD

**Issue by crookedneighbor** [paypal/paypal-checkout#562]
### Description

This is pretty benign, but in Braintree integrations in particular, we pass `example.com` as both the return and cancel urls (since it is not used and we have no way of collecting that data from the merchant). This makes for a strange experience for the merchant and customer as they hover over the cancel link and see their browser say it will direct them to example.com.

![example](https://user-images.githubusercontent.com/2916945/34260132-6809e4e6-e62a-11e7-87cd-790ea352836a.png)

**Comment by crookedneighbor** [comment]
Should be enough to change the link element to something other than a link, especially since the normal link behavior is intercepted anyway. Or, simply to set the href value to a PayPal url (or `#` or `javascript:void(0)` or whatever)

```html
<a track-link="cancel_and_return_to_merchant" href="[MERCHANT-PASSED-CANCEL-URL]" ng-click="cancelRedirect($event)" role="button" id="cancelLink" ng-hide="hideReturnCancelUrl()" aria-hidden="false">
  <span ng-bind-html="merchant ? content('base.cancelUrl', { merchantName: merchant, modelName: 'merchant' }) : content('common.cancelAndReturnToMerchant')" class="ng-binding">Cancel and return to [MERCHANT-NAME]</span>
</a>
```

**Comment by bluepnume** [comment]
Agreed with your solve. Thanks for the report! Will have something out to fix this in early jan.

**Comment by lacimarsik** [comment]
Hi all, we experienced the same issue recently with a customer. This issue can also confuse the "Open in new tab" function, and subsequently, we had a report of bad user experience on iOS web browsers.

Is it possible to look at voiding those values? Thanks for looking again.

**Comment by lacimarsik** [comment]
We also received screenshots with proofs that the redirection to `example.com` can happen after the checkout. I can provide some session details privately, if necessary.

**Comment by stevethatcodes** [comment]
@lacimarsik Did you ever get a resolution on this? We are noticing this happen as of today with no deployments to our site. This sounds like something between Braintree and PayPal?

**Comment by TrusPRO** [comment]
@stevethatcodes I had the same issue yesterday, only on sandbox and it's fix this morning. Guess it's on paypal side !

**Comment by bluepnume** [comment]
This is solved by the new payments sdk, in pilot. Return and cancel urls are now optional, and not used by the new integration.
