### ISSUE TITLE
Clicking on cancel and return link in the guest checkout page redirect to example.com instead of merchant website 

### ISSUE THREAD

**Issue by umulla** [paypal/paypal-checkout#564]
### Description

Please provide a short description of the issue here, along with:
1) The pop up seems to trigger the oncancel event as soon we click the PayPal button
2) The pop up seems to trigger a warning on the browser
3) The pop up itself is opening as an iframe
4) Clicking on Pay with debit or credit card closes the pop up and opens the guest checkout screen in full page 
5) Clicking on cancel and return link inside the pop up on the guest checkout page is closing the pop up and redirecting to example.com/token=xxx instead of the merchant website

- Screenshots or videos that show the issue: Attached
- Your code - live at http://www.campingworld.com, Integration is using EC via BT SDK
- The `paypal.version` from your browser console -  4.0.171
- The exact browser version - Latest Firefox with inbuilt pop up blocker turned on
- A link to your page with the issue, if possible - http://www.campingworld.com
- All console logs during the time of the issue, especially error messages
- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)? - No
- Does the issue occur consistently, or intermittently? Consistently

### Steps to reproduce
1) Go to http://www.campingworld.com using latest firefox browser on Mac. 
2) add something to cart and click on the PayPal button
3) click on Pay with debit or credit card 
4) click on cancel and return link in the bottom of the PayPal window

Please provide each individual step required to reproduce the issue

### Affected browsers
[Mozill_bug_Session.zip](https://github.com/paypal/paypal-checkout/files/1579794/Mozill_bug_Session.zip)

- [ ] Chrome
- [ ] Safari
- [x] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

[Mozill_bug_Session.zip](https://github.com/paypal/paypal-checkout/files/1579811/Mozill_bug_Session.zip)

**Comment by bluepnume** [comment]
Thanks for the detailed report!

> 1. The pop up seems to trigger the oncancel event as soon we click the PayPal button

Can you elaborate on this? Do you mean clicking on the the original PayPal button?

> 2. The pop up seems to trigger a warning on the browser
> 3. The pop up itself is opening as an iframe

This seems to be because of a popup blocker. This is expected when the script is unable to open a popup window.

> 4. Clicking on Pay with debit or credit card closes the pop up and opens the guest checkout screen in full page

This is a bug. Should be fairly straightforward to fix as it seems to happen consistently.

> 5. Clicking on cancel and return link inside the pop up on the guest checkout page is closing the pop up and redirecting to example.com/token=xxx instead of the merchant website

This is a result of the fact that it's going to full-page mode. So if we can fix 4, this will be fixed too.
