### ISSUE TITLE
Not working with JSF

### ISSUE THREAD

**Issue by Theocom** [paypal/paypal-checkout#568]
Checkout js library cannot load - page creation breaks.

<script src="https://www.paypalobjects.com/api/checkout.js" data-version-4></script>

I get:
javax.faces.view.facelets.FaceletException: Error Parsing /index.xhtml: Error Traced[line: 218] Attribute name "data-version-4" associated with an element type "script" must be followed by the ' = ' character.
	at com.sun.faces.facelets.compiler.SAXCompiler.doCompile(SAXCompiler.java:487)

**Comment by bluepnume** [comment]
You can safely remove `data-version-4`
