### ISSUE TITLE
Incorrect amount showing up for recurring payments in mini browser window

### ISSUE THREAD

**Issue by hdpinto** [paypal/paypal-checkout#569]
### Description

We're trying to update an older checkout flow to the new express-checkout using checkout.js, and it works for the most part but now our recurring donations seem to show an amount of `$0.01` on the mini browser window regardless of what the donor actually selected.

See screenshot:
![screenshot](https://puu.sh/ySM6N/8f1b83e48e.png)

Our implementation closely mirrors what is already on developer.paypal.com/demo/checkout for the server-side REST flow (_which is notably missing recurring transactions altogether_), this issue occurs consistently, and on every supported browser that we've tested so far.

Script Version: `4.0.171`
Sample Form: https://beta.canadahelps.com/en/dn/m/22536/donation

### Steps to reproduce
 
- Go to the provided page above
- Select monthly, and any donation amount
- Click next and proceed to fill in dummy information for the user info fields
- Click next and select PayPal as the payment option, and click the blue PayPal button
- Login to your sandbox account and notice that the amount appears at `$0.01`
- If you were to click "Agree & Pay", we'd see the correct amount debited from your account on our end.

### Affected browsers

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge
- [x] IE
- [x] Chrome Mobile/Tablet
- [x] Safari Mobile/Tablet

### Other

I've also submitted this question in PayPal Community [here](https://www.paypal-community.com/t5/About-Payments/Checkout-js-Express-Checkout-recurring-payment-amount-shows/m-p/1399685), I'm not sure if this is an implementation issue, a known and expected behavior, or if it's an actual bug somewhere.

**Comment by bluepnume** [comment]
Hi,

Which API are you calling to create the PayPal token? And can you check what amount you're sending there?

Thanks!

**Comment by hdpinto** [comment]
For anyone else having this issue, here's what ended up causing the issue:

We had a server that made the call to PayPal, this server's code was pretty old and created by a developer no longer working with us as far as I could tell. Apparently, there was a requirement in the past that a minimum amount of `0.01` be sent in to the PayPal API regardless of the transaction type, even if it was just a subscription.

_I can't verify this requirement ever existed_, this is just what one of the maintainers of this code told me. We changed the code to send in an amount of `0` and this seemingly fixed the problem. What I don't understand is how this ever worked, our previous redirect-based flow showed no amount, and still shows no amount, even if we send in `0.01`.

May this help whoever ends up having this problem in the future. This issue can safely be closed.
