### ISSUE TITLE
Paypal Express Button hangs at Image Placeholder : Internet Explorer 10.0.35

### ISSUE THREAD

**Issue by simonaberry** [paypal/paypal-checkout#570]
We have the express checkout button working well on all browsers, **_except_** for a specific build of IE (10.0.35). The issue also **does occur on the test site** (https://developer.paypal.com/demo/checkout). The image placeholder/pre-render loads ok, but if you click on the image (it never resolves into a real button, as far as we can tell) nothing ever happens.

- script src is 'https://www.paypalobjects.com/api/checkout.js'
- Paypal Version 4.0.171

**console warnings on click :**
`ie_meta_compatability_header_missing{"message":"Drop tag:  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">"`
`ppxo_button_pre_template_click {..}`
_suggest that the script hasn't loaded past the image placeholder_

**network analysis :** 
request to  https://www.sandbox.paypal.com/webapps/hermes/button -> (aborted)

error occurs in IE10.0.35 (available from crossbrowsertesting.com)
error does not occur in 10.0.59 (available from browserstack.com)

error happens all the time, consistently

**Comment by bluepnume** [comment]
Do you see the same issue in production mode?

**Comment by simonaberry** [comment]
Unfortunately we dont have a Live Account to test against. Perhaps someone else is able to do a quick check (happy to share the crossbrowsertesting account details to perform the test)

**Comment by tobsn** [comment]
We're seeing this too - it's rare but it's exactly as described.

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299

7 users out of thousands but all 7 with this exact UA throwing the exact same exception each time.
