### ISSUE TITLE
Blank page after clicking on checkout button for the second time

### ISSUE THREAD

**Issue by iranianpep** [paypal/paypal-checkout#571]
### Description

Encountered this issue on Facebook App web view when clicked on the checkout button, then clicked on "Cancel and return" link and finally when clicked on the checkout button again a blank page is displayed.

Could reproduce the issue on two iPhone devices running iOS 11 even with the demo page (https://developer.paypal.com/demo/checkout/#/pattern/server).

FYI, on other devices and browsers including Facebook App on Android it is working fine.

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [x] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Fix is in for next release.

**Comment by iranianpep** [comment]
Cool, Thanks.

**Comment by craftpip** [comment]
Is this fix out?, I'm facing the same problem.

**Comment by jasperck** [comment]
Hi, there! Does this issue been fixed, cause I still faced with blank page while opening the via the button in demo link. It could be reproduced with iOS 11 and Line WebView🙏
