### ISSUE TITLE
Integrate Paypal in Angular 2 without Paypal Button

### ISSUE THREAD

**Issue by ThakkarKhushbu** [paypal/paypal-checkout#572]
### Description

Please provide a short description of the issue here, along with:
Need paypal integration in angular 2 project , but don't want paypal button .
on click of custom button it should redirect to paypal and user can make payment via paypal

- Screenshots or videos that show the issue
- Your code
- The `paypal.version` from your browser console
- The exact browser version
- A link to your page with the issue, if possible
- All console logs during the time of the issue, especially error messages
- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
- Does the issue occur consistently, or intermittently?

### Steps to reproduce

Please provide each individual step required to reproduce the issue

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Hi, apologies but that is not something we plan to support as part of `checkout.js`.
