### ISSUE TITLE
SSL Cert Issue?

### ISSUE THREAD

**Issue by Hermities** [paypal/paypal-checkout#573]
![image](https://user-images.githubusercontent.com/22338421/34856121-97d8a0f4-f700-11e7-8ec2-a14651e7ec86.png)

### Affected browsers

- [ X Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by gopchi** [comment]
Same issue here. Also affects Facebook in app browser.

**Comment by bluepnume** [comment]
@trainerbill did you ever find anything on this?

**Comment by trainerbill** [comment]
it won't affect your integration and will be fixed internally in the coming months.
