### ISSUE TITLE
Line item details Missing when using Braintree option

### ISSUE THREAD

**Issue by Arvind6353** [paypal/paypal-checkout#579]
### Description
Hi,

Is there a way to pass in the line item details when using braintree option using jsv4.
I am able to see the line item details in the paypal checkout screen when am not using braintree as an option.

When using client / server side integrations with jsv4 , passing the line items in the create payment flow works . 
For example : 
transactions: [
    {
      amount:
      {
        total: "4.00",
        currency: "USD",
        details:
        {
          subtotal: "2.00",
          shipping: "1.00",
          tax: "2.00",
          shipping_discount: "-1.00"
        }
      },
      **item_list:
      {
        items: [
        {
          quantity: "1",
          name: "item 1",
          price: "1",
          currency: "USD",
          description: "item 1 description",
          tax: "1"
        },
        {
          quantity: "1",
          name: "item 2",
          price: "1",
          currency: "USD",
          description: "item 2 description",
          tax: "1"
        }]
      },
      description: "The payment transaction description.",
      custom: "merchant custom data"**
    }]

But I am not able to pass in the line item details when using braintree option with jsv4.

Is the line item details option supported in braintree ?

**Comment by ShaneSkuse** [comment]
Yes, I too have been scratching my head at this... The paypalCheckoutInstance.createPayment options seem limited! What's the best practice/workaround for adding line items with a Braintree client?

**Comment by bluepnume** [comment]
Hi! This would probably be a question best asked to Braintree, unless @crookedneighbor can weigh in if there are any plans to support line items?

**Comment by crookedneighbor** [comment]
Line items are now [supported on the server side](https://developers.braintreepayments.com/reference/request/transaction/sale/ruby#line_items), but it is not yet supported on the client side.

**Comment by ShaneSkuse** [comment]
Thanks guys, I've already implemented line items server side, would of liked to have the details appear on the Paypal client, just to complete the checkout experience. Perhaps a feature request for a future update...

**Comment by crookedneighbor** [comment]
It's on the roadmap, but since the line items can be displayed on the merchant's website underneath the PayPal popup, it's not a high priority at the moment.

**Comment by bluepnume** [comment]
Closing this issue here since no changes needed on checkout.js side.
