### ISSUE TITLE
Paypal Plus support for modern apps?

### ISSUE THREAD

**Issue by AAverin** [paypal/paypal-checkout#580]
### Description

In Europe Paypal provides a service called Paypal Plus. Not sure what would be the correct name in US.
Basically it's a somewhat advanced integration allowing support of additional payment methods like credit/debit cards and so on.

I am looking for a way to integrate Paypal Plus into my React app.
Does this javascript library provide any help with that or I am on my own and have to integrate manually?

**Comment by AAverin** [comment]
At the moment I am referring to this document: https://www.paypalobjects.com/webstatic/de_DE/downloads/PayPal-PLUS-IntegrationGuide.pdf

Although it seems a bit outdated, at least a few years

**Comment by AAverin** [comment]
A similar issue on stackoverflow stating that integration docs for paypal plus (Germany) are outdated:
https://stackoverflow.com/questions/45751754/actual-paypal-plus-integration-guide

**Comment by bluepnume** [comment]
Have you looked at something like our vertical buttons?

https://developer.paypal.com/demo/checkout/#/pattern/vertical
https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/customize-button/#multiple-button-layout

**Comment by AAverin** [comment]
@bluepnume I am using a react driver button at the moment

These vertical buttons is probably what I need, the problem is, I don't understand how to enable this for my paypal account.
Right now I have express checkout button, and when I click on it, paypal UI doesn't allow to "Buy as a guest". It always wants users to login to paypal.
My thought was that Paypal Plus would fix that.

So what confusing is – checking Paypal Plus and it's integration documentation doesn't say if I can or can not use this `paypal-checkout` library. Everything Paypal Plus related points to some outdated ppplus library
```
<script src="https://www.paypalobjects.com/webstatic/ppplus/ppplus.min.js"
type="text/javascript"></script>
```

**Comment by bluepnume** [comment]
Watch this space. We're working on creating a better experience for those credit card buttons.

**Comment by AAverin** [comment]
@bluepnume  I have talked with Paypal support and they said that basic integration is not enough.
They also shared this doc with me: https://developer.paypal.com/docs/paypal-plus/germany/integrate/
The flow I envision:
- I manually create a payment template using Paypal API and get back `approval_url`
- JS library gets a full response object that Paypal API returned + approval_url
- There should be methods to update payment object when, eg. shipping address changes
- Paypal checkout is displayed in an iframe. JS library calls methods to update payment and execute payment when necessary

Do you plan to provide something along these lines any time soon?
