### ISSUE TITLE
paypal.Button cancel loads cancelUrl inside popup

### ISSUE THREAD

**Issue by MagellanT** [paypal/paypal-checkout#581]
### Description

1. I use the Express Checkout via paypal.Button.render()
2. abort with the link at the bottom of the popup

Now instead of closing the popup the CancelUrl will be loaded inside the popup.

I am not sure about the wording but the screenshots are pretty clear:

![paypal1](https://user-images.githubusercontent.com/35726963/35275847-5d775604-0041-11e8-8881-335d2816b487.JPG)
![paypal2](https://user-images.githubusercontent.com/35726963/35275851-6147fd56-0041-11e8-952f-11060c532d3a.JPG)

- The exact browser version
Tested with FireFox and Chrome 63 and FireFox 56.0.2.

- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
No

- Does the issue occur consistently, or intermittently?
Consistently

- Your code

```js
paypal.Button.render({
                    env: 'production',
                    locale: 'de_DE',
                    style: { label: 'checkout', size:  'medium', shape: 'rect', color: 'blue' },
                    commit: false,
                    payment: function () {
                        var CREATE_URL = 'some.php';
                        var send_data = { ... };
                        return paypal.request.post(CREATE_URL, send_data).then(function (res) {
                            //...
                        }).catch(function(err) {
                            alert(err);
                        });
                    },
                    onAuthorize: function (data, actions) {
                        var EXECUTE_URL = 'some.php';
                        var send_data = { ... };
                        return paypal.request.post(EXECUTE_URL, send_data).then(function (res) {
                           //...
                        }).catch(function(err) {
                            alert(err);
                        });
                    }
                }, '#container_id');
```

Inside the PHP Code i tried removing the setCancelUrl() as well as the setExperienceProfileId() but nothing seems to have any effect.

Also tried adding the onCancel: in the Javascript code but this had no effect either.

### Steps to reproduce

1. go to https://www.party-kneipe-bar.com/de
2. put any product into your cart ( = "Warenkorb")
3. click on the yellow cart (top-right corner)
4. click the blue PayPal button
5. click the cancel link ("Abbrechen und zurück zu Party Kneipe Bar")

### Affected browsers

- [x ] Chrome
- [x ] Firefox
- [x ] Chrome Mobile/Tablet
- [x ] Safari Mobile/Tablet

**Comment by bluepnume** [comment]
This should be fixed now -- can you please check?

**Comment by MagellanT** [comment]
Confirmed. Works as expected on desktop as well as mobile.
thx
