### ISSUE TITLE
Option to send PayPal-Client-Metadata-Id on actions.payment.create()

### ISSUE THREAD

**Issue by wiliu** [paypal/paypal-checkout#583]
For raas API integration, PayPal-Client-Metadata-Id is required to pass to Payment API.  Is it possible to support client_metadata_id option during the payment.create() ? e.g. 
`actions.payment.create({
                     meta: {
                              client_metadata_id: 'xyz123'
                        },
....
)
`

**Comment by Arvind6353** [comment]
@bluepnume : Right now , we are able to set one header using  **meta.partner_attribution_id** in **rest.js**
                headers['PayPal-Partner-Attribution-Id'] = meta.partner_attribution_id;
           }

It would be easier to integrate on the client JSv4 if we have an option for adding  **PayPal-Client-Metadata-Id** as a header .

**Comment by TrevorHinesley** [comment]
@bluepnume how do we go about generating a `PayPal-Client-Metadata-Id` with this library? Or is there another way? I'm not seeing anything in PayPal's documentation about where to actually get this identifier from.
