### ISSUE TITLE
How to get the payer info in the data passed to onAuthorize

### ISSUE THREAD

**Issue by octopusinvitro** [paypal/paypal-checkout#585]
### Description

- The `paypal.version` from your browser console 
  `paypal.version "4.0.173"`

- The exact browser version
  `Firefox Quantum 58.0 (64-bit)`
  `Chrome Version 64.0.3282.119 (Official Build) (64-bit)`

- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
  Yes

- Does the issue occur consistently, or intermittently?
  Consistently

I am using Checkout with the [advanced integration](https://github.com/paypal/paypal-checkout/blob/master/docs/button.md#advanced-integration) approach, but when I receive the data in the authorize method it only comes with these keys: `paymentToken`, `orderID`, `intent`, `returnUrl`, `paymentID`, `payerID`.

How can I get name, email and address of the payer? I have searched the API docs for payments searching for a way to, for example, make a get request to the API with the payerID, and I also have searched in the checkout documentation.

Here is my authorize function:

```js
onAuthorize = function(data, actions) {
  var args = {};

  if (data.payer) { // I need this check because no payer is coming in data
    var shipping = data.payer.payer_info.shipping_address;
    args = {
      name: shipping.recipient_name,
      email = data.payer.payer_info.email,
      address_line1: shipping.line1,
      address_city: shipping.city,
      address_state: shipping.state,
      address_zip: shipping.postal_code,
      address_country: shipping.country_code
    };
  }
  // send args to my server
};
```

and these are the fields I pass to create my payment object in the server:
```ruby
        {
          intent: 'sale',
          payer: { payment_method: 'paypal' },
          redirect_urls: my_redirect_urls,
          transactions: [{
            amount: { total: amount, currency: currency }
          }]
        }
```
for which I am using my client id and client secret to identify.

All this is in sandbox mode.

What should I do to have this information coming in the data sent to the `onAuthorize` method?

**Comment by bluepnume** [comment]
Hi -- please see here for details on retrieving all of the payment info: https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/customize-the-checkout-flow/#show-a-confirmation-page
