### ISSUE TITLE
responsive issue (paypal button cutting from bottom).

### ISSUE THREAD

**Issue by logan-dev** [paypal/paypal-checkout#592]
### Description
**paypal button cutting from bottom**

Please provide a short description of the issue here, along with:

- Screenshots or videos that show the issue
![screenshot from 2018-02-07 14 27 50](https://user-images.githubusercontent.com/4978651/35907363-b5fc5e54-0c13-11e8-8b47-36d7c872b81e.png)

htmlCode:
```
<paypal-button  align='center' *ngIf ="duration == 'Monthly'" [props]="{
                  style:style,
                  env: env,
                  client: client,
                  commit: commit,
                  payment: payment,
                  onAuthorize: onAuthorize,
                  onCancel:onCancel
              }"></paypal-button>

```

TypeSriptCode:
``env = 'sandbox';
  client = {
      sandbox:    '',
      production: ''
  };
 
  style= {
    label: 'generic',  // checkout | credit | pay | buynow | generic
    size:  'responsive', // small | medium | large | responsive
    shape: 'rect',
    color: 'blue',
   
       
  };
  commit = true;

**Comment by bluepnume** [comment]
Can you please let me know if you're still facing this issue?
