### ISSUE TITLE
Load the PayPal button also on document.readyState === 'interactive' along with 'complete'

### ISSUE THREAD

**Issue by andreabondi** [paypal/paypal-checkout#593]
### Description

The function [window.payPalCheckoutReady](https://github.com/paypal/paypal-checkout/blob/e19a65eeed1754fcad0318b3ed32e2b17568a35b/src/legacy/ready.js#L13) is only executed once the PayPal script has ascertained that [document.readyState === 'completed'
](https://github.com/paypal/paypal-checkout/blob/f38eb616b86031e26807e83fbd6fc7a90465d288/src/lib/dom.js#L12)

According to the [spec for document.readyState](https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState) the ‘complete` status is only ever set when all sub-resources have completed loading. So it’s completely possible for an image, or unrelated JavaScript file to be still loading, but the page to be otherwise completely usable.

In some context, when loading other resources from CDN that may be blocked in certain parts of the world, the request can be timing out / taking a long time to respond. This will delay document.readyState === ‘completed’ which has the side-effect of making PayPal unusable.

### Proposed solution

Check for `document.readyState === ‘complete’ || ‘interactive’`

**Comment by bluepnume** [comment]
I'm totally ok if you want to pr this in to help with legacy integrations -- but right now we're not recommending that merchants use `window.paypalCheckoutReady` for any new integrations. Instead, if they just call `paypal.Button.render()`, the button will wait until the document (and container element) is ready before it renders.

**Comment by andreabondi** [comment]
Thanks Daniel. I see the document state is checked inside the isDocumentReady function. If this is updated to return true also when the state is interactive, will this affect also new integrations? What do you think of accepting as a ready state also interactive as well as complete?

**Comment by bluepnume** [comment]
Given that this function is only used for old v3 integrations, I'm leaning in the direction of letting it lie for now. Don't want to accidentally break any old integrations with any race conditions, and `paypal.Button.render()` should be much snappier for merchants who want to update.
