### ISSUE TITLE
Response from Paypal credit button 

### ISSUE THREAD

**Issue by maxisam** [paypal/paypal-checkout#594]
We try to have Paypal checkout and Paypal credit side by side base on Paypal's suggestion. 

Here is our implementation.
![image](https://user-images.githubusercontent.com/456807/36053896-4b975224-0db9-11e8-91c0-e9672b334369.png)

The problem shows in above image is we can't distinguish which button is pressed by users base on the response from Paypal. 

Is it possible to have a type property showing which payment method users selected?

**Comment by bluepnume** [comment]
Can you advise on your use case? Is there some specific functionality you want to change based on the button which is pressed?

**Comment by maxisam** [comment]
Well, in above screenshot, you can see we want to let users know which one they selected when they try to revise their payment. Currently, we can't distinguish which button they clicked base on the response.

**Comment by bluepnume** [comment]
Got it, thanks. We don't currently have plans to expose the selected funding source. I would recommend just messaging the user to retry with PayPal.

**Comment by maxisam** [comment]
Retry with Paypal? I don't think that would help the checkout flow. Honestly, supporting this was a request from Paypal. We were just trying to do it as a favor for Paypal.
