### ISSUE TITLE
onClick and validate is never triggered with angularJS 1.6

### ISSUE THREAD

**Issue by joweste** [paypal/paypal-checkout#596]
Hi,

Using angularJS 1.6, the validate and onClick  is never triggered.

//markup
<paypal-button  id="paypal-button-container" env="opts.env" 
                client="opts.client" ng-disabled="pagando"
                                 payment="opts.payment" commit="opts.commit" 
                                 data-style="opts.style"
                                 on-authorize="opts.onAuthorize">
                </paypal-button>

//In angular controller
opts={

        // Set your environment

        env: 'sandbox', // sandbox | production

        // PayPal Client IDs - replace with your own
        // Create a PayPal app: https://developer.paypal.com/developer/applications/create

        client: {
            sandbox:    'AZDxjDScFpQtjWTOUtWKbyN_bDt4OgqaF4eYXlewfBP4-8aqX3PiV8e1GWU6liB2CUXlkA59kJXE7M6R',
            production: '<insert production client id>'
        },

        validate: function(actions) {
          alert('validate');
        },

        onClick: function() {
           alert('click');
        },

        // Wait for the PayPal button to be clicked

        payment: function(data, actions) {

            // Make a client-side call to the REST api to create the payment

            return actions.payment.create({
                payment: {
                    transactions: [
                        {
                            amount: { total: '0.01', currency: 'USD' }
                        }
                    ]
                }
            });
        },

        // Wait for the payment to be authorized by the customer

        onAuthorize: function(data, actions) {

            // Execute the payment

            return actions.payment.execute().then(function() {
                window.alert('Payment Complete!');
            });
        }

**Comment by bluepnume** [comment]
Can you share the full code along with the `<paypal-button>` element?

**Comment by bluepnume** [comment]
```
<paypal-button  id="paypal-button-container" env="opts.env" 
                client="opts.client" ng-disabled="pagando"
                                 payment="opts.payment" commit="opts.commit" 
                                 data-style="opts.style"
                                 on-authorize="opts.onAuthorize">
```

You're not passing these callbacks down here.

**Comment by joweste** [comment]
Yes, I am. The callbacks are in opts object from controller in my post.

**Comment by bluepnume** [comment]
Sure -- but you need to pass down each prop separately. So you'd need to add `on-click="opts.onClick" and validate="opts.validate"`
