### ISSUE TITLE
supportsPopups() checking didn't work for iOS LINE in-app browsers

### ISSUE THREAD

**Issue by tinyjacky** [paypal/paypal-checkout#597]
### Description

Using LINE (8.1.1) in-app browsers for iOS 10.0.3, when clicking Paypal checkout button, the in-page popup was not displayed. Instead, an `about:blank` page was opened.

It seems Paypal button couldn't detect the user agent not supporting popups. The user agent is as follows: 
`MOZILLA/5.0 (IPHONE; CPU IPHONE OS 10_3_3 LIKE MAC OS X) APPLEWEBKIT/603.3.8 (KHTML, LIKE GECKO) MOBILE/14G60 SAFARI LINE/8.1.1`
which seems to have bypassed the regex
```
/(iPhone|iPod|iPad|Macintosh).*AppleWebKit(?!.*Safari)/i
/.+AppleWebKit(?!.*Safari)/
```
in supportsPopups() due to the presence of `Safari` after `AppleWebKit`.

Some help would be much appreciated. Thanks!

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [x] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Thanks for the report. I'll add a check in.
