### ISSUE TITLE
Disable debit and credit card payments. Only allow bank and PayPal balance.

### ISSUE THREAD

**Issue by safinn** [paypal/paypal-checkout#598]
Im wondering if it is possible to disable credit and debit card payments and only allow PayPal balance and bank payments. The reason for this is i am expecting payments from different countries and the cross-border fees when using cards are huge (All payments to be made in EUR).

Saw this similar issue: https://github.com/paypal/paypal-checkout/issues/491 but wasnt sure how to implement the `SOLUTIONTYPE` setting while using react. But reading the docs, it seems that i neet to set it it to `Mask` to guests cannot pay by card but even when logging in I want to disable choosing a card as the payment source.

My current code:

```js
export default class PayPalCheckout extends React.Component {

  onAuthorize = async (data) => {
    // Optional: display a confirmation page here
    // Make request to server to execute the PayPal payment.
    // Server uses `paypal-rest-sdk` to execute the payment.
    const response = await checkoutPaypal(data.paymentID, data.payerID);
  }

  payment = (data, actions) => {
    return actions.payment.create({
      transactions: [{
        amount: {
          total: this.props.price,
          currency: 'EUR'
        }
      }]
    });
  }

  render() {
    const client = {
			sandbox: 'sandboxkey',
			production: 'productionkey',
    };
    const env = process.env.NODE_ENV === 'production' ? 'production' : 'sandbox';

    return (
      <PayPalButton 
        env={env}
        client={client}
        payment={this.payment}
        commit={true}
        onAuthorize={this.onAuthorize}
        style={{
          label: 'pay',
          size:  'small',
          shape: 'rect', 
          color: 'gold', 
          tagline: false
      }}/>
    );
  }
}
```

**Comment by bluepnume** [comment]
I'm pretty sure this is not possible. @trainerbill any advice on this one?

**Comment by Austin57129** [comment]
Hey @safinn,

Are you referring to charges to the consumer from their bank or cross-border fees that you're charged from PayPal? If the latter, PayPal charges the same fee regardless of what funding source was used so the fees wouldn't be changed. Feel free to send me an email to mbaustin@paypal.com and we can talk about this some more.

**Comment by safinn** [comment]
Thank you for the reply. @Austin57129 I will send you an email to hopefully help my understanding of the fees. Is it at least possible to disable the guest checkout?
