### ISSUE TITLE
Reject in the payment promise

### ISSUE THREAD

**Issue by AssafMalki** [paypal/paypal-checkout#600]
Here is my code

```
  payment(accountType) {
    return new paypal.Promise(((resolve, reject) => {
      getBillingAgreementToken(accountType)
        .then((data) => {
          if (data.data.agreementToken) {
            resolve(data.data.agreementToken);
          } else {
            reject("Couldn't set up a token, please try later");
          }
        })
        .catch((err) => { reject(err); });
    }));
  }

  render() {
    return (
      <Button
        commit={this.state.commit}
        env={this.state.env}
        client={this.state.client}
        style={this.state.style}
        payment={() => this.payment(this.state.accountType)}
        onAuthorize={(data, actions) => this.onAuthorize(data, actions)}
        />
    );
  }

```

getBillingAgreementToken is a http promise which returns the agreement token.

How am I suppose to use the reject in the payment promise?
whether I reject with a string  or with the error element I get from the http promise, I still get an uncaught exception from the paypal-checkout library.

Thanks

**Comment by danechitoaie** [comment]
Been having same issue. Have you managed to get reject working without throwing that error in the console?

**Comment by AssafMalki** [comment]
Nop...

**Comment by danechitoaie** [comment]
I hope someone will be able to give an answer. Is this just normal behaviour and you always get that error in the console if you use reject, or we're doing something wrong.

**Comment by bluepnume** [comment]
Yes, this is expected. Rejecting in `payment()` is an error case and throwing to the console helps when we need to debug.
