### ISSUE TITLE
Allstar In-context Failure With IE and Edge

### ISSUE THREAD

**Issue by jskaggs80** [paypal/paypal-checkout#604]
### Description

Please provide a short description of the issue here, along with:

- Screenshots or videos that show the issue
- Your code
- The `paypal.version` from your browser console
- Edge and IE 11
- www.magicbax.com
- TypeError: Unable to get property 'close' of undefined or null reference
- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)? No
- Does the issue occur consistently, or intermittently? Consistently

### Steps to reproduce

add something to your cart then click PayPal to checkout. see error

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x ] Edge
- [ x] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

This is a Braintree integration.

**Comment by bluepnume** [comment]
[ closing as not an issue with checkout.js, this is a standalone braintree integration ]
