### ISSUE TITLE
failed to npm install paypal-checkout

### ISSUE THREAD

**Issue by sethomas** [paypal/paypal-checkout#605]
It's this again: https://github.com/paypal/paypal-checkout/issues/556

```
npm ERR! paypal-checkout@4.0.174 postinstall: `flow-typed install`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the paypal-checkout@4.0.174 postinstall script 'flow-typed install'.
```
For the time being I am going back to 4.0.173

**Comment by bluepnume** [comment]
Weird, I wonder why this is just cropping up now again. `flow-typed install` has been part of `postinstall` for a long time. Anyway -- removing this and re-publishing until I can debug properly.

**Comment by bluepnume** [comment]
OK, republished. Can you try once more?

**Comment by sethomas** [comment]
@bluepnume good to go! Thanks!
