### ISSUE TITLE
checkout button validate not working with some recent change

### ISSUE THREAD

**Issue by AMRITPK** [paypal/paypal-checkout#606]
###Description

Validation function not working with checkout js
Validate and onclick call back are not getting executed in the most recent version of  checkout.js

### Steps to reproduce

1. go to developer portal
https://developer.paypal.com/demo/checkout/#/pattern/validation

2. go to customization >validation 

3. click on checkout button

Expected- should not open incontext window
Observed- incontext window opening without going for the validation

##observation
validate function in the checkoutjs is not getting called even once. This issue is observed only from today 16 Feb  12AM PST

### Affected browsers
all

[checkout error.zip](https://github.com/paypal/paypal-checkout/files/1730754/checkout.error.zip)

**Comment by jonners99** [comment]
This appears to be occurring in our production environment as well.

**Comment by Arvind6353** [comment]
Hi,
Am also facing the same issue . It is working for checkout js versions 4.0.167 and below.

**Comment by eliotsykes** [comment]
Confirmed, seen in production and sandbox.

**Comment by eliotsykes** [comment]
@Arvind6353 from your comment it sounds like you've been able to use a URL to an older working version of checkout.js. Could you share here as that might be a viable workaround for some.

I don't think PayPal are aware of this issue yet, the status page, at time of writing, isn't showing this issue: https://www.paypal-status.com/product/production

**Comment by eliotsykes** [comment]
I've found the same as @Arvind6353 above, 4.0.167 seems to be the last version of checkout.js where `validate` API hasn't been changed/broken. 

The following versioned URL seems to work in my sandbox environment as expected: 

https://www.paypalobjects.com/api/checkout.4.0.167.js

All later versions (4.0.168-4.0.175) appear to have broken or changed the way `validate` works.

**Comment by eliotsykes** [comment]
Diff between 4.0.167 and 4.0.168, maybe someone can spot the issue: https://github.com/paypal/paypal-checkout/compare/v4.0.167...v4.0.168

**Comment by Arvind6353** [comment]
@eliotsykes : My guess is around the file hacks.js. Am trying to build the project in local but facing some issue .

**Comment by bluepnume** [comment]
All changes from yesterday have been rolled back. Please clear your browser cache and let me know if you still see the issue.

**Comment by AMRITPK** [comment]
Yes.. Working fine after the rollback
