### ISSUE TITLE
Window.paypal is undefined after doing npm run build 

### ISSUE THREAD

**Issue by Arvind6353** [paypal/paypal-checkout#607]
### Description
Hi,
I cloned the paypal-checkout repo and was able to set up the project in local .

When I tried npm run build , the build was successful and generated dist folder with js files .

I imported the checkout.4.0.176.js that got generated in the dist folder in my sample application and I got  the following error .

**Uncaught TypeError: Cannot read property 'Promise' of undefined
    at usePayPalPromise (promise.js:11)
    at setupButton (button.js:69)
    at button?version=4.0.176&env=sandbox&sessionID=c7a8b9f7bb_gezdunjqhiyta&buttonSessionID=8f6f3f96ca_gezdunjthizdo&funding.disallowed=venmo&funding.remembered=paypal&locale.x=en_US&style.color=gold&style.shape=pill&style.size=small&style.label=checkout&style.fundingicons=false&logLevel=warn&uid=7f02a8ac3b&xcomponent=1:1000**

Looks like **window.paypal** is coming as **undefined** .

Please help in resolving this .

**Comment by Arvind6353** [comment]
@bluepnume  : Any idea why this error is coming up when I am trying do npm run build ?

**Comment by bluepnume** [comment]
Can you please:

1. Use `checkout.js` rather than `checkout.4.0.176.js`
2. Add `data-paypal-checkout` to the script tag
