### ISSUE TITLE
Promise is undefined in IE11

### ISSUE THREAD

**Issue by crookedneighbor** [paypal/paypal-checkout#609]
### Description

We got an issue on braintree-web-drop-in about this: https://github.com/braintree/braintree-web-drop-in/issues/361

> The paypal button doesn't work on IE11. This could be related to the promise error.

> Tested on my local and also:
https://developers.braintreepayments.com/guides/drop-in/overview/javascript/v3

I tested independently and got the same error. On https://developer.paypal.com/demo/checkout/#/pattern/client I don't get the Promise undefined message, but the PayPal button does nothing when clicked.

![36294421-b891174a-1334-11e8-8436-fb86123b1b82](https://user-images.githubusercontent.com/2916945/36309479-68aa3f3a-12ea-11e8-8999-e96cde11aad7.png)

### Steps to reproduce

Open a checkout.js integration in IE11 and attempt to click the button.

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [x] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bsiggelkow** [comment]
I am also getting this error

**Comment by TheMushrr00m** [comment]
> I am also getting this error
I'm thinking that this error it's related to the Promise polyfill but i'm not sure.

It's happening at the demo page too.

**Comment by mcstover** [comment]
We're still seeing the Promise Undefined error in IE 11 on production. (kiva.org)

Tested with fresh session and in private mode.

**Comment by bluepnume** [comment]
Can you clear your cache and check again? We rolled back the script

**Comment by mcstover** [comment]
@bluepnume Unfortunately, no luck with that. 2 machines, cleared caches and other data.

**Comment by bluepnume** [comment]
Can you let me know what you see for `console.log(paypal.version)`?

**Comment by mcstover** [comment]
Ok so we just went through again and it worked. version 4.0.173.

Checked chrome and it's running 4.0.174

Maybe it was some type of DNS cache or whatever. Hopefully we're clear now, we'll let you know if we see it failing any more.

Thank you!

**Comment by bluepnume** [comment]
Thanks for checking again. I think there may be some stale cache hanging around in Akamai also. I'm kicking off another cache clean at that layer too.

**Comment by bluepnume** [comment]
Closing this. Bad build was rolled back, and got a fix in for the next release.
