### ISSUE TITLE
Unable to pass checkout in React

### ISSUE THREAD

**Issue by clustersnake** [paypal/paypal-checkout#611]
I'm using React and the paypal express button was warking fine until now. The express button opens the checkout window but there is no cart or total amount showin and after click the continue button, I got redirected to the summary paypal page.

I can see the transacctions in my account, but the are not completed. Has anyone got this issue before? the paypal example on the right works fine so I think the problem is mine, but the system was working for about six months with no issues.

![paypal](https://user-images.githubusercontent.com/16407149/36331360-d63379be-1343-11e8-8aca-71f0736c4874.jpeg)
![paypal-2](https://user-images.githubusercontent.com/16407149/36331365-e11fec54-1343-11e8-8123-3b56e8a6b29d.jpeg)

```
import React from 'react';
import ReactDOM from 'react-dom';
import paypal from 'paypal-checkout';

payment(data, actions) {
    return actions.payment.create({
        transactions: [
            {
                amount: { total: this.state.totalFee, currency: 'USD' }
            }
        ]
    });
}
onAuthorize(data, actions) {
    return actions.payment.execute().then(function(paymentData) {
        // Show a success page to the buyer
    });
}
...
render() {
let PayPalButton = paypal.Button.driver('react', { React, ReactDOM });

return (
     <div className = "col-sm-3 text-right">
            {
                this.state.env !== undefined ? 
                    <PayPalButton
                        commit={ true }
                        env={ this.state.env }
                        client={ this.state.client }
                        payment={ (data, actions) => this.payment(data, actions) }
                        onAuthorize={ (data, actions) => this.onAuthorize(data, actions) }
                    />
                    :
                    ''
            }

    </div>
);
```

**Comment by bluepnume** [comment]
Can you clear your browser cache and try once more? This may have been caused by a recent bug which was rolled back.

**Comment by clustersnake** [comment]
Thank you very much for your answer. The code online is not working but my local repository is working fine after updating the npm package, refactoring the code and clearing the browser cache.
So I will push my changes online. Thanks again!
![pay](https://user-images.githubusercontent.com/16407149/36332907-874693e8-134a-11e8-841d-ed210419b127.jpeg)
