### ISSUE TITLE
Popup is hanging on loading

### ISSUE THREAD

**Issue by telmogh** [paypal/paypal-checkout#613]
### Description

I'm using ReactJS and using the `paypal-checkout` npm package.

The popup opens without any problems and there's no console errors, just hangs there, loading.

Already tried using Chrome and Safari.

The only console warning is:

```
The SSL certificate used to load resources from https://www.paypal.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
```

**Comment by bluepnume** [comment]
Can you please open a new issue and fill out the questionnaire? Specifically with code samples. Thanks.
