### ISSUE TITLE
Works on local not on Live

### ISSUE THREAD

**Issue by frankdes** [paypal/paypal-checkout#615]
The paypal express checkout (https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/add-paypal-button/) works when I run from my local machine for both sandbox and production. However I get the following error from the live server
HTTP400: BAD REQUEST - The request could not be processed by the server due to invalid syntax.
(XHR)POST - https://www.paypal.com/webapps/hermes/api/payment/PAY-15S14565SW271463ALKIIOBY/execute

ppxo_xc_ppbutton_error [object Object] Error: No handler found for post message: xcomponent_init from https://www.paypal.com in http://timemoney.org/TimeMoney/CommonTM at Anonymous function (https://www.paypalobjects.com/api/checkout.js:3125:31) at ZalgoPromise.try (https://www.paypalobjects.com/api/checkout.js:9060:21) at _RECEIVE_MESSAGE_TYPE[] (https://www.paypalobjects.com/api/checkout.js:3122:13) at receiveMessage (https://www.paypalobjects.com/api/checkout.js:3055:25) at messageListener (https://www.paypalobjects.com/api/checkout.js:3076:13) at _RECEIVE_MESSAGE_TYPE[] (https://www.paypalobjects.com/api/checkout.js:3158:21) at receiveMessage (https://www.paypalobjects.com/api/checkout.js:3055:25) at messageListener (https://www.paypalobjects.com/api/checkout.js:3076:13)

{ack: "error", code: undefined, data: undefined, domain: "https://www.paypal.com", error: "No handler found for post message: xcomponent_init from https://www.paypal.com in http://timemoney.org/TimeMoney/CommonTM at Anonymous function (https://www.paypalobjects.com/api/checkout.js:3125:31) at ZalgoPromise.try (https://www.paypalobjects.com/api/checkout.js:9060:21) at _RECEIVE_MESSAGE_TYPE[] (https://www.paypalobjects.com/api/checkout.js:3122:13) at receiveMessage (https://www.paypalobjects.com/api/checkout.js:3055:25) at messageListener (https://www.paypalobjects.com/api/checkout.js:3076:13)"...}

[object Object]: {country: "AU", env: "production", errtype: "[object Error]", host: "www.paypal.com", lang: "en"...}
country: "AU"
env: "production"
errtype: "[object Error]"
host: "www.paypal.com"
lang: "en"
pageID: "a7cfe2f823"
path: "/webapps/hermes/button"
prev_corr_ids: ""
referer: "http://timemoney.org"
stack: "Error: No handler found for post message: xcomponent_init from https://www.paypal.com in http://timemoney.org/TimeMoney/CommonTM at Anonymous function (https://www.paypalobjects.com/api/checkout.js:3125:31) at ZalgoPromise.try (https://www.paypalobjects.com/api/checkout.js:9060:21) at _RECEIVE_MESSAGE_TYPE[] (https://www.paypalobjects.com/api/checkout.js:3122:13) at receiveMessage (https://www.paypalobjects.com/api/checkout.js:3055:25) at messageListener (https://www.paypalobjects.com/api/checkout.js:3076:13) at Anonymous function (https://www.paypalobjects.com/api/checkout.js:4795:21) at Anonymous function (https://www.paypalobjects.com/api/checkout.js:8937:37) at ZalgoPromise.prototype.dispatch (https://www.paypalobjects.com/api/checkout.js:8924:26) at ZalgoPromise.prototype.reject (https://www.paypalobjects.com/api/checkout.js:8911:17) at Anonymous function (https://www.paypalobjects.com/api/checkout.js:8933:37) at ZalgoPromise.prototype.dispatch (https://www.paypalobjects.com/api/checkout.js:8924:26) at ZalgoPromise.prototype.reject (https://www.paypalobjects.com/api/checkout.js:8911:17) at Anonymous function (https://www.paypalobjects.com/api/checkout.js:8949:33) at Anonymous function (https://www.paypalobjects.com/api/checkout.js:8937:37) at ZalgoPromise.prototype.dispatch (https://www.paypalobjects.com/api/checkout.js:8924:26)"
timestamp: 1519421890674
uid: "c138d26aed_giytumruhiydc"
ver: "4.0.178"
windowID: "544217b805"

**Comment by bluepnume** [comment]
> HTTP400: BAD REQUEST - The request could not be processed by the server due to invalid syntax.
(XHR)POST - https://www.paypal.com/webapps/hermes/api/payment/PAY-15S14565SW271463ALKIIOBY/execute

This is the most concerning thing to me. Can you share how you're making this `/execute` call and what params you're passing?

**Comment by frankdes** [comment]
It started working by itself with errors. The errors I get in sandbox is as follows
Error: No handler found for post message: xcomponent_error from https://www.sandbox.paypal.com in http://timemoney.org/TimeMoney/CommonTM at Anonymous function (https://www.paypalobjects.com/api/checkout.js:3125:31) at ZalgoPromise.try (https://www.paypalobjects.com/api/checkout.js:9060:21) at _RECEIVE_MESSAGE_TYPE[] (https://www.paypalobjects.com/api/checkout.js:3122:13) at receiveMessage (https://www.paypalobjects.com/api/checkout.js:3055:25) at messageListener (https://www.paypalobjects.com/api/checkout.js:3076:13) at _RECEIVE_MESSAGE_TYPE[] (https://www.paypalobjects.com/api/checkout.js:3158:21) at receiveMessage (https://www.paypalobjects.com/api/checkout.js:3055:25) at messageListener (https://www.paypalobjects.com/api/checkout.js:3076:13)

The code I am using is as follows. 


var paypalclientid = null;
var paypalcurrency = null;
var paypalamount = null;
var invoiceno = null;
var paypalpopupset = false;
var payapalpopup = "#payapalView";
var paypalbuttondiv = '#paypaldiv';
var paypalamountid = "amountid";
var paypalcurrencyid = "currencyid";
var paypalenvVal = 'sandbox'
var paypalPaymentDone = false;
var paypalDescription = null;
var paypalCustom = null;
var saveObject = null;
var paypalpayobj = null;
function SetPayPal() {
    if (paypalpopupset) {
        $(paypalbuttondiv).empty();
        $('#paypalamountdiv').remove();
        $('#paypalamountContainer').append("<div id='paypalamountdiv'></div>");
    }
    $("#paypalamountdiv").dxForm({
        formData: {
            Currency: paypalcurrency,
            Amount: paypalamount
         

           
        },
           readOnly : true
    });
    //document.getElementById(paypalamountid).innerHTML = paypalamount;
    //document.getElementById(paypalcurrencyid).innerHTML = paypalcurrency;
    if (!paypalpopupset)
    {
        paypalpopupset = true;
        $(payapalpopup).dxPopup({
            title: "Paypal payment"
        });
    }
    $(payapalpopup).dxPopup("show");
   

    paypal.Button.render({
        env: paypalenvVal,  // 'production', // Or 'sandbox',// https://developer.paypal.com/docs/api/payments/

        commit: true, // Show a 'Pay Now' button

        client: {
            sandbox: paypalclientid,
            production: paypalclientid,
        },

        style: {
            color: 'gold',
            size: 'small'
        },

        payment: function (data, actions) {
            return actions.payment.create({
                payment: {
                    transactions: [{
                        amount: {
                            total: paypalamount,
                            currency: paypalcurrency
                        },
                        custom: paypalCustom,
                        invoice_number : invoiceno,
                        description: paypalDescription
                    }]
                }
            });

        },

        onAuthorize: function (data, actions) {
            return actions.payment.execute().then(function (payment) {
                $(payapalpopup).dxPopup("hide");
                paypalPaymentDone = true;
                paypalpayobj = payment;
                if (saveObject != null)
                {
                    saveObject.PayPalSave();
                }
            });

        },

        onCancel: function (data, actions) {
            $(payapalpopup).dxPopup("hide");
            paypalPaymentDone = false;
           
            if (saveObject != null) {
                saveObject.PayPalSave();
            }
        },

        onError: function (err) {
            $(payapalpopup).dxPopup("hide");
            paypalPaymentDone = false;
            if (saveObject != null) {
                saveObject.PayPalSave();
            }
        }
    }, paypalbuttondiv);

  
}

**Comment by bluepnume** [comment]
Is the `invoice_number` unique for every call to the api?

**Comment by frankdes** [comment]
Yes, thanks. The platform is for different people to sell products. The platform will manage invoice number etc. However the different sellers are expected to use their own paypal client id to get the payment directly to them. Would this approach work? Thanks

**Comment by bluepnume** [comment]
Yes, that should work, but there's an issue with `invoice_number` -- if you try to execute payments with the same `invoice_number` the call will fail. Can you please make sure they're unique for each new call to `actions.payment.create()`?

**Comment by frankdes** [comment]
I will check on that and let you know if the issue remains. Thanks
