### ISSUE TITLE
How to only allow the in-page popup?

### ISSUE THREAD

**Issue by artofspeed** [paypal/paypal-checkout#616]
I have a react single-page application inside an Android Webview. Is there a way to force displaying in-page popup ONLY? Right now, first time it's displayed in-page. But second time it becomes a new tab and when we return back, we lose the data in the react SPA. How to ALWAYS display the popup as in-page?

Reproduce in Android Webview:
1. Click Paypal button
2. In-page popup is shown, click "Cancel and return to"
3. Click Paypal button again
3. Popup is shown in a complete new page, when pressing back button, popup is closed, React SPA page is refreshed, data there is lost.

**Comment by bluepnume** [comment]
This looks like a bug. Thanks for the report. Will have a fix in shortly.

**Comment by bluepnume** [comment]
Fix is in for the next release -- thanks again for the report!
