### ISSUE TITLE
PayPal In-Context Issue in mobile devices

### ISSUE THREAD

**Issue by abby999** [paypal/paypal-checkout#618]
Description

The PayPal In-Contex 'Click to Continue' page doesn't load as expected in mobile devices if 'initial-scale=1.0' is not set in viewport meta tag.

![paypal-background-overlay](https://user-images.githubusercontent.com/36861671/36689728-1b96bb30-1ae5-11e8-916a-69903f799d57.png)

Steps to reproduce:

1. Click Paypal button
2. In-page popup is shown
3. Close the window and go back to the website

Affected browsers

All

**Comment by bluepnume** [comment]
Thanks for the issue. Found the root cause, issue will be resolved for the next release.
