### ISSUE TITLE
PayPal button not loading PayPal window on Firefox

### ISSUE THREAD

**Issue by claudia-m-kaiser** [paypal/paypal-checkout#620]
### Description

On Firefox, the clicking the PayPal checkout button is not opening the PayPal pop-up window.
This can be reproduced easily by checking out on https://www.kogan.com/au/, and proceeding to the end of the checkout.

The issue is not occurring on the demo on developer.paypal.com. but it occurs always on the Kogan website.

**Comment by bluepnume** [comment]
Can you please raise a new issue and fill out the questionnaire that we've provided?
