### ISSUE TITLE
Changing the style of a PayPal Checkout Button as an Angular.js component?

### ISSUE THREAD

**Issue by synthecypher** [paypal/paypal-checkout#623]
How do you set the `style` option of the [PayPal Checkout](https://github.com/paypal/paypal-checkout) Button when using it as [Angular.js element][1] directive?

```javascript
    this.paypal = {
      // ...
      style: {
        color: 'black',
        shape: 'rect'
      }
    }
```

It would seem that the `style` option cannot be passed in a binding as `style` as this is already a reserved `HTMLElement` attribute?

```html
    <paypal-button
      client="$ctrl.paypal.client"
      commit="true"
      env="$ctrl.paypal.env"
      style="$ctrl.paypal.style"
      on-authorize="$ctrl.paypal.onAuthorize"
      on-cancel="$ctrl.paypal.onCancel"
      payment="$ctrl.paypal.payment">
    </paypal-button>
```
  [1]: https://github.com/paypal/paypal-checkout/blob/master/docs/frameworks.md#angularjs-element

**Comment by synthecypher** [comment]
Got it, you have to use `ng-attr-style="$ctrl.paypal.style"` and it will work.

**Comment by bluepnume** [comment]
Awesome, glad you got it working
