### ISSUE TITLE
iframe Issue when embedded as a "srcdoc"

### ISSUE THREAD

**Issue by ballawzi-pp** [paypal/paypal-checkout#625]
### Description
An e-commerce platform has received complaints from their merchants that the checkout.js button is not being loaded. 
This has occurred when the platform site is embedded in an iframe the following way: 
`<iframe src='javascript: window.frameElement.getAttribute("srcdoc");' srcdoc='html_code_here'></iframe>`

An example has been put together to demonstrate the issue: http://lamp.ecwid.com/~borman/paypal_3.html 

The console log gives the following errors: 
Uncaught Error: Could not get local global
Uncaught ReferenceError: paypal is not defined
Uncaught Error: Can not read window host

### Affected browsers

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge
- [x] IE
- [x] Chrome Mobile/Tablet
- [x] Safari Mobile/Tablet
- [x] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
I have a fix ready for this one. That said, I would strongly recommend against this pattern. Ideally, you should use a standard iframe with `<iframe src="https://foo.com/bar" />` to guarantee the best compatibility with checkout.js.

**Comment by bormanEcwid** [comment]
>I have a fix ready for this one.
@bluepnume When will fix be released?

**Comment by bluepnume** [comment]
I'm seeing the button being successfully rendered now, after the latest release.
