### ISSUE TITLE
value instanceof Function used rather than typeof value === 'function'

### ISSUE THREAD

**Issue by BenDol** [paypal/paypal-checkout#626]
### Description
When using this library with GWT [JSInterop](http://www.gwtproject.org/doc/latest/DevGuideCodingBasicsJsInterop.html) we have run into an issue with the follow check on line 5690 of the latest version of the library:
```javascript
if (!(value instanceof Function)) throw new Error("Prop is not of type function: " + key);
```
This is the full function snippet:
```javascript
function validateProp(prop, key, value, props) {
    var required = !(arguments.length > 4 && void 0 !== arguments[4]) || arguments[4];
    if (null !== value && void 0 !== value && "" !== value) {
        if (!value || "function" != typeof value.then || !prop.promise) {
            if ("function" === prop.type) {
                if (!(value instanceof Function)) throw new Error("Prop is not of type function: " + key);
            } else if ("string" === prop.type) {
                if ("string" != typeof value) throw new Error("Prop is not of type string: " + key);
            } else if ("object" === prop.type) try {
                JSON.stringify(value);
            } catch (err) {
                throw new Error("Unable to serialize prop: " + key);
            } else if ("number" === prop.type && isNaN(parseInt(value, 10))) throw new Error("Prop is not a number: " + key);
            "function" == typeof prop.validate && value && prop.validate(value, props);
        }
    } else if (required && !1 !== prop.required && !prop.hasOwnProperty("def")) throw new Error("Prop is required: " + key);
}
```

The issue we are having with this line is that the function type that we provide with our implementation is not an `instanceof Function` it seems to me there is no real reason to check for the instance of the Object type itself, rather that it is simply a `typeof value === 'function'`. This fixes the issue for us.

Would you please consider replacing all the uses of `instanceof Function` to `typeof value === 'function'` where appropriate? 

Thanks!

### Steps to reproduce

Using GWT JsInterop:

```java
@JsType
public class SomeImplementation {

  @JsFunction
  @FuncationalInterface
  public interface Function {
    Object call();
  }

  @JsProperty 
  Function property;
 
  public SomeImplementation() {
    property = new Function() {
      @Override
      public void call() {
        GWT.log("Tests").
      }
    }
 }
}
```

When debugging you will find that it is not an instance of Function, but it is still a function.

### Affected browsers

Not a browser specific issue,

**Comment by bluepnume** [comment]
Good catch. I'll gladly add a fix for this for the next release. `instanceof` also causes issues with cross-window objects, so glad to clear this up whenever it crops up.

**Comment by bluepnume** [comment]
This is now fixed and released.
