### ISSUE TITLE
undefined is not an object (evaluating 'window.navigator.userAgent.match')

### ISSUE THREAD

**Issue by edwardva** [paypal/paypal-checkout#627]
Hi I has error undefined is not an object (evaluating 'window.navigator.userAgent.match')

My Code is

PaypalButton.js

import React from 'react';
import ReactDOM from 'react-dom';
import scriptLoader from 'react-async-script-loader';
import paypal from 'paypal-checkout';

class PaypalButton extends React.Component {

  constructor(props) {
    super(props);

    window.React = React;
    window.ReactDOM = ReactDOM;

    this.state = {
      showButton: false,
    };
  }

  componentWillUnmount() {
    delete window.React
    delete window.ReactDOM
  }

  componentDidMount() {
    const {
      isScriptLoaded,
      isScriptLoadSucceed
    } = this.props;

    if (isScriptLoaded && isScriptLoadSucceed) {
      this.setState({ showButton: true });
    }
  }

  componentWillReceiveProps(nextProps) {
    const {
      isScriptLoaded,
      isScriptLoadSucceed,
    } = nextProps;

    const isLoadedButWasntLoadedBefore =
      !this.state.showButton &&
      !this.props.isScriptLoaded &&
      isScriptLoaded;

    if (isLoadedButWasntLoadedBefore) {
      if (isScriptLoadSucceed) {
        this.setState({ showButton: true });
      }
    }
  }

  render() {
     let ReactButton = paypal.Button.driver('react', {
            React: window.React,
            ReactDOM: window.ReactDOM
        });

    const {
      total,
      currency,
      env,
      commit,
      client,
      onSuccess,
      onError,
      onCancel,
    } = this.props;

    const {
      showButton,
    } = this.state;

    const payment = () =>
      paypal.rest.payment.create(env, client, {
        transactions: [
          {
            amount: {
              total,
              currency,
            }
          },
        ],
      });

    const onAuthorize = (data, actions) =>
      actions.payment.execute()
        .then(() => {
          this.setState({ showButton: false })
          const payment = {
            paid: true,
            cancelled: false,
            payerID: data.payerID,
            paymentID: data.paymentID,
            paymentToken: data.paymentToken,
            returnUrl: data.returnUrl,
          };

          onSuccess(payment);
        });

    return (
        <If condition={this.state.showButton}>
          <ReactButton
            env={env}
            client={client}
            commit={commit}
            payment={payment}
            onAuthorize={onAuthorize}
            onCancel={onCancel}
            onError={onError}/>
          </If>
    );
  }
}

export default scriptLoader('https://www.paypalobjects.com/api/checkout.js')(PaypalButton);

and Index.js

import React, { Component } from 'react';
import {AppRegistry, View} from "react-native";
import PaypalButton from './PaypalButton';

const CLIENT = {
  sandbox: process.env.PAYPAL_CLIENT_ID_SANDBOX,
  production: process.env.PAYPAL_CLIENT_ID_PRODUCTION,
};
const ENV = process.env.NODE_ENV === 'production'
  ? 'production'
  : 'sandbox';

class ReactBarcodeScannerProject extends Component {

render() {
        const onSuccess = (payment) =>
          console.log('Successful payment!', payment);

        const onError = (error) =>
          console.log('Erroneous payment OR failed to load script!', error);

        const onCancel = (data) =>
          console.log('Cancelled payment!', data);

        return (
                <PaypalButton
          client={CLIENT}
          env={ENV}
          commit={true}
          currency={'USD'}
          total={100}
          onSuccess={onSuccess}
          onError={onError}
          onCancel={onCancel}
        />
            );
    }
}

AppRegistry.registerComponent('ReactBarcodeScannerProject', () => ReactBarcodeScannerProject);

**Comment by bluepnume** [comment]
Are you running this code on the client or server side?

**Comment by edwardva** [comment]
Its in React-Native, client side.

**Comment by bluepnume** [comment]
Which browser are you using? `window.navigator.userAgent` should always be defined... can you try `console.log('User agent:', window.navigator.userAgent)`

**Comment by edwardva** [comment]
Yes the console log said "undefined". i am using the app in my android phone; i am develop an app with react-native

**Comment by bluepnume** [comment]
Ah right, gotcha. Yeah, this integration won't work with react native, it's intended only for web.

**Comment by edwardva** [comment]
Ok, so. How can i integrate paypal checkout with react-native??

**Comment by bluepnume** [comment]
@pvenkatakrishnan anything we can share here on the native sdk?

**Comment by PrateekGunnam** [comment]
How do you integrate this with react-native?
