### ISSUE TITLE
style.tagline is not working

### ISSUE THREAD

**Issue by alwaysraja** [paypal/paypal-checkout#630]
Tagline is not working by default. Even if we force to add tagline: true" still it disappears and not visible. We tested this is both Chrome and Firefox browser.

Steps to reproduce

1. Go to https://developer.paypal.com/demo/checkout/#/pattern/client
2. Navigate to any option from the left side menu
3. See the button tagline
![image](https://user-images.githubusercontent.com/886273/37081975-329295ba-2211-11e8-9633-a45c7c7750f2.png)
![image 1](https://user-images.githubusercontent.com/886273/37082008-4dcb349a-2211-11e8-956f-a4ed1e73d3dc.png)

### Affected browsers

Tested in the below browsers
- [x] Chrome
- [X] Firefox

**Comment by bluepnume** [comment]
As a hunch -- what is the zoom level of the page? is it set to 100%?
