### ISSUE TITLE
Reccuring payments

### ISSUE THREAD

**Issue by arnasziedavicius** [paypal/paypal-checkout#632]
This is more of an inquiry but I was wondering if there's any info on recurring payments using checkout.js? Or is it only possible through server side API?

Any pointers would be much appreciated.

**Comment by leave3644** [comment]
You can use either Billing Plan or Billing Agreement flow through REST server-side. The flow will be 1. Create a billing plan.
2. Activate the billing plan.
3. Create a billing agreement.
4. Execute the billing agreement.
See the api details [here](https://developer.paypal.com/docs/integration/direct/billing-plans-and-agreements/)
Or you can utilize the billing agreement with reference transaction feature (you'd need to contact the sales team to enable it on your account)
See the postman snippet [here](https://documenter.getpostman.com/view/483740/billing-agreement-flow/6YzwDkd)

**Comment by maximedupre** [comment]
But can we use checkout.js at all to facilitate the process, or do we have to manually call the REST API without using checkout.js at all?
