### ISSUE TITLE
Hide/Remove Pay with a debit or credit card

### ISSUE THREAD

**Issue by ermamud** [paypal/paypal-checkout#633]
I know this question was asked before but I haven't seen any specific answer for it.

I need to remove/hide the Pay with debit or credit card or create account, I only need to accept existing accounts, my clients can not pay with a non-existing account. Is this possible? or is there any trick to hide the button by css selectors or jQuery ?

Also I am trying to integrate this in my ionic 3 project. It works good, i can pay but the modal windows is not center align for small devices like iPhone 5. I can edit the css in the Safary Dev tools and i can make it better... is there a `right` way to replace css styles?

Regards,
Ernesto Ruano

**Comment by bluepnume** [comment]
> I need to remove/hide the Pay with debit or credit card or create account, I only need to accept existing accounts, my clients can not pay with a non-existing account. Is this possible? or is there any trick to hide the button by css selectors or jQuery ?

I'm pretty sure we don't support hiding that button. Please raise a new issue for the other problem, and provide all of the requested details including screenshots. Thanks!
