### ISSUE TITLE
IE 11 cannot render Paypal button in express checkout

### ISSUE THREAD

**Issue by kulkarnisan** [paypal/paypal-checkout#634]
Hi Guys,

I have a paypal button on my jsp page and I am using the same script available on developer.paypal site.

That button visible and working in Firefox,Chrome,Opera except IE11.

I have been following some articles to get rid of this issue. I read about changing local intranet configuration in IE using internet options.. Or making some change in the Registry..
Is there any other method available? because I cannot ask every end user to change their IE setting Or to change the Registry setting. 

This is the IE version I am using. 
![image](https://user-images.githubusercontent.com/37304436/37364341-3616c01a-26c8-11e8-890e-5b91dab60eb6.png)

When I load a page in IE11, in console, I can see the errors as below.

![image](https://user-images.githubusercontent.com/37304436/37364490-b01be804-26c8-11e8-8800-187a122c00f2.png)

With Firefox/Chrome/Opera..the paypal button is visible and working (I can pay using that button..in sandbox though)

Even if I make that button visible in IE 11 by making changes in local intranet options...that button is not working for me.... I am getting "Network Error" in IE 11. as I am using XmlHttpRequest object to make calls to paypal API's.

This  issue does not occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout) as I can see the paypal button there. But when I copy paste the same code in IE11...it does not appear.

The issue is consistent with IE11 only.

Guidance please
Sanket

**Comment by shoaibmir** [comment]
Please have a look at https://github.com/paypal/paypal-checkout/blob/e055fe139c3ad7fc26a3a1d61a65d5d8a7d47ae4/docs/debugging/ie-intranet.md which covers the exact same scenario.

cheers,
Shoaib

**Comment by bluepnume** [comment]
Please see: https://github.com/paypal/paypal-checkout/blob/master/docs/debugging/ie-intranet.md

End users should not experience this problem.

**Comment by kulkarnisan** [comment]
Thanks a lot...I got it what does it mean...

**Comment by nguyenchauhuyen** [comment]
@kulkarnisan  any solution for this? i got the same issue

**Comment by manish2307github** [comment]
I am also facing same issue, could you please let me know the solution. Fetch method is coming undefined
