### ISSUE TITLE
Script Incompatibility with checkout.js. Checkout button is not rendered

### ISSUE THREAD

**Issue by bormanEcwid** [paypal/paypal-checkout#635]
### Description

Merchants of our ecommerce platform complain to us that the checkout.js button is not being rendered. 
Our ecommerce platform can be used on any website or CMS (it is embedded using JS). We don't control what JS libraries and code our merchants use on their websites.
Recently we switched from PayPal Standard integration to the new "checkout.js" based one. Now some our merchants have issues with PayPal -- some JS code on their websites prevent it from working.

I prepared demo: http://lamp.ecwid.com/~borman/paypal_4.html
The console log gives the following error: Uncaught Error: Arguments not serializable -- can not be used to memoize

It seems to be related the scripts in the head blocking some of the checkout js functionality (as when removed it works).

How can we prevent this issue?

### Affected browsers

- [+] Chrome
- [+] Safari
- [+] Firefox
- [?] Edge
- [?] IE
- [?] Chrome Mobile/Tablet
- [?] Safari Mobile/Tablet
- [?] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Something in the page is overwriting `window.JSON`. checkout.js can not function without this in place.

**Comment by bormanEcwid** [comment]
@bluepnume Can you suggest any WA?
