### ISSUE TITLE
CDN can not delivery compressed checkout.js

### ISSUE THREAD

**Issue by bormanEcwid** [paypal/paypal-checkout#636]
### Description

Merchants of our ecommerce platform complain to us that the PayPal checkout button is not displayed for a long time. Customers don't know how to pay and leave the store. We found out reason - it's a slow download checkout.js.
For some regions paypal CDN can not delivery compressed content. So checkout.js has excessive size.

### Steps to reproduce
For example when I change DNS server to 62.192.160.39:
**nslookup OUTPUT:**

> host-57:~ user$ nslookup www.paypalobjects.com
Server:		62.192.160.39
Address:	62.192.160.39#53
>
>Non-authoritative answer:
www.paypalobjects.com	canonical name = geo.paypalobjects.com.akadns.net.
geo.paypalobjects.com.akadns.net	canonical name = pprussia.www.direct.paypalobjects.com.akadns.net.
Name:	pprussia.www.direct.paypalobjects.com.akadns.net
Address: 185.177.54.5

**curl OUTPUT:**
>host-57:~ user$ curl -I 'https://www.paypalobjects.com/api/checkout.min.js' --compressed
HTTP/1.1 200 OK
Server: Apache
Last-Modified: Thu, 15 Mar 2018 15:58:01 GMT
Accept-Ranges: bytes
Keep-Alive: timeout=5, max=100
Content-Type: application/x-javascript
Connection: Keep-Alive
Date: Fri, 16 Mar 2018 14:07:02 GMT
Age: 3314   
Content-Length: 902909
>
>host-57:~ user$ curl -s -w "Takes %{time_total}s, downloaded %{size_download} bytes\n" 'https://www.paypalobjects.com/api/checkout.min.js' -H 'Content-Type: application/x-javascript;charset=utf-8' --compressed -o /dev/null
Takes 18,628747s, downloaded 902909 bytes

Pay attention to the Content-Length header ~ 882KB. Also content is not compressed (response have no header content-encoding = gzip). And finally download js took 18.6s - it's too much.

When I change DNS server to 8.8.8.8 everything gets better
**nslookup OUTPUT:**

> host-57:~ user$ nslookup www.paypalobjects.com
Server:		8.8.8.8
Address:	8.8.8.8#53
>
>Non-authoritative answer:
www.paypalobjects.com	canonical name = geo.paypalobjects.com.akadns.net.
geo.paypalobjects.com.akadns.net	canonical name = hotspot.paypalobjects.com.akadns.net.
hotspot.paypalobjects.com.akadns.net	canonical name = www.paypalobjects.com.edgekey.net.
www.paypalobjects.com.edgekey.net	canonical name = e3691.g.akamaiedge.net.
Name:	e3691.g.akamaiedge.net
Address: 2.23.109.20

**curl OUTPUT:**
>host-57:~ user$ curl -I 'https://www.paypalobjects.com/api/checkout.min.js' --compressed
HTTP/1.1 200 OK
Server: Apache
Last-Modified: Thu, 15 Mar 2018 15:58:01 GMT
Accept-Ranges: bytes
Content-Type: application/x-javascript
Content-Encoding: gzip
Content-Length: 134866
Cache-Control: max-age=86400
Expires: Sat, 17 Mar 2018 14:34:56 GMT
Date: Fri, 16 Mar 2018 14:34:56 GMT
Connection: keep-alive
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000
>
>host-57:~ user$ curl -s -w "Takes %{time_total}s, downloaded %{size_download} bytes\n" 'https://www.paypalobjects.com/api/checkout.min.js' -H 'Content-Type: application/x-javascript;charset=utf-8' --compressed -o /dev/null
Takes 0,550980s, downloaded 134866 bytes

We get results:
- content length: 902909 bytes vs 134866 bytes
- download time: 18,628747s vs 0,550980s

Please fix it ASAP: this issue reduces the sales in stores of our merchants

### Affected browsers

- [+] Chrome
- [+] Safari
- [+] Firefox
- [+] Edge
- [+] IE
- [+] Chrome Mobile/Tablet
- [+] Safari Mobile/Tablet
- [+] Web View / Safari ViewController
- [+] Other

**Comment by bluepnume** [comment]
Are you still seeing this issue? Should have been resolved, looks like there was an issue with gzip on our CDN.

**Comment by bormanEcwid** [comment]
>Are you still seeing this issue?
Yes! I still reproduce this issue.
For example I reproduce it with DNS server 62.192.160.39

**nslookup OUTPUT:**
>host-57:~ user$ nslookup www.paypalobjects.com
>Server:		62.192.160.39
>Address:	62.192.160.39#53
>
>Non-authoritative answer:
>www.paypalobjects.com	canonical name = geo.paypalobjects.com.akadns.net.
>geo.paypalobjects.com.akadns.net	canonical name = >pprussia.www.direct.paypalobjects.com.akadns.net.
>Name:	pprussia.www.direct.paypalobjects.com.akadns.net
>Address: 185.177.54.13


**curl OUTPUT:**
>host-57:~ user$ curl -I 'https://www.paypalobjects.com/api/checkout.min.js' --compressed
>HTTP/1.1 200 OK
>Server: Apache
>Last-Modified: Fri, 23 Mar 2018 21:51:58 GMT
>Accept-Ranges: bytes
>Keep-Alive: timeout=5, max=100
>Content-Type: application/x-javascript
>Connection: Keep-Alive
>Date: Fri, 30 Mar 2018 05:14:42 GMT
>Age: 1607   
>**Content-Length: 903473**
Still not compressed

**Comment by bluepnume** [comment]
Ok thanks for the heads-up, let me follow up on this one.

**Comment by bluepnume** [comment]
I've checked on this and the resource is gzipped. You're making a HEAD request -- if you do a regular get you'll see it's gzipped.

**Comment by bormanEcwid** [comment]
>if you do a regular get you'll see it's gzipped.
No. I still reproduce this issue.

**nslookup OUTPUT**
>host-57:~ user$ nslookup www.paypalobjects.com
>Server:		62.192.160.39
>Address:	62.192.160.39#53
>
>Non-authoritative answer:
>www.paypalobjects.com	canonical name = geo.paypalobjects.com.akadns.net.
>geo.paypalobjects.com.akadns.net	canonical name = >pprussia.www.direct.paypalobjects.com.akadns.net.
>Name:	pprussia.www.direct.paypalobjects.com.akadns.net
>Address: 185.177.54.13

**curl OUTPUT**
>host-57:~ user$ curl -G 'https://www.paypalobjects.com/api/checkout.min.js' --compressed > out
>  % **Total**    % **Received** % Xferd  Average Speed   Time    Time     Time  Current
>                                 Dload  Upload   Total   Spent    Left  Speed
>100  **919k**  100  **919k**    0     0  1794k      0 --:--:-- --:--:-- --:--:-- 1798k

@bluepnume How can I help you investigate this issue? What more information can I provide for investigation?
