### ISSUE TITLE
Microsoft Edge doesnt work with standard paypal sandbox checkout url

### ISSUE THREAD

**Issue by yuriv1978** [paypal/paypal-checkout#637]
- Description
Sandbox checkout is successful  in Chrome/Firefox and IE, but Edge always fails.

![image](https://user-images.githubusercontent.com/33438565/37629691-91f06e52-2bb6-11e8-82fa-7082a3af0e61.png)

- Steps to Reproduce
To reproduce just try to open this paypal sandbox link (it suppose to prompt for login but instead in Edge it will show loading icon endlessly):

https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-8XL25053MF881021V

The Javascript error that only happens in Microsoft Edge:
SCRIPT 5022: PostMessage iframe domain (null), must be a *.paypal.com domain.

Please note this is related issue:
https://github.com/paypal/paypal-checkout/issues/550#issuecomment-374409793

- Exact version 
My Microsoft Edge version is 41.16299.248.0.

- Affected browsers
 Edge
 
- Reproducing
This issue persistently happens on two independent computer located in different networks.

**Comment by badgerpigeon** [comment]
I also encounter this issue on 
Microsoft Edge 41.16299.248.0
Microsoft EdgeHTML 16.16299

Can this get assigned to someone please?

**Comment by bluepnume** [comment]
Do you see the same issue in production mode?

**Comment by criss-zhou** [comment]
I also encounter this issue in sandbox environment. In production mode, it didn't happen. It seems this issue happens when creating one-time payments using  express checkout on login page.

**Comment by EduardoFer** [comment]
I'm having the same issue. Did anyone find a solution for this?

**Comment by bluepnume** [comment]
@EduardoFer  / @yuriv1978 can you also confirm if you're seeing the problem in sandbox only, or also in production?

**Comment by EduardoFer** [comment]
I just see this issue in sandbox, in production it's ok.

**Comment by tancevsasa** [comment]
I've having same issue is Sandbox mode. When to expect this to be fixed?

**Comment by bluepnume** [comment]
@vishakha94 -- can you take a look at this one while you're looking at Edge, see if you can repro?

**Comment by bluepnume** [comment]
Please let me know if you're still seeing this issue.

**Comment by tancevsasa** [comment]
I am confirming that issue has been fixed. Thanks a lot!

**Comment by tancevsasa** [comment]
this error started appearing again!
