### ISSUE TITLE
Popup overlays the close button, on mobile device with larger default zoom

### ISSUE THREAD

**Issue by artofspeed** [paypal/paypal-checkout#639]
On mobile device with larger display zoom, the popup overlays the close button, resulting users not able to close the popup, as indicated in the image:

![Display bug](https://i.imgur.com/O2RQwvd.jpg)

This is a serious issues as many of our customers have mobile devices that have display level set to "large". Especially, for devices of relatively large screen, sometimes the manufacture sets the default display larger than medium, so the texts wouldn't to be small to see. Also users of older age tend to set display zoom larger, because it's easier for them to see the screen and to tap on. Therefore it's a serious issue to consider. Of course there's always the "Cancel and return to ..." text, but people never notice that the first time.

Tested on Huawei Mate 9 webview and default browser. Suspect to happen on all mobile devices of zoom level higher than medium.

How to reproduce: On a mobile device, set display zoom to large, and view popup in webview.

**Comment by bluepnume** [comment]
@abarco could you take a look?

**Comment by bluepnume** [comment]
@walmik can you please take a look?

**Comment by walmik** [comment]
Will do @bluepnume

**Comment by bluepnume** [comment]
Assigning this back to @abarco -- I think that cross is being rendered on the overlay, by checkout.js, rather than UL. We should have a CSS rule to hide it below a certain width of window.

**Comment by bluepnume** [comment]
@mcntsh -- could you take a look into this one?

**Comment by mcntsh** [comment]
@artofspeed I know it's been a long time since, but a fix has been merged and will be out in our next release (Wednesday at 13:00 PST).
