### ISSUE TITLE
Guest checkout is not working  because we are unable to press the submit button

### ISSUE THREAD

**Issue by mahdinjim** [paypal/paypal-checkout#641]
This issue is really strange , we have a cordova mobile application and we used the express checkout client implementation to integrate paypal. 
After clicking the pay button, first the paypal login page is opened, when the user click on create account and choose the guest checkout and after filling the credit cards information we can't click the submit button, every time we click the button, the page jump to top, if we touch anything in the lowest area, the page jumps to top.
I would guess it is something to do with the new height of the page.

### Steps to reproduce
Use cordova application 
click pay button 
go to create account
scroll down to the submit button
click anywhere at the bottom of the page
Form jump to top again.

### Affected browsers

Android and IOS

**Comment by bluepnume** [comment]
@bluelnkd -- does our guest app support cordova integrations? Can you help triage or close this one?

**Comment by bluelnkd** [comment]
Webviews are not supported in the context of checkout. 
https://developer.paypal.com/docs/classic/lifecycle/info-security-guidelines/#secure-applications

We instead recommend using the PayPal SDKs instead for the most optimal user experience.

**Comment by mahdinjim** [comment]
@bluelnkd We are using the express checkout sdk, and the opened webview is managed by the paypal sdk. Should we switch to brainbox sdk ?
