### ISSUE TITLE
Form Validation and Error Handling

### ISSUE THREAD

**Issue by ste-camp** [paypal/paypal-checkout#645]
I'm trying to implement the checkout process with my backend server implementing the REST API, and I'm left quite confused on how to perform form validation and error handling with the paypal button.

I have already seen your demo about validation here: https://developer.paypal.com/demo/checkout/#/pattern/validation
and I have read issue #610 
but I think that your demo simplifies way too much the process of form validation: I have quite an input-rich form that I can't just reduce to a checkbox.
Usually form validation is performed with the onSubmit event of the form, but since the PayPal button actually replaces the purpose of the submit button to send the payment I no longer have onSubmit to trigger my form validation function.
How should I do it?
I have seen that the validate callback gets called during the setup of the button, so it's useless, I can't call validation when the form isn't filled yet.
The onClick callback doesn't seem to provide a way to stop the process, I have tried by returning false but that doesn't work.

I'm lost. Any suggestion?

**Comment by bluepnume** [comment]
Yeah, so there's a lot of discussion around this here: https://github.com/paypal/paypal-checkout/issues/139 -- but to summarize, it's problematic for us to allow stopping the flow in onClick. The idea of `validate()` is you need to set up event listeners which listen for any changes in your form, determine if it's valid or invalid, then call `actions.enable()` or `actions.disable()` in advance of the button being clicked.

**Comment by ste-camp** [comment]
Thanks for the reply :)
I guess it is actually possible for me to trigger the form validation at each change in the form, I was worring about performance though

**Comment by bluepnume** [comment]
Makes sense -- you can always use a debouncer to ease up the performance concerns a little.

**Comment by ste-camp** [comment]
Thank you!

Please please put all these info about validate and similar callbacks in the docs!
