### ISSUE TITLE
INVALID_RESOURCE_ID [Integrating with the PayPal REST API]

### ISSUE THREAD

**Issue by LiquidRayga** [paypal/paypal-checkout#647]
So I've been following your tutorial for integrating with Paypal REST API https://github.com/paypal/paypal-checkout/blob/master/docs/paypal-rest-api.md.

I can get my oauth access token and create a new transaction but when I'm passing the Payment ID to the front-end JS (AngularJS) I get the INVALID_RESOURCE_ID error and the PayPal modal says that "This transaction is invalid. Please return to the recipient's website to complete your transaction using their regular checkout flow.". 

What causes these errors to show up? I do not also know how to get the payer's ID because It is not included in when I create a new transaction.

Thank you for helping me. I really appreciate it.

**Comment by bluepnume** [comment]
Are you hitting sandbox or production?

**Comment by LiquidRayga** [comment]
I'm using sandbox.

On Apr 4, 2018 12:48 AM, "Daniel Brain" <notifications@github.com> wrote:

Are you hitting sandbox or production?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/paypal/paypal-checkout/issues/647#issuecomment-378318403>,
or mute the thread

**Comment by LiquidRayga** [comment]
I use PHP curl to generate my access token for PayPal REST API.

`$ch = curl_init();

$CLIENT_ID = 'xxxxxxx';
$SECRET = 'xxxxxxx';

curl_setopt($ch, CURLOPT_URL, "https://api.sandbox.paypal.com/v1/oauth2/token");
curl_setopt($ch, CURLOPT_HEADER, false);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_USERPWD, $CLIENT_ID.":".$SECRET);
curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=client_credentials");

$result = curl_exec($ch);

if(empty($result))die("Error: No response.");
else{
    $json = json_decode($result);
    print_r($json->access_token);
}

curl_close($ch);`

Then I have a post request in my front-end js (AngularJS) to create a new transaction, create my own transaction key to be used later, save the payment details to my database, save the oauth token from Paypal and then generate the PayPal button. 

        $scope.buy_now = function() {
		if ($scope.btn_buy_clicked == true) {
			return false;
		}
		make_transackey();

		var filter = {
			trasaction_key : $scope.new_transaction_key,
			oauth_token : $scope.oauth_token,
			payment_details : JSON.stringify($scope.PAYMENT_transaction)
		};

		var promise = PaypalFactory.buy_now(filter);
		promise.then(function(data){
			generate_paypal_button();

			alert("Please wait for the paypal button to show up!");
		})
		.then(null,function(data) {
			alert("An error occured! Please try again.");
		})
	}

	function generate_paypal_button(){
		$scope.btn_buy_clicked = true;

		paypal.Button.render({

			payment: function() {
				return new paypal.Promise(function(resolve, reject) {

            // Call your server side to get the Payment ID from step 3, then pass it to the resolve callback

            jQuery.post('./get_payment_id.php?transaction_key='+$scope.new_transaction_key)
            .done(function(data){
            	resolve(data.id);
            });
        });
			},

			onAuthorize: function(data) {

        // Call payment execute (see step 5)
    }}, '#paypalbutton');
	}

Then I can get the payment ID via the get payment_id.php using the custom transaction key that I generated and get the oauth token and payment details that I saved earlier in the front-end JS.

foreach ($data['result'] as $k => $v) {
		$oauth_token = $v['oauth_token'];
		$payment_details = $v['payment_details'];
		
$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, "https://api.sandbox.paypal.com/v1/payments/payment");
		curl_setopt($ch, CURLOPT_POST, true);
		curl_setopt($ch, CURLOPT_POSTFIELDS, $payment_details);
		curl_setopt($ch, CURLOPT_HTTPHEADER, array(
			"Content-Type: application/json",
			"Authorization: Bearer ".$oauth_token)
		);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
			echo 'Error:' . curl_error($ch);
		}else{
			$json = json_decode($result);
			print_r($json->id);
		}

		curl_close ($ch);

		header("HTTP/1.0 200 OK");
	}

Sorry if my codings are bad.

**Comment by bluepnume** [comment]
Thanks. You need to pass `env: 'sandbox'` when you call `paypal.Button.render()`.

**Comment by LiquidRayga** [comment]
Thank you so much!
