### ISSUE TITLE
Paypal not working nor in prod or sandbox with AngularJS Application

### ISSUE THREAD

**Issue by ITGuy9401** [paypal/paypal-checkout#649]
### Description

I'm having the problem related to #477 both in prod and Sandbox environment. I've integrated the Paypal Button (client-side REST) in my AngularJS application through an angular directive. there is an example of payload I send to PayPal (the API does not return any error)
The following gist contains both the example JSON we send to PayPal and the Directive I built to do the integration in AngularJS

https://gist.github.com/ITGuy9401/33cc2d4e5e381552bbde74e95ffb0a66

- The `paypal.version` from your browser console: 4.0.187
- The exact browser version: Mozilla Firefox Quantum 59.0.2
- All console logs during the time of the issue, especially error messages

```
ppxo_unhandled_error 
{
  "stack": "./node_modules/post-robot/src/index.js/_RECEIVE_MESSAGE_TYPE[conf.b.POST_MESSAGE_TYPE.RESPONSE]@https://www.paypalobjects.com/api/checkout.js:3298:31\nreceiveMessage@https://www.paypalobjects.com/api/checkout.js:2858:25\nmessageListener@https://www.paypalobjects.com/api/checkout.js:2879:13\n",
  "errtype": "[object Error]",
  "timestamp": 1522920021546,
  "windowID": "ac5321b88a",
  "pageID": "8fdeda8f71",
  "prev_corr_ids": "d55dedd1f0719, d55dedd1f0719,4d07a0c655a9f, 4d07a0c655a9f",
  "referer": "https://www.mylabnutrition.net",
  "host": "www.paypal.com",
  "path": "/webapps/hermes/button",
  "env": "production",
  "country": "US",
  "lang": "en",
  "uid": "720c65e115_ga4tumjzhi2ta",
  "ver": "4.0.187"
}

Error: Timed out waiting 10000ms for payment
decorate/<@https://www.paypalobjects.com/api/checkout.js:12668:172
resultValue@https://www.paypalobjects.com/api/checkout.js:5779:32
./node_modules/post-robot/src/lib/index.js/listenForMethods</</<@https://www.paypalobjects.com/api/checkout.js:3737:28
./node_modules/zalgo-promise/src/index.js/promise_ZalgoPromise</ZalgoPromise.try@https://www.paypalobjects.com/api/checkout.js:8879:30
./node_modules/post-robot/src/lib/index.js/listenForMethods</<@https://www.paypalobjects.com/api/checkout.js:3736:24
./node_modules/post-robot/src/index.js/_RECEIVE_MESSAGE_TYPE[conf.b.POST_MESSAGE_TYPE.REQUEST]/<@https://www.paypalobjects.com/api/checkout.js:3268:24
./node_modules/zalgo-promise/src/index.js/promise_ZalgoPromise</ZalgoPromise.try@https://www.paypalobjects.com/api/checkout.js:8879:30
./node_modules/post-robot/src/index.js/_RECEIVE_MESSAGE_TYPE[conf.b.POST_MESSAGE_TYPE.REQUEST]@https://www.paypalobjects.com/api/checkout.js:3264:17
receiveMessage@https://www.paypalobjects.com/api/checkout.js:2858:25
messageListener@https://www.paypalobjects.com/api/checkout.js:2879:13
 types.js:122:22
	./node_modules/post-robot/src/index.js/_RECEIVE_MESSAGE_TYPE[conf.b.POST_MESSAGE_TYPE.RESPONSE] types.js:122:22
	receiveMessage index.js:112:4
	messageListener index.js:138:4

```

- Does the issue occur consistently, or intermittently? it happens every time

### Steps to reproduce

Please provide each individual step required to reproduce the issue: using an angularjs application with a directive solution for integrate the paypal button 

### Affected browsers

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge
- [x] IE (not tested, is purposely, for users' safety, not compatible with our platform)
- [x] Chrome Mobile/Tablet
- [x] Safari Mobile/Tablet
- [x] Web View / Safari ViewController
- [x] Other

**Comment by bluepnume** [comment]
Looks like you're not returning any thing in `payment()` -- you need to directly return the promise returned by `actions.payment.create()`
