### ISSUE TITLE
[Question] Security Consideration

### ISSUE THREAD

**Issue by mfxuus** [paypal/paypal-checkout#651]
Hi there,

I've been looking into a lot of methods of implementing a Paypal button, and currently I like this one the most. I have very limited knowledge on the security side of these payment options, so I was wondering if anyone can give me some insights on how secure this implementation is (in particular, the Basic and Advanced integration documented [here](https://github.com/paypal/paypal-checkout/blob/master/docs/button.md). I know nothing is 100% secure, but a very high level discussion of what the concerns could be (if there is any significant ones), and what I can do to mitigate them, would be very very much appreciated!

Thanks in advance.

**Comment by bluepnume** [comment]
@trainerbill can you help elaborate on this one?

**Comment by trainerbill** [comment]
@mfxuus The easiest way to integrate is the basic integration which uses the REST api on the client side.  You would have to validate on your server that the totals are correct before completing your fulfillment.  If you do the advanced integration then you need to make a webservice that returns the paypal token.  In this scenario the amounts are generated on the server so you shouldn't have to validate it before fulfillment.  Here is a youtube playlist with some how to videos:  

https://www.youtube.com/playlist?list=PLAlKnErU5lvhj3Fqr5hrBxm3CgsQXpEeK

I think your best bet is the basic integration which would be the fourth and fifth videos on the playlist.  If you want to talk about this in realtime head over to the gitter room and I can answer any other questions you have.  

https://gitter.im/paypal/paypal-checkout
