### ISSUE TITLE
[Question] Paypal hybrid integration automated testing with doctored payment_id/payer_id?

### ISSUE THREAD

**Issue by pnemere** [paypal/paypal-checkout#653]
### Description

When testing a hybrid paypal integration, I'm having trouble finding a way to automate the server-side test. I'm creating the payment on the client-side and using the checkout.js button.render() method, however the onAuthorize() step calls through to my web server to handle the sale and execute the payment together.

I need to eliminate the paypal button click and login steps as they're not relevant to my server-side test.

With Stripe for example, I've got extensive automated integration testing and am able to test against Stripe easily, as they provide test credit card tokens (see https://stripe.com/docs/testing) that have specific meanings and produce expected error messages or valid sales.

I found the PayPal negative testing page:
https://developer.paypal.com/docs/api/nt-rest/

Which would partially do what I'm after, however this seems to only cater for error conditions and involves **_modifying my server code to have a "test" mode where it inserts mock headers into the POST request._**

### The Question

Can you perhaps provide a list of payment_id and payer_id's for the sandbox which could be used to call /execute the same way as production code would, and perform expected actions? Something like:

Payment ID | Payer ID | Result
----------- | --------- | ------
payment_id_CREDIT_CARD_CVV_CHECK_FAILED | anything | CREDIT_CARD_CVV_CHECK_FAILED error returned
payment_id_VALID | payer_id_WRONG_ID | CARD_TOKEN_PAYER_MISMATCH
payment_id_VALID | anything other than payer_id_WRONG_ID | return a successful payment with an id, etc.

Thanks!

**Comment by bluepnume** [comment]
> Which would partially do what I'm after, however this seems to only cater for error conditions and involves modifying my server code to have a "test" mode where it inserts mock headers into the POST request.

Can you elaborate on why that's problematic?

+ @lmarkus, whose team has been doing a lot on the negative-testing front

**Comment by lmarkus** [comment]
@pnemere , My team is actively building a negative testing framework that will support input-based triggers to complement the header-based ones.

It's meant to work more or less as you described.  If you don't mind, could we talk offline? I;m sur emy team would like to run some scenarios by you.  Please shoot me an email.  `lmarkus` at paypal dot c0m

**Comment by pnemere** [comment]
Thanks Markus, will email you.

@bluepnume Well it's problematic for 2 reasons:

1. You have to insert special test code, which you have to turn on & off, and effectively when it's running an integration test it's not testing the actual production code. Arguably it's a slight change with 1 flag but if the rest of the system doesn't need a special flag (like with Stripe)

2. I didn't see a way of producing a successful purchase result, which for an automated testing scenario is vital too.

Thanks for the quick replies guys!
