### ISSUE TITLE
Console Error Messages Useless in Firefox

### ISSUE THREAD

**Issue by DanielStout5** [paypal/paypal-checkout#655]
The error messages generated by checkout.js are extremely useless in Firefox; I wasted a fair amount of time trying to decipher it before I tried it in Chrome and immediately was able to tell what the issue was.

In Firefox:
![](https://i.imgur.com/60d7XVE.png)

In Chrome:
![](https://i.imgur.com/iY9Nbej.png)

- PayPal Version: 4.0.187
- Browser version: Firefox 59.0.2

**Comment by bluepnume** [comment]
Great callout. We'll get a fix in for this. Looks like Firefox's `err.stack` doesn't include the original error message.

**Comment by bluepnume** [comment]
Fix is made for the next release. Thanks again!
