### ISSUE TITLE
onAuthorize never getting fired.

### ISSUE THREAD

**Issue by mukesh-urbanpiper** [paypal/paypal-checkout#658]
### Description

Please provide a short description of the issue here, along with:
After making successful payment the popup is getting closed and instead of `onAuthorize`, `onCancel` is getting fired.
-Code
```
paypal.Button.render({
            env: 'sandbox', // sandbox | production                      
            client: {
                sandbox:    '------------',
                production: '-----------'
            },

			style: {
	            label: 'paypal',
	            size:  'medium', // small | medium | large | responsive
	            shape: 'rect',   // pill | rect
	            color: 'blue'   // gold | blue | silver | black
	        },
            commit: true,
            payment: async(data, actions)=> {
				var payment_create_id = await BF.extAjaxCallPromise('post', dummyPaypalData, this.state.create);
				return payment_create_id.data.id;
            },

            onAuthorize: async(data, actions)=> {
				var {paymentID, payerID} = data;
				var payment_executed = await BF.extAjaxCallPromise('post', data, this.state.execute);
				if(payment_executed && payment_executed.data.state == "approved") {
					alert('payment successful! '+payment_executed.data.id)
				}
            },
			onCancel: function(data, actions) {
			   	console.log('cancel', data, actions)
			},
			onError: function(err) {
				console.log('error', err)
			}

        }, '#paypal-button-container');
```
paypal version - 4.0.191

browser version -  Google chrome 65.0.3325

Console logs:
```
{
   "billingID":"EC-43S29120A4654034U",
   "cancelUrl":"https://example.com?token=EC-43S29120A4654034U",
   "intent":"sale",
   "paymentID":"PAY-3CM37666C6072671GLLKKY3A",
   "paymentToken":"EC-43S29120A4654034U"
}
```

- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
No
- Does the issue occur consistently, or intermittently?
Yes

### Affected browsers

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
@vishakha94 can you follow up on this and help narrow down if it's a bug on our side?

**Comment by vishakha94** [comment]
sure

**Comment by vishakha94** [comment]
@mukesh-urbanpiper Pls provide a test page where I can reproduce this?

**Comment by mukesh-urbanpiper** [comment]
Hi @vishakha94, I found that the the issue is only happening when an Indian paypal account is trying to pay with other currency (For my case it was USD). `onAuthorize` is not getting fired and rather the cancel event getting fired with no explicit error message.

**Comment by JerrodV** [comment]
I was able to correct this in my project. I will post my results tomorrow.
