### ISSUE TITLE
Calling close() does not close the overlay

### ISSUE THREAD

**Issue by ste-camp** [paypal/paypal-checkout#659]
### Description

I'm using the [Advanced Javascript Integration](https://github.com/paypal/paypal-checkout/blob/master/docs/button.md#advanced-integration) in my javascript with my REST backend.
I'm trying to understand how to handle errors when my backend gives and error during the execute phase (the onAuthorize callback in JS).
What I'm doing is calling actions.close() to close the PayPal popup and show an error on my page: the result it that the popup closes correctly but the grey PayPal overlay on my page stays there, without a closing button and the spinner in the center of the page.
I don't know if I'm doing somethinng wrong or it's a bug.
Here is my code
```javascript
...
onAuthorize: function(data, actions){
            return $.ajax({
                url: BACKEND_URL+'/execute',
                method: 'post',
                crossDomain: true,
                contentType: 'application/json; charset=UTF-8',
                dataType: 'json',
                jsonp: false,
                data: JSON.stringify({
                    lang: backendLang,
                    paymentID: data.paymentID,
                    payerID: data.payerID
                })
            }).done(function(data2){
                //Redirect to confirm page
            }).fail(function(xhr){
                var resp = JSON.parse(xhr.responseText);
                actions.close();
                backendErrorHandler(resp);
            });
        },
...
```

### Steps to reproduce

1. Click on the PayPal Button
2. Choose payment with a credit card (without loggin in to PayPal)
3. Insert Card and owner data (in my case to trigger the error I'm issuing a payment with an amount higher than the availability I have on the card)

I'm testing on Google Chrome and Firefox

**Comment by bluepnume** [comment]
Easy fix -- use `.then` and `.catch` and don't call `actions.close`.

```
onAuthorize: function(data, actions){
            return $.ajax({
                url: BACKEND_URL+'/execute',
                method: 'post',
                crossDomain: true,
                contentType: 'application/json; charset=UTF-8',
                dataType: 'json',
                jsonp: false,
                data: JSON.stringify({
                    lang: backendLang,
                    paymentID: data.paymentID,
                    payerID: data.payerID
                })
            }).then(function(data2){
                //Redirect to confirm page
            }).catch(function(xhr){
                var resp = JSON.parse(xhr.responseText);
                backendErrorHandler(resp);
            });
        },
```
