### ISSUE TITLE
Wrong height on responsive when using angular component

### ISSUE THREAD

**Issue by lalmanzar** [paypal/paypal-checkout#660]
When using the angular component the height is wrong and hides part of the button.

Here is an example comparing normal js vs angular

![image](https://user-images.githubusercontent.com/1315039/38962307-9b6f4eee-433a-11e8-8031-f8f099f43426.png)

https://jsfiddle.net/bdmqxr5y/4233/

Browsers: 
Google Chrome Version 65.0.3325.181 (Official Build) (64-bit) [**BROKEN**]
Safari 11.0.3 (13604.5.6) [**BROKEN**]
Firefox [**FINE**]

**Comment by bluepnume** [comment]
Great catch. Got a fix in for the next release.

**Comment by bluepnume** [comment]
This is now resolved
