### ISSUE TITLE
PayPal Express Checkout Button not rendering in iOS when used in Cordova application. It is working in Android but the button is not getting build up in iOS devices. 

### ISSUE THREAD

**Issue by AashutoshPrashar** [paypal/paypal-checkout#664]
### Description

Please provide a short description of the issue here, along with:

- Screenshots or videos that show the issue
- Your code
- The `paypal.version` from your browser console
- The exact browser version
- A link to your page with the issue, if possible
- All console logs during the time of the issue, especially error messages
- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
- Does the issue occur consistently, or intermittently?

### Steps to reproduce

Please provide each individual step required to reproduce the issue

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
We don't officially support cordova -- if you find any specific root cause, we'll be glad to accept a PR -- but otherwise I'm afraid this isn't likely to get a lot of priority.

**Comment by MaTToX3** [comment]
Just add <allow-navigation href="*" /> inside <platform name="ios"> tag and it will render.

**Comment by githins** [comment]
> Just add
> `<allow-navigation href="*" />`
> for ios platform in config.xml and it will render.

Thanks
It worked for me.

**Comment by netmikey** [comment]
As described in (cordova-plugin-whitelist)[https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/], it is not recommended to use the `*` wildcard to whitelist the whole world.

For a more limited whitelisting that still works, you could use:
```
    <allow-navigation href="about:*" />
    <allow-navigation href="https://www.paypal.com/*" />
    <allow-navigation href="https://www.paypalobjects.com/*" />
```
