### ISSUE TITLE
PayPal Express Checkout Button not rendering in iOS when used in Cordova

### ISSUE THREAD

**Issue by AashutoshPrashar** [paypal/paypal-checkout#665]
It is working in Android but the button is not getting build up in iOS devices. The example which I am referring to is 

https://developer.paypal.com/demo/checkout/#/pattern/client

I know that there are many other issues regarding this already raised but no one has got some useful solution so raising it again.

Also if there is any other way to integrate PayPal with Cordova please suggest that also.

**Comment by bluepnume** [comment]
We don't officially support cordova -- if you find any specific root cause, we'll be glad to accept a PR -- but otherwise I'm afraid this isn't likely to get a lot of priority.

**Comment by pooventhirankp** [comment]
1) Am developing hybrid application. Am using PayPal for payment. For PayPal integration am following the below link.

https://developer.paypal.com/demo/checkout/#/pattern/client

It works well in android, but in iOS the PayPal checkout button itself not rendering. When I use a command 'ionic serve' it works well in safari browser. After deploying it into the iPad, the PayPal checkout button not shown.

2) After clicking PayPal checkout button, the total amount is send to PayPal server immediately. Is it possible to delay for 5 seconds?

**Comment by RoseWebOnly** [comment]
@pooventhirankp  do you slove the problem？ I’m in same situation

**Comment by githins** [comment]
@pooventhirankp 
Do you have any solution for this issue??

Thanks

**Comment by githins** [comment]
> It is working in Android but the button is not getting build up in iOS devices. The example which I am referring to is
> 
> https://developer.paypal.com/demo/checkout/#/pattern/client
> 
> I know that there are many other issues regarding this already raised but no one has got some useful solution so raising it again.
> 
> Also if there is any other way to integrate PayPal with Cordova please suggest that also.

I am having the same issue and can't find any solution!!!
Please help if you know any.

Thanks
