### ISSUE TITLE
Blank white screen after checking out on mobile facebook/instagram checkout webview. Ideas?

### ISSUE THREAD

**Issue by trojans10** [paypal/paypal-checkout#666]
When a user uses paypal via an ad from facebook or instagram. Users can't checkout due to a blank white screen at the end of the process. This only occurs when users come from an ad on a mobile phone. My issue was recreated via an iPhone iOS and instagram app.

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ x] Web View / Safari ViewController
- [ ] Other

**Comment by trojans10** [comment]
Hi Khangoang,

Is there a way to send you private screenshots?

**Comment by trojans10** [comment]
@khanghoang Sent you an email. Please advise. Thanks so much :) Does it have to do with our paypal version on our order form?

**Comment by khanghoang** [comment]
@trojans10 thanks, I got your email. I will get back to you on this.

**Comment by khanghoang** [comment]
@trojans10 After checking this issue carefully with the details you sent, we find out that you're using the different PayPal integration with the one this repo provides. With that being said, it's out of the scope of this repo.

**HOWEVER**, we suggest that you should take a look at [this documentation](https://developer.paypal.com/demo/checkout/#/pattern/client) to find a integration that works best for your case.
