### ISSUE TITLE
PayPal Checkout button not working at demo site in Firefox on iOS

### ISSUE THREAD

**Issue by coderintherye** [paypal/paypal-checkout#672]
## Description
When trying to debug a different issue (Express Checkout falls back to Hermes w/ Firefox on iOS on first checkout attempt if not already logged in, fallback occurs upon login) I attempted to use the demo site to test that Firefox is working in iOS. 

> All console logs during the time of the issue, especially error messages

Unfortunately, I can't seem to find a way to get a console in Firefox on iOS :(

> Does the issue also occur at developer.paypal.com/demo/checkout?

YES

### Steps to reproduce
1. Open Firefox on iOS
2. Go to developer.paypal.com/demo/checkout
3. Click on "PayPal Checkout" button under "Try the button"

### Expected result:
Checkout comes up

### Actual result:
Browser flickers and nothing comes up

### Affected browsers
[X] Firefox - Version 10.5 (8741)
[X] iOS - Version 11.2.6 (15D100)

Separately, Chrome fails, but with a different issue, new tab opens and immediately closes

**Comment by vishakha94** [comment]
@coderintherye Can you pls specify the env in which you found this issue?
I tried reproducing the issue on my ios device and could not reproduce it.

**Comment by coderintherye** [comment]
@vishakha94 As noted, Firefox Version 10.5, on iOS version 11.2.6 on an iPad. I can try again today to see if it works on an iPhone vs. iPad.

**Comment by vishakha94** [comment]
@coderintherye `env` === `'production'` or `'sandbox'`?

**Comment by coderintherye** [comment]
@vishakha94 As noted, it's not in my env, it's at the demo site developer.paypal.com/demo/checkout
The bug I want to file, over Firefox on iOS not working on the first try (when not logged in), I can't even file because the demo site itself is not working in order to be able to test it for that bug.

**Comment by coderintherye** [comment]
Note, works as expected on iPhone, specifically not working for me with Firefox on iOS on iPad with the above noted versions

**Comment by bluepnume** [comment]
Hi @coderintherye. Are you still seeing this issue?

**Comment by coderintherye** [comment]
@bluepnume This was resolved in the last two weeks I believe and we're seeing it working now, thanks!

**Comment by bluepnume** [comment]
Awesome! Thanks for confirming
