### ISSUE TITLE
Test Environment Not Consistent

### ISSUE THREAD

**Issue by joelcardinal** [paypal/paypal-checkout#674]
Similar to [issue 199](https://github.com/paypal/paypal-checkout/issues/199) we are having difficulty running our automation tests against non-production (test/sandbox) PayPal checkout as the PayPal experience does not consistently use an iframe.  Interestingly, the production experience of PayPal does not use an iframe.

I don't understand why the test/sandbox PayPal checkout experience is inconsistent.  Are you experimenting with an A/B test?  Is there anyway we can prevent these inconsistencies?  This has been an issue for quite some time and the only external service we use that has such inconsistencies.

**Comment by bluepnume** [comment]
Can you elaborate on when you're seeing the iframe? Particularly, which user-agent you're using?

**Comment by gregsandell** [comment]
@bluepnume, I am on Joel's team so I can answer that.  The iframe is on the login screen.  I'm attaching a screengrab that illustrates the iframe in Mac Sierra Chrome 65.  I get the exact same HTML using and Mac Sierra Firefox 59 and Sierra Safari 11.1.  Is that specific enough user-agent info?
<img width="1322" alt="paypaliframe" src="https://user-images.githubusercontent.com/777014/39376928-386aacc4-4a08-11e8-94db-7105c5e21c6c.png">

**Comment by bluepnume** [comment]
Aaah ok, gotcha. Didn't realize you meant that iframe. So apologies, but this is just one of those things; occasionally the implementation is going to change, and if any tests rely on implementation details, they're likely to break too. 

That said, the experience should at least be consistent on sandbox. I'll double check on that on our side.
