### ISSUE TITLE
Error: Window did not load after Infinityms

### ISSUE THREAD

**Issue by hootlex** [paypal/paypal-checkout#675]
### Description
The last 5 days this error occurs for many customers.

`Error: Window did not load after Infinityms`

When this error happens, the popup window doesn't open and thus the purchase process stops.

Unfortunately, I cannot reproduce. We keep seeing this error on Sentry, and today we got a screenshot with the console errors from a customer.

The solution was to clear browser's cache and try again.

This issue might be related to the `post-robot` integration, that I see that changed [a couple of days ago](https://github.com/paypal/paypal-checkout/compare/v4.0.199...master), really close to when the errors started showing up.

----

- Screenshots or videos that show the issue

![](https://i.imgur.com/Co5fERm.png)
![](https://i.imgur.com/3i73hTM.png)

- Your code

The code has been the same for months. The issue first happened on April 25th 1:50 AM UTC.

- The `paypal.version` from your browser console

Not sure

- The exact browser version

According to Sentry, it happens in many browsers, including Chrome v66.

- A link to your page with the issue, if possible

https://vueschool.io/enroll/the-vuejs-master-class

- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?

Don't know

- Does the issue occur consistently, or intermittently?
Consistently. Since it first occured, it happens a couple of times a day and no clients have managed to make a purchase using PayPal, which is really unusual.

### Affected browsers

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge
- [x] IE
- [x] Chrome Mobile/Tablet
- [x] Safari Mobile/Tablet
- [X] Web View / Safari ViewController
- [X] Other

**Comment by bluepnume** [comment]
Good catch. This should now be resolved -- can you let me know if you still see the issue?
