### ISSUE TITLE
in context checkout turn to full page redirect after error recovery

### ISSUE THREAD

**Issue by alumbroso** [paypal/paypal-checkout#677]
### Description

Please provide a short description of the issue here, along with:

whilst in context checkout that when pressing "not you" link after the error recovery (AKA 10486) i am being redirected to a full page login rather than keeping it in context . it doesn't reproduce when clicking the link on a normal checkout flow . 

### Steps to reproduce
- opt to one touch
- perform a checkout on paypal in context
- provide a funding method that will fail and will return a 10486 error.
- implement action.restart() to restart the PayPal flow .
- click the "not you" link on the paypal review page.
Please provide each individual step required to reproduce the issue

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
@abarco could you take a look? Thanks!

**Comment by abarco** [comment]
Resolved, awaiting push

**Comment by abarco** [comment]
issue resolved
