### ISSUE TITLE
PayPal SPB & APM Button aren't responsive to Mobile view

### ISSUE THREAD

**Issue by gautia** [paypal/paypal-checkout#680]
PayPal SPB & APM Button aren't responsive to Mobile View

I have integrated PayPal client-side REST for the website https://contented-solopreneur.com/contented-solopreneur-consultation/ which is really good in web view but not aligned properly in Mobile View

- 
![image](https://user-images.githubusercontent.com/24381783/39660615-82a822d6-5060-11e8-9d3d-9abbff1cddf3.png)

- paypal.Button.render({
            env: 'production', // sandbox | production
			style: {
            layout: 'vertical',  // horizontal | vertical
            size:   'responsive',    // medium | large | responsive
            shape:  'rect',      // pill | rect
            color:  'gold'       // gold | blue | silver | black
        },
           // PayPal Client IDs - replace with your own
            // Create a PayPal app: https://developer.paypal.com/developer/applications/create
            client: {
                sandbox:    'AZDxjDScFpQtjWTOUtWKbyN_bDt4OgqaF4eYXlewfBP4-8aqX3PiV8e1GWU6liB2CUXlkA59kJXE7M6R',
                production: 'AdhIabEf6ediLxDvLHomRF2sK1qSFbj_s61PGWZYVEchWcFKcQBR7R7kAlt0yyFSlj_asiqN8URtqh4t'
            },
- 

### Steps to reproduce

Please provide each individual step required to reproduce the issue

### Affected browsers

- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController

**Comment by trainerbill** [comment]
I went to your site and it was displaying properly in chrome mobile mode for every device.

<img width="446" alt="screen shot 2018-06-06 at 1 04 56 pm" src="https://user-images.githubusercontent.com/3578259/41056618-662778f8-698a-11e8-9a86-bd9fdc06eb61.png">
