### ISSUE TITLE
ppxo_paypal_legacy_gettoken_initxo when user close dialog before load ?

### ISSUE THREAD

**Issue by psppro26** [paypal/paypal-checkout#681]
When user close the dialog pop up before it loads , the pop dont appear anymore before refresh ! 
with this error message :  ppxo_paypal_legacy_gettoken_initxo
I use the last prestashop paypal module on 1.6

**Comment by bluepnume** [comment]
This is now an unsupported integration. I would suggest asking prestashop to upgrade to the latest PayPal integration.
