### ISSUE TITLE
What fields are editable on payment execute call?

### ISSUE THREAD

**Issue by vblagomir** [paypal/paypal-checkout#685]
### Description

It is stated in the API documentation https://developer.paypal.com/docs/api/payments/#payment_execute
that the Request body transaction array contains the 'cart_base' object, and "For update and execute payment calls, the transactions object accepts only the amount object."

Yet I have managed to add 'invoice_number' during the payment execution, for example:

```
        {
          payer_id: 'some-payer-id',
          transactions: [{
            amount: {
              currency: 'USD',
              total: '0.99'
            },
            custom: `some-custom-field`,
            invoice_number: 'some-invoice-number'
          }]
        }
```
After executing the payment with the above mentioned parameters, I can see both the 'invoice_number' and 'custom' fields on payment execution response,  but only 'invoice_number' gets actually attached to the transaction (and I can see it in the Transaction details in sandbox business account), whereas the 'custom' field seem to be ignored without any error whatsoever. Both are attached to transactions if added during payment creation (not execution).

### Questions
1. Is the official documentation misleading and should it state instead "..accepts amount object and invoice_number"?
2. What fields are indeed can be added/amended during payment execution?

**Comment by bluepnume** [comment]
@trainerbill can you help answer this one?

**Comment by trainerbill** [comment]
@vblagomir I have recreated your issue here:

https://github.com/paypal/PayPal-REST-API-issues/issues/245

Since it is with our REST api product.
