### ISSUE TITLE
Support for integration tests

### ISSUE THREAD

**Issue by Dunnymeister** [paypal/paypal-checkout#686]
Related to both #199 and #674, we are trying to automate the PayPal sandbox purchase process to ensure that we're not breaking our integration. It appears as though there are roughly four different login pages at the moment that can be presented to the user at the moment which makes testing difficult.

So the PayPal purchase process can be included as part of our integration tests, could you please consider:

- Supplying a way to force a particular login form style (sandbox only is fine), or
- Writing some documentation that includes the markup on the pages so we can write xpath/css queries to access the input elements via selenium

**Comment by davefx** [comment]
Yes, please, allow sandbox users to specify a login form style.

**Comment by bluepnume** [comment]
Closing this issue as it's not specific to the checkout.js integration script, and unfortunately we can't offer guarantees of html selectors staying exactly the same over time.

**Comment by davefx** [comment]
I completely understand that html selectors must evolve following the progress of the PayPal production environment. However, it would be really nice if you keep _somewhere_ information about what is changing so adapting the tests to the new version may be much more easy for us, users of the sandbox.
