### ISSUE TITLE
First call to logger sends wrong info (React, IE11/Edge)

### ISSUE THREAD

**Issue by georgiosd** [paypal/paypal-checkout#687]
- Description

Using paypal-checkout with React, in IE11 specifically, the first request to logger contains the wrong info.

Using fiddler I see that the first POST has sandbox info in Chrome but production info in IE11.

- Your code

```
render() {
        const PayPalButton = paypal.Button.driver('react', { React, ReactDOM });
        return <PayPalButton
                                    env={window.appSettings.paypal.isSandbox ? 'sandbox' : 'production'}
                                    locale={'en_US'}
                                    style={ { size: 'responsive', color: 'gold', shape: 'rect' } }
                                    commit={true}
                                    validate={validate}
                                    onClick={gotoValidationStep}
                                    payment={createPayment}
                                    onAuthorize={executePayment}
                                    onCancel={cancelPayment} />
}
```

- The `paypal.version` from your browser console

`"paypal-checkout": "^4.0.202",`

- The exact browser version

Win 10, Microsoft Edge 41.16299.402.0

- A link to your page with the issue, if possible

https://demo.deliverback.com

- All console logs during the time of the issue, especially error messages

```
HTML1300: Navigation occurred.
 CSS3121: The media query -ms-viewport has been deprecated.
ie_meta_compatibility_header_missing [object Object]
SEC7120: Origin https://demo.deliverback.com not found in Access-Control-Allow-Origin header.
 HTTP403: FORBIDDEN - The server understood the request, but is refusing to fulfill it.
(XHR)POST - https://www.paypal.com/webapps/hermes/api/logger
```

- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?

No

- Does the issue occur consistently, or intermittently?

Consistently

### Steps to reproduce

- Load page

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [x] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Are you just concerned with the call to /logger, or is there a bug here which is causing an actual issue for checkouts?
