### ISSUE TITLE
Paypal certificate used to load resources

### ISSUE THREAD

**Issue by chefuss** [paypal/paypal-checkout#691]
Hi I just find that chrome is advising that PayPal use a systematic certificate, and soon users will start to see a notice that the page is not private.

"The SSL certificate used to load resources from https://www.paypal.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information."

What should we do about this? is PayPal going to fix this? because if the notice starts to appear user will find our site as not private, and we will start to have issues with this, is hard to explain to user that is not our site, is PayPal, and the payment method is not secure!. 

Thanks, and sorry for my english, maybe this is not the place to put my question, but couldn't find a better place.

**Comment by khanghoang** [comment]
@chefuss thanks for reporting this, I will let my team know and we will follow up with you on this.

**Comment by trainerbill** [comment]
This is known and we have a team working on it.  Will be resolved by the release of chrome 70.

**Comment by eliotsykes** [comment]
For developers hitting this already, here's a couple of suggestions that can help depending on your situation:

#### 1. Check existence of `paypal` before using it:

```js
function isPaypalAvailable() { return !!window.paypal; }
if (isPaypalAvailable()) { paypal.Button.render(...) }
```

Admittedly this may only be helpful if you've got other non-Paypal payment methods.

#### 2. Self-host paypal checkout.js

Some guidance here: https://github.com/paypal/paypal-checkout/blob/master/docs/cdn-npm.md

**Comment by trainerbill** [comment]
Update:  The new certs will be going in the next few weeks with the last being targeted for completion the week of August 6.

@UserCentrix this should not be preventing your site from taking payments.

**Comment by najmulbasit-360training** [comment]
This is what is happening for PayPal Express checkout, page, this doesn't load properly due to resources in chrome. something going wrong.

dom.js:95 GET https://www.paypalobjects.com/web/res/019/65173d3c7f3abd282157c6a6b370d/locales/PK/en.js 404 ()

https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-7SM803396T7828254#/checkout/genericError?code=RETRY

![image](https://user-images.githubusercontent.com/17830278/43132951-b8f6675a-8f56-11e8-8ae0-23f83b2c8bc2.png)

**Comment by crookedneighbor** [comment]
Any update on this? We're past the previously stated August 6th date.

**Comment by jimster480** [comment]
Last week? 
It is the last week of August now... All the updates are rolling out for browsers everywhere and people cannot pay.
I had to revert one of my browser versions just to be able to browse to paypal.

**Comment by tituscrow82** [comment]
Probably should open this back up since it was never actually fixed.

**Comment by trainerbill** [comment]
https://medium.com/paypal-engineering/migrating-to-digicert-root-certificates-eee71f6aabc7
