### ISSUE TITLE
Checkout button in sandbox env hangs after logging in IE11

### ISSUE THREAD

**Issue by OliverJEvans** [paypal/paypal-checkout#695]
### Description

PayPal Checkout button in the interactive demo hangs in sandbox env after entering sandbox login details on IE11. But works fine when in production mode.

I'm having this issue on my own site, but thought I'd use the interactive demo as a test to ensure it wasn't just my code that was causing the issue and there was in-fact an issue with the sandbox env itself.

Tested on multiple networks, ran in browserstack Win10 IE11 VM and an actual local IE11 on Win10. 

- **Gif of actions:** ![tkyid1qrol](https://user-images.githubusercontent.com/4497135/40429113-c7780ec0-5e99-11e8-927b-ab7106a37c14.gif)
- **Code:** Using interactive demo in sandbox mode
- **Paypal Version:** What ever is being used in the interactive sandbox
- **Browser Version:** IE11 (11.540.15063.0)
- **Link:** https://developer.paypal.com/demo/checkout/#/pattern/checkout
- Consistent issue

### Steps to reproduce

Navigate to interactive demo in IE11 browser, ensure in sandbox mode, click checkout button, click login in popup window, enter sandbox details, hit login....observe issue.

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [x] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Can you clarify; can't really see what happens after the gif ends. Does it break, or are you eventually able to complete the payment?
