### ISSUE TITLE
"Checkout" component isn't available

### ISSUE THREAD

**Issue by wchiquito** [paypal/paypal-checkout#698]
### Description

"Checkout" component isn't available from my domain, but it's available from the domain developer.paypal.com.

From developer.paypal.com
![paypalcom](https://user-images.githubusercontent.com/978213/40573187-a3f1d7b4-60ac-11e8-8f32-6265591a500a.png)

From my-domain.net or [JSFiddle](https://jsfiddle.net/zh2qb1ee/)
![mydomainnet](https://user-images.githubusercontent.com/978213/40573317-449f6b98-60af-11e8-8f10-dd9f9aa02d57.png)

**Comment by bluepnume** [comment]
Yup. That's by design. Please use the Button component.
