### ISSUE TITLE
PayPal popup issues in Firefox 60

### ISSUE THREAD

**Issue by samleetucker** [paypal/paypal-checkout#700]
### Description

If you launch the PayPal popup in Firefox and then click away, the popup stays behind the window and isn't brought to the foreground when clicking anywhere on the overlay or the "Continue" link. 

You can reproduce on the PayPal demo site (https://developer.paypal.com/demo/checkout/). Issue is consistent.

Testing in Firefox 59.0.2 and 60.0.1 - reproduced in both.

### Steps to reproduce

1. Click the PayPal Checkout button to launch the popup. 
2. Click away from the popup to send it to the background.
3. Attempt to click the overlay or the "Click to Continue" link to bring the popup back to the foreground.

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [x] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by abarco** [comment]
firefox has disabled that functionality for a while. Doesn't look like there's any other way we can support this for this browser. 

https://support.mozilla.org/en-US/questions/1174220

**Comment by fzan** [comment]
Hello,

It's possibile at least to remove the Message in the shaded background, if the browser is Firefox? In this case, maybe a localized message that ask the user to finish the payment in the popup, and no action? Seems more correct to me :)

**Comment by gety9** [comment]
Any way to solve this? It's makes paypal checkout UX far from ideal on FF. There are still lots of users for that browser.

**Comment by acomito** [comment]
@abarco Just to be clear, should we be telling our users that paypal doesn't support payments from firefox?

**Comment by bluepnume** [comment]
No -- we absolutely support payments from Firefox. This is just a corner-case around refocusing the PayPal window.

**Comment by bluepnume** [comment]
Closing this as there's no known fix. Calling `focus()` isn't working in Firefox; seems to be no way around that.

**Comment by qetzal** [comment]
What about this suggestion from @fzan ? 
> It's possibile at least to remove the Message in the shaded background, if the browser is Firefox? In this case, maybe a localized message that ask the user to finish the payment in the popup, and no action? Seems more correct to me :)
