### ISSUE TITLE
Set a limit of time to complete the payment.

### ISSUE THREAD

**Issue by menobra** [paypal/paypal-checkout#709]
Sorry if this is not a real issue, but i'm not sure where to post it neither how to set it up.

My question is: Is there any way to pass to the paypal script a time limit that the client has to complete the payment? and if the payment doesn't complete before the time limit exceeds, it runs the "onCancel:" functions.

Thank you beforehand!

**Comment by menobra** [comment]
I would like to specify in which case this would be usefull in my opinion: 
I have the "onClick: " parameter with it's functions when a user clicks on the paypal button.
I set the status of a reservation on "pending" when the user clicks on the button.
If client completes the payment status changes to "completed"
if he cancels it removes the reservation from my database.

But i think of a case where a client loses it's connection to internet and the reservation with "pending" status never gets deleted.

**Comment by bluepnume** [comment]
If you'd like, it should be possible to implement this yourself with some kind of `setTimeout` or periodic check for connection.
