### ISSUE TITLE
NVP checkoutNow, Unhandled api error

### ISSUE THREAD

**Issue by louiewiget** [paypal/paypal-checkout#719]
Hi everyone,
I am using SetExpressCheckout to do a payment, when I use "sandbox" to checkout, call the url "https://www.sandbox.paypal.com/webapps/hermes?flow=1-P&ulReturn=true&token=EC-9HS660411K158782G&country.x=CN&locale.x=zh_CN#/checkout/login&arc=1"  
it remain in "Securely logging you in...", and the page api "https://www.sandbox.paypal.com/webapps/hermes/api/checkout/EC-9HS660411K158782G/session/create" return **500 Internal Server Error**

Any help is welcome and thank you very much in advance,
Louie

in Google Chrome (Version  67)
Error
Status Code: "500 Internal Server Error"
Response of the PAYMENT API request from  "https://www.sandbox.paypal.com/webapps/hermes/api/checkout/EC-9HS660411K158782G/session/create" 

{"ack":"error","message":"Unhandled api error","meta":{"calc":"67eaf55c4c8","rlog":"RSKMc1pHz9j5qiE2NcrmPTrKSGKIqV0PieuDmlYz0%2BVQT6LWYUNrtn8abYqExCiTeEJD3AD6ZlfdNQBLz57PiQ_1641cdc803e"},"server":"A4m9IkFViPZ53qLxyB21yyqpLOxZZg_gro6k9r-MKdy9lHHH6I00wWCKiE0xVx0Cq-Fnroz0s110SW7IzAGaOZQua2iySGqbSmMzffZjzS9UWHtszAO3BIEUcQCs0vcFd7J0ltvJ5279oi1vuAUykfzmTbfG5K-KE4gKJYPBrsIJYICzmZ2iYVN4vUCWehp4CfVLEaB49DeE-1D5QWKZU48kCdE0ES5pcGusDY_DQD2E6-yvHp1WchN9i8nGgKu0Mc7oPnKB2NFSBK4QLuAvUm"}

**Comment by louiewiget** [comment]
seem to be ok. sandbox unstable?

**Comment by dudj** [comment]
您最后是怎么处理的呢

**Comment by bharatranpariya** [comment]
I got same error. any help on this ? is there any issue at our side ?

**Comment by florinmoqups** [comment]
`{"ack":"error","message":"Unhandled api error","meta":{"calc":"808d42a7e36a6","rlog":"7KSbBC9OtfFUbheAZYBtgInTI0i7Ufd6v0UzhvWAxrDbFGPtmYzn9DXwXfiY4tUDxmpYJRZViK7rWo7KfEgKiw_166aae51696"},"server":"QPMzfJ13U4fLQ6p_HaS6p7AVUl1yHwhkmTZN09NTS0J-_BAeBrf8DdiYiF4FWQ7H4EWJUrjvty-8dpKsoiZ7rsZ3HCddpHhPHp0lWhiKnSRVsERaFz9DUaGa4hySMjVFdbd0P5btN5LUPuzieKca9HkIhCUKGF19QCIGHAeOQRH7abkqZOzucv6Q5UP9i8kxX8ahbq3Fwdu8kSUxJqKZnvnDU8m4qWKMK3udV1PyXsBY7K82RoL4iLjJ3uTjXSz-ivrkmT00XuKG36SiM3aXhG"}
`

I have same issue

**Comment by florinmoqups** [comment]
It is working now for me. Probably something was not right on Paypal sandbox infrastructure.

**Comment by lotsofdan** [comment]
Can confirm, we're back :1st_place_medal:
