### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by reggarcia** [paypal/paypal-checkout#722]
My index.html file has this:

<code><script src="https://www.paypalobjects.com/api/checkout.js" data-version-4="" data-log-level="error"></script></code>

And I'm seeing this warning on Chrome console:

![image](https://user-images.githubusercontent.com/3925319/41689464-8ea0c3f4-74a5-11e8-96d7-02b2c6ec80ee.png)

Is there anything being done to address this?

**Comment by wchiquito** [comment]
See [Paypal certificate used to load resources #691](https://github.com/paypal/paypal-checkout/issues/691).

**Comment by vishakha94** [comment]
@trainerbill Can you pls comment here?

**Comment by trainerbill** [comment]
We will release a new SSL certificate before the deadline.

**Comment by tituscrow82** [comment]
Still not fixed,  what deadline date is PayPal targeting to complete the update?

**Comment by pillimoj** [comment]
Is this in progress? It is september now.
