### ISSUE TITLE
Does paypal.Button.render make a request to checkout.js?

### ISSUE THREAD

**Issue by lbrito1** [paypal/paypal-checkout#723]
Hi,

Calling `paypal.Button.render` seems to make a request to get checkout.js, which to me does not make a lot of sense. Is this expected for some reason?

Here's a jsfiddle demonstrating: https://jsfiddle.net/lbrito/szmajqc6/10/ . The requests when running:

![paypal](https://user-images.githubusercontent.com/2048939/41715284-d9005f9a-754a-11e8-8ab4-a6ae8dcab726.png)

The first `checkout.js` request comes from the `<script>`, as expected. Here's the initiator for the second request, which I assume is somewhere within the render function:

```js
<script src="https://www.paypalobjects.com/api/checkout.js" data-paypal-checkout data-no-bridge data-state="ppxo_meta" data-env="sandbox" }></script>
```

So I end up with two separate requests to essentially the same file. Am I overlooking something?

**Comment by jontrueandco** [comment]
No. That seems accurate, and weird on paypal's behalf. I agree with combining the scripts.

**Comment by lbrito1** [comment]
Okay, just read this:

>The reason for this is, the script is also loaded inside the button iframe and checkout popup window, in order to communicate with the parent window. Loading from the CDN means your users' browsers will cache the script, otherwise it will be re-downloaded inside the iframe/popup.

https://github.com/paypal/paypal-checkout/blob/362401ddce61a271942b8f44c083b5b8b8f78850/docs/performance.md

I think that explains my question. If some contributor could confirm, that'd be nice.

IMO I think this is a pretty important piece of info and should be highlighted somewhere in the README or at least higher up in the docs than in that specific section.

**Comment by wchiquito** [comment]
I can't reproduce the problem, using the jsfiddle indicated by you ([https://jsfiddle.net/lbrito/szmajqc6/10/](https://jsfiddle.net/lbrito/szmajqc6/10/)), the second request was obtained from the cache (Chrome: 67.0.3396.87):

![paypal](https://user-images.githubusercontent.com/978213/41734223-d4fe4314-7575-11e8-98a8-d1f70c3db943.png)

**Comment by lbrito1** [comment]
Darn, I had "disable cache" ticked :man_facepalming:  all's clear to me now, thanks.
