### ISSUE TITLE
paypalobjects.com (checkout.js and checkout.min.js)

### ISSUE THREAD

**Issue by wchiquito** [paypal/paypal-checkout#724]
When will the minified script be in the most recent version?:

https://www.paypalobjects.com/api/checkout.js -> Version: 4.0.204
https://www.paypalobjects.com/api/checkout.min.js -> Version: 4.0.203

**Comment by vishakha94** [comment]
We are currently having issue with our deploy and are looking for the most up to date release timeline for next week.

**Comment by Andyyyyyyyyyyyyyy** [comment]
@vishakha94 I am trying to make a multivendor website which uses PayPal and payments are direct from customer's PayPal to seller PayPal and I found this from looking through the code on another site and I think it might be what I need. I am not a programmer so I don't really understand what this is but I am thinking it could be the answer to my problem I have been stuck on for months. If you could contact me back I would really appreciate it and I will even pay for your help. I hope to hear from you - Andy
