### ISSUE TITLE
Crashes in google chrome since 67 version

### ISSUE THREAD

**Issue by parko** [paypal/paypal-checkout#731]
### Description

Reproduce only in Google Chrome desktop since 67 (linux, windows) version (66 version on desktop and all mobile Chrome and other browsers is ok)

After click on Paypal button I see modal window, but after 1-3 second it closed automatcly with error in console:

ppxo_unhandled_error {stack: "Error: No ack for postMessage postrobot_method in …ww.paypalobjects.com/api/checkout.min.js:1:62437)", errtype: "[object Error]", timestamp: 1530717411553, windowID: "371d57ac7f", pageID: "a556aa95c8", …}

"Error: An error was encountered while handling error:

 Error: No ack for postMessage postrobot_method in https://www.paypal.com in 2000ms
    at cycle (https://www.paypalobjects.com/api/checkout.js:2859:73)

Error: No ack for postMessage postrobot_method in https://www.paypal.com in 2000ms
    at cycle (https://www.paypalobjects.com/api/checkout.js:2859:73)
    at https://www.paypalobjects.com/api/checkout.js:6174:27
    at _loop (https://www.paypalobjects.com/api/checkout.js:8323:42)
    at ZalgoPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:8337:57)
    at ZalgoPromise.reject (https://www.paypalobjects.com/api/checkout.js:8298:22)
    at https://www.paypalobjects.com/api/checkout.js:8335:37
    at _loop (https://www.paypalobjects.com/api/checkout.js:8323:42)
    at ZalgoPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:8337:57)
    at ZalgoPromise.reject (https://www.paypalobjects.com/api/checkout.js:8298:22)
    at _loop (https://www.paypalobjects.com/api/checkout.js:8325:41)
    at ZalgoPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:8337:57)"

### Affected browsers

- [x] Chrome since 67 version
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Can you please answer the other questions to help us debug?

- Your code
- The exact browser version
- A link to your page with the issue, if possible
- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
- Does the issue occur consistently, or intermittently?

**Comment by parko** [comment]
I found the problem:

My code looks like this:
`                    paypal.Button.render({
                        env: 'production', // Or 'sandbox' or 'production',
                        commit: true, // Show a 'Pay Now' button
                        style: {
                            color: 'gold',
                            size: 'small'
                        },
                        payment: function (data, actions) {
                            let params = {'action': 'create'};
                            let payment = MarketAPI.executeOrder(that.order.id, that.constants.PAYMENT_SYSTEMS.PAYPAL, params, false);
                            if (payment.processed) {
                                that.successfullyBuy();
                            }
                            that.paymentId = payment.params.paymentId;
                            return that.paymentId;
                        },
                        onAuthorize: function (data, actions) {
                            let params = {
                                'action': 'execute',
                                'paymentId': data.paymentID != null ? data.paymentID : that.paymentId,
                                'payerId': data.payerID
                            };
                            let payment = MarketAPI.executeOrder(that.order.id, that.constants.PAYMENT_SYSTEMS.PAYPAL, params, false);
                            if (payment.processed) {
                                that.successfullyBuy();
                            }
                        },
                        onCancel: function (data, actions) {
                            Common.reloadPage();
                        },
                        onError: function (err) {
                            /*
                             * An error occurred during the transaction
                             */
//                    Common.reloadPage();
                        }
                    }, '#paypal-button');`

And if I change payment callback on code:
`return 'EC-6DJ64914TA163730D';`

its works fine. Function Market.executeOrder execute in 3-4 seconds and this is to much for PayPal component in Chrome 67. Can I increase aprove timeout for this callback?

**Comment by parko** [comment]
I change payment method with promise: 
```
payment: function () {
                    return new paypal.Promise(function(resolve, reject) {
                        let params = {
                            'action': 'create',
                            'use_billing_agreement': that.recurring
                        };
                        MarketAPI.executeOrder(that.order.id, that.constants.PAYMENT_SYSTEMS.PAYPAL, params, true,
                        function(data) {
                            if (data.processed) {
                                that.successfullyBuy();
                                return;
                            }
                            that.paymentId = data.params.paymentId;
                            resolve(that.paymentId);

                        });
                    });
                }
```

and it works fine now in chrome 67 too.
