### ISSUE TITLE
the documentation should explain about the env:'sandbox' option

### ISSUE THREAD

**Issue by flyon** [paypal/paypal-checkout#732]
I only filled in the sandbox clientId:

    let client = {
			sandbox:    'Af3u...', // from https://developer.paypal.com/developer/applications/
			production: 'xxxxxxxxx'  // from https://developer.paypal.com/developer/applications/
		};

but I kept getting an error that xxxxx is invalid.
took me quite a while to find out that I could use env:'sandbox' to switch to sandbox environment. This isn't stated in the examples or documentation anywhere and in my opinion should be added here: https://github.com/paypal/paypal-checkout/blob/master/docs/button.md#basic-integration

**Comment by bluepnume** [comment]
Please see the main set of docs here: https://developer.paypal.com/docs/checkout/
