### ISSUE TITLE
Paypal popup window incorrectly centered.

### ISSUE THREAD

**Issue by pkoutsogiannis** [paypal/paypal-checkout#734]
### Description

Paypal window after clicking on the paypal button is incorrectly centered on multi monitor systems and 
browser is in maximized state.

- Open a chrome browser in maximized state on a monitor that it is not in a centered position.
- Navigate to http://datasteam.com/pos/paypal/test-paypal-button.php
- Click on the button.
- Popup window incorrectly centered (not centered inside the browser's monitor bounds) 
- Restore and re-maximize the browser window
- Popup window correctly centered

Video demonstrating the behavior: https://webrtcweb.com/RecordRTC/uploads/RecordRTC-2018610-3pdmfk6w6wv.webm

(This is the 3rd monitor in my multi-monitor setup: 1 - 2 - 3)

### Affected browsers

- [x] Chrome (67.0.3396.99 on Windows7)
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
@mcntsh can you take a look at this one?

**Comment by pkoutsogiannis** [comment]
Added a video: https://webrtcweb.com/RecordRTC/uploads/RecordRTC-2018610-ciufzuhc6g.webm

**Comment by pkoutsogiannis** [comment]
Added a video: https://webrtcweb.com/RecordRTC/uploads/RecordRTC-2018610-3pdmfk6w6wv.webm

**Comment by mcntsh** [comment]
Good catch @pkoutsogiannis. I've identified the cause of this issue and I'm working on a fix right now.

**Comment by mcntsh** [comment]
Following back up here... [this appears to be a bug with Chrome](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-bugs/oHtZDAKp1EU) that remains unresolved. 

From our perspective, we are using the `window.screenLeft` and `window.screen.width` to determine the position to display the popup, but Chrome doesn't have the correct values if the browser is flushed against the left side of the non-primary monitor. At this point, it doesn't seem like there's much we can do unfortunately.

**Comment by mcntsh** [comment]
https://github.com/paypal/paypal-checkout/issues/734#issuecomment-430390039

**Comment by mc1973** [comment]
Hello. I know this is an old thread but I am expierencing this very same issue and was wondering to fix. Happening in multiple browsers.
