### ISSUE TITLE
How to make an autoclick on paypal checkout button?

### ISSUE THREAD

**Issue by ciltocruz** [paypal/paypal-checkout#735]
Hello!!

I have a personalized payment page with our own designs.

I want to hide the button generated by paypal checkout and have an automatic click on this button.

How can I access the id or name of the button to make a javascript click event?

Thanks!

**Comment by bluepnume** [comment]
Sorry, this use-case is not supported. We require you to use the paypal button to trigger the paypal checkout flow.
