### ISSUE TITLE
PayPal Review Page returning customers to the cart page inside of Twitter Mobile App

### ISSUE THREAD

**Issue by ryanmof** [paypal/paypal-checkout#736]
### Description

When you are using the twitter mobile app on iOS, and go to a merchants website within the twitter mobile browser it allows you to login to PayPal, but then redirects you back to the merchants cart page instead of directing you back to the merchants checkout flow. This seems to only be happening with JSv4 integrations.

Please provide a short description of the issue here, along with:

- Screenshots or videos that show the issue - Video already send to @bluepnume in Slack
- Your code
- The `paypal.version` from your browser console
- The exact browser version - Twitter Browser inside Twitter App
- A link to your page with the issue, if possible
- All console logs during the time of the issue, especially error messages
- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
- Does the issue occur consistently, or intermittently?

### Steps to reproduce

- Open up Twitter mobile app
- Go to @kendrascott or any website that has JSv4(Ex kendrascott.com, campingworld.com etc)
- Add item to cart
- Click JSv4 PayPal button
- Login
- Click Continue
- It then returns you to the merchants cart page, instead of their shipping or complete order page.
- And then the PayPal button is no longer clickable on kendrascott, but on a Shopify store it was clickable the 2nd time.

Please provide each individual step required to reproduce the issue

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [X ] Web View / Safari ViewController (Twitter)
- [ ] Other

**Comment by bluepnume** [comment]
@mcntsh can you investigate this one?

**Comment by mcntsh** [comment]
This fix went out in yesterday's release and appears to be resolved!
