### ISSUE TITLE
Checkout.js disable AMEX cards in payment method

### ISSUE THREAD

**Issue by oranze** [paypal/paypal-checkout#740]
How to disable, like example, AMEX card in payment methods?

**Comment by bluepnume** [comment]
You can set:

```javascript
funding: {
    disallowed: [ paypal.CARD.AMEX ]
}
```

**Comment by oranze** [comment]
bluepnume Also I try few times on LinkedIn and Facebook contact you. You, for mistake, got one payment, can you please make it charge back?

**Comment by bluepnume** [comment]
I've refunded the payment -- can you please check?

**Comment by oranze** [comment]
Good morning,
all fine, customer get money back. Thanks a lot.


>Среда, 18 июля 2018, 1:14 +02:00 от Daniel Brain <notifications@github.com>:
>
>I've refunded the payment -- can you please check?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Mihails Atamanskii
