### ISSUE TITLE
X-Frame-Options set to SAMEORIGIN in webview iframe

### ISSUE THREAD

**Issue by TheOddLinguist** [paypal/paypal-checkout#742]
## Summary

We were experiencing an issue with the checkout modal in webviews embedded in our native (JS) mobile app. It would fail to load beyond login, hanging on a white screen and throwing an error that it refused to display content from paypal.com because `it set 'X-Frame-Options' to 'sameorigin'`. The issue **has since resolved itself**, but I'm concerned–not knowing what caused it in the first place–that it may come back without us realizing.

## Description

We have (what I'm guessing is) a fairly standard implementation of the PayPal checkout button on a page in our site. (Current state of code below) It's used for recurring subscriptions: communicating with our server to create the agreement, passing the token back to the checkout library to handle the PayPal login and approval, and finally sending us the token of the agreement so we can execute it on our end.

Starting around June 13, we began to get support tickets from our customers saying that the "PayPal button just brought up a white screen" and that they couldn't proceed with the payment. After some investigating, we noticed that it was only affecting our iOS and Android apps (which display our site in a native webview). I was able to confirm that I could not only replicate in the apps themselves, but also by altering the user agent in my computer's browser to force the checkout button to render the iframe modal rather than the new tab/window.

Interestingly, I was only able to replicate on our production site (https://www.bark.us), but not with my local development environment–even when communicating with the production PayPal server.

## Details

I logged some information about the requests my browser was making in both environments:

---

**PayPal Debug ID**: 254496541a07c
This was my local environment, running the Bark webapp in production mode, pointing to PayPal's production environment, with the user agent altered to force the iframe modal. There was no `X-Frame-Options` header in any of the responses from `https://www.paypal.com/signin?intent=checkout`, and the request after signing in properly redirected with a `302` to the payment options screen (at which point I could complete the transaction).

(One interesting note is that the login screen in this setup was one form, displaying both username/password; whereas the requests from the actual production environment had two forms: one for username, followed by another for password.)

**PayPal Debug ID**: 4ed8f41dbbb1
This was the production environment, pointing to PayPal's production environment, with the user agent altered to force the iframe modal. This time, the response from the second request to `https://www.paypal.com/signin?intent=checkout` included an `X-Frame-Options` header with the value `SAMEORIGIN`. This appears to be the root of the issue, but I can't figure out why it's happening.

---

We had to move on to some other feature work, so we disabled the PayPal option in the native app and let it go. I've now returned to the problem and wanted to gather some more data to submit this issue, but it appears to be working now. (Debug IDs `600ccf63601c8`, `c3e4c0a1db99e`, `8904e29dc8109`, and `91b809e45bebd` were all part of the recent successful login)

So, I apologize for posting an issue that has resolved itself (and with such verbose detail), but I'm concerned that we didn't quite get to the bottom of it. I'd rather understand what might have happened and how to fix/avoid it in the future so I can feel confident that we've got it covered.

Please let me know if there's any more information I can provide to help figure out where the problem arose, and I sincerely appreciate your time looking into it. Thanks!

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [x] Web View / Safari ViewController
- [ ] Other

### Current Version of our Button Implementation

```js
paypal.Button.render({
  env: $("#paypal-button").data("env"),
  commit: true,
  payment: function(resolve, reject) {
    var errors, log;
    errors = document.getElementById('card-errors');
    errors.textContent = '';
    log = new App.Log("clicked_paypal_button");
    log.save();
    return paypal.request.post(CREATE_AGREEMENT_URL, {
      plan: $('input[name=plan]:checked').val()
    }).then(function(response) {
      if (response.success) {
        return response.agreement.token;
      } else {
        errors = document.getElementById('card-errors');
        errors.textContent = response.error;
        return reject(response.error);
      }
    });
  },
  onError: function(err) {
    return console.log(err);
  },
  onAuthorize: function(data) {
    return paypal.request.post(EXECUTE_AGREEMENT_URL, {
      token: data.paymentToken
    }).then(function(response) {
      if (response.success) {
        Turbolinks.visit(response.redirect);
      } else {
        console.log(response);
      }
    });
  }
}, '#paypal-button');
```

**Comment by bluepnume** [comment]
Sounds like this was a temporary issue that was fixed. Please let us know the moment you see anything like this again and we'll look into it. Thanks!
