### ISSUE TITLE
Make ajax call before create payment

### ISSUE THREAD

**Issue by quantumwebco** [paypal/paypal-checkout#743]
When a user clicks the pay now button is there a way to delay the api call so that it only happens on a successful response form an ajax call.

I want to create the order in the database when the button is clicked via ajax, if that is successful then go through paypal, then onAuthorize make another ajax call to update the payment status in the database

Is this possible?

Thanks

**Comment by wchiquito** [comment]
Perhaps the section [How To :: Implement a PayPal Checkout Server Integration](https://developer.paypal.com/docs/checkout/how-to/server-integration/) of the documentation be useful.

**Comment by quantumwebco** [comment]
Yeah I've implemented a server side integration before but I don't want to create a whole server side integration here, I just want to make an ajax call before the normal process after the button is clicked. Currently it immediately opens the paypal window and I just want to check something first then open the window if success.

**Comment by bluepnume** [comment]
It's not currently possible to do validation with an ajax call and prevent the popup from opening. The best we allow right now is a pattern like this: https://developer.paypal.com/demo/checkout/#/pattern/validation -- which allows enabling/disabling the button based on form inputs changing on the page.

**Comment by raky291** [comment]
In the client side integration, should be possible to make asynchronous calls before displaying the popup, for example:

```javascript
// every time the user click on the paypal button, the function will validate
// whether the popup should be displayed or not
onClick: function(actions) { // add "actions" as a parameter
    // instead of separating the logic into two functions, I consider it
    // easier to have only one function that controls the popup
    isFormValid()
        .then(function() {
            // only show the popup if this function are called
            actions.showPopup();
        })
        .catch(function() {
            showErrorMessage();
        });
}
```

Use async calls it's the most common in the JavaScript's world. I hope that people support my proposal.
```javascript
onClick: function(actions) {
    // another example, an asynchronous ajax call for validate the form
    $.ajax({
        url: 'server-side-validation',
        success: function() {
            actions.showPopup();
        }
    });
}
```

**Comment by bluepnume** [comment]
I agree. Unfortunately though, if we don't open the popup synchronously on click, it gets blocked by most browsers' popup blockers.
