### ISSUE TITLE
Edge | loading example.com in in-context window

### ISSUE THREAD

**Issue by dasx199** [paypal/paypal-checkout#749]
### Description

When following the integration pattern here: https://developers.braintreepayments.com/guides/paypal/checkout-with-paypal/javascript/v3#invoking-the-checkout-with-paypal-flow in Microsoft Edge, either completing the payment or hitting cancel and return loads example.com in the in-context window, and the faded background vanishes shortly after the popup window opens.

This integration works fine in both Firefox and Chrome.

- Screenshots or videos that show the issue:
![image](https://user-images.githubusercontent.com/20856338/42752454-d6ac8aa8-88e5-11e8-9409-399435b6de4b.png)

- The `paypal.version` from your browser console
4.0.204

- The exact browser version:
Microsoft Edge 38.14393.2068.0
Microsoft EdgeHTML 14.14393

- All console logs during the time of the issue, especially error messages:
![image](https://user-images.githubusercontent.com/20856338/42752723-b88f05d6-88e6-11e8-8b8c-f79959a23b5c.png)

- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)? No 
- Does the issue occur consistently, or intermittently? Consistently - 100% reproducible.

### Steps to reproduce

1. Integrate using the BT pattern linked above.
2. Click the PayPal button.
3. Observe that example.com is loaded in the window when completing or hitting cancel or return; and the background fade out disappears shortly after the popup opens.

### Affected browsers

- [X] Edge

**Comment by trainerbill** [comment]
This seems to be version specific.  cannot reproduce on 

![image](https://user-images.githubusercontent.com/3578259/42822952-ee710904-89a1-11e8-978d-7a1406772638.png)

![image](https://user-images.githubusercontent.com/3578259/42822967-f8cf8cb8-89a1-11e8-9c60-e9933d011063.png)

The version that is being reported is from 2016 and I don't have a way to test with it.

**Comment by bluepnume** [comment]
Sounds a lot like an intranet-mode problem. Can you please follow this guide and report back? https://github.com/paypal/paypal-checkout/blob/master/docs/debugging/ie-intranet.md
