### ISSUE TITLE
adaptive payments support?

### ISSUE THREAD

**Issue by ronl** [paypal/paypal-checkout#762]
We are currently using PayPal adaptive payments and the  lightbox flow as was specified with the paypal script https://www.paypalobjects.com/js/external/dg.js .  It appears that in the last week or so that this supported and availability has been deprecated and so now need to see if can use the new checkout integration.

We are using adaptive payments in order to split, who pays fees etc. payments.  In the backend before bringing up the lightbox, we make a call to the adaptive payments api, e.g.  https://svcs.sandbox.paypal.com/AdaptivePayments/Pay , get a paykey,  and then pass a flow url to the lightbox integration using this paykey, e.g.   https://www.sandbox.paypal.com/webapps/adaptivepayment/flow/pay?payKey=AP-35615978SK12345 .  

Also passed in the initial call to the adaptive payments api, were urls for the Instant Payment Notification to be called on success or failure of the process.

The user would then see the popup dialog that was also mobile responsive to complete the operation.  Using the paykey, our advanced payments handling was processed.  

Is this possible with the checkout integration?  I downloaded the entire github project and searched for adaptive and paykey and did not find any references.

Is the Instance Payment notification still supported?

**Comment by bluepnume** [comment]
@trainerbill do we have any guides on migrating adaptive calls over to EC/REST?

**Comment by trainerbill** [comment]
@ronl unfortunately we are in between products right now.  The old adaptive payments lightbox is deprecated and you now have to do a full page redirect to the following URLs.

Prod url:  https://www.paypal.com/webscr?cmd=_ap-payment&paykey=<PAY_KEY>
Sandbox url:   https://www.sandbox.paypal.com/webscr?cmd=_ap-payment&paykey=<PAY_KEY>

We have another product in active development that will be taking the place of adaptive payments in the future.  That product will be compatible with this javascript library.
