### ISSUE TITLE
Issues with popup in React Native WebView

### ISSUE THREAD

**Issue by alex-mironov** [paypal/paypal-checkout#772]
### Description

I'm facing issues with the layout of PayPal popup dialog when using in WebView of React Native. The issue is reproducible on both real device and ios simulator. 

https://youtu.be/z3hh2gZF_5E
PP_VERSION: 20171003
iOS version: 11.4.1
iPhone models: 6, 8

There is also some trace from the console:
<img width="780" alt="screen shot 2018-08-03 at 10 17 23 am" src="https://user-images.githubusercontent.com/2544767/43629642-87b4cd6e-9706-11e8-8154-07e3ff925d64.png">

The issue is reproducible in a production setup.
The issue occurs consistently.

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [x] Web View / Safari ViewController
- [ ] Other

**Comment by amitkatiyar0692** [comment]
> Any updates on this one? i believe i am facing the same issue. Paypal checkout button does not render in React Native WebView.

I am facing the same issue.

**Comment by bluepnume** [comment]
Please do not render the PayPal button inside a webview. This is not an officially supported pattern. Instead please make use of our native mobile sdks.
