### ISSUE TITLE
paypal express checkout not sync with magento 2.2.4

### ISSUE THREAD

**Issue by balwant20** [paypal/paypal-checkout#773]
1. When an Order is placed, registered notification about transaction complete on Paypal is not updated automatically in comment history.

2. Whenever we Refund the amount from Paypal, registered notification about refunded amount is not updated automatically in comment history.

3. If the order is in "Payment Review" status at the time order placing, then it should be automatically changed to "Processing" status whenever the funds got cleared from PayPal. Currently this is not syncing automatically from PayPal and we have to click on "Get Payment Update" to check the status.

**Preconditions**
Magento 2.2.4
PHP 7.1.18 
PayPal Express enabled in-checkout payment methods(for sandbox mode)

**Steps to reproduce**
STEP:1 place order on magento store.
STEP:2 Go to https://www.sandbox.paypal.com
STEP:2 open recent order history
STEP:3 issue refund

**Expected result**
paypal transaction status maintain in magento admin order view page in comment history section and also refund comment should be visbile on order view page in comment history section.

**Actual result**
there is no sync between paypal and magento store. any activity which done in paypal panel ,not reflect in magento admin panel.

below the screenshot of  magento 2.1.7 admin order view page when the order is placed from paypal expree checkout .
![screenshot 2](https://user-images.githubusercontent.com/31465231/43635502-e4da3e04-972c-11e8-8eab-b0ba9de18421.PNG)

**Comment by bluepnume** [comment]
Hi, can you please raise this issue with Magento. This repo is only for the javascript button integration.
