### ISSUE TITLE
CDN can not delivery compressed checkout.min.js

### ISSUE THREAD

**Issue by bormanEcwid** [paypal/paypal-checkout#778]
### Description

Merchants of our ecommerce platform complain to us that the PayPal checkout button is not displayed for a long time. Customers don't know how to pay and leave the store. We found out reason - it's a slow download checkout.js.
For some regions paypal CDN can not delivery compressed content. So checkout.js has excessive size.

### Steps to reproduce

For example when I change DNS server to 83.172.0.212:
nslookup OUTPUT:

> host-57:~ user$ nslookup www.paypalobjects.com
> Server:		83.172.0.212
> Address:	83.172.0.212#53
>
>Non-authoritative answer:
>www.paypalobjects.com	canonical name = geo.paypalobjects.com.akadns.net.
>geo.paypalobjects.com.akadns.net	canonical name = >pprussia.www.direct.paypalobjects.com.akadns.net.
>Name:	pprussia.www.direct.paypalobjects.com.akadns.net
>Address: 185.177.54.13

curl OUTPUT:

>    host-57:~ user$ curl -G 'https://www.paypalobjects.com/api/checkout.min.js' --compressed > out
> % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
>100 1008k  100 1008k    0     0   432k      0  0:00:02  0:00:02 --:--:--  432k
>
>    host-57:~ user$ curl -I 'https://www.paypalobjects.com/api/checkout.min.js' --compressed
>HTTP/1.1 200 OK
>Server: Apache
>Last-Modified: Tue, 07 Aug 2018 00:59:35 GMT
>Accept-Ranges: bytes
>Keep-Alive: timeout=5, max=100
>Content-Type: application/x-javascript
>Connection: Keep-Alive
>Date: Tue, 07 Aug 2018 06:28:18 GMT
>Age: 3523   
>Content-Length: 1032537

Pay attention  content is not compressed (response have no header content-encoding = gzip) and downloaded size = 1008k. Size of gzipped content = 174k

**When I change DNS server to 8.8.8.8 everything is OK**

nslookup OUTPUT:

>    host-57:~ user$  nslookup www.paypalobjects.com
>Server:		8.8.8.8
>Address:	8.8.8.8#53
>
>Non-authoritative answer:
>www.paypalobjects.com	canonical name = geo.paypalobjects.com.akadns.net.
>geo.paypalobjects.com.akadns.net	canonical name = hotspot.paypalobjects.com.akadns.net.
>hotspot.paypalobjects.com.akadns.net	canonical name = www.paypalobjects.com.edgekey.net.
>www.paypalobjects.com.edgekey.net	canonical name = e3691.g.akamaiedge.net.
>Name:	e3691.g.akamaiedge.net
>Address: 2.23.109.20

curl OUTPUT:

>    host-57:~ user$ curl -G 'https://www.paypalobjects.com/api/checkout.min.js' --compressed > out
> % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
>100  174k  100  174k    0     0   386k      0 --:--:-- --:--:-- --:--:--  386k

>    host-57:~ user$ curl -I 'https://www.paypalobjects.com/api/checkout.min.js' --compressed
HTTP/2 200 
>server: Apache
>last-modified: Tue, 07 Aug 2018 00:59:35 GMT
>accept-ranges: bytes
>content-type: application/x-javascript
>content-encoding: gzip
>cache-control: max-age=86400
>expires: Wed, 08 Aug 2018 06:55:58 GMT
>date: Tue, 07 Aug 2018 06:55:58 GMT
>content-length: 178681
>vary: Accept-Encoding
>x-content-type-options: nosniff
>strict-transport-security: max-age=31536000

Affected browsers

    [+] Chrome
    [+] Safari
    [+] Firefox
    [+] Edge
    [+] IE
    [+] Chrome Mobile/Tablet
    [+] Safari Mobile/Tablet
    [+] Web View / Safari ViewController
    [+] Other

**Comment by bluepnume** [comment]
Can you please check now? According to the relevant team this should now be fixed.

**Comment by bormanEcwid** [comment]
>Can you please check now?
Now I can not reproduce it.
