### ISSUE TITLE
checkout.js docs

### ISSUE THREAD

**Issue by SergeyZubatkin** [paypal/paypal-checkout#779]
### Description

Could anybody know where I can find complete checkout.js documentation for checkout button.

As specified on https://developer.paypal.com/demo/checkout/#/pattern/validation
I can use validate or onClick method, but there are not any information on github docs about these methods and their contracts.
Thanks.

**Comment by martinmckenna** [comment]
Agreed. Your documentation is really sub-par and after reading that demo code, it's still not really clear how you do form validation before sending the user to paypal.com to authorize the payment.

**Comment by bluepnume** [comment]
Closing this issue; if you have a specific question, please feel free to open a new issue and we'll be glad to help. For now the demo app should give an idea of how validate() can be used.
