### ISSUE TITLE
Content Security Policy  - paypal

### ISSUE THREAD

**Issue by nasimqota** [paypal/paypal-checkout#781]
### Description
after checkout from My Site with Debit or credit card it gives this error.

> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'nonce-7kmS7OLZ8AFuHnrCo8UNEPq1MgO4EgM/egvjnURVwcHr4oNG' 'self' https://*.paypal.com https://*.paypalobjects.com 'unsafe-eval' 'unsafe-inline'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list

Magento : 2.1.3
Php 7.0.30
server nginx 

Help Please.

Note : i can see this issue with Braintree and they have reslove it like this Please Click  https://github.com/braintree/braintree-web/issues/53

**Comment by nasimqota** [comment]
Any Alien to help ?

**Comment by bluepnume** [comment]
Closing as duplicate of https://github.com/paypal/paypal-checkout/issues/447
