### ISSUE TITLE
Getting error 400 when using item lists

### ISSUE THREAD

**Issue by Direclaw** [paypal/paypal-checkout#782]
I'm trying to set up payments for my website but I keep getting error 400. The error stops when I remove the item list from the transaction but I would like to use it. here is the error message when I use it:

`at PayPalHttpConnection->execute('{"intent":"Sale","payer":{"payment_method":"paypal"},"redirect_urls":{"return_url":"http://carambola.test/status","cancel_url":"http://carambola.test/status"},"transactions":[{"amount":{"currency":"BRL","total":"34.00"},"item_list":{"items":[{"name":"Torradeira Walita - Eco - 3904 Plus","currency":"BRL","quantity":1,"price":"40.00"}]}}]}')`

`Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment.`

because of the specificity of the error I feel like it is an error on my code.

```
$item = new Item();
$item->setName($cart->name)
     ->setCurrency('BRL')
     ->setQuantity($cart->number)
     ->setPrice($cart->unit);
$item_list->addItem($item);
$amount = new Amount();
$amount->setCurrency('BRL')
     ->setTotal($cart->result);
$transaction = new Transaction();
$transaction->setAmount($amount)
     ->setItemList($item_list);
```

**Comment by vishakha94** [comment]
@Direclaw you are getting a 400 possibly because the price of the item list (40.00) doesnot match the transaction (34.00). Try changing one value to other and it should work.
