### ISSUE TITLE
[A11Y] Close control proximity

### ISSUE THREAD

**Issue by PhilibertDugas** [paypal/paypal-checkout#785]
The PayPal overlay modal content and Close control are located some distance apart. Low vision users who rely on screen magnification may not be able to easily associate the Close control making it difficult to return to the previous screen.

**HTML:**
```html
<a href="#" class="paypal-checkout-close"></a>
```
## Steps to reproduce

1. Go to https://www.chubbiesshorts.com/ with any supported browser
2. Add some items to the cart
3. Proceed to the Cart
4. Activate the PayPal control
5. `Cmd` + `~` back to the main window
6. Review the placement of the Close control

### Results

**Expected:**
- Close controls to be in close proximity of its main content

**Actual:**
- Close control is placed in top right corner of screen

## Recommendation

- Move the Close control closer to its content which will help alleviate any proximity issues.

## Additional information

- **WCAG Principle:** Perceivable
- **WCAG SC:** 1.3.3 Sensory Characteristics
- **Severity:** Medium

## Screenshots
<img width="944" alt="screen shot 2018-03-05 at 3 03 27 pm" src="https://user-images.githubusercontent.com/1392632/36997128-a5a79474-2086-11e8-924f-52aee1a5f361.png">

**Comment by bluepnume** [comment]
@vishakha94 can you take this one?

**Comment by vishakha94** [comment]
Closing this issue for now.
