### ISSUE TITLE
Popup displaying default checkout page

### ISSUE THREAD

**Issue by grandchaseway** [paypal/paypal-checkout#789]
### Description

Strangely, the popup began to present the PayPal default checkout page.

![image](https://user-images.githubusercontent.com/42282461/43988510-987445be-9d0d-11e8-9d14-09a7f03d56ad.png)

- `paypal.version`: 4.0.213
- Browser: Google Chrome 67.0.3396.99 (64-bit)
- Store address: https://shop.gcway.co

I temporarily disabled the express checkout so that payments will not be retained.

**Comment by bluepnume** [comment]
Can you please fill out the entire issue form and resubmit after answering all the questions?
