### ISSUE TITLE
Handling Funding Source Failure

### ISSUE THREAD

**Issue by vicatcu** [paypal/paypal-checkout#790]
I was reading this little section of the PayPal Checkout docs: https://developer.paypal.com/docs/checkout/how-to/customize-flow/#manage-funding-source-failure. Here they include this code snippet:

```javascript
paypal.Button.render({
  //Configure environment
  env: 'production', // To test, set to `sandbox`
  payment: function () {
    // Set up the payment here, when the buyer clicks on the button
  },
  onAuthorize: function (data, actions) {
    // Call your server to execute the payment
    if (error === 'INSTRUMENT_DECLINED') {
      actions.restart();
    }
  }
}, '#paypal-button');
```
Does anyone know if that documentation is correct? Does the PayPal checkout.js manage an error variable in the global scope? If not, how do you correctly implement this guidance? Or is this guidance just defunct?

Note: cross-posted https://stackoverflow.com/questions/51824283/paypal-checkout-js-error-handling

**Comment by vishakha94** [comment]
https://developer.paypal.com/demo/checkout/#/pattern/server
Example:
```
return paypal.request.post(EXECUTE_URL, data)
                    .then(function (res) {
                        if (res.error === 'INSTRUMENT_DECLINED') {
                          return actions.restart();
                        }
                        window.alert('Payment Complete!');
                    });
```

**Comment by vicatcu** [comment]
Ok, thanks for clarifying. So in the client side library, onAuthorize is an implication of success,  unconditionally,  right?

**Comment by vishakha94** [comment]
For client side, paypal-checkout handles this error by calling `actions.restart()`.

**Comment by vicatcu** [comment]
Many thanks, I'll withdraw the question, but can you point me to the authoritative docs for the client side library?

**Comment by vishakha94** [comment]
https://developer.paypal.com/docs/checkout/integrate/#3-execute-the-payment
https://developer.paypal.com/demo/checkout/#/pattern/client

**Comment by Justin-Credible** [comment]
I have the same question; looking at the code sample from the documentation again:

```
paypal.Button.render({
  //Configure environment
  env: 'production', // To test, set to `sandbox`
  payment: function () {
    // Set up the payment here, when the buyer clicks on the button
  },
  onAuthorize: function (data, actions) {
    // Call your server to execute the payment
    if (error === 'INSTRUMENT_DECLINED') {
      actions.restart();
    }
  }
}, '#paypal-button');
```

The `error` object is not available. I think this issue needs to be re-opened and the documentation needs to be fixed here.
