### ISSUE TITLE
Is subscription supported in client side library? 

### ISSUE THREAD

**Issue by vicatcu** [paypal/paypal-checkout#792]
Is it possible to sign a customer up to a subscription using checkout.js (client side library)  in a manner similar to the programmatic button generation for "Buy Now" functionality? Had trouble finding documentation on how to do that, if it's possible at all.

**Comment by vishakha94** [comment]
@vicatcu What do you mean by a subscription? Do you mean billing agreements?
I am not sure how you are linking Buy Now button with subscriptions here?

**Comment by vicatcu** [comment]
I just mean, can you inspire a subscription (yes, recurring billing) workflow with checkout.js using something like paypal.Button.render?

**Comment by vishakha94** [comment]
We currently do not support billing agreements for client-side integration. Do you need to do it server-side?

**Comment by vishakha94** [comment]
@vicatcu Having a button which would denote any kind of subscription is definitely easy to implement but not in our roadmaps right now.

**Comment by esokullu** [comment]
Bummer! Please do implement. Many online businesses are subscription based today.
