### ISSUE TITLE
Early return in payment method and prevent opening Paypal

### ISSUE THREAD

**Issue by martinmckenna** [paypal/paypal-checkout#794]
### Description

I'd like a way to not open the Paypal site if there is a validation error with the form. Instead, I'd like to early return within the `payment` callback

I stumbled upon this demo:

https://developer.paypal.com/demo/checkout/#/pattern/validation

But it's not really helpful because I don't want to have to validate each time a user changes a form element. I want to do all my validation when the user submits the form and if there's an error, the user should not be navigated to paypal.com

**Comment by bluepnume** [comment]
Please see here for the full discussion on why that's not possible at this time: https://github.com/paypal/paypal-checkout/issues/139
