### ISSUE TITLE
Paypal checkout is working on sanbox but not on live mode

### ISSUE THREAD

**Issue by AzamatShaimerden** [paypal/paypal-checkout#797]
Hi,

Our checkout was working just fine few days ago but not now. I have tested multiple times on sandbox mode  and it`s working however on live mode still not able to accept credit, debit cards.

During live test I have found this in chrome console log ""POST https://www.paypal.com/webapps/hermes/api/checkout/9AM82377CY632213N/session/createPayment 400 ()

and card option disappears. And when I choose all other options all disappears.

Our form is 

```
<form class="paypal" action="payments.php" method="post" id="paypal_form">
        <input type="hidden" name="cmd" value="_xclick" />
        <input type="hidden" name="no_note" value="1" />
        <input type="hidden" name="lc" value="USD" />
        <input type="hidden" name="bn" value="PP-BuyNowBF:btn_buynow_LG.gif:NonHostedGuest" />
        <input type="hidden" name="first_name" value="Customer's First Name" />
        <input type="hidden" name="last_name" value="Customer's Last Name" />
        <input type="hidden" name="payer_email" value="customer@example.com" />
		<input type="hidden" name="item_name" value="Lifetime access" />
		<input type="hidden" name="business" value="business_email" />
        <input type="hidden" name="amount" value="150.00" />
        <input type="submit" name="submit" class="joinsubmitst" value="Submit Payment"/>
		</form>
```

 What could be the issue?

Thanks,
Azamat

**Comment by bluepnume** [comment]
Please contact paypal technical support. This repo is only for the javascript integration.
