### ISSUE TITLE
Is there a Changelog of some kind?

### ISSUE THREAD

**Issue by sharang-d** [paypal/paypal-checkout#798]
@bluepnume Is there a changelog somewhere which says what changed in every release?
I would like to know as I want to upgrade versions.

**Comment by wchiquito** [comment]
Here was an attempt: [Express Checkout and Direct Payment release notes](https://developer.paypal.com/docs/classic/release-notes/merchant/), but clearly not updated.

**Comment by bluepnume** [comment]
For now I would rely on the commit log. Every new change is backwards compatible, so you should be able to upgrade without any issues.

**Comment by sharang-d** [comment]
Ok, thanks!
