### ISSUE TITLE
Cache not cleared for checkout.js?xyz

### ISSUE THREAD

**Issue by bluepnume** [paypal/paypal-checkout#8]
Need to figure out a way to flush the akamai cache for not just `checkout.js` but also `checkout.js?xyz`, since there are merchants integrating with their own query strings and it's causing them to get older versions of the script living in the akamai cache.

**Comment by jamacon36** [comment]
There's [this](https://community.akamai.com/thread/3776#comment-11293) from Akamai

**Comment by bluepnume** [comment]
Fixed and pushed.
