### ISSUE TITLE
Focused checkout button missing outline

### ISSUE THREAD

**Issue by jalymiller** [paypal/paypal-checkout#802]
In a new audit for ADA compliance on our site, the PayPal checkout button was flagged because it only uses color to show focus instead of an outline. Here is the information from the audit report and a screenshot:

[Issue]
When the user navigates to 'Paypal checkout' button, the visual indication of keyboard focus is made available by change in color and the (dotted rectangle) is not visible on this button due to the use of CSS outline property 'outline:none'.
[Impact]
When the visual focus is not visible then the keyboard only users including color blind and low vision users will not know what element has the keyboard focus and may activate the undesired element. This will also make the keyboard only users use extra keystroke to figure out which element has the focus.
[Recommendation]
Developer need to avoid the use of CSS property 'outline:none' on the actionable elements because 'outline:none' declaration removes the default focus rectangle from focused elements within the browser. And if the visual focus is not visible on actionable elements then developers are recommended to use style properties like 'outline-style', 'outline-color' and 'outline-width' to provide good color contrast, width and styles.
![paypal-button-outline](https://user-images.githubusercontent.com/36636893/44271819-c72b3f00-a200-11e8-86da-27d74d4af362.png)

**Comment by mcntsh** [comment]
Released [v4.1.7](https://github.com/paypal/paypal-checkout/tree/v4.1.7)
