### ISSUE TITLE
4.1.0 tag in Github doesn't have the expected `dist` files

### ISSUE THREAD

**Issue by davidchin** [paypal/paypal-checkout#804]
### Description

4.1.0 Github tag doesn't have the expected `dist` files.

[4.1.0](https://github.com/paypal/paypal-checkout/commit/c1943124fcbac2eacbf60b84b9f667ad66867be0) has the following files:
<img width="1017" alt="screen shot 2018-08-20 at 3 18 12 pm" src="https://user-images.githubusercontent.com/667603/44321614-526c3500-a48c-11e8-8ec9-2a1c5b2fb7d3.png">

I expect it to have files similar to the previous release [4.0.213](https://github.com/paypal/paypal-checkout/commit/45bd7fb8b1f50781d40eebcc6b43eb940dcb950c) (a minor release should only contain additive changes):
<img width="1015" alt="screen shot 2018-08-20 at 3 17 47 pm" src="https://user-images.githubusercontent.com/667603/44321646-92cbb300-a48c-11e8-9b6a-c1e579eecc24.png">

I notice that, for some reason, `4.1.0` is based on [v5](https://github.com/paypal/paypal-checkout/compare/v5) branch instead of master. Maybe something went wrong with the release?

### Steps to reproduce

Please provide each individual step required to reproduce the issue

1. Compare the two recent releases and pay attention to the Git history of https://github.com/paypal/paypal-checkout/releases/tag/v4.1.0 vs https://github.com/paypal/paypal-checkout/releases/tag/v4.0.213

**Comment by bluepnume** [comment]
How are you using this tag? It hasn't been published to npm or to our CDN

**Comment by davidchin** [comment]
Just Bower, which references Git tags directly.

**Comment by bluepnume** [comment]
OK thanks for the heads-up. Given that bower is now deprecated, and we have not officially supported it for a long time, I would strongly recommend upgrading to npm and yarn.

**Comment by davidchin** [comment]
Ok, cool, if you say Bower is no longer supported, I'll close this issue. Thank you.
