### ISSUE TITLE
Unavailable checkout.min.js/checkout.js

### ISSUE THREAD

**Issue by bormanEcwid** [paypal/paypal-checkout#805]
### Description

Can not get checkout.js:
https://www.paypalobjects.com/api/checkout.min.js and https://www.paypalobjects.com/api/checkout.js returns 404 error

### Steps to reproduce
Try to get https://www.paypalobjects.com/api/checkout.min.js 
It returns 404

nslookup and curl output:
```
host-174:~ borman$ nslookup www.paypalobjects.com
Server:		172.17.10.9
Address:	172.17.10.9#53

Non-authoritative answer:
www.paypalobjects.com	canonical name = geo.paypalobjects.com.akadns.net.
geo.paypalobjects.com.akadns.net	canonical name = pprussia.www.direct.paypalobjects.com.akadns.net.
Name:	pprussia.www.direct.paypalobjects.com.akadns.net
Address: 185.177.54.5

host-174:~ borman$ curl https://www.paypalobjects.com/api/checkout.min.js
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /api/checkout.min.js was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
```

### Affected browsers

- [+] Chrome
- [+] Safari
- [+] Firefox
- [+] Edge
- [+] IE
- [+] Chrome Mobile/Tablet
- [+] Safari Mobile/Tablet
- [+] Web View / Safari ViewController
- [+] Other

**Comment by sharang-d** [comment]
> Can not get checkout.js:
https://www.paypalobjects.com/api/checkout.min.js and https://www.paypalobjects.com/api/checkout.js returns 404 error

@bormanEcwid These links open for me when typed in the address bar in the browser.

**Comment by bormanEcwid** [comment]
Now I can not reproduce it. 
But when I posted ticket paypal returned 404

Are you sure that it will not happen again?

**Comment by bluepnume** [comment]
Please raise another issue if you see the same problem again.

**Comment by bormanEcwid** [comment]
Why dit it happen?
Can I be sure that it will not happen again?
