### ISSUE TITLE
Considering VueJs

### ISSUE THREAD

**Issue by saleem-hadad** [paypal/paypal-checkout#812]
### VueJs integration

Hi, thank you for your efforts in making this package available. However, I'm wondering if you are planning to consider **`VueJs`** framework in addition to its friends AngularJs and ReactJs? 👨‍🍳

**Comment by bluepnume** [comment]
Yup, we do. @vishakha94 any chance you could add a demo to the /demo folder?

**Comment by saleem-hadad** [comment]
Thank you, dude!

**Comment by mcntsh** [comment]
Demo is added!
