### ISSUE TITLE
Missing properties when using Component.jsx with braintree

### ISSUE THREAD

**Issue by hanloong** [paypal/paypal-checkout#815]
### Description

I've been building a new integration using paypal-checkout and braintree in React.
As part of the integration we want to use PayPal to collect shipping details (using the `enableShippingAddress` option.

However the react button component drops everything from the payload but the `nonce`
https://github.com/paypal/paypal-checkout/blob/master/src/button/component.jsx#L573

It would be great if we could either.
 - Pass `resp` through unchanged
 - Or, make sure the extra attributes `details` and `creditFinancingOffered` also get passed trough in the response.

Ref: https://github.com/braintree/braintree-web/blob/master/src/paypal-checkout/paypal-checkout.js#L405

- Screenshots or videos that show the issue
NA
- Your code

```jsx
// The wrapper component I'm building
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import PropTypes from 'prop-types';
import Braintree from 'braintree-web';
import paypal from 'paypal-checkout';

const PayPalButton = paypal.Button.driver('react', { React, ReactDOM });

const propTypes = {
  env: PropTypes.oneOf(['sandbox', 'production']).isRequired,
  token: PropTypes.string.isRequired,
  onAuthorize: PropTypes.func.isRequired,
  billingAgreementDescription: PropTypes.string,
};

const defaultProps = {
  billingAgreementDescription: 'Stich Fix Inc',
};

class PayPal extends Component {
  constructor(props) {
    super(props);
    this.onAuthorize = this.onAuthorize.bind(this);
    this.payment = this.payment.bind(this);
  }

  onAuthorize(_, actions) {
    return actions.payment
      .tokenize()
      .then(payload => this.props.onAuthorize(payload));
      // payload only ever returns { nonce: "some-value" }
  }

  payment(_, actions) {
    return actions.braintree.create({
      flow: 'vault',
      billingAgreementDescription: this.props.billingAgreementDescription,
      enableShippingAddress: false,
    });
  }

  render() {
    const { env, token } = this.props;

    return (
      <PayPalButton
        braintree={Braintree}
        commit
        env={env}
        style={{
          label: 'paypal',
          size: 'responsive',
          shape: 'rect',
          color: 'blue',
          tagline: false,
        }}
        client={{
          sandbox: env === 'sandbox' ? token : '',
          production: env === 'production' ? token : '',
        }}
        payment={this.payment}
        onAuthorize={this.onAuthorize}
      />
    );
  }
}

PayPal.propTypes = propTypes;
PayPal.defaultProps = defaultProps;
export default PayPal;

```

- The `paypal.version` from your browser console
taken form package.json
```json
{
    "braintree-web": "^3.35.0",
    "paypal-checkout": "^4.0.213",
}
```

- The exact browser version

FireFox Mac 61.0.2

- A link to your page with the issue, if possible
- All console logs during the time of the issue, especially error messages
- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
- Does the issue occur consistently, or intermittently?
consistently

### Steps to reproduce

Example code included above

### Affected browsers

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge
- [x] IE
- [x] Chrome Mobile/Tablet
- [x] Safari Mobile/Tablet
- [x] Web View / Safari ViewController
- [x] Other

**Comment by mcntsh** [comment]
#816 released in [`v4.0.217`](https://github.com/paypal/paypal-checkout/tree/v4.0.217)
