### ISSUE TITLE
The "The safer, easier way to pay" label is hidden

### ISSUE THREAD

**Issue by matthieu-D** [paypal/paypal-checkout#828]
### Description

The "The safer, easier way to pay" label is not visible when I try it on my iphone, pc but on my mac it's all good.

- Screenshots or videos that show the issue:

<img width="172" alt="screen shot 2018-08-28 at 18 00 15" src="https://user-images.githubusercontent.com/5333018/44735271-3dc31900-aaec-11e8-9a73-4caff4214f2c.png">

- Your code (in fact it's the code that you generate):

`<div class="paypal-button-tagline paypal-button-tagline-color-blue" style="visibility: hidden;"><span class="paypal-button-text">The safer, easier way to pay</span></div>
`

- The `paypal.version` from your browser console: 
"4.0.215"

- The exact browser version:

safari on the latest iOS, or chrome on windows 

- A link to your page with the issue, if possible: 

https://javascripttuts.com/hit-the-ground-running-with-ionic-3/

- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)? Yes it does

- Does the issue occur consistently, or intermittently? Consistently

### Steps to reproduce

Grab an iphone or a PC go to the demo page and the text is not here.

### Affected browsers

- [x] Chrome
- [ ] Chrome Mobile/Tablet
- [x] Safari Mobile/Tablet

**Comment by matthieu-D** [comment]
The :
Button.render method displays the text (👍 )

It's the:
 Button.driver("react", {
      React,
      ReactDOM
    })
That doesn't. 👎 
Quite annoying since it's in the React documentation.

**Comment by mcntsh** [comment]
@matthieu-D I am going back through old tickets. I believe this issue has since been solved... can you confirm?

Thanks!

**Comment by mcntsh** [comment]
Closing this out. If this pops up again for you please feel free to re-open the issue!
