### ISSUE TITLE
Paypal button work in developer.paypal.com/demo/checkout but not in localhost

### ISSUE THREAD

**Issue by ckgagan** [paypal/paypal-checkout#829]
Hi I am having problem with paypal button lately. Previously it worked without any problem, but not it stopped working.

I pasted the same code from 
https://developer.paypal.com/demo/checkout/#/pattern/client OR
https://developer.paypal.com/demo/checkout/#/pattern/confirm
with my client_id
Ab9GzTPdwikNy4-mmGP2nNXuOeYCABf-U5Ct7UsCuvTC6a60gUbBCygj8-fivy5_KufPHAfQCdKuQfCS
Here is the code snippet

   ```
 paypal.Button.render({
      env: $('#paypal-button-container').data('env'), // sandbox | production

      // PayPal Client IDs - replace with your own
      // Create a PayPal app: https://developer.paypal.com/developer/applications/create
      client: {
        sandbox: $('#paypal-button-container').data('client-id')
      },

      // Show the buyer a 'Pay Now' button in the checkout flow
      commit: true,

      // payment() is called when the button is clicked
      payment: function(data, actions) {

          // Make a call to the REST api to create the payment
          return actions.payment.create({
              payment: {
                  transactions: [
                      {
                          amount: { total: "#{total}", currency: 'GBP' }
                      }
                  ]
              }
          });
      },

      // onAuthorize() is called when the buyer approves the payment
      onAuthorize: function(data, actions) {
        // return actions.payment.get().then(function(data) {
        //   var shipping = data.payer.payer_info.shipping_address;
        // }

          // Make a call to the REST api to execute the payment
          return actions.payment.execute().then(function(data) {
            $.post( "/charges", { data: data } );
          });
      },
      onError: function (err) {
        // Show an error page here, when an error occurs
      }

    }, '#paypal-button-container');
  }
```
$('#paypal-button-container').data('env') returns 'sandbox' and
$('#paypal-button-container').data('client-id') returns sandbox clientid (Ab9GzTPdwikNy4-mmGP2nNXuOeYCABf-U5Ct7UsCuvTC6a60gUbBCygj8-fivy5_KufPHAfQCdKuQfCS)

Few days ago it worked without any problem but not it didn't work at all.
Now when I click the Paypal button, the popup appears and disappears in about 3 seconds and nothing happens.

I get this warning when I load the page containing the Paypal button.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.paypal.com/webapps/hermes/api/logger. (Reason: CORS request did not succeed).
Use of Mutation Events is deprecated. Use MutationObserver instead. script.js:60:8
Use of Mutation Events is deprecated. Use MutationObserver instead.
```

**I tested with Live client_id as well, but not luck.**

Tested with
google chrome Version 68.0.3440.106
Firefox 61.0.2

**Comment by bluepnume** [comment]
Are you running on a local server or a `file://` path

**Comment by ckgagan** [comment]
@bluepnume No I am running a Rails localserver http://localhost:3000

**Comment by ckgagan** [comment]
@bluepnume Found out the issue. I and sending total as undefined. Sent the any float value and it worked
