### ISSUE TITLE
Edge Checkout redirecting to 

### ISSUE THREAD

**Issue by elliotj1** [paypal/paypal-checkout#838]
After choosing the billing and shipping information in the PayPal login modal the modal redirects to "https://example.com/?...". This leaves the modal up and does not return focus to the included site.
Only effects IE Edge:
   
- PayPal Version "4.0.215"
- Browser:
   Microsoft Edge 42.17134.1.0
   Microsoft EdgeHTML 17.17134
- Issue does not occur on developer.paypal.com/demo/checkout
- Issue occurs every time 

![image](https://user-images.githubusercontent.com/42850786/44881303-c5d42a80-ac74-11e8-96f1-c95e8a4c365b.png)

![image](https://user-images.githubusercontent.com/42850786/44881535-a7bafa00-ac75-11e8-8124-dc69f3e229a4.png)

![image](https://user-images.githubusercontent.com/42850786/44881651-02ecec80-ac76-11e8-8b75-f3a073d4f7f3.png)

### Steps to reproduce
Choose PayPal Express or Mark flow checkout
Log in
Click "continue" button

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Thanks for raising the issue.

- At any point do you see the overlay behind the popup window disappear?
- Do you see any errors in the console for the popup, during any part of the flow?

**Comment by bluepnume** [comment]
Can you please confirm if you're still seeing this issue?

**Comment by elliotj1** [comment]
I tried to complete the PayPal login modal once and got the error, then
cleared Edge's browser cache and it seems to be working now on production.
I do still see the issue on sandbox.paypal.com with Microsoft Edge version
42.17134.1.0 Microsoft EdgeHTML version 17.17134.

I also have access to Microsoft Edge version 41.16299.611.0 Microsoft
EdgeHTML version 16.16299 and it is still seeing the issue on both
production and sandbox environments (after clearing cache).

On Mon, Sep 10, 2018 at 1:33 PM Daniel Brain <notifications@github.com>
wrote:

> Can you please confirm if you're still seeing this issue?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_paypal_paypal-2Dcheckout_issues_838-23issuecomment-2D420015190&d=DwMCaQ&c=MD2TCZurVTbVhl_owkqnbQ&r=5MyMvt-8Skim-_p_m89q1DCIWRPsKDzoMtJfx2D6W5g&m=t7ad-2FLWh519O2tSD39GwQvAHQwQDJINSToxoS7rZI&s=qlmDEIh3qQcvPPBq_oumK3gcqGaE0MT8crtmktswvrk&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Ao3Z4nIR2whjRVNAc-5Fa-2D5mAZk0RqxFkYks5uZrBrgaJpZM4WUSpd&d=DwMCaQ&c=MD2TCZurVTbVhl_owkqnbQ&r=5MyMvt-8Skim-_p_m89q1DCIWRPsKDzoMtJfx2D6W5g&m=t7ad-2FLWh519O2tSD39GwQvAHQwQDJINSToxoS7rZI&s=-6pWcF3mmwWFDn4RT1lr3ajDsFTkGabLff3x5p5C1eI&e=>
> .
>


-- 
Jason Elliott

**Comment by bluepnume** [comment]
@vishakha94 could you follow up on this one?

**Comment by mcntsh** [comment]
@elliotj1 Following back up on this. Do you have a website that we can repro on Edge?

**Comment by elliotj1** [comment]
https://www.dillards.com still has the issue

On Wed, Nov 28, 2018 at 6:34 PM Jon McIntosh <notifications@github.com>
wrote:

> @elliotj1
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_elliotj1&d=DwMCaQ&c=MD2TCZurVTbVhl_owkqnbQ&r=5MyMvt-8Skim-_p_m89q1DCIWRPsKDzoMtJfx2D6W5g&m=UBkE6kP-wyoHv7Ql6irU4sF-1Ta7BmeGo7LoOvV8lXM&s=JKwq5ZaxgM71A0l_K63d9HkIL4c8NGPnbbP3u18eAjg&e=>
> Following back up on this. Do you have a website that we can repro on Edge?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_paypal_paypal-2Dcheckout_issues_838-23issuecomment-2D442659855&d=DwMCaQ&c=MD2TCZurVTbVhl_owkqnbQ&r=5MyMvt-8Skim-_p_m89q1DCIWRPsKDzoMtJfx2D6W5g&m=UBkE6kP-wyoHv7Ql6irU4sF-1Ta7BmeGo7LoOvV8lXM&s=ap9QEG-tjR8EKFWWpdVux8tvCb2ISEqxzd3Ua8L1t2M&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Ao3Z4gi6cC0nk13EXoSSoWM5yx1q-5Fg73ks5uzyuAgaJpZM4WUSpd&d=DwMCaQ&c=MD2TCZurVTbVhl_owkqnbQ&r=5MyMvt-8Skim-_p_m89q1DCIWRPsKDzoMtJfx2D6W5g&m=UBkE6kP-wyoHv7Ql6irU4sF-1Ta7BmeGo7LoOvV8lXM&s=G_SCmrsLBqsPArkqe-WhFjq_iW1j-bQ_kd-OErHEQeU&e=>
> .
>


-- 
Jason Elliott

**Comment by mcntsh** [comment]
Hey @elliotj1 there are quite a few reports mentioning a similar bug. Could you please see [this comment on issue #959](https://github.com/paypal/paypal-checkout/issues/959#issuecomment-443851819) and let me know if this solves your problem?

This will help us keep track of which ticket is related to which bug, since the example.com redirect can happen for a few different reasons.

**Comment by elliotj1** [comment]
While [the comment on issue #959](https://github.com/paypal/paypal-checkout/issues/959#issuecomment-443851819) that you suggested did not solve our issue, [the comment a few messages down](https://github.com/paypal/paypal-checkout/issues/959#issuecomment-444002221) that mentions adding "https://www.paypal.com" to the trusted site list did fix it. Thanks for the help!
