### ISSUE TITLE
PayPal Express Checkout - IE11 and Edge Popup Closes Immediately After Opening

### ISSUE THREAD

**Issue by elitenick** [paypal/paypal-checkout#842]
### Description

Hi there,

In Edge and IE11, we are seeing the PayPal Express popup open then immediately close, with vague errors. This is also happening on the PayPal checkout demo page with the same implementation we are using. I also visited a few other websites that use PayPal Express checkout and am getting the same behavior. As one more test, I visited the demo page via BrowserStack IE11, and the same issue occurs again.

![edge-paypal-expresscheckout](https://user-images.githubusercontent.com/2449067/44915972-750b1300-ad02-11e8-9b19-edb821d5d1c1.png)

- CODE:
```
   p.Config = {
        env: currentEnv,
        style: {
            label: 'checkout',
            size: 'medium',
            shape: 'pill',
            color: 'gold',
            tagline: false
        },
        client: {
            sandbox: '---------------------------',
            production: '----------------------------'
        },
        commit: false,
        payment: function (data, actions) {
            return actions.payment.create({
                payment: {
                    transactions: [
                        {
                            amount: {
                                total: round(cp.Cart.Vue.cart.total),
                                currency: cp.Cart.Vue.cart.currencyCode
                            }
                        }
                    ]
                }
            });
        },
        onAuthorize: function (data, actions) {
            actions.payment.get().then(function (payment) {
                cafepress.Cart.Vue.gotoCheckout();
                createPaypalShippingInfoCookie(payment);
            }, function (error) {
                console.log("The following error is preventing checkout via PayPal: " + error);
            });
        },
        onError: function (err) {
            alert("an error occurred: " + err);
        }
    };

    paypal.Button.render(p.Config, '#paypal-button');
```

- PayPal version: 4.0.216
- Browers: IE11 (11.228.17134.0) and Edge (42.17134.1.0)
- Page this is occurring: https://www.cafepress.com.au/cart and https://developer.paypal.com/demo/checkout
- Console logs:
```
ppxo_unhandled_error [object Object]

 SCRIPT462: SCRIPT462: The remote server machine does not exist or is unavailable
checkout.js (8307,33)

 SCRIPT1717: 
ready.js (13,5)
```
- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)? YES
- Does the issue occur consistently, or intermittently? Consistently in IE11 and Edge

### Steps to reproduce

1) Visit https://developer.paypal.com/demo/checkout in IE11 or Edge
2) Click the PayPal button
3) Notice the popup open, then close soon after

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge
- [x] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by elitenick** [comment]
The issue is no longer occurring. It appears the PayPal version reverted from 4.0.216 to 4.0.215.

**Comment by bluepnume** [comment]
Thanks for the report! Yep, we reverted the new version while we identify the problem. Appreciate your help!

**Comment by prasannashr** [comment]
Hi @bluepnume How did you solve this issue.
I am also facing this error in my react/mobx project in IE-Edge/IE11.
It will be great help if you could share the solution.

Thanks :)

**Comment by irbrownie** [comment]
Any update on this?
