### ISSUE TITLE
[Question ] is there an npm command to install paypal-checkout ?

### ISSUE THREAD

**Issue by JDevjs** [paypal/paypal-checkout#843]
im trying to use paypal-checkout with my angularjs app (mean stack) but there is no clear way of installation in docs only the integration part ...thanks.

**Comment by realfresh** [comment]
You have to add their checkout script to your page before using their code examples, thats about it. Not sure if there is an NPM installation.

`<script src="https://www.paypalobjects.com/api/checkout.js" data-version-4></script>`

That said I think whats really missing from these docs is a complete description of the API available. Right now it's just a bunch of examples, or so it feels, I want to read the full API of whats available with the checkout widget and see what parameteres and responses each of the function are.

Might have to read the code to figure it out but it would be nice if this was detailed for us given how useful it would be to everyone.

**Comment by JDevjs** [comment]
i totally agree i dont even know what to put here ... im wasting too much time man
```
$scope.client = {
                ...
            };

            $scope.payment = function() {
                ...
            };

            $scope.onAuthorize = function(data) {
                ...
            };
        });
```

**Comment by realfresh** [comment]
Agreed, this has to be one of the most painful libraries / API's I've had to work with over the last 2 years.

**Comment by bluepnume** [comment]
We support npm using the `paypal-checkout` package. Please let me know if you have any specific problems using this package.
