### ISSUE TITLE
PayPal SSL Certs need to be replaced

### ISSUE THREAD

**Issue by tituscrow82** [paypal/paypal-checkout#844]
Need to know if Paypal.com and paypalobjects.com will have their certs updated **before** users start using the beta.  Need to understand release plan in order to evaluate a change to stripe or other payment collection company.

**Issue**
The SSL certificate used to load resources from https://www.paypalobjects.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.

The SSL certificate used to load resources from https://www.paypal.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.

Release | First Canary | First Beta | Stable Release
Chrome 70 | ~ July 20, 2018 | ~ September 13, 2018 | ~ October 16, 2018

**Comment by wchiquito** [comment]
See [Paypal certificate used to load resources #691](https://github.com/paypal/paypal-checkout/issues/691).
