### ISSUE TITLE
China Union Pay is not shown as one of the accepted cards for users from China

### ISSUE THREAD

**Issue by ksuralta** [paypal/paypal-checkout#847]
### Description

China Union Pay is expected as one of the card types that PayPal supports.  However, the vertical layout of Smart Payment Button only shows the logos of Visa, MasterCard and AMEX when I set the locale to China/Chinese "zh_CN".

- Screenshots or videos that show the issue
![image 2](https://user-images.githubusercontent.com/4402049/45139236-6afd7e80-b1f2-11e8-84da-9076a6273ff1.png)

- Your code
`    paypal.Button.render({

        // Set your environment

        env: 'sandbox', // sandbox | production

        // Specify the style of the button

        style: {
            layout: 'vertical',  // horizontal | vertical
            size:   'medium',    // medium | large | responsive
            shape:  'rect',      // pill | rect
            color:  'gold'       // gold | blue | silver | black
        },

        // Specify allowed and disallowed funding sources
        //
        // Options:
        // - paypal.FUNDING.CARD
        // - paypal.FUNDING.CREDIT
        // - paypal.FUNDING.ELV

        funding: {
            allowed: [ paypal.FUNDING.CARD, paypal.FUNDING.CREDIT ],
            disallowed: [ ]
        },

        // PayPal Client IDs - replace with your own
        // Create a PayPal app: https://developer.paypal.com/developer/applications/create

        client: {
            sandbox:    'AZDxjDScFpQtjWTOUtWKbyN_bDt4OgqaF4eYXlewfBP4-8aqX3PiV8e1GWU6liB2CUXlkA59kJXE7M6R',
            production: '<insert production client id>'
        },

        payment: function(data, actions) {
            return actions.payment.create({
                payment: {
                    transactions: [
                        {
                            amount: { total: '0.01', currency: 'USD' }
                        }
                    ]
                }
            });
        },

        onAuthorize: function(data, actions) {
            return actions.payment.execute().then(function() {
                window.alert('Payment Complete!');
            });
        },
        locale: 'zh_CN'}, '#paypal-button-container');`

- The `paypal.version` from your browser console
4.0.217

- The exact browser version
Chrome v68.0.3440.106 

- A link to your page with the issue, if possible
NA

- All console logs during the time of the issue, especially error messages
NA

- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
Yes

- Does the issue occur consistently, or intermittently?
Consistently

### Steps to reproduce

Please provide each individual step required to reproduce the issue

### Affected browsers

- [X] Chrome
- [X] Safari
- [X] Firefox
- [X] Edge
- [X] IE
- [X] Chrome Mobile/Tablet
- [X] Safari Mobile/Tablet
- [X] Web View / Safari ViewController
- [ ] Other

**Comment by khanghoang** [comment]
WIP by this PR #869
