### ISSUE TITLE
Set expiration time for PayPal popup

### ISSUE THREAD

**Issue by sirikumara** [paypal/paypal-checkout#870]
I have integrated PayPal popup with Java web application. I want to set up expiration time for the popup to avoid user paying some specific time. Let's say after 15 min. The user should not be allowed to pay.  Is there a way to do this with PayPal?

**Comment by bluepnume** [comment]
Hi @sirikumara -- there's no built-in way. I'd recommend using a `setInterval` or `setTimeout` to check and if 15 minutes has elapsed, you can destroy the button.
