### ISSUE TITLE
Invalid Shipping Address

### ISSUE THREAD

**Issue by rafaelcentric** [paypal/paypal-checkout#872]
### Description

Shipping address is always invalid if country code is PH.

### Steps to reproduce

Here is my button

paypal.Button.render({
    env: 'sandbox', // sandbox | production
    commit: true,
    style: {
        size:   'medium',    // medium | large | responsive
        shape: 'pill',
        color:  'gold'       // gold | blue | silver | black
    },
    client: {
        sandbox:    'HadfgIeiFiz6s-0V6E4aLvRIPY2JhUg8gnqJzgJCCabgijn0sQo9yv-t3-BsdfgfdZPMvDcbx5H',
        production: 'GasdfgU690oI-7jzf_LlwZIGMy4qu-mEpYva8xdfhdfhfasdfgmYYuj56nCmIxpfgphasdfas'
    },
    payment: function(data, actions) {
        console.log('payment callback...');
        
        return actions.payment.create({
            payment: {
                transactions: [
                    {
                        amount: { total: 123.00, currency: 'PHP' },
                        item_list: {
                            items: {
                                name: 'a',
                                description: 'abc',
                                quantity: 1,
                                price: 123.00,
                                tax: 0,
                                sku: 'a',
                                currency: 'PHP'
                            },
                            shipping_address: {
                                recipient_name: 'Brian Robinson',
                                line1: '4th Floor',
                                line2: 'Unit #34',
                                city: 'San Jose',
                                country_code: 'PH',
                                postal_code: '1600',
                                phone: '09567888987',
                                state: 'Metro Manila'
                            }
                        }
                    }
                ],
                redirect_urls: {
                    return_url: window.location.origin + "/success",
                    cancel_url: window.location.origin + "/failure"
                }
            },
            experience: {
                input_fields: {
                    no_shipping: 1
                }
            }
        });
    },

    // Wait for the payment to be authorized by the customer

    onAuthorize: function(data, actions) {
        // Execute the payment
        console.log('authorization completed...');
        actions.redirect();
    },
    onCancel: function(data, actions) {
        console.log('authorization completed...');
        actions.redirect();
    },
    onError: function (err) {
        // Show an error page here, when an error occurs
        console.log(err);
    }

}, '#paypal-button-container')
.then(function() {
    console.log('button rendered...');
})

**Comment by bluepnume** [comment]
Can you check this one out @trainerbill ?

**Comment by trainerbill** [comment]
First off you client id didn't work so I grabbed the one from the demo app.  Secondly your JSON was not correct.  The items: is an array.  This worked for me in the payment callback.
```
payment: function(data, actions) {
            return actions.payment.create({
                payment: {
                    transactions: [
                        {
                            amount: { total: 123.00, currency: 'PHP' },
                            item_list: {
                                items: [{
                                    name: 'a',
                                    description: 'abc',
                                    quantity: 1,
                                    price: 123.00,
                                    tax: 0,
                                    sku: 'a',
                                    currency: 'PHP'
                                }],
                                shipping_address: {
                                    recipient_name: 'Brian Robinson',
                                    line1: '4th Floor',
                                    line2: 'Unit #34',
                                    city: 'San Jose',
                                    country_code: 'PH',
                                    postal_code: '1600',
                                    phone: '09567888987',
                                    state: 'Metro Manila'
                                }
                            }
                        }
                    ],
                    redirect_urls: {
                        return_url: window.location.origin + "/success",
                        cancel_url: window.location.origin + "/failure"
                    }
                },
                experience: {
                    input_fields: {
                        no_shipping: 1
                    }
                }
            });
        },
```

**Comment by rafaelcentric** [comment]
**First off you client id didn't work so...** - I apologize as I intentionally changed some part of the client id. 
**Secondly your JSON was not correct. The items: is an array...** -  I apologize again. I don't know what happened but I guess I was a bit of in hurry when I created this issue. I actually have a dynamic array items:. I used the exact JSON above but still not working. Funny, because in my Paypal Guest Checkout, my country is still United States and my State is empty. Everything else is fine. When I try to login, I am getting this error. **SHIPPING_ADDRESS_INVALID**

`{
	"ack": "success",
	"data": {
		"memberSegment": {
			"ack": "success",
			"data": {
				"memberSegment": ""
			},
			"meta": {
				"calc": "67bc1d9dc17d8",
				"rlog": "eabmw6eM025ODHFzdx07Yoo2WAXwZaCjXTHV9EO%2FQbLZ7aU%2F55sxLgPni%2B0ZMUTEgRKmrSaBBF7CMMQcO8GC%2FQ_16632fa274d"
			},
			"server": "0g2uzX1wwa2_-MrXpEHyPUo_1Rs75Vk_vjed--Xf7W2PbjMSgDnSW01MBqAsGEj9qie0Za5pxRdlMNMUkIwf7-Q5XMgjPUnEH52WjFYDDtjmc8Lv-DOdv4sDHcqR85ppVgINsx7xl1ahkw2Hw-t8uuX1H6zn4NEkszRPPmE2xAPIVzxkrfs3gQTli_CtZWbQCFQdD6s5-W8FqvwvTe3MHyvvxgEE60569-JkmQvElq6ma0BXm4doj6bEv91NjryuYvRaypM9sBi"
		},
		"eConsent": {
			"ack": "success",
			"data": {
				"required": false
			},
			"meta": {
				"calc": "67bc1d9dc17d8",
				"rlog": "eabmw6eM025ODHFzdx07Yoo2WAXwZaCjXTHV9EO%2FQbLZ7aU%2F55sxLgPni%2B0ZMUTEgRKmrSaBBF7CMMQcO8GC%2FQ_16632fa274d"
			},
			"server": "VnR8njViKdmmVBwgLhaNct4vxz1qRFHn9A7s7iclIn-1i0e0Ri1_wk506oU-LXg_3hVopD5P6Y2C0YqIM5LEAfkgoUqBonU6ehFud44rwmcKfd7Kl5JVE4er9lgO35yY35hieXk8MIPxES_G7sOiTu_mwN6VWRyBB6LGnqWinzUYqi3QoKcmmV0AXVNf9asZoKAm4De5qdFbeGgTzvKZ_GDM_e_HmUsDFdEpUlnZSOW9zvPfQoZwWuO_88-RRm1T"
		},
		"createCheckoutSession": {
			"ack": "contingency",
			"contingency": "SHIPPING_ADDRESS_INVALID",
			"errorData": {
				"step_up_context": {}
			},
			"meta": {
				"calc": "67bc1d9dc17d8",
				"rlog": "eabmw6eM025ODHFzdx07Yoo2WAXwZaCjXTHV9EO%2FQbLZ7aU%2F55sxLgPni%2B0ZMUTEgRKmrSaBBF7CMMQcO8GC%2FQ_16632fa274d"
			},
			"server": "Yn0VjrLObqVaOIa-6aAD_43_Ebn8o9bJynM2wCld9IgPQ08AIA0QaergBksjhdPMoh-BcbHz0VcPwQz0ccX0ezekz9R8JUgMyk09zDITXVCbdiVyIEY12_7Vc10Bp5KAukfPY2npP2-7JCxI0KnBN1hsFWLptVrdQhxG0j9yqQN19hKHfjLAAgQFPPsIegPNf4QUU5PaLowJE6GXzmC8dK6eEFtDVkrt1zeRRxkDNdXcMoUts1e8b7NXrSP24X2gF_O2acvrGxAnpA0oBjYwiW"
		}
	},
	"meta": {
		"calc": "67bc1d9dc17d8",
		"rlog": "eabmw6eM025ODHFzdx07Yoo2WAXwZaCjXTHV9EO%2FQbLZ7aU%2F55sxLgPni%2B0ZMUTEgRKmrSaBBF7CMMQcO8GC%2FQ_16632fa274d"
	},
	"server": "I2BI5CpYLDBraOBtAkWZjnf1xYxkxd8Iq1yAE5yH4J8W2HAQLKEo3h8WvG649XpxEQSUYQSMHneisY2EawcAKFKfwqJD-Y9HKjwjhjtB0bH3B4WdyZuNd9ugIJgIk9VfEeQai_XDccYkQGxxw0Y6LVzRiB6ckTyGP1YJcxsiVLwUF6NS5hiSIvWCWgfH0GDhiTdbw083YWuF9tYwd_heXc5sZ3v-fcJk90Yq-sygD_W145QLZjMy-iMPQYS2zEPu"
}`

Thank you.

**Comment by trainerbill** [comment]
@rafaelcentric ok that is in our guest checkout product.  It is actually a known issue.  I will try and get some additional visibility to it.  The cause is the way we choose the default country in the list.  Right now it defaults to the merchants locale and not what is passed into the rest api call.

**Comment by rafaelcentric** [comment]
@trainerbill thank you for the support. Actually, the merchant's locale is also Philippines, not United States.  Anyway, we turned off the shipping address for now. Thanks.

**Comment by maxisam** [comment]
I used the same way paypal.Button.render ....

The error message for invalid address is kinda unclear. I use braintree-web with paypal. The error message is like

**PAYPAL_INVALID_PAYMENT_OPTION **

it doesn't really indicate it is an address error.

Braintree does return full error however, paypal-checkout seems like removing some error details.

Could you guys improve the error handling?



Full error is like
```
code: "PAYPAL_INVALID_PAYMENT_OPTION"
message: "Error: PayPal payment options are invalid.↵    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.4.0.233.js:2569:31)↵    at receiveMessage (https://www.paypalobjects.com/api/checkout.4.0.233.js:2611:60)↵    at messageListener (https://www.paypalobjects.com/api/checkout.4.0.233.js:2632:13)"
stack: "Error: Error: PayPal payment options are invalid.↵    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.4.0.233.js:2569:31)↵    at receiveMessage (https://www.paypalobjects.com/api/checkout.4.0.233.js:2611:60)↵    at messageListener (https://www.paypalobjects.com/api/checkout.4.0.233.js:2632:13)↵    at deserializeError (http://localhost:8888/Content/build/dist/Checkout/vendor.js?hash=a1e52b3a82:153042:27)↵    at http://localhost:8888/Content/build/dist/Checkout/vendor.js?hash=a1e52b3a82:153063:274↵    at http://localhost:8888/Content/build/dist/Checkout/vendor.js?hash=a1e52b3a82:152877:34↵    at eachArray (http://localhost:8888/Content/build/dist/Checkout/vendor.js?hash=a1e52b3a82:152860:55)↵    at each (http://localhost:8888/Content/build/dist/Checkout/vendor.js?hash=a1e52b3a82:152866:39)↵    at replaceObject (http://localhost:8888/Content/build/dist/Checkout/vendor.js?hash=a1e52b3a82:152876:17)↵    at http://localhost:8888/Content/build/dist/Checkout/vendor.js?hash=a1e52b3a82:152878:173↵    at eachObject (http://localhost:8888/Content/build/dist/Checkout/vendor.js?hash=a1e52b3a82:152863:69)↵    at each (http://localhost:8888/Content/build/dist/Checkout/vendor.js?hash=a1e52b3a82:152866:148)↵    at replaceObject (http://localhost:8888/Content/build/dist/Checkout/vendor.js?hash=a1e52b3a82:152876:17)"
```

**Comment by trainerbill** [comment]
@maxisam are you using the client side integration pattern, calling actions.payment.create in the payment callback?  If so then you can see the exact error in the network tab when the XHR is called.

**Comment by maxisam** [comment]
Well, braintree throw an error that is clear, but when it bubbles up to PayPal, PayPal doesn't preserve the detail of the error. You guys should work together to handle errors better.
