### ISSUE TITLE
Paypal Express checkout button is not working on production mode

### ISSUE THREAD

**Issue by danpress** [paypal/paypal-checkout#875]
### Paypal Express checkout button is not working after switch from sandbox mode.

Please check these screenshots
http://prntscr.com/kzj20q
http://prntscr.com/kzj2jw

It is working on sandbox mode, but not working on production mode.

I tried again after create new paypal app and key, secret. but failed.

**Comment by bluepnume** [comment]
Can you share your client IDs?

**Comment by danpress** [comment]
```
const client = {
    sandbox:    'Aaii5bce92CIHhO5t_8AKOOzINJd6DKo0JhY3Aaz9Lzsi8-QOlz63dXhvz8E8ikutEABPMPCyNV2M0cx',
    production: 'EL2_9jwgIiWnspwt2C_9fbN-DQ8mU572kNhPE7hgrVmHvdfJquvwHVZHmr9j-WHIj-IF_c9-KPQSKCGW'
};
```

**Comment by danpress** [comment]
@bluepnume 
It works for you?

**Comment by bluepnume** [comment]
Looks like `Aaii5bce92CIHhO5t_8AKOOzINJd6DKo0JhY3Aaz9Lzsi8-QOlz63dXhvz8E8ikutEABPMPCyNV2M0cx`is a valid production client id -- not a sandbox id.

Are you changing the `env` setting in your integration to `sandbox` and `production`?

**Comment by danpress** [comment]
Any updates?

**Comment by bluepnume** [comment]
`Aaii5bce92CIHhO5t_8AKOOzINJd6DKo0JhY3Aaz9Lzsi8-QOlz63dXhvz8E8ikutEABPMPCyNV2M0cx ` -> this is a production client id

`EL2_9jwgIiWnspwt2C_9fbN-DQ8mU572kNhPE7hgrVmHvdfJquvwHVZHmr9j-WHIj-IF_c9-KPQSKCGW ` -> this doesn't work for me in either env.

Can you please try creating a new sandbox client id. You can use that first id for production.
