### ISSUE TITLE
Paypal express checkout not working in production mode

### ISSUE THREAD

**Issue by kartik2206** [paypal/paypal-checkout#879]
When I am using paypal express checkout in sandbox mode everything seems to be fine and transactions get successful but when I use it in production mode I am shown the below screen after authorization from bank i.e. I guess the execution gets an error because I saw the console and there was this message 

![image](https://user-images.githubusercontent.com/28218177/46397387-c0547f00-c70f-11e8-8f0a-59c560f44dd5.png)

![production](https://user-images.githubusercontent.com/28218177/46397219-43290a00-c70f-11e8-8f5f-245827a79ba4.png)

I have used correct production client id, there is nothing wrong with it. How can I make the transactions in production successful ?

You can check this error live on [Workern](https://www.workern.com) by logging in and going to profile.

**Comment by bluepnume** [comment]
@mcntsh looks similar to another issue you were looking into. Can you try to repro and narrow this down?

**Comment by mcntsh** [comment]
Hey @kartik2206, could you start by posting the button render code? Please edit out any sensitive information like keys and email addresses.

**Comment by mcntsh** [comment]
@kartik2206 since you're trying to take INR payments, have you gone through [this checklist](https://www.paypalobjects.com/digitalassets/c/website/marketing/apac/IN/enable-inr-for-merchants/enabling-inr-payments-direct-website-ec.pdf)? 

> As per Indian Regulations, you need to compete Domestic KYC to start receiving domestic payments in INR.

[What Is the KYC Procedure](https://www.paypal.com/in/webapps/mpp/how-to-guides/kyc-process).

**Comment by kartik2206** [comment]
I contacted mts a few days back and they replied with the transaction had been declined by the bank. I wasn't able to talk further on this issue to mts support due to time constraints. I had questions like when I use the same debit card using paypal on other website it works and it is not declined.  Other than this the three steps written in the pdf file you sent are already done.

**Comment by mcntsh** [comment]
I would suggest following up with MTS on this issue since it seems like the transaction is being rejected either due to risk or, like you mentioned, being declined from the bank. As far as I can tell this isn't an error related to Checkout.js.

**Comment by mcntsh** [comment]
Closing this for now. Please re-open a ticket if you are still experiencing issues with Checkout.js after you've gone through the MTS channels 👍
