### ISSUE TITLE
javax.validation.ValidationException: HV000028: Unexpected exception during isValid call.[java.lang.NullPointerException]

### ISSUE THREAD

**Issue by majorvms** [paypal/paypal-checkout#881]
### Description

Paypal button doesn't work for customers from Sint Maarten.
If I pass US country code it works well
```
payer_info: {
  billing_address: {
    ....
    country_code: "US",
    state: "FL"
  }
}
```

But for SX country code it doesn't
```
payer_info: {
  billing_address: {
    ....
    country_code: "SX",
    state: "Florida"
  }
}
```

PayPal popup doesn't appear. There is the error in console
```
VM2992:1 POST https://www.sandbox.paypal.com/v1/payments/payment 500 (Internal Server Error)
strategies.js:55 Uncaught Error: Error: Invalid json: javax.validation.ValidationException: HV000028: Unexpected exception during isValid call.[java.lang.NullPointerException]. Correlation id: f75c279fdffb8, f75c279fdffb8
```

![image](https://user-images.githubusercontent.com/20680958/46478397-f40dd280-c7fd-11e8-8628-017f07bf6111.png)

### Steps to reproduce

1. Visit https://developer.paypal.com/demo/checkout/#/pattern/client
2. Put this code
```

<!DOCTYPE html>

<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://www.paypalobjects.com/api/checkout.js"></script>
</head>

<body>
    <div id="paypal-button-container"></div>

    <script>
        paypal.Button.render({

            env: 'sandbox', // sandbox | production

            // PayPal Client IDs - replace with your own
            // Create a PayPal app: https://developer.paypal.com/developer/applications/create
            client: {
                sandbox:    'AZDxjDScFpQtjWTOUtWKbyN_bDt4OgqaF4eYXlewfBP4-8aqX3PiV8e1GWU6liB2CUXlkA59kJXE7M6R',
                production: '<insert production client id>'
            },

            // Show the buyer a 'Pay Now' button in the checkout flow
            commit: true,

            // payment() is called when the button is clicked
            payment: function(data, actions) {

                // Make a call to the REST api to create the payment
                return actions.payment.create({
                    payment: {
                        payer: {
                            payment_method: "paypal",
                            payer_info: {
                              billing_address: {
                                phone: "1234567890",
                                line1: "test",
                                line2: "test",
                                city: "Miami",
                                country_code: "SX",
                                postal_code: "33172",
                                state: "Florida"
                              }
                            }
                          },
                        transactions: [
                            {
                                amount: { total: '0.01', currency: 'USD' }
                            }
                        ]
                    }
                });
            },

            // onAuthorize() is called when the buyer approves the payment
            onAuthorize: function(data, actions) {

                // Make a call to the REST api to execute the payment
                return actions.payment.execute().then(function() {
                    window.alert('Payment Complete!');
                });
            }

        }, '#paypal-button-container');

    </script>
</body>
```
3. Click PayPal Checkout button

### Affected browsers

- [x] Chrome
- [x] Safari
- [x] Firefox

**Comment by majorvms** [comment]
Also this error affects production.

**Comment by bluepnume** [comment]
Is 

```
    country_code: "SX",
    state: "Florida"
```

A valid combination? Do you see this error for any valid country/state combinations?

**Comment by majorvms** [comment]
It is not valid, that is just for example. But the error occurs for any combination with country_code: "SX". Either if I pass any value in state or miss it.

**Comment by bluepnume** [comment]
OK. Good to know. If there are any examples which show a valid combination which cause the api to fail, please feel free to share them. I'll pass them along to the api team.

**Comment by qetzal** [comment]
@bluepnume 
I think this issue needs to be fixed. Here is why: 

1. If an incorrect country/state combination is submitted, we expect to get an error describing that, so we can communicate the issue to a customer. At this moment we get 500 error and `NullPointerException` on a PayPal side. It doesn't look like an expected and correct behaviour. 

2. Sint Maarten ("SX") country doesn't have regions/states. As @majorvms said if we omit the `state` field or send an empty string, we still get the 500 internal error. It means that customers from Sint Maarten cannot pay using PayPal. Yes, the Sint Maarten population isn't big (35k), however we have customers from this country as well.

**Comment by bluepnume** [comment]
> As @majorvms said if we omit the state field or send an empty string, we still get the 500 internal error

OK that's good to know. Re-opening this and I've passed it on to the correct team.

**Comment by bluepnume** [comment]
Closing for now, since this issue is being tracked internally, and this repo is primarily for the sdk itself.
