### ISSUE TITLE
Multiple PayPal checkout buttons not appearing correctly on page

### ISSUE THREAD

**Issue by flyingL123** [paypal/paypal-checkout#882]
Our website is hosted with BigCommerce, and I have noticed recently that our PayPal buttons do not all appear as expected on the cart page. The cart page has 3 locations where the button is supposed to appear.

Location 1: Mobile-only top location
Location 2: Desktop-only top location
Location 3: Mobile and Desktop bottom location

The buttons used to appear in all three locations as expected, but recently I've noticed that only Location 1 is appearing, and the other two locations do not show a button.

Is PayPal performing some sort of logic to prevent the button from appearing multiple times on a page? This is troublesome for us since we need the button to appear in multiple places. For example, here is the mobile layout, which works correctly since the mobile-only top location is the first one in the markup. The PayPal button appears correctly underneath the AmazonPay button:

<img width="378" alt="screen shot 2018-10-05 at 9 57 20 am" src="https://user-images.githubusercontent.com/2486712/46539679-2a426500-c885-11e8-9a7e-01e401cf3d64.png">

However, there should also be a PayPal button in Location 3 underneath the Amazon button, but as you can see, it does not appear:

<img width="378" alt="screen shot 2018-10-05 at 9 57 27 am" src="https://user-images.githubusercontent.com/2486712/46539707-3f1ef880-c885-11e8-97a0-6f243b2ebf25.png">

Additionally, on desktop, no PayPal buttons appear since desktop uses Location 2 and Location 3:

<img width="1190" alt="screen shot 2018-10-05 at 9 59 38 am" src="https://user-images.githubusercontent.com/2486712/46539755-64136b80-c885-11e8-834c-e1f29cecf72e.png">

The website is https://www.storeyourboard.com. Just add a product to your cart to see the issue. Feel free to tinker around if needed. `paypal.version` says 4.0.224. Using Chrome Version 69.0.3497.100 (Official Build) (64-bit).

**Comment by flyingL123** [comment]
Anyone seeing this? The issues is still occurring.

**Comment by bluepnume** [comment]
Hi, can you please fill out an issue and answer all of the requested questions? Otherwise it's difficult for us to debug.
