### ISSUE TITLE
No ack for postMessage xcomponent_init error message when larger number of items in cart

### ISSUE THREAD

**Issue by jdhaack** [paypal/paypal-checkout#885]
I have a merchant getting a large number of errors when their cart reaches an approximate size (about 30ish items).  Specifically several of these
      Error: No ack for postMessage xcomponent_init in https://www.paypal.com in 2000ms

After a couple seconds the paypal button disappears.

Please provide a short description of the issue here, along with:

Video:
https://cl.ly/7f583a45faa6
Screenshot:
<img width="1802" alt="screen shot 2018-10-05 at 5 55 20 pm" src="https://user-images.githubusercontent.com/21247141/46637367-84f7ed00-cb21-11e8-9124-4e15aa64ccfc.png">

- The exact browser version
Several (my most recent test is in Version 69.0.3497.100 of Chrome)

- A link to your page with the issue, if possible
Listed in steps to reproduce

- All console logs during the time of the issue, especially error messages
***************************
Several of these:
checkout.js:249 ppxo_xc_ppbutton_error {error: "Error: No ack for postMessage xcomponent_init in h…://www.paypalobjects.com/api/checkout.js:2708:73)", timestamp: 1539039347412, windowID: "d5be2c771e", pageID: "255b935c78", prev_corr_ids: "", …} 

 Error: No ack for postMessage xcomponent_init in https://www.paypal.com in 2000ms
    at cycle (https://www.paypalobjects.com/api/checkout.js:2708:73)
***************************
- Does the issue occur consistently, or intermittently?
Consistently

### Steps to reproduce
•	EXISTING USER
1.	navigate to https://www.boxed.com
2.	login as paypal-test@example.com / payment123
3.	cart should load with 30+ items
4.	click on checkout
5.	select Paypal as payment type and click "save + continue"
6.	see Paypal & Paypal Credit buttons 
7.	wait 10+ seconds
8.	Paypal & Paypal Credit buttons disappear

•	NEW USER
1.	navigate to https://www.boxed.com
2.	create a new account 
3.	add 30+ individual items 
4.	continue with checkout steps as above

### Affected browsers
All

**Comment by bluepnume** [comment]
@abarco can you take a look?

**Comment by abarco** [comment]
Hi @jdhaack, I took a look at your site and it seems you're using React.js. Can you let me know what kind of integration you are using? For a react integration we prefer that you use this patterns:
https://github.com/paypal/paypal-checkout/blob/master/demo/react.htm
https://github.com/paypal/paypal-checkout/blob/master/docs/frameworks.md

I believe that there might be problems updating the DOM if you go with the regular integration without using these solutions. 

Another thing that could be helpful, can you let us know when this problem started? Let us know if you have any visibility on that.

**Comment by jdhaack** [comment]
Update from Merchant (Let em know if you want me to add you to the thread with them):

We pushed the "react" integration changes to one of our preprod environments but I see the same issue there as well but the only difference is, sometimes the PayPal buttons are visible after the console errors and sometimes the buttons are not. We have two sets of buttons, a pair on the top of checkout and a pair near the bottom of checkout. I'm not sure when these issues started since it is only occasionally reported by our customer service team.

here is a snippet of our PayPal button integration
https://gist.github.com/johnkimz/e1499464a1405cf4834aa58f2f960b96


Test Environment
https://vpc-preprod-web-perf-public.boxed.com
•	EXISTING USER
1.	navigate to https://vpc-preprod-web-perf.boxed.com
2.	login as paypal-test@example.com / payment123
3.	cart should load with 30+ items
4.	click on checkout
5.	select Paypal as payment type and click "save + continue"
6.	see Paypal & Paypal Credit buttons 
7.	wait 10+ seconds
8.	Paypal & Paypal Credit buttons disappear
•	NEW USER
1.	navigate to https://vpc-preprod-web-perf.boxed.com
2.	create a new account 
3.	add 30+ individual items 
4.	continue with checkout steps as above

**Comment by bluepnume** [comment]
Closing this as issue seemed to be with the merchant's site blocking the event loop. Please let me know if this is still a problem.
