### ISSUE TITLE
PayPal button crashes on mounting 

### ISSUE THREAD

**Issue by pasyukevich** [paypal/paypal-checkout#886]
###Description

We use react button from PayPal-checkout.js
Also we use braintree-web 3.34 that we inserted as a property to PayPal button.

Browser version: Google Chrome 69.0.3497.100
This error is not reproducible in sandbox mod.

<img width="534" alt="2018-10-10 12 22 47" src="https://user-images.githubusercontent.com/23215729/46726946-2b5e0280-cc88-11e8-9f8b-4d88b346b82c.png">

weakmap.js:128 Uncaught Error: WeakMap expected key
    at CrossDomainSafeWeakMap.get (weakmap.js:128)
    at Object.linkUrl (parent.js:201)
    at index.js:161
    at _loop (promise.js:156)
    at ZalgoPromise.dispatch (promise.js:147)
    at ZalgoPromise.then (promise.js:240)
    at index.js:159
    at Function.ZalgoPromise.try (promise.js:393)
    at ParentComponent.tryInit (index.js:1283)
    at ParentComponent.render (index.js:115)

### Steps to reproduce
1. Clear site data
2. Open site page with PayPal button.
3. PayPal would fire onError action.
4. Check the button. It disappeared.

**Comment by bluepnume** [comment]
Do you have a page where I can repro this? Is it reproducible at https://developer.paypal.com/demo/checkout ?

**Comment by pasyukevich** [comment]
I can not reproduce it at https://developer.paypal.com/demo/checkout. You can see this issue on the www.tireamerica.com/checkout/billing-information. Sometimes it crashes even without fired onError. It reproducible only for the first time after clear site data from application tab in dev tools.

**Comment by pasyukevich** [comment]
It reproduces again.

**Comment by bluepnume** [comment]
<img width="498" alt="screen shot 2018-10-22 at 9 39 03 am" src="https://user-images.githubusercontent.com/1219075/47308660-19b11f00-d5e7-11e8-9322-87d1fb56b626.png">

Looks like there are multiple `head` and `body` elements on the page. That's throwing checkout.js for a loop.
