### ISSUE TITLE
React - paypal.Button.driver vs paypal.Button.render

### ISSUE THREAD

**Issue by leotm** [paypal/paypal-checkout#889]
### React - paypal.Button.driver vs paypal.Button.render

Not really an issue, but are there any pros/cons to the `paypal.Button.driver` React implementation over the `paypal.Button.render` vanilla JS implementation transpiled to React+TypeScript something like this?

```
import React from 'react'

interface Props {
  ...
}

interface State {
  ...
}

export default class App extends React.Component<Props, State> {
  constructor(props: Props) {
    super(props)
    this.state = {
      ...
    }
  }

  componentDidMount() {
    ;(window as any).paypal.Button.render(
      {
        env: 'sandbox',
        payment: () => {
          ...
        },

        onAuthorize: data => {
          ...
        },

        onCancel: (data) => {
          ...
        },
      },
      '#myContainerElement',
    )
  }
  render() {
    return <div id="myContainerElement" />
  }
}
```
Cheers

**Comment by bluepnume** [comment]
I think in your example above, the element won't be ready by the time `componentDidMount` is called.

The other main thing we need the react driver for is if you're passing in any props which you expect to change.

It's also a bit more native; relies less on you directly passing in a DOM element, and follows the react rendering convention.
