### ISSUE TITLE
IE Intranet Error should fire onError

### ISSUE THREAD

**Issue by trainerbill** [paypal/paypal-checkout#894]
![image](https://user-images.githubusercontent.com/3578259/47047333-e260ef00-d15c-11e8-8fc7-942d6a977da7.png)

**Comment by mcntsh** [comment]
Adding this is contingent upon some additional error handling logic within Zoid. I have a PR open which calls the `onError` prop if any errors are thrown in your validators.

**Comment by mcntsh** [comment]
With our latest release ([v4.0.233](https://github.com/paypal/paypal-checkout/tree/v4.0.233)), all errors thrown in validation will now also pass through `onError`, including the _IE intranet mode_ error. Can you confirm this is the case for you?

**Comment by mcntsh** [comment]
I just tested in IE 11 Intranet Mode and I did hit the `onError` callback 👍.
