### ISSUE TITLE
Provide SRI 

### ISSUE THREAD

**Issue by jag1989** [paypal/paypal-checkout#897]
With the interest of security, checkout.min.js should allow integrity checks on the request. [SRI](https://www.w3.org/TR/SRI/), This is fairly well supported in browsers now: https://caniuse.com/#search=sri

Proposal:

Current
`<script src="https://www.paypalobjects.com/api/checkout.min.js"></script>`

With SRI
`<script src="https://www.paypalobjects.com/api/checkout.min.js" 
   integrity="sha512-hash"
   crossorigin="anonymous"></script>`

**Comment by bluepnume** [comment]
Hmm. My only concern is, we update this script pretty frequently. That's not going to work with SRI right?
