### ISSUE TITLE
Split out and lazy load resources.

### ISSUE THREAD

**Issue by bluepnume** [paypal/paypal-checkout#90]
For content that needs to be rendered on the merchant site, like overlay template, content.

- [ ] Overlay template
- [ ] Component template
- [ ] Overlay content
- [ ] Button content?

**Comment by vasanthk** [comment]
@bluepnume Came here after reading #44 
Wondering if you have any updates on the progress for this since it's been a while.

**Comment by vasanthk** [comment]
@bluepnume Is there a way to do this now?
