### ISSUE TITLE
Checkout suddenly stops working for me, server errors from paypal

### ISSUE THREAD

**Issue by kgrosvenor** [paypal/paypal-checkout#910]
Continuously loading when trying to log in on the modal, my server was successful in creating the payment then your server gave a 500 error

I followed the server and client integration guide and this was working until today on sandbox? 

This was working last night...

Screen shot of the network log:

[![Screenshot from Gyazo](https://gyazo.com/4e7af4f579fb4c148bfce7a84986617d/raw)](https://gyazo.com/4e7af4f579fb4c148bfce7a84986617d)

**Comment by cyberaleks** [comment]
+1 Same for us. I guess the sandbox server is down.

**Comment by crookedneighbor** [comment]
Another report here: https://github.com/paypal/paypal-checkout/issues/911

**Comment by Niceplace** [comment]
Same here, our automation test suite continously fails:

```
NoSuchWindowError: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=70.0.3538.67)
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 3.10.0-862.11.6.el7.x86_64 x86_64)
```

**Comment by kgrosvenor** [comment]
Seems to be back now 🤟

**Comment by mcntsh** [comment]
I'm closing this out because it seems to be related to some downtime on Sandbox that is now resolved.
