### ISSUE TITLE
Unhandled API error

### ISSUE THREAD

**Issue by lotsofdan** [paypal/paypal-checkout#914]
Set Buyer returns:
`{"ack":"success","data":{"eConsent":{"ack":"success","data":{"required":false},"meta":{"calc":"220a521696e4d","rlog":"dDWhi9MDnnpHvbTDE3CGQThDPJxLLyVCyLwydHLwFL6ZZn1DwPdPfea%2FUb%2FWO%2Ff0BB56x7ASFvrfJQvH%2FfOATA_166aaf25f8d"},"server":"SriJGE3Lr5_bwVMqHAXvUOdzri0aYQMy95aHRUuaSrDLr2unR5SUm7-8wUstfA9--5LHWfF6OWMtUzkGMHqLkHd5KQ05W8fddB7uJj_M_S-WmNGcroFnPGfCyLc0ERbhTViRAAve5J9CGP-A9q19Nbj9QLjFTymFK7ktztdg54UnJr7Eb79_Hj9VNzRDGHgPV2X848U-Cp0ui0FnfP9wwUHnT4n5Vqyigc2O0kMVqJ8fRorjW1yssbm-IMe6V0VM"},"memberSegment":{"ack":"success","data":{"memberSegment":""},"meta":{"calc":"220a521696e4d","rlog":"dDWhi9MDnnpHvbTDE3CGQThDPJxLLyVCyLwydHLwFL6ZZn1DwPdPfea%2FUb%2FWO%2Ff0BB56x7ASFvrfJQvH%2FfOATA_166aaf25f8d"},"server":"gPd-W1Z2H8DyhMDzD2o8xVRWmAL4mc72GE-rJUpDEnRZKtut88UpO7zVt4380nwiM2PJir6W2OPY2E8SHk5TX3ebUVA4pKUpEQau6vv1Xbs39UB7Gy1s47hgiv-E0yr5c6E45jB2q71QR6_ZH2PmZVmMAOnlcFB_vlJh4BWZTmuXxdX5EstvYKp8UNv-LKU_qD1EuzkQSag3O6LxEYRaLK_p71dhlKdSvaaJ2nldwhS2560wos3WgcmIs7FxOcN0z0RskhpsVyu"},"createCheckoutSession":{"**ack":"error","message":"Unhandled api error"**,"meta":{"calc":"220a521696e4d","rlog":"dDWhi9MDnnpHvbTDE3CGQThDPJxLLyVCyLwydHLwFL6ZZn1DwPdPfea%2FUb%2FWO%2Ff0BB56x7ASFvrfJQvH%2FfOATA_166aaf25f8d"},"server":"WyD54lI1TaTDjRV-fwTTHc3aUyc4tfHvO1X6MXDyTn2V0RBFfp8m7BHJUnehvmEqj-gjo92vjv63bcs1RekH244piSBDqzaxTvq6hvt2cSYVrDSSwG1WTu__HB4-LzFszM7J1Garf53fbhrFedJqPCiJw-frHFh3Qbkgu1pnC9Vla9RwkJuiny9rH_jLjJJHDjcf-zA-QlyX8hE45Aqxk7rcBiDkiekaiO8bN-9GcX7J5NqAAxF5nJaiE1M0BIZ3KPwWR6Kcp_GwtwCduoIUeW"}},"meta":{"calc":"220a521696e4d","rlog":"dDWhi9MDnnpHvbTDE3CGQThDPJxLLyVCyLwydHLwFL6ZZn1DwPdPfea%2FUb%2FWO%2Ff0BB56x7ASFvrfJQvH%2FfOATA_166aaf25f8d"},"server":"I8OyWOhrE5fciIScMWsE-54fE1IcQgh8jyVh8WpoJZKTP4Q0_otY7Z208NCsUeONhMFVAKWVJFYaSCCA3L9Zm2z4JsMlVuMN0OWdUzxKGcOoO67SYuHmBvDjOjKCwoIOaBDRZIvrhp72vXQ7UBN5nxXc8wB1c00m1G3bJIJR0PCHwaLrESSlkGipo99ime6bDRQTY3gIDb9PCrigYGZkFQ7kBYt9-8R3WZXqUPZ-OKJK0ubtuZx78DJ8D3Qd1am5"}`

Create returns:

`{"ack":"error","message":"Unhandled api error","meta":{"calc":"536cefb07d6b0","rlog":"5nnZF61VvpEUv3bjDhsdER7f04m%2FjM3Ly2be%2FW7hU1%2BmuQIEr%2BcVi%2FnGBOUyKMupaj1pbQ%2FyUteDKZ087wX%2Frg_166aaf34650"},"server":"KDeK5FrzIx8rYeytpqDeth1k1NqpajVK17ywFfBw9nXewjVPiBKQqx16az9mMUD_G23kIfSMN0pEX-3P8Sw821mXCWuT5qiDcyq4LK8LPLqdivsTG_o7LjPJUdJK-0jsO0CGhvUI3WJBiD0n6J4Rxls-r0TXRtGducgkBcoqmldFXR5_qlyQS7UGo4GFpisSwyqwaVsiKKIT1wBL6gAiCCQFMi6GqNXZbr6aRX_Twa1PZe7x98Q4wD0j_AwR2PHxAMcx3FqjKsqbJWREY_D9GG"}`

Getting an error in the paypal sandbox using the new checkout.js paypal integration. Window for login opens but after a minute or so of spinning we get the above error on https://www.sandbox.paypal.com/webapps/hermes/api/checkout/EC-48H800935J469730C/session/create

This was working this morning, looking at some stackoverflow posts and recent git comments there are others facing the same error. Looks like an update gone awry your end?

**Comment by ferencbalogh** [comment]
This problem still exist. 
![kepkivagas](https://user-images.githubusercontent.com/2694621/53365228-06211680-3941-11e9-8e2f-b8532e0ceb9d.JPG)

**Comment by dpccristi** [comment]
Yeah.. me too, @ferencbalogh , do you found a solution?

**Comment by lotsofdan** [comment]
honestly pal, i gave up and just built against the production api and set the payments to £1 and just refunded myself every day until i was done testing. It sounds like a cop-out, but I couldn't wait for paypal to sort out their shit

**Comment by ferencbalogh** [comment]
@dpccristi Test in production better than sandbox, other things really funny, we provide 30 days access to premium content. We cant disable shipping address. :D

**Comment by mauriblint** [comment]
> @dpccristi Test in production better than sandbox, other things really funny, we provide 30 days access to premium content. We cant disable shipping address. :D

Hey, I'm having the same issue using the sandbox API testing my integrations with Smart Buttons. To disable the shipping, add this param:

`          application_context: {
              'shipping_preference': 'NO_SHIPPING'
          }`
