### ISSUE TITLE
'No certificates found' message is shown in Chrome on Android

### ISSUE THREAD

**Issue by iaaflaafc** [paypal/paypal-checkout#915]
### Description

I am using `paypal-checkout` in my web app.
In Chrome 69.0.3497.100 on Android, the following message is shown when the web app loads
![image](https://user-images.githubusercontent.com/34213562/47497824-f3a2ad80-d878-11e8-9af3-7298a69df3a6.png)

This message is not shown in Chrome on MacOS or in Firefox on MacOS.

version of `paypal-checkout` - `4.0.228`.

Can anyone help me how to resolve this message?

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [x] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by lparenteau** [comment]
Seeing this issue as well, on Chrome on Android devices, and Samsung's browser (Android too).
