### ISSUE TITLE
"Сontacting the merchant to update your shipping address" error message when trying to pay with PayPal

### ISSUE THREAD

**Issue by UnaEcwid** [paypal/paypal-checkout#916]
### Description

Customers are not able to place an order: they try to pay with PayPal and get this error: "Сontacting the merchant to update your shipping address". Some payments may successfully go through and appear in PayPal accounts, but orders won't be placed in Ecwid stores. 

>- Screenshots or videos that show the issue

http://take.ms/AwE4Q

>- Steps to reproduce

1) Open https://store15436277.ecwid.com/, add a product to the shopping bag and proceed to checkout;
2) Click the "Pay with PayPal" button;
3) Fill in the payment form and pay.

What happens: 

1) The session is successfully created, but

`POST https://www.paypal.com/webapps/xoonboarding/api/checkout/EC-4U117753FY9470635/session/create` returns 200

2) The authorization request is successful and 

`POST https://www.paypal.com/webapps/xoonboarding/api/checkout/EC-4U117753FY9470635/session/authorize` returns 200 too

3) Then, a charge occurs, but customers are not redirected to the store

### Affected browsers

It can be reproduced in any browser.

**Comment by mcntsh** [comment]
Hey @UnaEcwid,

Could you please post your integration code?

**Comment by simonaberry** [comment]
We are seeing exactly the same issue with checkout.js 4.0.228, started today.

**Comment by mcntsh** [comment]
We've identified the issue and are rolling out a fix. Thanks for your patience, guys.

**Comment by ChesterEcwid** [comment]
I've checked - it's working correctly now, thanks!
