### ISSUE TITLE
Trigger paypal iframe on click of custom button

### ISSUE THREAD

**Issue by avinashlitmus7** [paypal/paypal-checkout#923]
### Description
Is it possible to trigger Paypal iframe on click of a custom edit button on our website

We are using Paypal for our checkout process. On the review step of checkout , we have an EDIT button. Is it possible to trigger the Paypal iframe window when we click EDIT button ?

**Comment by mcntsh** [comment]
Hey @avinashlitmus7, unfortunately we do not expose any sort of API to trigger the pop-up other than a click on the button.
