### ISSUE TITLE
Lightbox opening when opened in a mini-browser.

### ISSUE THREAD

**Issue by ppnsanders** [paypal/paypal-checkout#925]
### Description

Please provide a short description of the issue here, along with:

When opening a browser via JavaScript and showing the PayPal buttons in the new window when the PayPal button is clicked a lightbox opens showing "Something went wrong".

### Steps to reproduce

Information provided directly to @mcntsh 

### Affected browsers

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by mcntsh** [comment]
There have been a couple attempts at fixing this bug! [This PR](https://github.com/paypal/paypal-checkout/pull/929) should solve it, though, and it will be out in the next release.
