### ISSUE TITLE
Useraction commit is not honored when initiating popup from lightbox

### ISSUE THREAD

**Issue by trainerbill** [paypal/paypal-checkout#93]
Reproduce: 

1.  Get PayNow  button using commit: true
2.  Get lightbox experience
3.  Click Not You?
4.  Login

Button now says continue and not pay now.

**Comment by abarco** [comment]
Hi @trainerbill,

Thanks for bringing this up. We have a fix for this issue and it should be pushed by early January.

**Comment by bluepnume** [comment]
Again assuming this is fixed @abarco, closing.
