### ISSUE TITLE
Overlay does not close upon onAuthorize, IE 11

### ISSUE THREAD

**Issue by cbathgate** [paypal/paypal-checkout#942]
### Description

Please provide a short description of the issue: **PayPal overlay does not go away after user hits "Agree & Continue" on the PayPal pop-up. The PayPal pop-up goes away, but the overlay doesn't. IE 11 only.**

Screenshots or videos that show the issue:
<img width="1436" alt="screen shot 2018-11-07 at 5 04 32 pm" src="https://user-images.githubusercontent.com/20331607/48171103-40da4280-e2af-11e8-8730-6bc188ac914e.png">

<img width="1442" alt="screen shot 2018-11-07 at 5 04 40 pm" src="https://user-images.githubusercontent.com/20331607/48171111-48015080-e2af-11e8-86e4-4a87a089d166.png">

Code: https://gist.github.com/cbathgate/38fa76fbaad54c8380f6870259207fd7
The `paypal.version` from your browser console: **4.0.231**
The exact browser version: **11.0.9600.19155**
A link to your page with the issue, if possible: **PayPal feature is not on production. Still only lives in our staging environment.**
All console logs during the time of the issue, especially error messages:
<img width="1383" alt="screen shot 2018-11-07 at 4 42 39 pm" src="https://user-images.githubusercontent.com/20331607/48170887-69157180-e2ae-11e8-878d-698a23d08a23.png">
The following console logs occur when I try to click out of the overlay:
<img width="1431" alt="screen shot 2018-11-07 at 4 57 17 pm" src="https://user-images.githubusercontent.com/20331607/48170908-76326080-e2ae-11e8-838c-07aa45c0a3f9.png">
Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)? : **No**
Does the issue occur consistently, or intermittently?: **Consistently**

### Steps to reproduce

1) Click on the PayPal button. PayPal pop-up + overlay should appear
2) Sign-in at the PayPal pop-up
3) Choose a payment method
4) Click "Agree & Continue"
5) PayPal pop-up disappears, but overlay stays in place. Clicking the "close" button on the upper right-hand corner does nothing

### Affected browsers
- IE

**Comment by mcntsh** [comment]
Hey @cbathgate,

Could you perhaps provide some details on what these functions do within the `onAuthorize` callback? If there is any synchronous code in here that blocks the thread this could be the source of the issue.

To give you some background, we look for a response from that `onAuthorize` callback. If you return void (like above), or a non-promise we will resolve the callback immediately, and if you return a promise we will resolve the callback whenever the promise resolves. If there's no resolve in 2 seconds you'll see this error.

**Comment by cbathgate** [comment]
Thanks for getting back to me. So you are expecting a promise to be returned? So I updated the code and wrapped everything in the onAuthorize in the promise and returning that promise. I am still seeing the same errors in the console, and the overlay is not disappearing on IE:
``` onAuthorize(data) {

        const necessaryPromise = new Promise((resolve => resolve('Success')));
        return necessaryPromise
            .then(() => {
                this.props.resetPaymentProfile();
                this.props.setToken(data.paymentToken);
                this.props.setPaymentProfileFormMode(
                    constants.PAYMENT_METHOD_PAYPAL_ADD
                );
            }).catch(() => {
                console.log('Failed');
            });
    }```

**Comment by cbathgate** [comment]
ok, so when I refactored a bit, I was able to get IE to work and the errors to disappear. Now there is only one function in `onAuthorize`
```
onAuthorize(data) {
      this.props.setToken(data.paymentToken);
} 
```
Is there documentation that specifies what `onAuthorize` is expected to return?

**Comment by cbathgate** [comment]
Background on the functions inside the original `onAuthorize` : they are actions that update our redux state. `this.props.resetPaymentProfile` sets a property to null, `this.props.setToken(data.paymentToken)` sets a property to a new string, and `this.props.setPaymentProfileFormMode` sets a property to a new string. I timed this, and these three actions averages to about 100ms total. How would that cause the error?

**Comment by mcntsh** [comment]
Documentation is still a work-in-progress! We are spending a good amount of time revamping them to provide more clarity around these callbacks, so I apologize that they are a bit of a "black box" right now. 

Thanks for the info about your functions. I'm going to set up my own instance with Redux and see if I can replicate this.

**Comment by cbathgate** [comment]
Thank you so much @mcntsh . Looking forward to see what you find

**Comment by mcntsh** [comment]
Alright I have a suspicion about what's going on... is either `resetPaymentProfile` or `setPaymentProfileFormMode` causing the button template to re-render? If so we lose that communication between the parent and child component.

That being said, we should be performing a clean-up when this happens and the overlay should definitely close. I'll have to do some digging to see what's going on in IE11.

**Comment by cbathgate** [comment]
yes, you know what, `setPaymentProfileFormMode` is causing that re-render. I will go ahead and test moving just that action to another part of our application and see if that does the trick. And thank you for investigating the IE 11 portion of the issue in the meantime

**Comment by cbathgate** [comment]
Confirmed, that was the issue. Now the errors are no longer present in all browsers, and we no longer have the frozen overlay problem. Looking forward to hearing why the clean-up wasn't happening in IE

**Comment by mcntsh** [comment]
Following up here -- I haven't forgotten about this! 

Fixing this bug will most-likely require changes to [`cross-domain-utils`](https://github.com/krakenjs/cross-domain-utils/blob/master/src/utils.js#L425). It appears as though in certain cases, `isWindowClosed` is not returning `true` after the Checkout window is cleaned up which prevents the other clean-up tasks from happening. This is trickier to determine than you'd think, as is most things with IE!

I'll update this issue when the fix is out.

**Comment by cbathgate** [comment]
Thank you for the follow-up: looking forward to the fix

**Comment by bluepnume** [comment]
@mcntsh -- I added https://github.com/krakenjs/cross-domain-utils/commit/2f044960143346210d6d20bdb45fc1ae63ef04d8 -- it trades off memory usage in IE11 for extra reliability for `isWindowClosed()`. Can you please pull this into your test env and see if it resolves this issue?

**Comment by mcntsh** [comment]
Following up on this. As of `v4.0.240` we are using `cross-domain-utils@2.0.22`, which has a fix for this issue. I just tested myself in IE 11 using the latest checkout.js (https://www.paypalobjects.com/api/checkout.js) and am no longer able to reproduce. 

@cbathgate are you still seeing this issue on IE 11?

**Comment by mcntsh** [comment]
Closing this out. If you see the issue crop again, feel free to open it back up!
