### ISSUE TITLE
How is the `payment` function called when using `paypal.Button`?

### ISSUE THREAD

**Issue by ziyadparekh** [paypal/paypal-checkout#944]
This is more of a question, but I'm trying to figure out where in the codebase the `payment` function prop is called. In the documentation it says that the function is called when someone clicks the button, but in the component definition inside `/button.component.jsx` I could find the appropriate logic to figure out where the prop was being invoked.

Can someone point me in the right direction? 

I'm trying to use the Zoid framework to build a similar flow, where I want to call a function prop as soon as a user clicks on the button to open the popup.

Thanks!

**Comment by mcntsh** [comment]
Hey @ziyadparekh,

We attach a click event to the button on the child page, which is the page inside of the iframe that renders the button. If you take a look at the zoid [Quick example](https://github.com/krakenjs/zoid#quick-example) section you'll see how this is done: A button is rendered on the child page, and we call a function prop passed down from the parent when it's clicked. 

In PayPal checkout, we define the `payment` prop in [src/button/component.jsx](https://github.com/paypal/paypal-checkout/blob/master/src/button/component.jsx#L333), and pass it down to the button page to be called when the button is clicked.

I hope this answers your question!

**Comment by ziyadparekh** [comment]
Opening this up again because I have a follow up question. How does the click event on the button open an external popup to the checkout page? Is that using zoid again inside the button component to control the popup?

**Comment by mcntsh** [comment]
We render _another_ zoid component from within the child page :-). So we pass the props from the parent page down to the child page where the buttons are rendered, and then when you click the button we render another component – this time through a pop-up – onto the parent page using [`renderTo`](https://github.com/krakenjs/zoid/blob/master/docs/api.md#componentrendertowin-props-container).

**Comment by ziyadparekh** [comment]
thats what i thought. Thank you! closing now
