### ISSUE TITLE
Error after clicking the continuing button in IE

### ISSUE THREAD

**Issue by benzookapi** [paypal/paypal-checkout#946]
### Description

Our partner said once they click "continue" in PayPal checkout page in IE, the attached error message shown and cannot proceed it.  

- Screenshots or videos that show the issue
![image](https://user-images.githubusercontent.com/899580/48399108-0ddbf700-e766-11e8-91cb-3131a49feb97.png)

This looks the similar error https://github.com/dfahlander/Dexie.js/issues/365

- Your code
- The `paypal.version` from your browser console
- The exact browser version
![image](https://user-images.githubusercontent.com/899580/48399192-53002900-e766-11e8-9694-48a8d77a3b45.png)

- A link to your page with the issue, if possible
http://www.w2solution.com/TestSite/DevelopV5ForPaymentTest/

- All console logs during the time of the issue, especially error messages
- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
- Does the issue occur consistently, or intermittently?

consistently

### Steps to reproduce

Goto http://www.w2solution.com/TestSite/DevelopV5ForPaymentTest/
Choose one item and click カートに入れる 
Click PayPal button and login/continue as a Sandbox account

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [x] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by mcntsh** [comment]
Hey @benzookapi, I can't access the site you've linked to reproduce, it seems to be behind a login.

**Comment by benzookapi** [comment]
@mcntsh Oh sorry...  the basic auth is  test_paypal/vm!8nHSX

**Comment by mcntsh** [comment]
It appears that this error is happening inside the `paypalPostAction` function after the `onAuthorize` callback. I don't believe this is happening from the Checkout.js side.

**Comment by benzookapi** [comment]
@mcntsh  Thank you for quick reply.  OK,  I will feedback this to the reporter.

**Comment by mcntsh** [comment]
No problem! Feel free to re-open if something else comes up.
