### ISSUE TITLE
Allow to pass `FormData` as `data` for requests

### ISSUE THREAD

**Issue by AlexWayfer** [paypal/paypal-checkout#953]
### Description

Please, allow to pass [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData) for `actions.request.post`.

You have [code for `Object`](https://github.com/paypal/paypal-checkout/blob/5cb32864e8699793bd80853cee112082bbdf5413/src/lib/http.js#L136-L140), but `FormData` has its own functions (iterators).

It's supported by native `XMLHTTPRequest` and `fetch`.

#### Screenshots or videos that show the issue

No.

#### Your code

```js
payment: (data, actions) => {
  // 2. Make a request to your server
  return actions.request.post(
    '/payments/create', new FormData(form)
  )
    .then(response => {
      // 3. Return res.id from the response
    return response.data.id;
  });
},
```

#### The `paypal.version` from your browser console

`4.0.235`

#### A link to your page with the issue, if possible

Not yet.

#### All console logs during the time of the issue, especially error messages

Just no `Form Data` in the Network tab of Chromium DevTools.

#### Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?

I think, yes.

#### Does the issue occur consistently, or intermittently?

Consistently.

### Steps to reproduce

1. Create the `<form>`.
2. Create the PayPal button with code above.
3. Click on button.

### Affected browsers

- [x] Chrome

**Comment by bluepnume** [comment]
Thanks for the request -- but `actions.request.post` is unlikely to evolve much beyond its current form. This is intended only as a helper to make simple ajax calls, and for more advanced functionality we'd recommend using an external library.

**Comment by AlexWayfer** [comment]
> This is intended only as a helper to make simple ajax calls, and for more advanced functionality we'd recommend using an external library.

I thought, standard is simple, not "advanced"…

**Comment by bluepnume** [comment]
We'll actually be removing this from future versions. `actions.request.post` from future versions. With simple promise-returning apis like fetch, there's not much utility for it any more.

**Comment by AlexWayfer** [comment]
> We'll actually be removing this from future versions. actions.request.post from future versions. With simple promise-returning apis like fetch, there's not much utility for it any more.

OK, thanks.
