### ISSUE TITLE
landing with flash bottom and loading in react-native webView

### ISSUE THREAD

**Issue by L17826879707** [paypal/paypal-checkout#955]
### Description
- Screenshots or videos that show the issue
[issue video.zip](https://github.com/paypal/paypal-checkout/files/2604123/issue.video.zip)

- The `paypal.version` from your browser console
4.0.235
- Does the issue occur consistently, or intermittently?
consistently in ios

### Affected browsers
react-native webView

**Comment by bluepnume** [comment]
Webviews are not officially supported by this SDK. Please try redirecting from your app to a full browser window with the paypal experience.
