### ISSUE TITLE
PayPal button won't start incontext checkout with Compatibility view mode and X-UA-Compatible

### ISSUE THREAD

**Issue by sshimizupp** [paypal/paypal-checkout#957]
### Description

PayPal Checkout button is shown but won’t when clicked work with Compatibility view mode and X-UA-Compatible, showing this message on console. I waited for a minute, but I still get the same.

- paypal.version: 4.0.235
- IE11
- The site that shows PayPal button is added in Compatibility View in IE11.
- The site has <meta http-equiv=“X-UA-Compatible” content=“IE=edge” />
- paypal.isEligible() = true
- console logs
ppxo_button_pre_template_click {“timestamp”:1542788763503,“windowID”:“a8f1ad8947”,“pageID”:“47cf83f4ac”,“prev_corr_ids”:“”,“referer”:“developer.paypal.com”,“host”:“developer.paypal.com”,“path”:“/demo/checkout/“,”env”:“production”,“country”:“US”,“lang”:“en”,“uid”:“0060ed9143_ga4dumrshi2dk”,“ver”:“4.0.235”}

- The issue also occurs at https://developer.paypal.com/demo/checkout/#/pattern/client.
- The issue occurs consistently.

### Steps to reproduce

- Add the site that shows PayPal button in Compatibility View in IE11.
- Add <meta http-equiv=“X-UA-Compatible” content=“IE=edge” />
- Load the site, you will see the PayPal button, but when the button is clicked, nothing happens.

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [x ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by mcntsh** [comment]
Hey @sshimizupp, the fact that the pop-up never happens makes me suspect you might be trying to render the button in Intranet Mode. Could you please check this page out and see if it helps you?

https://github.com/paypal/paypal-checkout/blob/master/docs/debugging/ie-intranet.md

**Comment by sshimizupp** [comment]
Hi @mcntsh, I'm aware of this intranet mode issue and this time is a different issue. The site is not in Intranet mode but added to Compatibility view mode.  I understand we don't support Compatibility view mode as IE works in IE7 mode, but when there is meta tag X-UA-Compatible IE=edge, it should disable Compatibility view mode, but when I click the button I see ppxo_button_pre_template_click. Seems like some necessary codes would not be loaded.

Below is for Classic NVP integration and it is old, but we recommended adding this meta tag then. Could you please check if this is still true?
https://developer.paypal.com/docs/classic/express-checkout/in-context/javascript_advanced_settings/#browser-support

Thanks,

**Comment by bluepnume** [comment]
If the site is in compatibility mode, there is no way for the PayPal button to work. Which mode do you see being enabled in the IE11 developer console?

**Comment by sshimizupp** [comment]
Even when in Edge mode, I see the issue.

**Comment by bluepnume** [comment]
OK I was able to repro just now. Even though IE dev-tools shows "Edge", the button is still being loaded with an IE7 user-agent. So this is unlikely to be something we're going to fix. We would just recommend avoiding setting compatibility mode for any site where you're rending the paypal button.
