### ISSUE TITLE
Input password page bottom popup on Phone;Implement a PayPal Checkout Server Integration

### ISSUE THREAD

**Issue by haohualiangshi** [paypal/paypal-checkout#958]
**I use a PayPal Checkout server integration for my app;The HTML copy from this  [docs](https://developer.paypal.com/docs/checkout/how-to/server-integration/#1-set-up-your-client-to-call-your-server);In my app I use WKWebview load this html;but when I open paypal password page;the bottom is popup;**

![20181122_113829](https://user-images.githubusercontent.com/19658421/48880472-9b48d680-ee4b-11e8-84b1-156ae0a6a1db.gif)

**Comment by bluepnume** [comment]
Webviews are not fully supported. Please use a redirect integration instead, and redirect to a full browser window from your app.
