### ISSUE TITLE
Edge: Login appears and paypal redirect to the cancel website

### ISSUE THREAD

**Issue by SCPhilippHolzmann** [paypal/paypal-checkout#959]
### Description

On the Edge Browser, if the paypal login mask comes up, the website redirect to the cancel URL without any user action.

- Screenshots or videos that show the issue
![paypalissue1](https://user-images.githubusercontent.com/35449774/48936506-6bf99e80-ef0b-11e8-9fa3-1024640ca9bf.png)
![paypalissue2](https://user-images.githubusercontent.com/35449774/48936513-6ef48f00-ef0b-11e8-9e28-a7eaab0fab85.png)
![paypalissue3](https://user-images.githubusercontent.com/35449774/48936517-72881600-ef0b-11e8-8622-40ac1b16248f.png)
![paypalissue4](https://user-images.githubusercontent.com/35449774/48936520-75830680-ef0b-11e8-8580-632cfec1d133.png)

- Your code
```
<div id="paypal-button">
            </div>
            <script src="https://www.paypalobjects.com/api/checkout.js"></script>
            <script>
                paypal.Button.render({
                    //Configure environment
                            env:'sandbox',
                    client: {
                        sandbox:'my sandbox id',
                        production: 'production_client_id'
                    },
                    locale:'de_DE',
                    style:{
                        size:'small',
                        color:'gold',
                        shape:'pill',
                    },
                    commit:true,
                    payment: function(data,actions){
                        return actions.payment.create({
                            transactions: [{
                                amount: {
                                    total: 10,
                                    currency: 'EUR'
                                },
                                description:'Event zum Geldausgeben',
                                invoice_number:20,
                                item_list:{
                                    items:[{
                                        name:'Event zum Geldausgeben',
                                        quantity:1,
                                        price:10,
                                        currency:'EUR',
                                    }]
                                }
                            }],
                            redirect_urls:{
                                return_url:'http://uic.web-dev-004.mpsc.intern/event-payment/?tx_sfeventmgt_pipayment%5Bregistration%5D=20&tx_sfeventmgt_pipayment%5Bhmac%5D=0082b7e1324b2515bcc6e2f4fd79ea669c9673bd&tx_sfeventmgt_pipayment%5Baction%5D=success&tx_sfeventmgt_pipayment%5Bcontroller%5D=Payment',
                                cancel_url:'http://uic.web-dev-004.mpsc.intern/event-payment/?tx_sfeventmgt_pipayment%5Bregistration%5D=20&tx_sfeventmgt_pipayment%5Bhmac%5D=90fa267ff7f3db5a930ec2f0540899863a68f9da&tx_sfeventmgt_pipayment%5Baction%5D=cancel&tx_sfeventmgt_pipayment%5Bcontroller%5D=Payment'
                            }
                        });
                    },
                    // Execute the payment
                    onAuthorize: function(data, actions) {
                        return actions.payment.execute().then(function() {
                            // Show a confirmation message to the buyer
                            //window.alert('Thank you for your purchase!');
                            //document.location.href="http://uic.web-dev-004.mpsc.intern/event-payment/?tx_sfeventmgt_pipayment%5Bregistration%5D=20&tx_sfeventmgt_pipayment%5Bhmac%5D=0082b7e1324b2515bcc6e2f4fd79ea669c9673bd&tx_sfeventmgt_pipayment%5Baction%5D=success&tx_sfeventmgt_pipayment%5Bcontroller%5D=Payment";
                            console.log(data);
                            console.log(actions);
                            actions.redirect();
                        });
                    },
                onCancel:function(data,actions){
                    console.log(data);
                    console.log(actions);
                        actions.redirect();
                }
                },'#paypal-button');
            </script>
```

- All console logs during the time of the issue, especially error messages
![paypalissueconsole](https://user-images.githubusercontent.com/35449774/48936531-7c117e00-ef0b-11e8-8920-c6e265fe2373.png)

- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
No
- Does the issue occur consistently, or intermittently?
This issue occur every time i use edge

### Steps to reproduce

- klick on Paypal Checkout Button
- wait until the Paypal login mask comes up
- wait around 10 - 20 seconds and then the cancel redirect comes up

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ X ] Edge (40.15063.674.0  Microsoft EdgeHTML 15.15063)
- [ ] IE 
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by netoper** [comment]
i have same problem.

**Comment by mcntsh** [comment]
Hey @SCPhilippHolzmann,

I took your integration code and ran it myself in Edge, and was able to render the checkout without issues. We've had a few different reports for a similar issue so I appreciate any help you can give us so that we can get to the bottom of this...

You mentioned that you are able to reproduce this consistently. Are you getting any errors logged to your console? What about failed requests in your network tab?

**Comment by SCPhilippHolzmann** [comment]
Hey @mcntsh 

The Window with my site throws no errors and each request is successful.

I am not sure the Paypal Pop Window thorws no error because the Edge close the console right before the Login appears. Before and after there are no errors or failed requests on this window.

This is the Log from my Side. There are some errors but i think it has nothing to do with my Problem:
![2018-11-30 15_30_18-_event-payment_ f12-entwicklungstools - microsoft edge](https://user-images.githubusercontent.com/35449774/49295214-90c6b680-f4b5-11e8-8772-3c35863e35ab.png)

**Comment by SCPhilippHolzmann** [comment]
I made a clone from the internal dev server and take it to another server. I test the checkout and the problem does not appear. On the internal Server the Problem is still there.

**Comment by mcntsh** [comment]
@SCPhilippHolzmann I'm able to reproduce. Are you by chance accessing the PayPal Checkout through a corporate device?

**Comment by SCPhilippHolzmann** [comment]
@mcntsh I'm not sure what you want with "corporate device". I test my site with a coporate computer. The Internal Server is not available from the internet.

**Comment by mcntsh** [comment]
@SCPhilippHolzmann To give you some more information, there is a bug with IE and Edge where the parent window can not properly communicate with a child that it outside of its security zone. I'm wondering if this is what you are running into.

The way that I was able to fix this was by removing sites from my *Trusted Sites* security zone that were added by default on my corporate computer. Please try going to **Internet Options > Security > Trusted Sites > Sites** and removing all instances of `paypal.com` or sites that you aretesting the integration on (like your internal server). Then restart Edge and see if this fixes the problem.

We are working on detecting this early so it doesn't appear to be a bug or display this unexpected behavior.

**Comment by vuvutestaccount** [comment]
@mcntsh - this unfortunately does not resolve the problem as the developer has already tried this. We went down this route when I mentioned not to use intranet mode.

**Comment by mcntsh** [comment]
@vuvutestaccount did the developer also remove their sites from the *Trusted sites* and other zones, not just Intranet?

**Comment by SCPhilippHolzmann** [comment]
@mcntsh I tried to remove the internal site and all paypal.com sites. But the field are empty. I added for fun the internal server and the "https://www.sandbox.paypal.com" size to the trusted Sites and restart the Browser. After that the Paypal checkout does not cancel the payment. I think we can close the issue.

**Comment by vuvutestaccount** [comment]
@mcntsh - yes they did. As mentioned, this was done when we also disabled intranet mode.

**Comment by SCPhilippHolzmann** [comment]
@mcntsh The two Servers are only in the Trusted Sites not in the Internal Sites. The Internal Sites are empty. The three Include Checkboxes of the Local Intranet are checked. Maybe, this settings help others.

**Comment by bluepnume** [comment]
Closing this specific issue. @mcntsh will be updating the intranet documentation to reflect what we've found around both IE11 and Edge. Glad it's at least working for you now.

**Comment by sandymca94** [comment]
#1087 still i am waiting to get a response to solve edge browser issue.

@bluepnume  please help me on this
