### ISSUE TITLE
Payment list request returns wrong payment items

### ISSUE THREAD

**Issue by mahdiridho** [paypal/paypal-checkout#960]
### Description
I have the shop run client REST API for payment checkout over 1 year. Everything works well untill yesterday I got a strange issue when request the payment list : 

`curl -v "https://api.paypal.com/v1/payments/payment?count=4" -H "Content-Type: application/json" -H "Authorization: Bearer SESSION_TOKEN"`

I can see 4 payment items on the list of the API response. However the list items are incorrect, I can't see a new payment item created on Nov 25th, 2018. While it has been existing on my paypal account activities, so the list should return the following items : 

1. trx ID Nov 25th, 2018
2. trx ID Nov 13th, 2018
3. trx ID Nov 8th, 2018
4. trx ID Nov 7th, 2018

But, on the response I get the following items : 

1. trx ID Nov 13th, 2018
2. trx ID Nov 8th, 2018
3. trx ID Nov 7th, 2018
4. trx ID Nov 6th, 2018

The print out of trx ID Nov 25th, 2018 : 
![nov 25th](https://user-images.githubusercontent.com/10230037/48989014-6c4ca080-f17c-11e8-94c2-0ededde42518.jpg)

Nothing strange with the transaction, all info are fine. Why does it not exist on the response of the list payment ?

```
[
  {id: "PAYID-xxxx", intent: "sale", state: "approved", cart: "xxxx", payer: {objects}, transactions: [objects], create_time:"2018-11-13T02:52:41Z", "update_time": "2018-11-13T03:18:17Z", links: [objects],
  {id: "PAYID-xxxx", intent: "sale", state: "approved", cart: "xxxx", payer: {objects}, transactions: [objects], create_time: "2018-11-08T01:53:32Z", "update_time": "2018-11-09T09:54:28Z", links: [objects],
  {id: "PAYID-xxxx", intent: "sale", state: "approved", cart: "xxxx", payer: {objects}, transactions: [objects], create_time: "2018-11-07T10:09:14Z", "update_time": "2018-11-07T10:14:22Z", links: [objects],
  {id: "PAYID-xxxx", intent: "sale", state: "approved", cart: "xxxx", payer: {objects}, transactions: [objects], create_time: "2018-11-06T08:19:56Z", "update_time": "2018-11-06T10:22:48Z", links: [objects],
]
```

What is the exact problem here? And where is it from?

**Comment by bluepnume** [comment]
Please raise a ticket at https://www.paypal-support.com/s/?language=en_US -- this repo is only for checkout.js issues and questions.

**Comment by flatmax** [comment]
WE are still suffering from this problem.
Is there any reason why the items aren't being picked up ? I can see them in paypal, but they don't appear in the API

**Comment by mahdiridho** [comment]
> Please raise a ticket at https://www.paypal-support.com/s/?language=en_US -- this repo is only for checkout.js issues and questions.

We're using checkout.js on the client shop then we pull the paypal list payments api on the admin shop. So we're wondering if any related problem between checkout.js or paypal api?

**Comment by flatmax** [comment]
We have now opened a technical support ticket against this issue.
