### ISSUE TITLE
Paypal lightbox raise error on some devices

### ISSUE THREAD

**Issue by vikasd989** [paypal/paypal-checkout#961]
### Description
 Error showing on the top of the checkout button
http://gearbubble-dev.s3.amazonaws.com/vendor_product_images/attachments/547/preview/paypal_error.jpg

### Steps to reproduce
1. Purchase this product with payment method paypal:
https://www.gearbubble.com/bff-sister-plus-0627

2. On checkout page click 'Paypal checkout' button. Error is produced.
### Affected browsers

- [ ] Safari Mobile/Tablet

**Comment by vishakha94** [comment]
@vikasd989 I tried to reproduce the issue on safari mobile browser and could not reproduce it. 
-Is this error producing immediately after you click the PayPal button?
-Can you look at the console and see if you see any error?

**Comment by vishakha94** [comment]
@vikasd989 Tried the issue on an iPad safari and am unable to repro. CLosing the issue for now.
