### ISSUE TITLE
A way to force checkout on load page

### ISSUE THREAD

**Issue by vankk** [paypal/paypal-checkout#962]
Hello, how I can force the checkout after the page is loaded? The solution for my problem is to remove the Paypal Button Render and force it loads automatic after the page is loaded. I tried to Google it, but I couldn't find nothing.

Thank you.

Regards,
vankk.

**Comment by mcntsh** [comment]
Hey @vankk, could you clarify what you mean by forcing the checkout? Are you talking about the button render, or are you trying to force the pop-up open without a click? 

Just so you're aware, there is no way to open the Checkout flow automatically; the buyer must click on the button.

**Comment by vankk** [comment]
Hello @mcntsh thank for you reply, I was meaning "forcing the Checkout" by forcing the pop-up without on the PayPal Button.

At my case the user select the amount and proceed, and, after that it is suppost to force the pop-up without the PayPal Button, so, if that won't be possible, I'll try to figure out another solution.

Thank you.

**Comment by mcntsh** [comment]
No problem! :)
