### ISSUE TITLE
Does it support Recurring Payment?

### ISSUE THREAD

**Issue by baybird** [paypal/paypal-checkout#963]
### Description
Does this "paypal-checkout" package support Recurring Payment? 

I know what need to do in the back-end for the recurring payment, but I can't find any documents regarding **how to integrate this 'paypal-checkout' (front-end application) with the back-end application for Recurring Payment?**

Have tried to call back-end API to create plan and activate plan in the front-end payment() method, return with plan id as payment id. But the front-end always show message "Things don’t appear to be working at the moment."

Can anyone help?

Things need to do in the back-end:
1. Create a plan
2. Activate a plan
3. Create an agreement
4. Get customer approval
5. Execute an agreement

**Comment by vishakha94** [comment]
@baybird Can you please copy here the integration script you have used? Also, the EC-token in the URL when you get the error message?

**Comment by baybird** [comment]
I am using following script to integrate  "paypal-checkout" with recurring payment.

- The payment() method would call the CREATE_PAYMENT_URL endpoint to create a billing plan, activate it and create an agreement.

- The onAuthorize() method would call the EXECUTE_PAYMENT_URL  endpoint to execute that agreement after buyer approved it.

- Latest EC token is EC-2RK5964401035115L

**My questions are:**
1. Dose  the "paypal-checkout" package support recurring payment?
2. If yes, can you provide an example of how to integrate it with recurring payment?

```
const React        = require('react');
const ReactDOM     = require('react-dom');
const paypal       = require('paypal-checkout')
const PayPalButton = paypal.Button.driver('react', {React, ReactDOM});

class PayPalRecurring  extends React.Component {
    constructor(props) {
        super(props);

        this.CREATE_PAYMENT_URL  = config.url.buy_plan_with_paypal;
        this.EXECUTE_PAYMENT_URL = config.url.verify_payment_paypal;

        this.state = {
            env: config.paypal.env , // 'production' , 'sandbox'
            client: {
                sandbox    : config.paypal.sandbox.client_ID,
                production : config.paypal.production.client_ID
            },
            commit: true,
            style: {
                label       : 'pay',
                fundingicons: true, // optional
                branding    : true, // optional
                size        : 'medium', // small | medium | large | responsive
                shape       : 'rect', // pill | rect
                color       : 'gold' // gold | blue | silve | black
            }
        };
    }

    onError(data, actions) {
        // Show an error page here, when an error occurs
    }

    validate(actions) {
    }

    onClick() {
    }

    // payment() is called when the button is clicked
    payment(data, actions) {
        var self = this
        return paypal.request.post(this.CREATE_PAYMENT_URL, this.props.data ).then(function(res) {
            console.log('1 create payment - success ')
            console.log(res);
        }).catch(res=>{
            console.log('1 create payment - error ')
            console.log(res);
        })
    }

    // onAuthorize() is called when the buyer approves the payment
    onAuthorize(data, actions) {
        console.log('onAuthorize()');
        var self = this

        // Set up the data you need to pass to your server
        var data = {
            ...
        };

        // Make a call to your server to execute the payment
        return paypal.request.post(this.EXECUTE_PAYMENT_URL, data).then(function(res) {
            console.log(res)
        });
    }

    render() {
        return (
            <PayPalButton
                commit      ={this.state.commit}
                env         ={this.state.env}
                client      ={this.state.client}
                style       ={this.state.style}
                onClick     ={()=>{this.onClick()}}
                validate    ={(actions)=>{this.validate(actions)}}
                payment     ={(data, actions) => this.payment(data, actions)}
                onAuthorize ={(data, actions) => this.onAuthorize(data, actions)}
            />
        )
    }
}

PayPalRecurring.defaultProps ={
    action : 'buyplan',
    data   : {}
}

module.exports = PayPalRecurring

```

**Comment by mcntsh** [comment]
Hey @baybird,

We do not support EC Billing Agreements through Checkout.js, instead we recommend you integrate through [Braintree Vaulting](https://developers.braintreepayments.com/guides/paypal/vault/javascript/v3). This would be a strictly client-side implementation, and would look something like this:

```
// ...
const paypal     = require('paypal-checkout')
const braintree = require('braintree-web/client');
// ...

class PayPalRecurring  extends React.Component {

    braintree,

    // ...

    payment(data, actions) {
        return actions.braintree.create({
            amount: '0.01',
            currency: 'USD',
            flow: 'vault'
        });
    },

    onAuthorize(data, actions) {
        return actions.payment.tokenize().then((data) => {
            console.log(`Braintree nonce: ${data.nonce}`);
        });
    },

    // ...

});

**Comment by bluepnume** [comment]
@trainerbill can you help @baybird with the process for getting approved for billing agreements?

**Comment by trainerbill** [comment]
@baybird If you haven't already you will need a billing plan id so execute:

https://developer.paypal.com/docs/api/payments.billing-plans/v1/#billing-plans_create

Then you have to activate the plan

https://developer.paypal.com/docs/api/payments.billing-plans/v1/#billing-plans_update

Then you will need to create a web service that executes the create billing agreement api

https://developer.paypal.com/docs/api/payments.billing-agreements/v1/#billing-agreements_create

returns the EC- token from the response.links[0].href.

`res.send({ token: response.links[0].href.match(/(EC-\w+)/i)[0] })` should work.

Create another webservice to run the execute billing agreement api

https://developer.paypal.com/docs/api/payments.billing-agreements/v1/#billing-agreements_execute

then in the payment callback of checkoutjs hit the webservice to get the token and in the onAuthorize callback hit the webservice to execute the agreement.

```
payment: function () {
  return paypal.request.get('WEBSERVICE_URL).then(function (res) { return res.token });
},
onAuthorize: function () {
  return paypal.request.post(WEBSERVICE_FOR_EXECUTE)
}
```

If you need help hit me up on the gitter chat.  https://gitter.im/paypal/paypal-checkout.  I can share an example there.

**Comment by baybird** [comment]
@trainerbill @bluepnume Thanks. Just tried. Yep, it works with recurring payment. 

So, it calls the back-end to creates an agreement with billing plan and returns the agreement token in the payment() method, instead of returning the billing plan ID.


```
class PayPalRecurring  extends React.Component {
    //...
    
    payment(data, actions) {
        return paypal.request.post(this.CREATE_PAYMENT_URL, this.props.data ).then(function(res) {            
            try{
                // find approval url
                for(var link of map.links){
                    if(link.rel.toUpperCase() == 'approval_url'.toUpperCase()){
                        var approval_url = link.href
                        break;
                    }
                }
            }
            catch(error){
                throw(error)
            }
            
            if(approval_url){
                try{
                    // extract token from approval_url
                    var agreement_token = new window.URL(approval_url).searchParams.get('token')
                    
                    return agreement_token
                }
                catch(error){
                    throw(error)
                }
            }else{
                throw(`Could not find approval_url.`)
            }
        }).catch(res=>{
            if(res.error){
                this.props.errorHandling(res.error)
            }else{
                this.props.errorHandling(error)
            }
        })
    }

    //...
}
```

It would be nice, if recurring payment can be mentioned in the [dev docs ](https://github.com/paypal/paypal-checkout#learn-more-in-our-dev-docs)

**Comment by baybird** [comment]
Hey @mcntsh , thanks for the recommendation, I will try later.
