### ISSUE TITLE
IC window not loading after PP button clicked in FF and sometimes Chrome

### ISSUE THREAD

**Issue by ajlangsdon** [paypal/paypal-checkout#964]
### Description

When checking out on https://www.stuartweitzman.com, the PP button on the checkout page triggers an error in Firefox. I was able to reproduce this issue using Firefox 63.0.3. After clicking the checkout button, I see this error: http://prntscr.com/lt8rid. The IC window loads and then immediately closes.

This issue seems to be isolated to this specific website and the PayPal button does work on the bag page, but not the checkout page.

PP version: 4.0.239

**Comment by bluepnume** [comment]
I see the following code in the integration:

```
            if (!ValidateStep(step)) {
                EnableButton(step);
                return reject();
            }
```

They're using `reject()` as a means of doing validation and forcing the popup to close. That isn't recommended. reject is intended for error cases, and should always be passed an error explicitly -- like `reject(new Error('Ajax call to /foo failed'))`

They should follow this pattern for validation: https://developer.paypal.com/demo/checkout/#/pattern/validation
