### ISSUE TITLE
Production: Timed out waiting 10000ms for payment

### ISSUE THREAD

**Issue by mrtristan** [paypal/paypal-checkout#968]
i know this is something that has been reported on and off before, but i don't see any recent issues for it:

we're seeing in our PRODUCTION environment the following error many times per day:

```
Error: Error: Timed out waiting 10000ms for payment
    at ParentComponent.<anonymous> (https://www.paypalobjects.com/api/checkout.js:11951:172)
    at Object.resultValue (https://www.paypalobjects.com/api/checkout.js:5107:41)
```

**Comment by osielccenviaflores** [comment]
this problem that trigger because your request is more than 10 seconds

**Comment by mcntsh** [comment]
@mrtristan We have a timeout in this callback for 10s, so if we don't get a resolved promise or a return in 10s we will throw this error.

What does your integration look like? Are fetching a token from a server via AJAX in this `payment()` method?

**Comment by Azwan611** [comment]
rLHzPsX6oXkzU2qL12kHCH8G8cnZv1rBJh

**Comment by Azwan611** [comment]
rLHzPsX6oXkzU2qL12kHCH8G8cnZv1rBJh

**Comment by Azwan611** [comment]
rLHzPsX6oXkzU2qL12kHCH8G8cnZv1rBJh

**Comment by Azwan611** [comment]
Yes

**Comment by mcntsh** [comment]
@mrtristan Closing this for now. If you have any update regarding this timeout error you are free to open it back up :)

**Comment by Azwan611** [comment]
Then One comment has good information only

**Comment by osielccenviaflores** [comment]
> @mrtristan Closing this for now. If you have any update regarding this timeout error you are free to open it back up :)

Yes, i get a token from the server side and this is more than 10 seconds
