### ISSUE TITLE
Credit Button

### ISSUE THREAD

**Issue by bluepnume** [paypal/paypal-checkout#97]
We should support credit button style.

In theory that should be all it takes to support credit flow, since we're entering/exiting the checkout flow at the same point, and the rest of the credit set-up is tokenized in the payment token, which we are agnostic to.

**Comment by abarco** [comment]
Need to involve the credit team to support Canceled transactions

**Comment by bluepnume** [comment]
This is now ready to push, targeted for this week.

**Comment by bluepnume** [comment]
Pushed.
