### ISSUE TITLE
Bridge Domain / Bridge Url confusion

### ISSUE THREAD

**Issue by ziyadparekh** [paypal/paypal-checkout#980]
I'm confused about PayPal checkout's implementation of bridge urls and bridge domains. The Zoid documentation says that a `Bridge Domain` is only "required if the final domain of the bridge is different to that of the initial bridgeUrl provided - for example, if the original url does a 302 redirect to a different domain or subdomain."

From the source on line:
https://github.com/paypal/paypal-checkout/blob/1a029c84abdc9f55bb05bc2b90cf29b4423819e3/src/checkout/component.js#L83

It seems that the domains for the both the checkout app and the bridge url are the same for each environment i.e sandbox = https://sandbox.paypal.com and production = https://www.paypal.com

Why then does the checkout zoid component have to provide both the bridgeUrl and bridgeDomain. Shouldn't the bridgeUrl be enough since there is no 302 redirect to a different domain/subdomain?

**Comment by bluepnume** [comment]
Yep you're right. The only reason it's defined here is to make sure our tests work.

**Comment by mcntsh** [comment]
Closing this out since I think this answers your question. Feel free to open it back up otherwise.
