### ISSUE TITLE
Potential clean-up issue in IE 11 after establishing a billing agreement

### ISSUE THREAD

**Issue by jylc08** [paypal/paypal-checkout#981]
### Description

Hello. I'm experiencing an issue with the PayPal checkout modal in IE 11. In a nutshell, when a user completes a billing agreement flow the first time, the second time they initiate the flow they get a `You've already set up preapproved payments with...` message. 

In all other browsers the user is able to go through the modal flow and establish a billing agreement for the second time. Is there any clean-up of cookies that happens when a billing agreement flow is complete that may potentially not happen in IE 11? I've provided a use case in the steps to reproduce below in which we run into the issue.

Our page is in our staging environment so unfortunately it's not available. PayPal version is `4.0.239`. IE version is `11.785.16299.0`. The issue is consistent and we don't get any errors in the console. The issue does not occur on the PayPal demo but our implementation is the billing agreement flow rather than the default payment flow.

Thanks!

![screen shot 2019-01-07 at 1 11 46 pm](https://user-images.githubusercontent.com/10815790/50852857-97a6db80-1335-11e9-8d42-4f009f43ad46.png)

### Steps to reproduce

1. On our checkout page a customer clicks the PayPal checkout button
2. PP Modal appears, customer enters PP credentials and confirms the billing agreement
3. Our checkout page is updated with PP as the method of payment
4. Button is clicked for a second time and the modal appears
5. "You've already set up preapproved payments with..." message appears in the modal and the user isn't able to go through the billing agreement flow a second time

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [x] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by mcntsh** [comment]
Hey @jylc08, what are you returning for the `payment()` callback the second time around? You can not establish a billing agreement more than once per payment, so in this case IE 11 is working as intended.

My question is why it appears to be working on other browsers. I just tested myself by returning an EC-token in `payment()` which was already used to authorize a Billing Agreement, and got the "You've already set up preapproved payments with..." error in Chrome.

**Comment by jylc08** [comment]
Hey Jon. In `payment()` we are hitting our own endpoint to fetch a billing agreement token ID. This should give a new token on each request. Given that the `You've already set up preapproved payments...` message is shown when an already-used token is returned in `payment`, I feel like IE might be caching the request. I'll investigate.

**Comment by jylc08** [comment]
IE was indeed caching the request. Adding the `Cache-Control` header on the response solved the problem. Thanks for the help @mcntsh.
