### ISSUE TITLE
enablecheckoutiframe is undefined

### ISSUE THREAD

**Issue by malliapi** [paypal/paypal-checkout#983]
enablecheckoutiframe is undefined when trying to use it, however it seems available on these demos
https://developer.paypal.com/demo/checkout/#/pattern/validation

also paypal.Checkout is undefined?

version: v4.0.239

**Comment by mcntsh** [comment]
Hey @malliapi do you have any code we can look at or perhaps a URL so that we can attempt to reproduce?
