### ISSUE TITLE
Unable to start paypal flow without button click

### ISSUE THREAD

**Issue by muhammad-asad-26** [paypal/paypal-checkout#992]
Hi,
I've been using BrainTree Paypal SDK, I don't want to render paypal button, instead I want to trigger checkout flow on my own button click, The button which is rendered by javascript client causes issues with react.js application. A new button is created on any state change or button click inside the web page.

![screen shot 2019-01-23 at 8 13 22 am](https://user-images.githubusercontent.com/38201402/51612346-df596580-1ee6-11e9-8735-72532078304d.png)

```
windowLoaded &&
      braintree.client
        .create({
          authorization: clientToken
        })
        .then(function(clientInstance) {
          return braintree.paypalCheckout.create({
            client: clientInstance
          });
        })
        .then(function(paypalCheckoutInstance) {
          return paypal.Button.render(
            {
              env: "sandbox", // or 'production'
              commit: true,
              style: {
                label: "paypal",
                size: "large",
                shape: "rect",
                color: "blue",
                tagline: false
              },

              payment: function() {
                return paypalCheckoutInstance.createPayment({
                  flow: "checkout",
                  amount: amount,
                  currency: "USD",
                  enableShippingAddress: false,
                  shippingAddressEditable: true
                });
              },

              onAuthorize: function(data, actions) {
                return paypalCheckoutInstance
                  .tokenizePayment(data)
                  .then(function(payload) {
                    console.log(payload);
                    initiateBooking(payload);
                  });
              },

              onCancel: function(data) {
                console.log(
                  "checkout.js payment cancelled",
                  JSON.stringify(data, 0, 2)
                );
              },

              onError: function(err) {
                console.error("checkout.js error", err);
              }
            },
            "#paypal-button-div"
          );
        })
        .then(function() {
        })
        .catch(function(err) {
          console.error(err);
        });
    return windowLoaded && <div id="paypal-button-div" />;
```
What I want to do is to hide this paypal button(s) and then my own custom button on click I want to start the checkout flow.

**Comment by mcntsh** [comment]
Hey @muhammad-asad-26 

We don't support opening the PayPal Checkout without a click on our button as it could pose a potential security risk to our buyers. You mentioned that our button is causing issues with your React.js application – is there a any help that we can give you to solve that problem instead?

**Comment by muhammad-asad-26** [comment]
Hey @mcntsh 
Thanks for the response but we have solved the problem. I'm closing this issue now.

**Comment by dan003400** [comment]
Payflow should be able to be programmatically started, you can currently see this happening all over the web via old SDKs.

Thanks for making it harder to use PayPal and adding more frictions to customers trying to checkout using PayPal.
