### ISSUE TITLE
Error message not shown during validation

### ISSUE THREAD

**Issue by audiopilot** [paypal/paypal-checkout#996]
### Description

The error message is no longer displayed if there is a validation problem. This is a major concern and is resulting in loss of sales; from the user's perspective, the PayPal button is simply broken.

### Steps to reproduce

1. Go to https://developer.paypal.com/demo/checkout/#/pattern/validation

2. Click on the PayPal button without clicking on the checkbox.

3. Checkout is correctly halted, but no error message is displayed.

### Notes

_I believe that actions.disable() is preventing onClick() from firing._ Please fix this ASAP!

**Comment by bluepnume** [comment]
Can you clear cache and try again? This issue should be resolved.

**Comment by audiopilot** [comment]
Looks good now, thanks.
